.github/workflows/CI.yml
=> Update upstream to branch instead of tag

.github/workflows/CI.yml
use opensearch 1.0 branch as upstream for rc1 release.
=> Update upstream to use 1.0

jni/CMakeLists.txt
Allow CPACK_PACKAGE_VERSION to be set from command line.
if no value is passed, "local" will be used as default plugin version.
=> Update PACKAGE_VERSION to k-NN plugin version

build.gradle, src/main/java/org/opensearch/knn/index/KNNMethodContext.java, src/main/java/org/opensearch/knn/index/MethodComponentContext.java, src/test/java/org/opensearch/knn/index/KNNMethodContextTests.java, src/test/java/org/opensearch/knn/index/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/index/MethodComponentContextTests.java
This PR adds equals and hashcode overrides to KNNMethodContext and MethodComponentContext in order to prevent mapper merge from failing.
#38 
=> Add equals and hashcode to KNNMethodContext MethodComponentContext

.gitignore, .idea/copyright/SPDX_ALv2.xml, .idea/copyright/profiles_settings.xml, build.gradle
1. Re-enabled the 'licenseHeaders' check in the build.gradle file.
2. Added an IntelliJ copyright profile to auto-generate the SPDX license header.
Related to - opensearch-project/opensearch-plugins#49
Signed-off-by: Ketan Verma <vermketa@amazon.com>
=> Enabled automated license header checks

src/main/java/org/opensearch/knn/training/VectorReader.java, src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java, src/test/java/org/opensearch/knn/training/VectorReaderTests.java
Adds a vector reader for training that scans an index for knn_vector's based on the field, and passes them to a Consumer to do "something" with. In the future, "something", can pass the training data to the jni layer where it can be used for training.
The vector reader executes a scan query against the index, collecting all documents in the index that contain the knn field of interest. The scan terminates either when the index has no more documents to search, or the maximum number of vectors has been collected. 
#27  …
=> Add vector reader to scan index containing k-NN vectors

src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
This PR comments out the flaky test to prevent integration tests from failing. This is a minor test that checks to see if the `graph_query_errors` stat is getting incremented on error.
Added information in a comment above the test:
> // This test case intended to check whether the "graph_query_error" stat gets incremented when a query fails.
// It sets the circuit breaker limit to 1 kb and then indexes documents into the index and force merges so that
// the sole segment's graph will not fit in the cache. Then, it runs a query and expects an exception. Then it
// checks that the query errors get incremented. This test is flaky:
// https://github.com/opensearch-project/k-NN/issues/43. During query, when a segment to be
// searched is not …
=> Comment out flaky test

src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
Cherry picks #54 to 1.x branch
=> Cherry-pick #54 to 1.x

src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
Cherry picks #54 to 1.0 branch
=> Cherry-pick #54 to 1.0

src/main/java/org/opensearch/knn/index/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/indices/Model.java, src/main/java/org/opensearch/knn/indices/ModelCache.java, src/main/java/org/opensearch/knn/indices/ModelDao.java, src/main/resources/mappings/model-index.json, src/test/java/org/opensearch/knn/indices/ModelCacheTests.java, src/test/java/org/opensearch/knn/indices/ModelDaoTests.java, src/test/java/org/opensearch/knn/indices/ModelTests.java
Currently, the model system index stores a model's base64 encoded model_blob and associated knn_engine. This PR adds the space type and the dimension of the model to this index to make it easier for users to create indices and for the plugin to rescore queries. To accomplish this, it creates a `Model` class that stores all information about the model.
Eventually, a user should be able to create an index from a model with this simple mapping:
```
"my_vector":{
"type":"knn_vector",
"model_id": "my_model_id"
}
```
During index creation, we require a user to specify a dimension. This is later used for parsing ingested vectors/query vectors. Additionally, a user will be required to specify a dimension during training as well, which will be used to validate training data that is used. If we …
=> Update model index to include additional meta data

.github/workflows/CI.yml, build.gradle, jni/CMakeLists.txt
update ci to build against 1.x branch and use snapshot.
#78 #73  
=> Fix snapshot build, build against OpenSearch 1.1

.github/workflows/CI.yml
Fixes failure seen here: https://github.com/opensearch-project/k-NN/actions/runs/1186790338/workflow#L35.
OpenSearch 1.0 points to 1.0.1. However, this has not yet been released. Therefore, we update CI to point directly to 1.0.0.
- [ X ] Commits are signed as per the DCO using --signoff 
=> Update CI to point to 1.0.0

src/main/java/org/opensearch/knn/index/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java, src/test/java/org/opensearch/knn/index/KNNVectorFieldMapperTests.java
Currently, there are several ways a user can specify a knn_vector field: provide a model, provide a method definition, or provide parameters to nmslib's hnsw implementation in the index settings. These alternative methods have caused the code in the field mapper to become messy. 
This PR refactors that conditional logic using polymorphism. KNNVectorFieldMapper is converted to an abstract class. For the 3 methods mentioned above, each has a corresponding mapper that extends KNNVectorFieldMapper. The primary job of the subclasses is to define what information needs to be put into the field info.
#69 
For more information on …
=> Refactor field mapper conditional logic to subclass

src/main/java/org/opensearch/knn/common/KNNConstants.java, src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java, src/main/java/org/opensearch/knn/indices/Model.java, src/main/java/org/opensearch/knn/indices/ModelCache.java, src/main/java/org/opensearch/knn/indices/ModelDao.java, src/main/java/org/opensearch/knn/indices/ModelMetadata.java, src/main/java/org/opensearch/knn/indices/ModelState.java, src/main/resources/mappings/model-index.json, src/test/java/org/opensearch/knn/index/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java, src/test/java/org/opensearch/knn/indices/ModelCacheTests.java, src/test/java/org/opensearch/knn/indices/ModelDaoTests.java, src/test/java/org/opensearch/knn/indices/ModelMetadataTests.java, src/test/java/org/opensearch/knn/indices/ModelStateTests.java, src/test/java/org/opensearch/knn/indices/ModelTests.java, src/test/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataRequestTests.java, src/test/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataTransportActionTests.java
This PR adds additional metadata to the Model System index, so that we can implement the APIs specified in #70. The metadata that is added is:
1. State - the lifecycle state the model is in - training, created, failed
2. Timestamp - when the model was created
3. Description - field allowing users to add detail to their models
4. Error - When model is in failed state, error will indicate why it failed
Additonally, this PR adds update functionality in ModelDao so that models can initially start in TRAINING state and later be updated.
Along with this, some minor code quality changes were made as well.
This PR also adds a TODO to fix the bug in clearing the cache in the ModelDao. This will be tracked in #93.
This PR does not add search …
=> Refactor model management to support apis 

.github/workflows/CI.yml, build.gradle, src/main/java/org/opensearch/knn/index/KNNMethod.java, src/main/java/org/opensearch/knn/index/KNNMethodContext.java, src/main/java/org/opensearch/knn/index/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/MethodComponent.java, src/main/java/org/opensearch/knn/index/util/KNNEngine.java, src/main/java/org/opensearch/knn/index/util/KNNLibrary.java, src/test/java/org/opensearch/knn/index/KNNMethodContextTests.java
* Update build step to use 1.1.0-SNAPSHOT for upstream.
* With faiss, we will now support 2 methods of creating a k-NN OpenSearch index (ignoring legacy details):
From method definition
`{
"method": {
"name": "hnsw",
"engine": "faiss",
"parameters": {
"m": 42
}
}
}`
From model template
`{
"model_id": "asfnbjb"
}`
It is implied that creating an index from the first mapping requires that the underlying method requires no training.
If it did, it would fail. To differentiate those models that requires training from other, add new method that
lets library to specify whether training is required or not. Later, add it to parameter validation to fail fast rather than
fail during index operation.
By submitting this …
=> Update upstream build and add validation for model training requirement

src/main/java/org/opensearch/knn/common/KNNConstants.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java, src/main/java/org/opensearch/knn/index/util/KNNLibrary.java, src/main/java/org/opensearch/knn/indices/ModelMetadata.java, src/main/java/org/opensearch/knn/plugin/KNNPlugin.java, src/main/java/org/opensearch/knn/training/TrainingJob.java, src/main/java/org/opensearch/knn/training/TrainingJobRunner.java, src/test/java/org/opensearch/knn/index/JNIServiceTests.java, src/test/java/org/opensearch/knn/training/TrainingJobRunnerTests.java, src/test/java/org/opensearch/knn/training/TrainingJobTests.java
This PR adds training execution functionality by making several changes:
1. A single thread, KNN training pool is added in the KNNPlugin. This will allow us to sandbox resources for training
2. TrainingJob class is a runnable that was added to encapsulate everything needed to perform training
3. TrainingJobRunner class was added to handle job submission and model serialization. In handling job submission, it will only allow 1 job to be ran at a time. If a job is submitted while one is already running, it will be rejected. It serializes the model before and after training to the model system index. It adds error messages to the model on failure.
From a review perspective, please pay attention to how errors are being handled in TrainingJobRunner. I would appreciate feedback on this.
In …
=> Add training execution functionality

src/main/java/org/opensearch/knn/common/KNNConstants.java, src/main/java/org/opensearch/knn/plugin/KNNPlugin.java, src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoAction.java, src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoNodeRequest.java, src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoNodeResponse.java, src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoRequest.java, src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoResponse.java, src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoTransportAction.java, src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoNodeResponseTests.java, src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoResponseTests.java, src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoTransportActionTests.java
This PR adds a transport action that gets the number of jobs running on each node in the cluster. The response of this action will look like:
```
{
"nodes": {
"id_1": {
"training_job_count": 1
},
"id_2": {
"training_job_count": 2
},
"id_3": {
"training_job_count": 3
},
}
}
```
This action will be used in the training api to determine which node the job should be sent to.
This PR builds on top of #103. The only changes in this PR are in the following files:
1. src/main/java/org/opensearch/knn/common/KNNConstants.java
1. src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
1. src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoAction.java
1. src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoNodeRequest.java
1. …
=> Add action to get training job count on each node

src/main/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataTransportAction.java
This adds the UpdateModelMetadataAction name to the constructor of UpdateModelMetadataTransportAction. This was not caught before because the action name defaulted to "". But, when I tried adding another action with the default action name, I received an error.
=> Update action name from default to constant for UpdateModelMetadataTransportAction

src/main/java/org/opensearch/knn/indices/ModelDao.java, src/main/java/org/opensearch/knn/indices/ModelMetadata.java, src/main/java/org/opensearch/knn/training/TrainingJob.java, src/test/java/org/opensearch/knn/index/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java, src/test/java/org/opensearch/knn/indices/ModelCacheTests.java, src/test/java/org/opensearch/knn/indices/ModelDaoTests.java, src/test/java/org/opensearch/knn/indices/ModelMetadataTests.java, src/test/java/org/opensearch/knn/indices/ModelTests.java, src/test/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataRequestTests.java, src/test/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataTransportActionTests.java
Changes representation of model timestamp to a string so that indexing models does not fail.
#112 
=> Updating timestamp internal representation to string

src/main/java/org/opensearch/knn/index/KNNMethodContext.java, src/main/java/org/opensearch/knn/index/MethodComponentContext.java, src/test/java/org/opensearch/knn/index/KNNMethodContextTests.java, src/test/java/org/opensearch/knn/index/MethodComponentContextTests.java
This PR implements streaming for KNNMethodContext and MethodComponentContext classes. The train request for the train api will have a KNNMethodContext, so KNNMethodContext needs to implement stream interfaces so that the request can be passed around to different nodes.
#114 
=> Add streaming functionality to KNNMethodContext and MethodComponentContext

src/main/java/org/opensearch/knn/index/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/indices/ModelDao.java, src/test/java/org/opensearch/knn/indices/ModelDaoTests.java
This is a small change in modeldao. Instead of throwing an exception when the model is not there, it will return null. This is primarily because when validating a training request, we need to make sure that the model does not already exist, as we do not support updates. So, instead of catching an error, we can just do a null check.
=> Modify ModelDoa's getMetadata to return null instead of throw exception

src/main/java/org/opensearch/knn/indices/ModelDao.java, src/main/java/org/opensearch/knn/plugin/KNNPlugin.java, src/main/java/org/opensearch/knn/plugin/rest/RestDeleteModelHandler.java, src/main/java/org/opensearch/knn/plugin/transport/DeleteModelAction.java, src/main/java/org/opensearch/knn/plugin/transport/DeleteModelRequest.java, src/main/java/org/opensearch/knn/plugin/transport/DeleteModelTransportAction.java, src/test/java/org/opensearch/knn/plugin/action/RestDeleteModelHandlerIT.java, src/test/java/org/opensearch/knn/plugin/transport/DeleteModelRequestTests.java
Added delete model  API to delete previously added model for given ModelID.
This requires Handler to register route and prepare request,
DeleteModelRequest, DeleteModelResponse to represent request and response,
DeleteModelTransportAction to sends request across nodes.
=> Add FAIS delete model API

.github/workflows/CI.yml, build.gradle
Fetch dependencies from published locations in the following order
maven local, aws sonatype, central.
#106  
=> Use published daily snapshot dependencies

src/main/java/org/opensearch/knn/index/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/index/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/KNNWeight.java, src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java, src/main/java/org/opensearch/knn/plugin/KNNPlugin.java, src/test/java/org/opensearch/knn/index/KNNCreateIndexFromModelTests.java, src/test/java/org/opensearch/knn/index/KNNQueryBuilderTests.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
This change moves model metadata retrieval out of the model mapper build logic. The reason for this can be found in #110. From a user's perspective, the model_id they pass in during index creation will not be validated until they start ingesting documents. 
As a side effect of this change, we can no longer write values such as KNNEngine and SpaceType to the Mapper's Lucene fieldType. These values are read elsewhere in the plugin, such as during indexing in the KNNDocValuesConsumer, as well as during querying. Therefore, that logic needed to be changed as well.
I tested the changes manually on my train API implementation and they work. I also added a single node test case that creates an index from a model. Currently, this fails due to an issue with writing the timestamp. I will submit …
=> Move model metadata retrieval out of mapper build method

src/main/java/org/opensearch/knn/index/KNNMethod.java, src/main/java/org/opensearch/knn/index/MethodComponent.java, src/main/java/org/opensearch/knn/index/util/KNNLibrary.java, src/test/java/org/opensearch/knn/index/KNNMethodContextTests.java
This PR fixes a bug in the require training logic. Encoders are parameters of methods. For instance:
```
{
"name": "ivf",
"parameters": {
"encoder": {
"name": "pq",
...
}
}
}
```
Because the encoder may require training, it needs to be checked as well.
=> Fix requires training to check nested params

src/main/java/org/opensearch/knn/common/KNNConstants.java, src/main/java/org/opensearch/knn/index/IndexUtil.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryEntryContext.java, src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportAction.java, src/main/java/org/opensearch/knn/plugin/transport/TrainingModelRequest.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryAllocationTests.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryCacheManagerTests.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryEntryContextTests.java, src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportActionTests.java, src/test/java/org/opensearch/knn/plugin/transport/TrainingModelRequestTests.java
This PR switches all size estimates from Long to Int. For any native allocation type, we store a size number with it that corresponds to the number of kilobytes the allocation takes up in native memory. This is used by the cache to manage memory.
Each entry in the cache needs to provide its size as an int. Interestingly, however, the weight of the cache is a long. This is done [intentionally](https://github.com/google/guava/issues/3202).
Any way, this PR converts size estimates to ints and for functions that return long, it wraps them in `Math.toIntExact` function so that an exception will be thrown if int is overloaded by long.
#126 
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> Convert size estimates for individual allocations to ints

src/main/java/org/opensearch/knn/training/TrainingJobRunner.java, src/test/java/org/opensearch/knn/KNNRestTestCase.java, src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/plugin/action/RestTrainModelHandlerIT.java, src/test/java/org/opensearch/knn/plugin/transport/TrainingModelTransportActionTests.java, src/test/java/org/opensearch/knn/training/TrainingJobRunnerTests.java
This change will return the training response immediately after the model is initially serialized in the training state. For example:
```
POST /_plugins/_knn/models/my_model/_train
{
"training_index": "train_index",
"training_field": "train_field",
"dimension": 8,
"method": {
"name":"ivf",
"engine":"faiss",
"space_type": "l2",
"parameters":{
"nlist":16,
"encoder":{
"name":"pq",
"parameters":{
"code_size":8,
"code_count": 2
}
}
}
}
}
{"model_id":"my_model"}
GET /_plugins/_knn/models/my_model?pretty
{
"model_id" : "my_model",
"state" : "training",
"timestamp" : "2021-10-15T20:18:06.357557Z",
"error" : "",
"model_blob" : "",
"space_type" : "l2",
"dimension" : 8,
"engine" : "faiss"
}
...
GET /_plugins/_knn/models/my_model?pretty
{
"model_id" : …
```
=> Return from training after model is initially serialized

src/main/java/org/opensearch/knn/common/KNNConstants.java, src/main/java/org/opensearch/knn/index/util/KNNLibrary.java
Small PR to add `nprobes` parameter as parameter for IVF method. `nprobes` will determine how many buckets are searched during query.
=> Add nprobes as parameter to IVF

scripts/build.sh
This PR undefines simd instructions in faiss's distances_simd.h file in our build logic. These were not compiling on ARM Centos 7. I was able to confirm that this change fixes the build. In the future, I will take a closer look at this
=> Disable simd for arm faiss

src/main/java/org/opensearch/knn/indices/Model.java, src/main/java/org/opensearch/knn/indices/ModelDao.java, src/main/java/org/opensearch/knn/indices/ModelMetadata.java, src/test/java/org/opensearch/knn/plugin/action/RestGetModelHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestSearchModelHandlerIT.java, src/test/java/org/opensearch/knn/plugin/transport/GetModelResponseTests.java
Update Model Search API response to Model Index document search response.
#160 
=> Support source filtering for model search

src/main/java/org/opensearch/knn/plugin/rest/RestTrainModelHandler.java, src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportAction.java, src/main/java/org/opensearch/knn/training/TrainingJobRunner.java
PR changes validation logic to throw 400 error codes as opposed to 500 errors codes during training.
In RestTrainModelHandler, change parser.text to parser.textOrNull to allow a user to pass in a null string argument. Validation is then done later.
In training request execution, throw a validation exception if there is no training capacity. This results in a 400 error being returned
=> Return 400 on failed training request

src/main/java/org/opensearch/knn/indices/Model.java, src/main/java/org/opensearch/knn/indices/ModelDao.java, src/main/java/org/opensearch/knn/training/TrainingJob.java, src/main/java/org/opensearch/knn/training/TrainingJobRunner.java, src/main/resources/mappings/model-index.json, src/test/java/org/opensearch/knn/KNNRestTestCase.java, src/test/java/org/opensearch/knn/index/KNNCreateIndexFromModelTests.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java, src/test/java/org/opensearch/knn/indices/ModelCacheTests.java, src/test/java/org/opensearch/knn/indices/ModelDaoTests.java, src/test/java/org/opensearch/knn/indices/ModelTests.java, src/test/java/org/opensearch/knn/plugin/action/RestSearchModelHandlerIT.java, src/test/java/org/opensearch/knn/plugin/transport/RemoveModelFromCacheTransportActionTests.java, src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoTransportActionTests.java, src/test/java/org/opensearch/knn/training/TrainingJobRunnerTests.java, src/test/java/org/opensearch/knn/training/TrainingJobTests.java
This PR restructures the model id to be a part of the model index's mapping. Previously, the model_id was stored only as the document id of the model in the index. This PR adds the "model_id" field to the mapping.
Additionally, this PR refactors the model logic to require a non-null model id during construction. Therefore, to create a Model object, a non-null model id needs to be passed in.
This PR will allow users to filter model search by model_id using _source_includes.
#136  …
=> Make model id part of index

build.gradle, jni/CMakeLists.txt, jni/tests/faiss_wrapper_test.cpp, scripts/build.sh
This PR adds the libgomp library into the knn zip. This will make it so that tar users do not need to install openmp on their machine to use. 
I tested by building the zip and copying it in to opensearch tar on arm and x64 for AL2, Ub16, Ub20. 
Along with this, I fixed a testcase for JNI, simplified CMake logic and fixed build.gradle to just build the lib and not the tests.
#174 
=> Package openmp lib with knnlib in zip and minor fixes

src/main/java/org/opensearch/knn/indices/ModelDao.java, src/main/java/org/opensearch/knn/plugin/stats/KNNStatsConfig.java, src/main/java/org/opensearch/knn/plugin/stats/StatNames.java, src/main/java/org/opensearch/knn/plugin/stats/suppliers/ModelIndexStatusSupplier.java, src/test/java/org/opensearch/knn/indices/ModelDaoTests.java, src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
Add Model Index Status to Stats API.
1. if model index is not created, value will be null,
2. if model index exists, return index health status as model index status.
#151 
=> Include Model Index status as part of Stats API

src/main/java/org/opensearch/knn/training/TrainingJob.java, src/main/java/org/opensearch/knn/training/TrainingJobRunner.java, src/test/java/org/opensearch/knn/training/TrainingJobTests.java
This change generalizes the error message exposed to user when training fails. Before, we just set the message as the exception. However, this can expose internal details of the service. So, this generalizes the messages.
=> Generalize error message set in model metadata

jni/src/jni_util.cpp
Delete local references during map conversion. This should not have an effect on maps we're looping over now, given that they are so small, but could have an effect on maps we loop over in the future.
=> Delete local references when looping over map

jni/include/jni_util.h, jni/src/faiss_wrapper.cpp, jni/src/jni_util.cpp, jni/src/nmslib_wrapper.cpp, jni/src/org_opensearch_knn_jni_FaissService.cpp, jni/src/org_opensearch_knn_jni_NmslibService.cpp, jni/tests/test_util.cpp, jni/tests/test_util.h
This PR adds Java class and method caching to both JNI libraries. FindClass/FindMethod functions can be expensive calls from C++ layer, so it is [recommended](https://developer.ibm.com/articles/j-jni/) to cache these values. For caching implementation, I followed [this SO post answer](https://stackoverflow.com/a/13940735). From a high level, the JNI_onLoad and JNI_onUnload methods will be called when the library is loaded/unloaded by the JVM. Here, we call an initialization function which sets up the caches.
gradle tests as well as google tests both pass.
For more information on following Developer Certificate of Origin and …
=> Add caching of java classes/methods

jni/include/faiss_wrapper.h, jni/include/jni_util.h, jni/include/org_opensearch_knn_jni_FaissService.h, jni/src/faiss_wrapper.cpp, jni/src/jni_util.cpp, jni/src/nmslib_wrapper.cpp, jni/src/org_opensearch_knn_jni_FaissService.cpp, src/main/java/org/opensearch/knn/common/KNNConstants.java, src/main/java/org/opensearch/knn/index/KNNWeight.java, src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java, src/main/java/org/opensearch/knn/jni/FaissService.java, src/main/java/org/opensearch/knn/jni/JNIService.java, src/main/java/org/opensearch/knn/training/TrainingJob.java, src/test/java/org/opensearch/knn/jni/JNIServiceTests.java, src/test/java/org/opensearch/knn/training/TrainingJobTests.java
This change fixes a couple bugs related to parameter passing in the JNI. First, we accidentally deleted the logic to pass efSearch and indexThreadQty to jni for nmslib. This fix is added here.
Second, faiss uses OpenMP for thread management. To set the number of threads, we can use the function `omp_set_num_threads`. This function will determine how many threads to use for parallel sections of the code later in the thread. This call will only impact the parallel function calls made in this thread so it is thread safe. This PR adds the indexThreadQty setting to set this for faiss. …
=> Fix bugs in parameter passing to JNI

jni/src/jni_util.cpp
Minor bug fix. With #186 we changed how we looked up classes and methods. With this change, it is no longer necessary to look up classes in the map conversion function. This PR removes those calls.
=> Remove unused code from function

jni/src/faiss_wrapper.cpp, src/main/java/org/opensearch/knn/index/MethodComponent.java, src/main/java/org/opensearch/knn/index/util/KNNLibrary.java, src/test/java/org/opensearch/knn/index/MethodComponentTests.java
This PR fixes 2 bugs. First, in the faiss jni, it was trying to parse a sub map in the parameters to set additional parameters. However, in Java, no sub map of parameters is created. The additional parameters are just added to the parameters directly. To fix this, we just flatten out the setting extra parameters call. This is hard to test with unit tests, so I verified manually with logs.
Second, this PR fixes an issue with passing default values to the JNI. Previously, defaults were not getting added to the parameter map, so they were not getting passed to the JNI. This was causing us to use the defaults of the libraries. To fix this, I added a step of adding default parameters into the map when they are not passed by the user.
By …
=> Fix issue setting parameters

jni/src/faiss_wrapper.cpp, jni/src/nmslib_wrapper.cpp, src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java, src/main/java/org/opensearch/knn/index/util/KNNLibrary.java, src/test/java/org/opensearch/knn/index/util/KNNLibraryTests.java, src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
This PR finishes fixing the issue that was originally addressed in #199. The problem was that nmslib expected algo parameters to be in a flat map while faiss expected algo parameters to be nested in a parameters sub map. This PR fixes that issue: the expectation is algo params are in a nested parameters sub map.
This logic is very confusing and should be simplified in the future. I will create an issue to track this
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin …
=> Fix parameter validation for both libs

src/main/java/org/opensearch/knn/index/IndexUtil.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryEntryContext.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategy.java, src/main/java/org/opensearch/knn/plugin/transport/TrainingModelRequest.java, src/main/java/org/opensearch/knn/plugin/transport/TrainingModelTransportAction.java, src/main/java/org/opensearch/knn/training/TrainingJob.java, src/main/java/org/opensearch/knn/training/VectorReader.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryEntryContextTests.java, src/test/java/org/opensearch/knn/training/VectorReaderTests.java
This PR fixes the bug when training data index shard is not on training node. It uses the validation logic used in training model request in VectorReader. Additionally, for VectorReader, IndicesService is swapped out with ClusterService.
Lastly, this PR adds a couple error increments in TrainingJob that were not getting picked up.
#205 
=> Fix field validation in VectorReader

release-notes/opensearch-knn.release-notes-1.2.0.0.md
Adds release notes for 1.2. Included notes are all PR's merged to main. PR's merged to feature/faiss-support are not included in release notes
#102 
=> Add release notes for 1.2

jni/CMakeLists.txt.in
Changes google test from master to main. WIll fix https://github.com/opensearch-project/k-NN/actions/runs/1463837306.
=> Change googletest from master to main

.github/workflows/backport.yml, DEVELOPER_GUIDE.md
Add autobackport functionality to k-NN. Will try on 1.2.
#233 
=> Add auto backport functionality to k-NN

.github/workflows/links.yml, src/main/java/org/opensearch/knn/index/KNNVectorFieldMapper.java, src/test/java/org/opensearch/knn/KNNRestTestCase.java, src/test/java/org/opensearch/knn/index/OpenSearchIT.java
Add ability to reset vector value by using 'null'
Adding possibility to unset vector's value by updating vector field with 'null' value
#51 
=> Add reset for vector

build.gradle, jni/CMakeLists.txt
=> Bump OpenSearch version to 1.2.1

.github/workflows/CI.yml, build.gradle, jni/CMakeLists.txt, src/test/java/org/opensearch/knn/plugin/transport/RemoveModelFromCacheTransportActionTests.java
Bump to 1.2.2 and comment flaky tests
#243 
=> Bump to 1.2.2 and comment flaky tests

src/test/java/org/opensearch/knn/KNNRestTestCase.java, src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestTrainModelHandlerIT.java, src/test/java/org/opensearch/knn/plugin/transport/RemoveModelFromCacheTransportActionTests.java
In #246 , @martin-gaievski suggested we Ignore as opposed to commenting out for flaky tests. I agree this is a cleaner way of handling flaky test so this PR adds that.
It also fixes one of the commented out tests from training that had been left commented out because the particular functionality was not available when the tests were written.
Lastly, it removes the KNNStats flaky test. This test is too complicated for the value it adds (making sure a counter gets incremented). Therefore, I think it is better just to remove it. We have tested counter functionality in uTs and other iTs.
#43
For more information on following Developer Certificate of Origin and signing off your …
=> Clean up flaky tests

build-tools/repositories.gradle, build.gradle
Removing all direct dependencies on jcenter() within a repositories block. Repository has been shut down and replaced by mavenCentral(), see parent issue for detailed explanation. 
[Remove jcenter repository #260](https://github.com/opensearch-project/k-NN/issues/260)
=> Removing jcenter repo from repositories blocks in gradle files

.github/workflows/backport.yml
Copying backport action permissions fix from OpenSearch repo [Fixing auto backport workflow](https://github.com/opensearch-project/OpenSearch/pull/1845). 
Currently backport action workflow is failing with "permission denied", [example](https://github.com/opensearch-project/k-NN/runs/4808810861?check_suite_focus=true).
NA
=> Adding write permissions to backport action

src/test/java/org/opensearch/knn/KNNRestTestCase.java, src/test/java/org/opensearch/knn/TestUtils.java, src/test/java/org/opensearch/knn/bwc/KNNBackwardsCompatibilityIT.java, src/test/java/org/opensearch/knn/recall/RecallTestsIT.java
Adding recall tests to integration tests and backward compatibility tests. This includes two separate tests where the vectors are generated using some standard function in one test and randomly generated vectors in other test. 'l2' is the spaceType used to measure distance between two points.
https://github.com/opensearch-project/k-NN/issues/250
=> Add Recall Tests

src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
With this change making KNNPlugin implementing ExtensiblePlugin interface. This enables plugin extension to contributors who had forked from main OS repository. ExtensiblePlugin has default implementation for its only method loadExtensions, and KNNPlugin does not override it with this initial implementation.
[#180](https://github.com/opensearch-project/k-NN/issues/180)
=> Adding ExtensiblePlugin to KNNPlugin

benchmarks/perf-tool/README.md, benchmarks/perf-tool/okpt/io/config/parsers/util.py, benchmarks/perf-tool/okpt/io/dataset.py, benchmarks/perf-tool/okpt/test/steps/steps.py, benchmarks/perf-tool/sample-configs/faiss-sift-ivf/test.yml, benchmarks/perf-tool/sample-configs/nmslib-sift-hnsw/test.yml
This change refactors how the benchmarking tool works with datasets. It creates a DataSet interface and implements the interface for the existing HDF5 format as well as the formats specified in [Big ANN Benchmarks](https://big-ann-benchmarks.com/index.html#bench-datasets). It then introduces these changes in the steps that need datasets. 
=> Refactor benchmark dataset format and add big ann benchmark format

DEVELOPER_GUIDE.md, build.gradle, src/test/java/org/opensearch/knn/index/KNNCircuitBreakerIT.java
Adding integTestRemote gradle task that allows to run kNN integration tests in remote cluster 
#198 
=> Adding gradle task for running integ tests in remote cluster

src/main/java/org/opensearch/knn/index/KNNWeight.java
This change adds L2 space type fall back during query. This prevents backwards compatibility issues for clusters upgrading from ES 7.1 and 7.4. In those versions, space type was not introduced as a field attribute yet.
#255 
=> Set default space type to L2 to support bwc

benchmarks/perf-tool/README.md, benchmarks/perf-tool/okpt/test/steps/steps.py
Makes the document and query count configurable in the benchmarking tool. With this functionality, users can now specify to only index or search a subset of the vectors in the data set. This is useful for indices that require training that may only need a subset of the data set for training.
A query or ingest step might look like this now:
```
steps:
...
- name: ingest
index_name: target_index
field_name: target_field
bulk_size: 500
dataset_format: hdf5
dataset_path: mydata.hdf5
doc_count: 50000
...
- name: query
k: 100
r: 1
index_name: target_index
field_name: target_field
dataset_format: hdf5
dataset_path: mydata.hdf5
query_count: 5
neighbors_format: hdf5
neighbors_path: mydata.hdf5
```
By submitting this pull request, I confirm that my …
=> Make doc and query count configurable in benchmark

.github/workflows/CI.yml, DEVELOPER_GUIDE.md
Adding JDK 11 to CI matrix of java versions, replacing as minimum prerequisite in Dev readme guide. Main reason for change - JDK 11 is the latest supported LTS. For now I couldn't make JDK 8 and 17 work, plugin build has multiple issues with each of those versions.
#220 
=> Adding JDK 11 to CI and docs

benchmarks/perf-tool/okpt/test/steps/steps.py
When running a benchmark with one of the BIGANN data sets, the tool was killed due to OOM during ingest step:
```
dmesg -T| grep -E -i -B100 'killed process'
...
[Fri Jan 28 02:00:36 2022] Out of memory: Killed process 8825 (python3) total-vm:72456280kB, anon-rss:70883120kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:139388kB oom_score_adj:0
```
Looking into the ingest step, I realized the problem was most likely that we were collecting the responses to the index requests. Because we dont use these responses (we just track total time), we can just get rid of this collection.
For more information on following Developer …
=> [Benchmark] Remove ingest results collection

src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
CI keeps failing because of our Codec tests: https://github.com/opensearch-project/k-NN/actions/runs/1820922609. It is due to threads leaking. This PR closes a 2 closeables that were causing an issue:  IndexLoadStrategy, resourceWatcherService.
CI was able to pass on my fork: https://github.com/jmazanec15/k-NN-1/actions/runs/1821011151.
=> [FLAKY TEST] Fix codec test causing CI to fail

src/main/java/org/opensearch/knn/index/IndexUtil.java, src/main/java/org/opensearch/knn/index/KNNIndexShard.java, src/main/java/org/opensearch/knn/index/KNNWeight.java, src/test/java/org/opensearch/knn/index/IndexUtilTests.java
Warmup is used to load native library files into memory so that there are no initial latency penalties during search. The load process for search and warmup are very similar. 
Currently, warmup api has a similar bug to #267. It does not default to a space type. For customers upgrading to 1.2 from ES 7.1 or 7.4 this will cause warmup failure. This only applies to 1.2. 1.1 and 1.0 do not have this bug in warmup.
Additionally, for nmslib, we allow the ef_search parameter to be set after indexing. To do this, we pass the parameter in during loading. In 1.2, we did not pass this parameter in. This will cause default ef_search to be used during warmup. To clean this up a bit, I abstracted generating load parameters into a utility function and used the same one for both search as well as warmup. …
=> [BUG FIX] Add space type default and ef search parameter in warmup

.github/workflows/CI.yml
Github doesn't support non-standard like @daily, we have to use
standard cron syntax.
=> Add CI to run every night

src/main/java/org/opensearch/knn/index/IndexUtil.java, src/main/java/org/opensearch/knn/index/KNNIndexShard.java, src/main/java/org/opensearch/knn/index/KNNWeight.java, src/test/java/org/opensearch/knn/index/IndexUtilTests.java
Sets the default value of space type to L2 in KNNIndexShard.
KNNIndexShard is used during warmup to load segments into memory. For
indices created in ES 7.1 and 7.4, they will not have this value set
because the only space we supported was l2. So, we need to hardcode the
defaults here.
For nmslib, the ef_search parameter is configurable at load time. So, it
needs to be passed as a parameter in both the search load phase as well
as warmup. This commit adds it to the warmup phase and abstracts load
parameters to a helper function so that it can be consistent for both
search and warmup.
For more information on following Developer Certificate of Origin and signing off your …
=> [Backport 1.2] [BUG FIX] Add space type default and ef search parameter in warmup

.github/workflows/delete_backport_branch.yml
Signed-off-by: Vacha Shah <vachshah@amazon.com>
(cherry picked from commit cb1a7d8a305bf67911280d0f072e6d8962b4eb77)
Manually backporting since my DCO was messed up in the PR from bot #290.
=> Adding auto delete workflow for backport branches (#289)

build.gradle, checkstyle/checkstyle.xml
Upgrades guava dependency as well as checkstyle dependency (which has a guava dependency as well) to address CVE.
#283 #282 
=> Updates Guava versions to address CVE

src/main/java/org/opensearch/knn/index/KNNIndexShard.java, src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java, src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java, src/test/java/org/opensearch/knn/index/KNNIndexShardTests.java
Fixes getEnginePaths in KNNIndexShard to retrieve all engine paths, regardless of what version the index was created. Prevents silent failure when warmup completes but doesnt load any segments.
Instead of checking if the engine file that the current version of the plugin would create is in the segment, it just checks the prefix and suffix of the file that would be created. To prevent this failure in the future, a new test was added. Intentionally, the structure is hardcoded. This will ensure that this will be caught in the future if segment file naming conventions change.
#308  …
=> [BUG FIX] Fix knn index shard to get bwc engine paths

release-notes/opensearch-knn.release-notes-1.3.0.0.md
Add release notes for 1.3.0.0
https://github.com/opensearch-project/k-NN/issues/300
=> Add release notes for 1.3.0.0

build.gradle
Removing support for JDK8 to be in sync with main OpenSearch. 
#311 
=> Change minimum supported JDK version from 8 to 11

.github/workflows/CI.yml, DEVELOPER_GUIDE.md
Adding JDK17 support - added JDK17 to CI matrix, updated developer guide with note of support
#312 
=> Adding JDK 17 to CI

benchmarks/perf-tool/requirements.txt, build.gradle, jni/CMakeLists.txt
Removes setting of versions in CMake and pushed them to build.gradle. Version is used in CMake for building RPM/DEB with CPack. Currently, the CPack logic is not used in the OpenSearch project. Not removing because it may be used by others that build the plugin separately.
In addition, PR bumps numpy to fix whitesource failures. This is in line with 1.x branch.
#82 
=> Remove version from CMakeLists.txt

src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
Manually adds Lucene footer to engine files to prevent an unnecessary copy from one file to another.
A few things had to be changed to get this to work. First, before creating the enginefile, an IndexOutput had to be created and then closed so that the [TrackingDirectoryWrapper](https://github.com/apache/lucene/blob/branch_9_0/lucene/core/src/java/org/apache/lucene/store/TrackingDirectoryWrapper.java#L42) would be able to track the file. 
Next, the footer magic number and crc algorithm index (0) had to be appended to the end of the file. More details on how Lucene does this can be found [here](https://github.com/apache/lucene/blob/branch_9_0/lucene/core/src/java/org/apache/lucene/codecs/CodecUtil.java#L390-L412).
Lastly, the checksum gets computed and added to the end of the file.
No new …
=> Manually add footer to engine files

build.gradle
We need to apply build.version_qualifier parameter only to plugin artifacts. For base OpneSearch the version with its qualifier has to be set explicitly via opensearch.version. 
Base [on this reply](https://github.com/opensearch-project/k-NN/pull/329#issuecomment-1075820345)
#315
=> Applying build qualifier only to knn plugin version

.github/workflows/CI.yml
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
Remove hardcoding of version in knn CI.
The value should be taken from build.gradle.
Thanks.
Part of https://github.com/opensearch-project/opensearch-build/issues/1632
=> Remove hardcoding of version in knn CI

.github/workflows/CI.yml, build.gradle, jni/CMakeLists.txt
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
Bump version to 1.3.1
Part of https://github.com/opensearch-project/opensearch-build/issues/1805
=> Bump version to 1.3.1

DEVELOPER_GUIDE.md
Put description of new versioning for codecs from PR description #328 to dev guide.  
No master issue yet, aiming 2.0 release
=> Adding documentation on codec versioning

build-tools/knnplugin-coverage.gradle, src/test/java/org/opensearch/knn/KNNRestTestCase.java
According to security recommendation and as per the best coding practice, removing hardcoded URL in tests. 
=> remove hardcoded URL

benchmarks/perf-tool/okpt/test/steps/factory.py, benchmarks/perf-tool/okpt/test/steps/steps.py
Adding clear_cache step to benchmarking tool. It can be used at the beginning of each query run to clean up OpenSearch query cache. This should give more relevant results for test with multiple runs. 
Example of usage:
```
- name: clear_cache
index_name: target_index
```
=> Adding clear cache test step

.github/workflows/CI.yml
Remove support for JDK 14
#342
=> Dropping support for JDK 14

build.gradle, jni/CMakeLists.txt
Signed-off-by: Sayali Rohidas Gaikawad <gaiksaya@amazon.com>
Coming from https://github.com/opensearch-project/opensearch-build/issues/1805 post release activity.
=> Incremented version to 1.3.2.

src/main/java/org/opensearch/knn/index/KNNMethodContext.java, src/main/java/org/opensearch/knn/index/MethodComponentContext.java, src/test/java/org/opensearch/knn/bwc/KNNBackwardsCompatibilityIT.java, src/test/java/org/opensearch/knn/index/KNNMethodContextTests.java, src/test/java/org/opensearch/knn/index/MethodComponentContextTests.java
By default, in OpenSearch 1.0 and 1.1, if parameters were not set for method definitions, they were assigned a value of null. This causes an issue on upgrade to 1.2+, where null values for parameters are not accepted and throw a MappingParsingException.
The fix is to skip parsing the parameter value as a map in the input JSON if it is null.
#353 
=> Allow null value for params in method mappings

src/main/java/org/opensearch/knn/index/KNNMethodContext.java, src/main/java/org/opensearch/knn/index/MethodComponentContext.java, src/test/java/org/opensearch/knn/index/KNNMethodContextTests.java, src/test/java/org/opensearch/knn/index/MethodComponentContextTests.java
Allow user to input null value for parameters field for KNNMethodContext
and MethodComponentContext. Adds tests to reproduce Mapping Parsing Error when the parameters take
the value null as well as BWC tests.
Backport: #354 
(cherry picked from commit b08127c2c4dcd1844072302e838f44897c8f18f5)
=> [Backport 1.2] Allow null value for params in method mappings

src/main/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataTransportAction.java, src/test/java/org/opensearch/knn/indices/ModelDaoTests.java, src/test/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataTransportActionTests.java
Change `master` nomenclature to `cluster manager`. Still there are few changes(package names, method names) which needs to be done. Will make those changes after those changes are implemented in opensearch core.
https://github.com/opensearch-project/k-NN/issues/307
=> Nomenclature changes from master to cluster manager

build.gradle
Update jacoco version to 0.8.7 for JDK17 support. Current version gives error:
` Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61`
#299 
=> Update jacoco version to 0.8.7 to support JDK 17

scripts/build.sh
=> [Backport 1.x] Rename knnlib to lib

build.gradle
Switching to 2.0 main branch after 2.0 rc1 has been released
#384 
=> Remove rc1 build qualifier for 2.0 GA release

build.gradle, scripts/build.sh, settings.gradle
Follow [campaign](https://github.com/opensearch-project/opensearch-build/issues/1916) and use custom plugin to publish zips to maven
#378 
=> Use custom plugin to publish zips to maven

build.gradle
Currently [default command](https://quip-amazon.com/ChbFAQFDCpFt/k-NN-OpenSearch-Release-Process-13#temp:C:HZJ7eff15970940422e91225734f) for  running integTests doesn't work because [core OS](https://github.com/opensearch-project/OpenSearch/blob/main/test/framework/src/main/java/org/opensearch/bootstrap/BootstrapForTesting.java#L125-L192) can't set security manager properly. This happens for the plugin while setting read-only property that has been already set for core OS
```
Caused by:
java.lang.IllegalStateException: codebase property already set: codebase.opensearch-knn -> file:/Users/gaievski/dev/opensearch/k-NN/build/distributions/opensearch-knn-2.0.0.0-SNAPSHOT-test-fixtures.jar, cannot set to …
```
=> Set tests.security.manager flag to false in integTestRemote task

.github/workflows/backwards_compatibility_tests_workflow.yml, build.gradle, gradle/wrapper/gradle-wrapper.properties, qa/restart-upgrade/build.gradle, src/main/java/org/opensearch/knn/index/codec/KNNCodecFactory.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecFactoryTests.java, src/testFixtures/java/org/opensearch/knn/ODFERestTestCase.java
Upgrade core OpenSearch version to 2.1.0 after 2.0.0 GA release. 
#385 
=> Bumping main version to opensearch core 2.1.0

src/main/java/org/opensearch/knn/training/VectorReader.java, src/test/java/org/opensearch/knn/training/VectorReaderTests.java
Refactors VectorReaderListener onResponse to expect arrays of Number type from search result instead of Double type. This will allow the training to handle cases where the vectors source is stored as an integer array. Adds test case to confirm that it can handle Integer type. Cleans up tests in VectorReaderTest class. 
Credit to @martin-gaievski for the suggested fix.
#415 
=> Change VectorReaderListener to expect number array

src/main/java/org/opensearch/knn/plugin/script/KNNWhitelistExtension.java, src/test/java/org/opensearch/knn/plugin/script/PainlessScriptIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
When KNN Vector values are being accessed inside "scripted_metric", following error is observed
```
caused_by":{"type":"illegal_argument_exception","reason":"Illegal list shortcut value [value]."}}}]},"status":400}
```
This is because, ScriptedMetricContext is not added to allow list for doc['knn_vector'].value method to be accessible. 
This PR adds those context that are needed to be included to allow list.
#414 
=> Include scripted metric context to allow list

src/main/java/org/opensearch/knn/index/KNNMethod.java, src/main/java/org/opensearch/knn/index/KNNMethodContext.java, src/main/java/org/opensearch/knn/index/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/MethodComponent.java, src/main/java/org/opensearch/knn/index/MethodComponentContext.java, src/main/java/org/opensearch/knn/index/codec/KNNCodecFactory.java, src/main/java/org/opensearch/knn/index/codec/KNNCodecService.java, src/main/java/org/opensearch/knn/index/codec/util/CodecBuilder.java, src/main/java/org/opensearch/knn/training/TrainingJob.java, src/test/java/org/opensearch/knn/index/KNNMethodContextTests.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecFactoryTests.java, src/test/java/org/opensearch/knn/index/codec/KNNFormatFactoryTests.java, src/test/java/org/opensearch/knn/jni/JNIServiceTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceTests.java, src/test/java/org/opensearch/knn/training/TrainingJobTests.java
Refactor few things in plugin in order to open possibilities for future extensions required for https://github.com/opensearch-project/k-NN/issues/39
- add KNNMethodContext to KNNVectorFieldType
- pass mapperService to codec implementation, so later we can read type information when initialize codec. We can retrieve knn vector mappedFieldType similar to what is done in POC for core https://github.com/martin-gaievski/OpenSearch/blob/lucene-ann-integ/server/src/main/java/org/opensearch/index/codec/KnnVectorsFormatFactory.java#L33. This is required to initialize per field vector format with _m_ (_max_connections_) and _efConstruction_ (_beam_width_) based on mapping values.
- code cleanup, use lombok syntax where applicable
building block …
=> Refactor knn type and codecs

src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java, src/main/java/org/opensearch/knn/index/codec/KNN920Codec/KNN920Codec.java, src/main/java/org/opensearch/knn/index/codec/KNNCodecFactory.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java, src/test/java/org/opensearch/knn/index/LuceneIT.java, src/test/java/org/opensearch/knn/index/codec/KNN920Codec/KNN920CodecTests.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecFactoryTests.java, src/test/java/org/opensearch/knn/index/codec/KNNFormatFactoryTests.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
Adding field mapper and per field format for Lucene knn vector format including one integ test for indexing
Related https://github.com/opensearch-project/k-NN/issues/380
=> [feature/lucene-knn] Add field mapper and per field format

src/main/java/org/opensearch/knn/index/codec/KNN920Codec/KNN920Codec.java, src/main/java/org/opensearch/knn/index/codec/KNN920Codec/KNN920PerFieldKnnVectorsFormat.java, src/main/java/org/opensearch/knn/index/codec/KNNCodecFactory.java, src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java, src/test/java/org/opensearch/knn/index/codec/KNN920Codec/KNN920CodecTests.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
Added more unit tests around Lucene hnsw, refactor KNN920PerFieldKnnVectorsFormat into a public class (mainly to improve testability)
part of https://github.com/opensearch-project/k-NN/issues/380
=> Refactor per field format to a class, add more unit tests

src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/plugin/script/PainlessScriptIT.java
Adds support for doc values for fields using the Lucene engine. If enabled, doc values will be produced for Lucene k-NN fields. This means that users can use painless scripting for indices using the Lucene engine.
#380 
=> Support doc values for fields using Lucene engine

src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/util/KNNEngine.java, src/main/java/org/opensearch/knn/indices/ModelMetadata.java, src/test/java/org/opensearch/knn/index/OpenSearchIT.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/indices/ModelTests.java
Re-write validation for max dimensions to make it engine specific comparing to one global validation. 
building block for #380 
=> Add engine specific validation for max dimensions

src/main/java/org/opensearch/knn/index/KNNMethodContext.java, src/main/java/org/opensearch/knn/index/SpaceType.java, src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java, src/test/java/org/opensearch/knn/index/KNNMethodTests.java, src/test/java/org/opensearch/knn/index/LuceneEngineIT.java, src/test/java/org/opensearch/knn/index/LuceneIT.java, src/test/java/org/opensearch/knn/index/SpaceTypeTests.java, src/testFixtures/java/org/opensearch/knn/TestUtils.java
Adds query integration tests for the lucene engine. Moves spacetype to
lucene vectorsimilarityfunction translation to SpaceType enum for
testability.
=> Add query integration tests for Lucene engine

.github/workflows/backwards_compatibility_tests_workflow.yml, qa/rolling-upgrade/build.gradle
Update Rolling Upgrade BWC framework to read BWC version from backwards_compatibility_tests_workflow.
=> Read BWC Version from Github workflow

gradle/wrapper/gradle-wrapper.properties
Bump Gradle version to 7.5
https://github.com/opensearch-project/k-NN/issues/468
=> Bump Gradle version to 7.5

.github/workflows/backwards_compatibility_tests_workflow.yml, qa/rolling-upgrade/build.gradle
(cherry picked from commit 9f71ede43c7d6e7e90156fae65d7d45f676cc39e)
Backport https://github.com/opensearch-project/k-NN/pull/476/commits/e02557512aa7ea618de23dd087132a2129f8c8e7 from https://github.com/opensearch-project/k-NN/pull/476
=> [Backport 2.x] Read BWC Version from Github workflow (#476)

src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
Address appsec finding related to expose of extra info and returning response code 500. Catching error on parsing and throw IllegalArgumentException error that results in error code 400. 
```
Problem Details
When some field key names or dimension values are submitted to the /<INDEX_‐
NAME>/_mapping API, the service responds with a HTTP 500 error response.
dimension Integer Overflow
The k-NN plugin does not allow knn_vector fields with a dimension greater than 1024.
Values of dimension between 1025 and 2,147,483,647 (i.e., 231 − 1) return a 400 error as
1. Create an example index.
curl -X PUT "http://<cluster_host>/example_index"
2. Attempt to create a kNN field with a dimension of 2,147,483,648 or greater.
curl -v -X PUT …
```
=> Change validation error for dimension value

src/main/java/org/opensearch/knn/index/util/Lucene.java, src/test/java/org/opensearch/knn/index/LuceneEngineIT.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
Remove Inner product (or Dot product) from list of supported similarity functions for Lucene engine. This is due to specifics of [Lucene implementation of Dot product](https://github.com/apache/lucene/blob/branch_9_2/lucene/core/src/java/org/apache/lucene/index/VectorSimilarityFunction.java#L72-L74), score can be negative which violates OpenSearch concept. Tested by following test case. Plan is to test/address this issue properly and then open support in later versions.
for 2 vectors ```[-10.0, -10.0]``` and ```[10.0, 10.0]```  and search request ```[10, 10]``` here is the response
```
{
"took": 1,
"_shards": {
"total": 1,
"successful": 1,
"skipped": 0,
"failed": 0
},
"hits": {
"total": {
"value": 2,
"relation": "eq" …
```
=> Make innerproduct similarity not supported

src/main/java/org/opensearch/knn/index/util/KNNEngine.java, src/main/java/org/opensearch/knn/indices/ModelMetadata.java
Increases max dimension to 16k for nmslib and faiss. Lucene has its own limit which we cannot override, so that will not change. 
> Running benchmarks for 16k dimension random data set. Once complete, I will add them to #455 and take PR out of draft mode.
Benchmarks completed. Details can be found https://github.com/opensearch-project/k-NN/issues/455#issuecomment-1204584999.
#455 
=> Increase max dimension to 16k for nmslib and faiss

.github/workflows/backwards_compatibility_tests_workflow.yml
Remove 1.0.0 BWC and switch to version 1.1.0, related issue https://github.com/opensearch-project/OpenSearch/issues/3001
=> Remove 1.0.0 for BWC test

jni/src/faiss_wrapper.cpp
Removes overallocation of 2 c++ vectors in faiss querying functionality.
Performance results can be viewed in [497](https://github.com/opensearch-project/k-NN/issues/497#issuecomment-1208643311).
In general, this change could provide a small improvement in memory
footprint during search workloads.
#497 
=> Remove overallocation in faiss query path

src/main/java/org/opensearch/knn/index/query/KNNWeight.java
Currently, we grow the size of the DocIDSetBuilder to the maximum id in the results returned by the query. The grow function, however, is intended to take the [number of docs](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/util/DocIdSetBuilder.java#L187) the iterator should have, not the maximum doc id.
Internally, this method has logic to determine whether the iterator should be a sparse set of doc ids, or a dense bit set, where 1 indicates whether a docid is set or not. This can cause problems where the wrong iterator type is created. For instance, assume our results are [200,000,000]. Num docs = 1, but max doc = 200,000,000. This would then cause a bitset of 200,000,000 entries to be created for a single doc. Instead, if we set the length to 1, the …
=> Change initial size of DocIdSetBuilder

benchmarks/osb/README.md, benchmarks/osb/params/no-train-params.json, benchmarks/osb/params/train-params.json, benchmarks/osb/procedures/no-train-test.json, benchmarks/osb/procedures/train-test.json
Adds a configurable forcemerge operation in our opensearch benchmarks
procedures. After refreshing the indexing, forcemerging will control the
number of segments that will be created before querying. This will make
query latencies more consistent.
Added 2 parameters: 
1. target_index_max_num_segments - Number of segments to merge target index down to before beginning search
2. target_index_force_merge_timeout - Timeout for of force merge requests.
Updated docs. Ran procedures using sift data set and pasted results in README score section.
#504  …
=> Add force merge operation in OSB tests

src/main/java/org/opensearch/knn/index/KNNCircuitBreaker.java, src/main/java/org/opensearch/knn/indices/ModelGraveyard.java, src/main/java/org/opensearch/knn/plugin/transport/UpdateModelGraveyardTransportAction.java, src/main/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataTransportAction.java, src/test/java/org/opensearch/knn/plugin/transport/UpdateModelGraveyardTransportActionTests.java, src/test/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataTransportActionTests.java
Nomenclature Changes- Replace "master" with "cluster manager"
The below two packages are still not supported by opensearch core and is expected to be ready by 3.0 : 
- org.opensearch.action.support.master.AcknowledgedRequest -> org.opensearch.action.support.clusterManager.AcknowledgedRequest
- org.opensearch.action.support.master.AcknowledgedResponse -> org.opensearch.action.support.clusterManager.AcknowledgedResponse
https://github.com/opensearch-project/k-NN/issues/307 …
=> Replace terminology 'master' with 'cluster manager'

.github/workflows/backwards_compatibility_tests_workflow.yml
Updated the BWC workflow to have 2.2.0 as the backward supported version in BWC tests
#524
=> Updated the BWC workflow to have 2.2.0 as the backward supported version in BWC tests

src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java, src/test/java/org/opensearch/knn/index/LuceneEngineIT.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
Multiple changes:
- adding tests
- adding log info
- minor code adjustments/reformatting 
https://github.com/opensearch-project/k-NN/issues/376
=> Adding tests and logs for Lucene k-NN filtering 

README.md
Signed-off-by: cwillum <cwmmoore@amazon.com>
Replaced the link to the Forum discussion in the README.md file so that it points to the OpenSearch forum rather than the defunct Open Distro forum.
This fixes the issue for the k-NN plugin in [#921](https://github.com/opensearch-project/documentation-website/issues/921).
=> Replace Forum link in k-NN plugin README.md

benchmarks/perf-tool/release-configs/faiss-ivf/index.json, benchmarks/perf-tool/release-configs/faiss-ivf/method-spec.json, benchmarks/perf-tool/release-configs/faiss-ivf/test.yml, benchmarks/perf-tool/release-configs/faiss-ivf/train-index-spec.json, benchmarks/perf-tool/release-configs/faiss-ivfpq/index.json, benchmarks/perf-tool/release-configs/faiss-ivfpq/method-spec.json, benchmarks/perf-tool/release-configs/faiss-ivfpq/test.yml, benchmarks/perf-tool/release-configs/faiss-ivfpq/train-index-spec.json, benchmarks/perf-tool/release-configs/lucene-hnsw/index.json, benchmarks/perf-tool/release-configs/lucene-hnsw/test.yml, benchmarks/perf-tool/release-configs/nmslib-hnsw/index.json, benchmarks/perf-tool/release-configs/nmslib-hnsw/test.yml
Added sample perf-test configs for faiss-ivf, faiss-ivfpq, lucene-hnsw. As offline configs get stale very easily this is a good way to maintain the perf test configs.
Signed-off-by: Navneet Verma <navneev@amazon.com>
#554
=> [554]Added sample perf-test configs for faiss-ivf, faiss-ivfpq, lucene-hnsw

src/main/java/org/opensearch/knn/index/codec/KNN920Codec/KNN920Codec.java, src/test/java/org/opensearch/knn/index/codec/KNN920Codec/KNN920CodecTests.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
Current structure of unit tests for codec does not allow to upgrade codec easy. For new codec it's required to copy test code to a new codec specific unit test. With this change this test has been parametrized and codec and perFieldFormat can be injected by caller. 
=> Refactor unit tests for codec

qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/LuceneFilteringIT.java, src/main/java/org/opensearch/knn/index/KNNClusterContext.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/plugin/KNNPlugin.java, src/test/java/org/opensearch/knn/index/KNNClusterContextTests.java, src/test/java/org/opensearch/knn/index/KNNClusterTestUtils.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
Adding serialization for filter in Knn query. Without the change multi-node cluster may be in inconsistent state, meaning some shards will execute knn query without the filter and search result will be irrelevant.   
Special case for rolling and restart upgrades. Let's say we do have existing cluster on 2.3 (we call it old) and we want to upgrade to 3.0 (we call it new). Nodes need to handle following cases for success run:
- old -> old        just existing cluster works before the upgrade. This should already work
- old -> new      this is part of restart and rolling upgrades
- new -> old      part of rolling upgrade   
- new -> new    upgraded cluster works
The easiest way to satisfy all criteria is to only write and read filter field …
=> Adding serialization for filter field in KnnQueryBuilder

src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java
Fixes constructor for FieldInfo, which changed with Lucene upgrade.
#570 
=> Fix KNNCodecUtil FieldInfo construction

src/main/java/org/opensearch/knn/index/codec/KNN920Codec/KNN920PerFieldKnnVectorsFormat.java, src/main/java/org/opensearch/knn/index/codec/KNN940Codec/KNN940Codec.java, src/main/java/org/opensearch/knn/index/codec/KNN940Codec/KNN940PerFieldKnnVectorsFormat.java, src/main/java/org/opensearch/knn/index/codec/KNNCodecFactory.java, src/main/java/org/opensearch/knn/index/codec/KNNFormatFactory.java, src/main/resources/META-INF/services/org.apache.lucene.codecs.Codec, src/test/java/org/opensearch/knn/index/codec/KNN920Codec/KNN920CodecTests.java, src/test/java/org/opensearch/knn/index/codec/KNN940Codec/KNN940CodecTests.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecFactoryTests.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java, src/test/java/org/opensearch/knn/index/codec/KNNFormatFactoryTests.java
This PR includes the following changes:
- Backport [package name changes for lucene 92](https://github.com/opensearch-project/k-NN/pull/498/commits/2f6b72a9d1680c4156503c537061f5fe5fb575ce)
- Backport https://github.com/opensearch-project/k-NN/pull/571
- Backport [Lucene 94 changes(Add KNN940Codec)](https://github.com/opensearch-project/k-NN/pull/498/commits/d4e84bce0fd229134fc202989cb3bdcc94d35c6f) 
https://github.com/opensearch-project/k-NN/issues/568
=> Backport lucene changes

qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ModelIT.java, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ScriptScoringIT.java, qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java, qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/StatsIT.java, qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java, src/main/java/org/opensearch/knn/plugin/transport/KNNStatsNodeRequest.java, src/main/java/org/opensearch/knn/plugin/transport/RemoveModelFromCacheNodeRequest.java, src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoNodeRequest.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/KNNCircuitBreakerIT.java, src/test/java/org/opensearch/knn/index/KNNESSettingsTestIT.java, src/test/java/org/opensearch/knn/index/KNNMapperSearcherIT.java, src/test/java/org/opensearch/knn/index/LuceneEngineIT.java, src/test/java/org/opensearch/knn/index/NmslibIT.java, src/test/java/org/opensearch/knn/index/OpenSearchIT.java, src/test/java/org/opensearch/knn/plugin/action/RestDeleteModelHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestGetModelHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestKNNWarmupHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNStatsHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNWarmupHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestSearchModelHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestTrainModelHandlerIT.java, src/test/java/org/opensearch/knn/plugin/script/KNNScriptScoringIT.java, src/test/java/org/opensearch/knn/plugin/script/PainlessScriptIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java, src/testFixtures/java/org/opensearch/knn/ODFERestTestCase.java
Remove usage of deprecated BaseNodeRequest (https://github.com/opensearch-project/OpenSearch/pull/4702). For now no need in downport as core PR is for 3.0.0. 
=> Replacing BaseNodeRequest by TransportRequest

src/main/java/org/opensearch/knn/index/KNNClusterContext.java, src/test/java/org/opensearch/knn/index/KNNClusterContextTests.java, src/test/java/org/opensearch/knn/index/KNNClusterTestUtils.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
Found simpler way of reading min deployed version for cluster, we can remove direct iteration over cluster nodes - https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/node/DiscoveryNodes.java#L399. Changing that for context of filtering feature.
https://github.com/opensearch-project/k-NN/issues/376
=> Read min cluster version directly from DiscoveryNodes

src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/plugin/stats/KNNCounter.java, src/main/java/org/opensearch/knn/plugin/stats/KNNStatsConfig.java, src/main/java/org/opensearch/knn/plugin/stats/StatNames.java, src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
Adding counter stat "knn_query_with_filter_requests" for queries with filter field. Example of response with new stat
```
"nodes": {
"gIsW_7cBQwqSeZ2sr5knEw": {
"graph_memory_usage_percentage": 0.0,
"graph_query_requests": 0,
"graph_memory_usage": 0,
"cache_capacity_reached": false,
"load_success_count": 0,
"training_memory_usage": 0,
"indices_in_cache": {},
"script_query_errors": 0,
"hit_count": 0,
"knn_query_requests": 2,
"total_load_time": 0,
"miss_count": 0,
"knn_query_with_filter_requests": 1,
"training_memory_usage_percentage": 0.0,
"lucene_initialized": true,
"graph_index_requests": 0,
"faiss_initialized": false,
"load_exception_count": 0,
"training_errors": 0,
"eviction_count": 0,
"nmslib_initialized": false, …
```
=> Adding stat for query with filter

.github/workflows/CI.yml
=> Add mac platform to CI

build.gradle, scripts/build.sh
Updates build script to publish zip to local maven. This allows plugins like neural search to pick up the zip as a dependency.
Fixes bug in build script where group was being set to org.opensearch as opposed to org.opensearch.plugin.
Publish to maven passed:
```
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.5/userguide/command_line_interface.html#sec:command_line_warnings
Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.
BUILD SUCCESSFUL in 16s
38 actionable tasks: 38 executed
Tried with variety
./gradlew :publishToMavenLocal -Dbuild.snapshot=true …
```
=> Update build script to publish to maven local

scripts/build.sh
Add Windows Build.sh Related Changes in k-NN.
Include new changes in windows and streamline linux builds.
This is based on @naveentatikonda 2.x windows support branch.
Needs to be merged only when https://github.com/opensearch-project/k-NN/pull/583 is merged.
We also need the ci repo PR https://github.com/opensearch-project/opensearch-ci/pull/212 to be merged to support `$MINGW_BIN`.
Thanks
https://github.com/opensearch-project/opensearch-build/issues/2306
#157
=> Add Windows Build.sh Related Changes in k-NN

.github/workflows/CI.yml
Disable code coverage for mac and windows platforms in CI to avoid duplicate reports.
=> Disable Code Coverage for Windows and Mac Platforms

scripts/build.sh
Add Windows Build.sh Related Changes in k-NN.
Include new changes in windows and streamline linux builds.
Cherry-picked from 65b613bf1aa4377f469a61c6946ecd7aed926a6f
https://github.com/opensearch-project/k-NN/issues/157
=> Add Windows Build.sh Related Changes

src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
This is a manual backport of https://github.com/opensearch-project/k-NN/pull/610. That PR is currently blocked by other unrelated issues with rolling upgrades. 
Fixed flaky unit tests, narrow assertion logic and adjust for test runs with multi node mock cluster
Repro for certain seeds:
```
./gradlew ':test' --tests "org.opensearch.knn.index.codec.KNN940Codec.KNN940CodecTests.testKnnVectorIndex" -Dtests.seed=B5E0DC7BF07CBCC1 -Dtests.security.manager=false -Dtests.locale=el-CY -Dtests.timezone=America/Mendoza -Druntime.java=17
org.opensearch.knn.index.codec.KNN940Codec.KNN940CodecTests > testKnnVectorIndex FAILED
org.mockito.exceptions.verification.TooManyActualInvocations:
kNN940PerFieldKnnVectorsFormat.getKnnVectorsFormatForField(
<any …
```
=> Fixing flaky test for knn codecs

release-notes/opensearch-knn.release-notes-2.4.0.0.md
Signed-off-by: Heemin Kim <heemin@amazon.com>
Add release note for 2.4.0
=> Add release note for 2.4.0

src/main/java/org/opensearch/knn/indices/ModelGraveyard.java, src/test/java/org/opensearch/knn/indices/ModelGraveyardTests.java
Add fix to fromXContent and toXContent in ModelGraveyard, where before adding this fix it will fail to bootup after a node drop or if cluster is killed.
https://github.com/opensearch-project/k-NN/issues/619
=> Add fix to fromXContent and toXContent in ModelGraveyard

src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
Fixed flaky unit tests, narrow assertion logic and adjust for test runs with multi node mock cluster
Rolling upgrades are failing, presumable due to issue with security plugin https://github.com/opensearch-project/security/issues/2228
Repro for certain seeds:
```
./gradlew ':test' --tests "org.opensearch.knn.index.codec.KNN940Codec.KNN940CodecTests.testKnnVectorIndex" -Dtests.seed=B5E0DC7BF07CBCC1 -Dtests.security.manager=false -Dtests.locale=el-CY -Dtests.timezone=America/Mendoza -Druntime.java=17
org.opensearch.knn.index.codec.KNN940Codec.KNN940CodecTests > testKnnVectorIndex FAILED
org.mockito.exceptions.verification.TooManyActualInvocations:
kNN940PerFieldKnnVectorsFormat.getKnnVectorsFormatForField(
<any string>
);
``` 
After …
=> Fixed failing unit test

gradle/formatting.gradle, src/main/java/org/opensearch/knn/index/SpaceType.java, src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNStatsHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNWarmupHandlerIT.java
Get rid of rachet and apply spotless on every PR before raising it like in main branch. Making this change to fix the OS distribution build failure 
```
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':spotlessCheck'.
> Could not create task ':spotlessJavaCheck'.
> Could not create task ':spotlessJava'.
> No such reference 'origin/1.x'
```
https://github.com/opensearch-project/k-NN/issues/647
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#deve …
=> Get rid of Rachet to fix failing build

gradle/formatting.gradle, src/main/java/org/opensearch/knn/index/SpaceType.java, src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNStatsHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNWarmupHandlerIT.java
Backported from PR : https://github.com/opensearch-project/k-NN/pull/648
Cherry-picked from 4488fbdbaf59baf3d017ef3b677796fb3b056c3b
=> [Backport 1.3]Get rid of Rachet to fix failing build

scripts/build.sh
Excluding jacocoTestReport in distribution build script to fix the below error:
```
> Task :jacocoTestReport FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':jacocoTestReport'.
> Unable to read execution data file /tmp/tmp3x3409pg/k-NN/build/jacoco/integTest.exec
``` 
https://github.com/opensearch-project/k-NN/issues/650
=> Exclude jacocoTestReport in distribution build script

scripts/build.sh
Update build script to build JNI libraries separately and then do gradle assemble instead of gradle build
=> Update build script to build JNI lib and gradlew assemble

.github/workflows/backwards_compatibility_tests_workflow.yml, qa/build.gradle, qa/restart-upgrade/build.gradle, qa/rolling-upgrade/build.gradle
Updates rolling bwc  to 2.5.0 and restart bwc to include 2.5.0.
=> Update bwc tests for 2.5.0

src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
Extends SystemIndexPlugin. Adds k-NN model system index plugin to SystemIndexPlugin list of system index descriptors.
The [system index plugin](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/plugins/SystemIndexPlugin.java#L55-L57) has one method:
```
Collection<SystemIndexDescriptor> getSystemIndexDescriptors(Settings settings) {
return Collections.emptyList();
}
```
The implementing plugin is expected to return a list of [SystemIndexDescriptors](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/indices/SystemIndexDescriptor.java) for its system indices. A SystemIndexDescriptor contains an index pattern, which corresponds to the name of the index, and a description.
The SystemIndexDescriptors are …
=> Extend SystemIndexPlugin for k-NN model system index

src/main/java/org/opensearch/knn/index/codec/KNNCodecVersion.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecServiceTests.java
In certain scenarios codec can be initialized as part of recovery process for shard (e.g. index close and open operations). In such cases mapperService can be passed as null, but currently this causes NPE exception on kNN side with below stacktrace. It's ok to allow null value as codec is not actually required and is initialized just to create new engine and read segment information. In addition to that we do have another check for null references in [kNN code](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java#L45-L47) 
```
[WARN ][o.o.i.c.IndicesClusterStateService] [integTest-0] [target_index][5] marking and sending shard failed due to [failed recovery] …
```
=> Allow mapping service to be null for scenarios of shard recovery from translog

src/main/java/org/opensearch/knn/index/codec/KNNCodecFactory.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecServiceTests.java
Backport https://github.com/opensearch-project/k-NN/commit/c412c8a403cf2c4b6008df7b36847f2ee329e887 from https://github.com/opensearch-project/k-NN/pull/685
=> [Backport 2.2] Allow mapping service to be null for scenarious of shard recovery from translog (#685) (#687)

src/main/java/org/opensearch/knn/index/codec/KNNCodecFactory.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecServiceTests.java
Backport https://github.com/opensearch-project/k-NN/commit/c412c8a403cf2c4b6008df7b36847f2ee329e887 from https://github.com/opensearch-project/k-NN/pull/685
=> [Backport 2.3] Allow mapping service to be null for scenarious of shard recovery from translog (#685) (#687)

src/main/java/org/opensearch/knn/indices/ModelGraveyard.java, src/test/java/org/opensearch/knn/indices/ModelGraveyardTests.java
Add Backward Compatibility and Validation checks to ModelGraveyard XContent Bugfix
- Update ModelGraveyard fromXContent logic to add backward compatibility to those domains that have parsed the old toXContent logic.
- Add more validations in fromXContent logic.
- Add more test cases to validate them
=> Add Backward Compatibility and Validation checks to ModelGraveyard XContent Bugfix

src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
Adding integ test for scenario with index close/open, closing gap in https://github.com/opensearch-project/k-NN/pull/685. In short, for lucene based index with data, index close call caused exception and index became inoperable. 
=> Adding integ test for index close/open scenario

src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
* Adding integ test for index close/open scenario
Backport https://github.com/opensearch-project/k-NN/pull/693
(cherry picked from commit https://github.com/opensearch-project/k-NN/commit/54a433ee3681a2f48acee5c1aacf9a3058f85641)
=> [Backport 2.x] Adding integ test for index close/open scenario

DEVELOPER_GUIDE.md, src/main/java/org/opensearch/knn/index/codec/KNN950Codec/KNN950Codec.java, src/main/java/org/opensearch/knn/index/codec/KNN950Codec/KNN950PerFieldKnnVectorsFormat.java, src/main/java/org/opensearch/knn/index/codec/KNNCodecVersion.java, src/main/resources/META-INF/services/org.apache.lucene.codecs.Codec, src/test/java/org/opensearch/knn/index/codec/KNN950Codec/KNN950CodecTests.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecFactoryTests.java
Adding new kNN codec that wraps Lucene new codec that is part of Lucene 9.5 and [latest core](https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/version.properties#L2). Existing 9.4 codec doesn't work as we use it for both reads and writes, but writes only allowed for latest codec version. This already [blocking PRs](https://github.com/opensearch-project/k-NN/actions/runs/3832927379/jobs/6523807366) for main in our CI.
Backport is not required as [core 2.x](https://github.com/opensearch-project/OpenSearch/blob/2.x/buildSrc/version.properties#L2) is still on Lucene 9.4 …
=> Add Lucene 9.5 codec and make it new default

src/test/java/org/opensearch/knn/index/codec/KNN940Codec/KNN940CodecTests.java, src/test/java/org/opensearch/knn/index/codec/KNN950Codec/KNN950CodecTests.java
Updates tests for backwards codecs to prevent backwards codecs from writing with a read only codec.
Right now, testKnnVectorIndex requires that the Hnsw Lucene Format have the capability to write. For backwards codecs, however, they are not able to write (see https://github.com/apache/lucene/blob/main/lucene/backward-codecs/src/java/org/apache/lucene/backward_codecs/lucene94/Lucene94HnswVectorsFormat.java#L150). 
To resolve this, we are removing the "testKnnVectorIndex" from backwards compatibility tests. For reading/writing backwards compatibility testing, we will rely on Lucene, where tests can be found in https://github.com/apache/lucene/tree/main/lucene/backward-codecs/src/test/org/apache/lucene/backward_codecs/lucene94.
It adds a test that checks that our custom format is correctly …
=> Update tests for backwards codecs

src/main/java/org/opensearch/knn/index/util/Lucene.java, src/test/java/org/opensearch/knn/index/util/KNNEngineTests.java, src/test/java/org/opensearch/knn/index/util/LuceneTests.java
Update version of Lucene kNN engine, it matches version of Lucene that is coming with core OpenSearch. Currently it's used as engine text description, it shouldn't cause bwc issues. 
=> Making version of lucene k-nn engine match lucene current version

release-notes/opensearch-knn.release-notes-2.5.0.0.md, src/main/java/org/opensearch/knn/index/util/KNNEngine.java, src/main/java/org/opensearch/knn/index/util/KNNLibrary.java, src/main/java/org/opensearch/knn/index/util/Lucene.java, src/main/java/org/opensearch/knn/plugin/KNNPlugin.java, src/test/java/org/opensearch/knn/index/util/KNNEngineTests.java, src/test/java/org/opensearch/knn/index/util/LuceneTests.java
We're including file extensions for vector value files from Lucene 9.4 to the list of extensions that Core OpenSearch will use with HybridFS store type and MMap file I/O. This increases performance for both data ingestion and queries for p99. Setting is abstracted at engine level with specific implementation for Lucene. Setting is set at cluster defaults level, index specific overrides will take priority over it.  
Tested locally on 1M dataset
Before change (baseline):
data ingestion
```
"results": {
"test_took": 2706990.31884,
"create_index_took_total": 2702.2581160000004,
"ingest_took_total": 513438.04862599995,
"refresh_index_store_kb_total": 2810943.876953125,
"refresh_index_took_total": 641.9670379999616,
"force_merge_took_total": …
```
=> Add Lucene specific file extensions to core HybridFS 

.github/workflows/backwards_compatibility_tests_workflow.yml
Upgrade main to use 2.6 snapshot for bwc
=> Update bwc to 2.6.0-SNAPSHOT

release-notes/opensearch-knn.release-notes-2.5.0.0.md
In 2.5, we accidentally included #700 in our release notes. However, this did not get backported to 2.5 and does not make sense because Lucene 95 has not yet been released. This PR removes it from the release notes.
=> Remove lucene 95 upgrade from release notes

src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManagerDto.java, src/test/java/org/opensearch/knn/KNNTestCase.java, src/test/java/org/opensearch/knn/index/KNNSettingsTests.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
Removes the latestSettings cache from the KNNSettings class. latestSettings cache gets updated in a consumer when the particular settings are updated.
[KNNSettings.getSettingValue](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/KNNSettings.java#L305) would pull from this cache and then fallback to the default if it is not present. However, in the case when the settings are set via opensearch.yml config file, the settings get set before any functions can be registered. So the config values never get put in the cache. This leads to getSettingValue to always return the default instead of the value specified in the config file.
To fix this, this change refactors getSettingValue to pull from the cluster settings and removes the latestSetting cache. …
=> Remove latestSettings cache from KNNSettings

benchmarks/osb/requirements.txt, benchmarks/perf-tool/requirements.txt
Update the `certifi` dependency version to "2022.12.7" as per the security recommendation.
Validated the version by compiling the requirements file. Then, tested it by triggering the perf test to make sure there are no version incompatibilities. 
=> Update certifi dependency version

benchmarks/perf-tool/README.md, benchmarks/perf-tool/okpt/test/steps/factory.py, benchmarks/perf-tool/okpt/test/steps/steps.py, benchmarks/perf-tool/okpt/test/test.py
Adding few metrics to perf tool, I used them while working on vec file io improvements for lucene knn. One is total number of segments in index, search and committed. Second added is p99.9 and p100 for query latencies, this allows to get info on a data tail.
This is example of test run result with num of segments and p99.9/p100. 
```
"results": {
"test_took": 46429.944159499944,
"get_stats_num_of_committed_segments_total": 8.0,
"get_stats_num_of_search_segments_total": 8.0,
"get_stats_took_total": 186.8456724999713,
"clear_cache_took_total": 164.59848699996982,
"query_took_total": 46078.5,
"query_took_p50": 4.5,
"query_took_p90": 6.0,
"query_took_p99": 7.0,
"query_took_p99.9": 7.0,
"query_took_p100": 11.5,
"query_memory_kb_total": 0.0, …
```
=> Adding p99.9, p100 and num_of_segments metrics to perf-tool

DEVELOPER_GUIDE.md, src/main/java/org/opensearch/knn/index/codec/KNN940Codec/KNN940PerFieldKnnVectorsFormat.java, src/main/java/org/opensearch/knn/index/codec/KNN950Codec/KNN950Codec.java, src/main/java/org/opensearch/knn/index/codec/KNN950Codec/KNN950PerFieldKnnVectorsFormat.java, src/main/java/org/opensearch/knn/index/codec/KNNCodecVersion.java, src/main/resources/META-INF/services/org.apache.lucene.codecs.Codec, src/test/java/org/opensearch/knn/index/codec/KNN940Codec/KNN940CodecTests.java, src/test/java/org/opensearch/knn/index/codec/KNN950Codec/KNN950CodecTests.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecFactoryTests.java
This PR includes the following changes:
- Update lucene94 package name to backward_codecs
- Add Lucene95 codec and make it default (Cherry-picked 4f9a8b296241c316bbc2d7dbfe67f20a59893302 from https://github.com/opensearch-project/k-NN/pull/700)
- Update tests for backwards codecs (Cherry-picked 8b168311d345228c30408bbb8078943b13477823 from https://github.com/opensearch-project/k-NN/pull/710)
https://github.com/opensearch-project/k-NN/issues/745
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md …
=> Update codec version to 9.5

.github/workflows/backwards_compatibility_tests_workflow.yml
Switch main to use 2.5.0 release instead of 2.5.0-SNAPSHOT for bwc. Decided it would be better to point to 2.5.0 as opposed to 2.5.1-SNAPSHOT for now because we arent sure if there will be a patch release for 2.5.
=> Update bwc 2.5 to release

.github/workflows/backwards_compatibility_tests_workflow.yml, build.gradle
Upgrades 2.5 to 2.5.1. Also updates 1.3 patch to 1.3.8 in bwc testing.
=> Upgrade 2.5 to 2.5.1

build.gradle, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java, src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
We do not have unit tests for KNNWeight, having it would help to catch issues with size of DocIdSetBuilder, like https://github.com/opensearch-project/k-NN/issues/500 and https://github.com/opensearch-project/k-NN/issues/751. Along with test adding dependencies for doing mocks of static classes and/or methods.
=> Adding test for KNNWeight

src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
Sets NoMerge as merge policy for codec tests. This allows us to reliably predict how many segments will be created.
This fixes flaky test case that caused 3.0 build to fail
#750 
=> Set NoMergePolicy for codec tests

src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java, src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java
KnnQueryVector has been [marked as deprecated in Lucene 9.5](https://github.com/apache/lucene/blob/branch_9_5/lucene/core/src/java/org/apache/lucene/search/KnnVectorQuery.java#L35) and new implementation created instead. We need to follow Lucene path as we do return their implementation directly. 
https://github.com/opensearch-project/k-NN/issues/766
=> Replace KnnQueryVector by KnnFloatVectorQuery for Lucene knn

CHANGELOG.md, build.gradle
Bump byte-buddy version from 1.12.22 to 1.14.2 to avoid build failures as OpenSearch core incremented the version in this [PR](https://github.com/opensearch-project/OpenSearch/pull/6678)
=> Bump byte-buddy version from 1.12.22 to 1.14.2

CHANGELOG.md, benchmarks/perf-tool/requirements.txt
Update Certifi version to 2022.12.7 to fix the failing whitesource security check
https://github.com/opensearch-project/k-NN/pull/809/checks?check_run_id=12067423521
=> Update Certifi version to 2022.12.7

benchmarks/perf-tool/requirements.txt
Manually Backporting https://github.com/opensearch-project/k-NN/pull/817/commits/3292d92e0923f23c2eaa56c3ad63214b9044264a from https://github.com/opensearch-project/k-NN/pull/817
=> [Backport 1.3] Update Certifi version to 2022.12.7

CHANGELOG.md, benchmarks/osb/requirements.txt, benchmarks/perf-tool/requirements.txt
Backport (cherry picked from commit f7f12022fdecad7f8fa0dbf1f9727480b91b392c) from #811
=> [Backport 2.x] Bump numpy from 1.22.x to 1.24.2 (#811)

build.gradle
Add a conditional check to make sure the BWC version matrix is not updated before adding new versions to the BWC Matrix. This change will help to avoid creation of unnecessary version bump PRs https://github.com/opensearch-project/k-NN/pull/826 after the version is already incremented.
=> Fix the BWC Version Bump Issues

CHANGELOG.md, build.gradle
Bump byte-buddy to follow core and avoid compilation errors like this: https://github.com/opensearch-project/k-NN/actions/runs/4612290817/jobs/8153018668#step:6:154. This is not needed for 2.x
=> Bump byte-buddy version to 1.14.3

CHANGELOG.md, build.gradle
Need to limit scope for common-utils lib as it causes compile/runtime errors for neural-search 
https://github.com/opensearch-project/neural-search/issues/148
=> Set gradle dependency scope for common-utils to testFixturesImplementation

CHANGELOG.md, src/test/java/org/opensearch/knn/index/NmslibIT.java
Fixing integ test, when running in secure cluster it produces WarningException like below. For tests we can ignore such warnings, there is a setting for rest client that needs to be enabled
```
java.lang.AssertionError: Exception not expected as valid index arguements passed: org.opensearch.client.WarningFailureException: method [PUT], host [https://localhost:9200/], URI [/test_index], status line [HTTP/1.1 200 OK]
Warnings: [[index.knn.algo_param.ef_construction] setting was deprecated in OpenSearch and will be removed in a future release! See the breaking changes documentation for the next major version.]
{"acknowledged":true,"shards_acknowledged":true,"index":"test_index"}
at __randomizedtesting.SeedInfo.seed([B9031256349BA03A:D1B6ED99033EDC32]:0)
at …
```
=> Add client setting to ignore warning exceptions

.github/workflows/test_security.yml, CHANGELOG.md
Adding github action to run integ tests against cluster with security plugin. Approach is mainly taken from AD plugin https://github.com/opensearch-project/anomaly-detection/blob/main/.github/workflows/test_security.yml. Currently we're not able to build artifacts for native libraries in our regular assemble task, so for this iteration will be using latest pre-built versions from docker image. This means they may be different from PR version in case we're changing those libs in scope of PR.  We'll be running tests on linux as this gives sufficient confidence, and for macos/win the docker setup has some difficulties.
PR requires https://github.com/opensearch-project/k-NN/pull/827  and https://github.com/opensearch-project/k-NN/pull/847 to be merged …
=> Add github action for secure integ tests

CHANGELOG.md, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ModelIT.java, src/main/java/org/opensearch/knn/common/exception/DeleteModelWhenInTrainStateException.java, src/main/java/org/opensearch/knn/indices/ModelDao.java, src/main/java/org/opensearch/knn/plugin/transport/DeleteModelResponse.java, src/main/java/org/opensearch/knn/plugin/transport/DeleteModelTransportAction.java, src/test/java/org/opensearch/knn/indices/ModelDaoTests.java, src/test/java/org/opensearch/knn/plugin/action/RestDeleteModelHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestSearchModelHandlerIT.java, src/test/java/org/opensearch/knn/plugin/transport/DeleteModelResponseTests.java
Throws errors on model deletion. Previously we were indicating failure, but returning 200 response codes. This changes that to throw exceptions with the correct response code.
Deprecates constructor for [DeleteModelResponse](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/plugin/transport/DeleteModelResponse.java) that takes an error/result, as this result should only be returned on success.
#831 
=> Throw errors on model deletion failures

CHANGELOG.md, release-notes/opensearch-knn.release-notes-2.7.0.0.md
Manually backport https://github.com/opensearch-project/k-NN/pull/857
=> [ Backport 2.7 ] Add 2.7.0 Release Notes (#857)

benchmarks/perf-tool/release-configs/lucene-hnsw/filtering/restrictive-filter/restrictive-filter-test.yml
Fix the filter_spec file name in restrictive-filter-test.yml
=> Fix the filter_spec file name in restrictive-filter-test

CHANGELOG.md, jni/CMakeLists.txt, jni/src/nmslib_wrapper.cpp
For nmslib, we need to allocate objects that wrap vectors with metadata. This PR updates the objects to be allocated in one buffer as opposed to allocating objects individually. This was shown to prevent memory fragmentation.
For this change, I ran the same experiments as were run for #772 and they showed significant improvements in the RSS of the process after the indexing workload was run. 
Configuration | RSS beginning (KB) | RSS after indexing (KB) | Vectors Indexed (vectors)
-- | -- | -- | --
nmslib-default (baseline) | 8984748 | 11125772 | 648500
nmslib with bulk update | 8972132 | 9439540 | 628000
Specifically, the change in RSS decreases by about 78% with this change in the experiment above.
In addition to this, fix bug in CMakeLists.txt file preventing unit tests from being …
=> Bulk allocate objects for nmslib index creation

MAINTAINERS.md
Cherry-picked from https://github.com/opensearch-project/k-NN/pull/883
=> [Backport 2.x] Baseline Maintainers (#883)

gradle/wrapper/gradle-wrapper.properties
Fixes checksum for gradle 7.6.1
Related: https://github.com/opensearch-project/k-NN/actions/runs/4931642285/jobs/8813885647
Checksums can be found here.
Command to generate:
```
./gradlew wrapper --gradle-version 7.6.1 --gradle-distribution-sha256-sum 518a863631feb7452b8f1b3dc2aaee5f388355cc3421bbd0275fbeadd77e84b2 --distribution-type all
```
=> Fix sha256 on gradle 7.6.1

gradle/wrapper/gradle-wrapper.properties
=> Fix checksum for gradle

CHANGELOG.md, src/test/java/org/opensearch/knn/index/FaissIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Standard method refreshAllIndices refreshes all indices including system. This produces error warnings when running integration tests for indices like '.opensearch-knn-models'. In this change we're filtering indices and do refresh only if its name doesn't start with system prefix.  
```
Suite: Test class org.opensearch.knn.index.FaissIT
2> may 25, 2023 8:29:50 PM org.opensearch.client.RestClient logResponse
2> AVERTISSEMENT: request [POST http://localhost:9200/_refresh?expand_wildcards=open%2Chidden] returned 2 warnings: [299 OpenSearch-2.8.0-4bd47e16e300cd6147d24e329ac05014fd61cb80 "this request accesses system indices: [.opendistro_security], but in a future major version, direct access to system indices will be prevented by default"],[299 …
```
=> Disable index refresh for system indices

CHANGELOG.md, benchmarks/perf-tool/requirements.txt
Fix CVE by bumping `requests` dependency version from 2.26.0 to 2.31.0
https://github.com/opensearch-project/k-NN/issues/910
=> Bump requests version from 2.26.0 to 2.31.0

CHANGELOG.md, src/test/java/org/opensearch/knn/index/FaissIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Backport from https://github.com/opensearch-project/k-NN/pull/915
(cherry picked from commit https://github.com/opensearch-project/k-NN/commit/a5214a3dfe86d5790fe204385bc92af147f98434)
=> [Backport 2.x] Do refresh only for non system indices (#915)

CHANGELOG.md, benchmarks/perf-tool/requirements.txt
Backport from #913 
(cherry picked from commit 15319e2e57aace412809abed0ac4e29e6d18a4ad)
=> [Backport 2.x] Bump requests version from 2.26.0 to 2.31.0 (#913)

CHANGELOG.md, release-notes/opensearch-knn.release-notes-2.8.0.0.md
Adding release notes for 2.8 release
https://github.com/opensearch-project/k-NN/issues/905
=> Adding release notes for 2.8

DEVELOPER_GUIDE.md, jni/CMakeLists.txt, jni/include/faiss_wrapper.h, jni/include/org_opensearch_knn_jni_FaissService.h, jni/src/faiss_wrapper.cpp, jni/src/org_opensearch_knn_jni_FaissService.cpp, src/main/java/org/opensearch/knn/index/query/KNNQuery.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java, src/main/java/org/opensearch/knn/index/query/KNNScorer.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/main/java/org/opensearch/knn/index/util/KNNEngine.java, src/main/java/org/opensearch/knn/index/util/KNNLibrary.java, src/main/java/org/opensearch/knn/jni/FaissService.java, src/main/java/org/opensearch/knn/jni/JNIService.java, src/main/java/org/opensearch/knn/plugin/rest/RestGetModelHandler.java, src/main/java/org/opensearch/knn/plugin/rest/RestKNNStatsHandler.java, src/main/java/org/opensearch/knn/plugin/rest/RestKNNWarmupHandler.java, src/main/java/org/opensearch/knn/plugin/transport/DeleteModelRequest.java, src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportAction.java, src/main/java/org/opensearch/knn/training/TrainingJob.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategyTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java, src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
This is an initial PR for enabling the pre-filtering support for Faiss Engine.
1. Upgrading the Faiss to commit id: https://github.com/facebookresearch/faiss/commit/3219e3d12e6fc36dfdfe17d4cf238ef70bf89568
2. Doing an optimization to select when to use IDArraySelector and IDBitMapSelector.
3. Don't run Faiss search if no docIds are returned from filters.
1. Optimize the JNI interfaces to have single query interface.
2. Write Unit tests for both java and c++ code.
3. Write ITs for filtering.
5. Do perf testing, compare with lucene and share the results on the github issue.
6. Figure out better way to select IDSelector Map.
7. Implement Exact search optimization when filterIds < k
#903 
###Testing
Tested the code using the example mentioned here: …
=> Enabled the efficient filtering support for Faiss Engine

benchmarks/perf-tool/README.md, benchmarks/perf-tool/okpt/io/config/parsers/test.py, benchmarks/perf-tool/okpt/io/config/schemas/test.yml, benchmarks/perf-tool/okpt/test/steps/steps.py, benchmarks/perf-tool/release-configs/faiss-hnsw/filtering/relaxed-filter/index.json, benchmarks/perf-tool/release-configs/faiss-hnsw/filtering/relaxed-filter/relaxed-filter-spec.json, benchmarks/perf-tool/release-configs/faiss-hnsw/filtering/relaxed-filter/relaxed-filter-test.yml, benchmarks/perf-tool/release-configs/faiss-hnsw/filtering/restrictive-filter/index.json, benchmarks/perf-tool/release-configs/faiss-hnsw/filtering/restrictive-filter/restrictive-filter-spec.json, benchmarks/perf-tool/release-configs/faiss-hnsw/filtering/restrictive-filter/restrictive-filter-test.yml, benchmarks/perf-tool/release-configs/faiss-hnsw/index.json, benchmarks/perf-tool/release-configs/faiss-hnsw/test.yml, benchmarks/perf-tool/release-configs/lucene-hnsw/filtering/restrictive-filter/restrictive-filter-test.yml, jni/src/faiss_wrapper.cpp
Fixed the ef_search default value for faiss HNSW with filters and updated the perf-tool to include Faiss HNSW tests
https://github.com/opensearch-project/k-NN/issues/903
=> Fixed the ef_search default value for faiss HNSW with filters and updated the perf-tool to include Faiss HNSW tests

src/main/java/org/opensearch/knn/index/query/KNNWeight.java
Added exact search for cases when filteredIds < k to improve the recall for filtered k-NN Search
1. Add the unit tests and integration tests.
2. Add the benchmark results on the github issue and compare them with Lucene.
#903 
=> Added exact search for cases when filteredIds < k to improve the recall for filtered k-NN Search

benchmarks/perf-tool/okpt/test/steps/steps.py, src/main/java/org/opensearch/knn/index/query/KNNWeight.java
Improved Exact Search to return only K results and added client side latency metric for query Benchmarks
#903 
=> Improved Exact Search to return only K results and added client side latency metric for query Benchmarks

src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/LuceneEngineIT.java, src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java, src/test/java/org/opensearch/knn/jni/JNIServiceTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
-> Added Integration Tests and Unit test for Efficient Filtering for Faiss Engine.
-> Removed some TODOs and fixed an edge case in the code which failed during Unit tests.
#903 
=> Added Integration Tests and Unit test for Efficient Filtering for Faiss Engine

.github/workflows/backwards_compatibility_tests_workflow.yml
Update versions after 2.8 release: change 2.8.0-SNAPSHOT to 2.8.0, add 2.9.0-SNAPSHOT, it's routine maintenance similar to what is done for every version ([ref for 2.7->2.8](https://github.com/opensearch-project/k-NN/commit/5a0b20d81b48874f995f8295919c62b5460602e4)) 
=> Update bwc version after 2.8 release

benchmarks/perf-tool/requirements.txt
Backport https://github.com/opensearch-project/k-NN/pull/913 to 1.3
=> [Backport 1.3] Bump requests version from 2.26.0 to 2.31.0 (#913)

src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
Added Unit Tests for KNNQueryBuilder for Faiss Filtering
#903 
=> Added  Unit Tests for KNNQueryBuilder for Faiss Filtering

DEVELOPER_GUIDE.md, jni/tests/faiss_wrapper_test.cpp, jni/tests/test_util.cpp, jni/tests/test_util.h
Fixing unit test for Faiss due to faiss upgrade.
NA
```
16:51 ~/workplace/k-NN/jni faiss-unit$ ./bin/jni_test
Running main() from /Users/navneev/workplace/k-NN/jni/googletest-src/googletest/src/gtest_main.cc
[==========] Running 12 tests from 12 test suites.
[----------] Global test environment set-up.
[----------] 1 test from FaissCreateIndexTest
[ RUN      ] FaissCreateIndexTest.BasicAssertions
[       OK ] FaissCreateIndexTest.BasicAssertions (11 ms)
[----------] 1 test from FaissCreateIndexTest (11 ms total)
[----------] 1 test from FaissCreateIndexFromTemplateTest
[ RUN      ] FaissCreateIndexFromTemplateTest.BasicAssertions
[       OK ] FaissCreateIndexFromTemplateTest.BasicAssertions (5 ms)
[----------] 1 test from FaissCreateIndexFromTemplateTest (5 ms total)
[----------] 1 test …
```
=> Fixing unit test for Faiss due to faiss upgrade.

CHANGELOG.md, src/main/java/org/opensearch/knn/common/KNNConstants.java, src/main/java/org/opensearch/knn/index/VectorDataType.java, src/main/java/org/opensearch/knn/index/VectorField.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java, src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java, src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
This PR contains changes which adds indexing support to lucene byte sized vector and corresponding tests to validate it. It helps users to index vectors as byte sized vectors(which theoretically saves 75% of memory when compared to float vectors) by setting the optional `data_type` field as `byte` while creating the index. As we are not adding support for Quantization Techniques, users are expected to index vectors that are in the byte range [-128 to 127] without any decimal values. Also, right now this feature is only supported for lucene engine.
https://github.com/opensearch-project/k-NN/issues/812 
For more information on following Developer Certificate of Origin and …
=> Add Indexing Support for Lucene Byte Sized Vector

src/main/java/org/opensearch/knn/common/exception/DeleteModelWhenInTrainStateException.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/plugin/rest/RestDeleteModelHandler.java, src/main/java/org/opensearch/knn/plugin/rest/RestGetModelHandler.java, src/main/java/org/opensearch/knn/plugin/rest/RestKNNStatsHandler.java, src/main/java/org/opensearch/knn/plugin/rest/RestKNNWarmupHandler.java, src/main/java/org/opensearch/knn/plugin/transport/DeleteModelRequest.java, src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportAction.java, src/main/java/org/opensearch/knn/training/TrainingJob.java, src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportActionTests.java, src/test/java/org/opensearch/knn/plugin/transport/TrainingModelRequestTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
* Backport part of https://github.com/opensearch-project/k-NN/pull/885 to 2.x
* Fix run error from "org.opensearch.core.common" import
=> Move ImmutableOpenMap usage to j.u.Map

CHANGELOG.md, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java, src/test/java/org/opensearch/knn/index/LuceneEngineIT.java, src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java, src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java
The changes in this PR adds querying support to lucene byte sized vector.
https://github.com/opensearch-project/k-NN/issues/812
=> Add Querying Support to Lucene Byte Sized Vector

jni/src/faiss_wrapper.cpp
Setting the OMP thread to 1 while doing the query in Faiss to reduce thread creation overhead.
#903 
=> Setting the OMP thread to 1 while doing the query in Faiss to reduce thread creation overhead.

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNVectorDVLeafFieldData.java, src/main/java/org/opensearch/knn/index/KNNVectorIndexFieldData.java, src/main/java/org/opensearch/knn/index/KNNVectorScriptDocValues.java, src/main/java/org/opensearch/knn/index/VectorDataType.java, src/main/java/org/opensearch/knn/index/codec/KNNCodecService.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java, src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtil.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringUtil.java, src/test/java/org/opensearch/knn/index/KNNVectorDVLeafFieldDataTests.java, src/test/java/org/opensearch/knn/index/KNNVectorIndexFieldDataTests.java, src/test/java/org/opensearch/knn/index/KNNVectorScriptDocValuesTests.java, src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java, src/test/java/org/opensearch/knn/index/VectorDataTypeTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtilTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringUtilTests.java
The changes in this PR adds doc values support for fields with byte sized vectors, which helps users to perform script scoring and painless scripting search functionalities on these indices.
https://github.com/opensearch-project/k-NN/issues/812
=> Add DocValues Support for Lucene Byte Sized Vector

release-notes/opensearch-knn.release-notes-2.9.0.0.md, src/main/java/org/opensearch/knn/common/KNNConstants.java, src/main/java/org/opensearch/knn/index/KNNVectorDVLeafFieldData.java, src/main/java/org/opensearch/knn/index/KNNVectorIndexFieldData.java, src/main/java/org/opensearch/knn/index/KNNVectorScriptDocValues.java, src/main/java/org/opensearch/knn/index/VectorDataType.java, src/main/java/org/opensearch/knn/index/VectorField.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java, src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtil.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringUtil.java, src/test/java/org/opensearch/knn/index/KNNVectorDVLeafFieldDataTests.java, src/test/java/org/opensearch/knn/index/KNNVectorIndexFieldDataTests.java, src/test/java/org/opensearch/knn/index/KNNVectorScriptDocValuesTests.java, src/test/java/org/opensearch/knn/index/LuceneEngineIT.java, src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java, src/test/java/org/opensearch/knn/index/VectorDataTypeTests.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java, src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtilTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringUtilTests.java
This PR contains changes which adds indexing, querying and docValues support to lucene byte sized vector and corresponding tests to validate it. It helps users to index vectors as byte sized vectors(which theoretically saves 75% of memory when compared to float vectors) by setting the optional `data_type` field as `byte` while creating the index. As we are not adding support for Quantization Techniques, users are expected to index vectors that are in the byte range [-128 to 127] without any decimal values. Also, right now this feature is only supported for `lucene engine`.
https://github.com/opensearch-project/k-NN/issues/812
For more information on following Developer …
=> Add Support for Lucene Byte Sized Vector

release-notes/opensearch-knn.release-notes-2.9.0.0.md, src/main/java/org/opensearch/knn/common/KNNConstants.java, src/main/java/org/opensearch/knn/index/KNNVectorDVLeafFieldData.java, src/main/java/org/opensearch/knn/index/KNNVectorIndexFieldData.java, src/main/java/org/opensearch/knn/index/KNNVectorScriptDocValues.java, src/main/java/org/opensearch/knn/index/VectorDataType.java, src/main/java/org/opensearch/knn/index/VectorField.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java, src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtil.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringUtil.java, src/test/java/org/opensearch/knn/index/KNNVectorDVLeafFieldDataTests.java, src/test/java/org/opensearch/knn/index/KNNVectorIndexFieldDataTests.java, src/test/java/org/opensearch/knn/index/KNNVectorScriptDocValuesTests.java, src/test/java/org/opensearch/knn/index/LuceneEngineIT.java, src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java, src/test/java/org/opensearch/knn/index/VectorDataTypeTests.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java, src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtilTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringUtilTests.java
(cherry picked from commit bf04854c483fdfd38663bdc490e1730c994bda6d)
=> [Backport 2.9] Add Support for Lucene Byte Sized Vector (#971)

release-notes/opensearch-knn.release-notes-2.9.0.0.md, src/main/java/org/opensearch/knn/common/KNNConstants.java, src/main/java/org/opensearch/knn/index/KNNVectorDVLeafFieldData.java, src/main/java/org/opensearch/knn/index/KNNVectorIndexFieldData.java, src/main/java/org/opensearch/knn/index/KNNVectorScriptDocValues.java, src/main/java/org/opensearch/knn/index/VectorDataType.java, src/main/java/org/opensearch/knn/index/VectorField.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java, src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtil.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringUtil.java, src/test/java/org/opensearch/knn/index/KNNVectorDVLeafFieldDataTests.java, src/test/java/org/opensearch/knn/index/KNNVectorIndexFieldDataTests.java, src/test/java/org/opensearch/knn/index/KNNVectorScriptDocValuesTests.java, src/test/java/org/opensearch/knn/index/LuceneEngineIT.java, src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java, src/test/java/org/opensearch/knn/index/VectorDataTypeTests.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java, src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtilTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringUtilTests.java
(cherry picked from commit bf04854c483fdfd38663bdc490e1730c994bda6d)
=> [Backport 2.x] Add Support for Lucene Byte Sized Vector (#971)

jni/src/faiss_wrapper.cpp
Fixing the opensearch-build issue happening due to lower version of gcc.
Jenkins link: https://build.ci.opensearch.org/blue/organizations/jenkins/distribution-build-opensearch/detail/distribution-build-opensearch/8108/pipeline/129/
```
Consolidate compiler generated dependencies of target opensearchknn_common
[ 96%] Built target opensearchknn_common
[ 96%] Building CXX object CMakeFiles/opensearchknn_faiss.dir/src/org_opensearch_knn_jni_FaissService.cpp.o
/tmp/tmphvvuwegd/k-NN/jni/src/org_opensearch_knn_jni_FaissService.cpp: In function 'jlong Java_org_opensearch_knn_jni_FaissService_loadIndex(JNIEnv*, jclass, jstring)':
/tmp/tmphvvuwegd/k-NN/jni/src/org_opensearch_knn_jni_FaissService.cpp:75:12: warning: converting to non-pointer type 'long int' from NULL [-Wconversion-null]
return NULL; …
```
=> Fixing the opensearch-build issue happening due to lower version of gcc.

scripts/build.sh
Add gcc version verification before building k-NN
https://github.com/opensearch-project/k-NN/issues/975
=> Add gcc version verification before building k-NN

scripts/build.sh
Add gcc version ceiling verification before building k-NN on arm64
https://github.com/opensearch-project/k-NN/issues/975
=> Add gcc version ceiling verification before building k-NN on arm64

scripts/build.sh
Only check the gcc version ceiling when it is on linux
https://github.com/opensearch-project/k-NN/issues/975
=> Only check the gcc version ceiling when it is on linux

.github/workflows/backwards_compatibility_tests_workflow.yml, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ModelIT.java, src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java, src/test/java/org/opensearch/knn/plugin/action/RestDeleteModelHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestGetModelHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestSearchModelHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestTrainModelHandlerIT.java, src/test/java/org/opensearch/knn/plugin/script/KNNScriptScoringIT.java, src/test/java/org/opensearch/knn/plugin/transport/DeleteModelResponseTests.java, src/test/java/org/opensearch/knn/plugin/transport/GetModelResponseTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java, src/testFixtures/java/org/opensearch/knn/ODFERestTestCase.java, src/testFixtures/java/org/opensearch/knn/TestUtils.java
Update versions after 2.9 release: change 2.9.0-SNAPSHOT to 2.9.0, add 2.10.0-SNAPSHOT.
=> Update bwc version after 2.9 release

CHANGELOG.md, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Enabled the IVF algorithm to work with Filters of K-NN Query.
#903 
Current main branch build is broken. I will forward port that change once the issue is resolved.
=> Enabled the IVF algorithm to work with Filters of K-NN Query.

qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ModelIT.java, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/KNNVectorIndexFieldData.java, src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java, src/test/java/org/opensearch/knn/index/KNNSettingsTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java, src/test/java/org/opensearch/knn/plugin/action/RestDeleteModelHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestGetModelHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestSearchModelHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestTrainModelHandlerIT.java, src/test/java/org/opensearch/knn/plugin/script/KNNScriptScoringIT.java, src/test/java/org/opensearch/knn/plugin/transport/DeleteModelResponseTests.java, src/test/java/org/opensearch/knn/plugin/transport/GetModelResponseTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java, src/testFixtures/java/org/opensearch/knn/ODFERestTestCase.java, src/testFixtures/java/org/opensearch/knn/TestUtils.java
Fixed XContent, MediaTypeRegistry, CircuitBreaker, ByteSizeValue etc breaking changes coming from core.
NA
=> Fixed XContent, MediaTypeRegistry, CircuitBreaker, ByteSizeValue etc breaking changes coming from core.

CHANGELOG.md, build.gradle
Update Guava Version to 32.0.1 to address [CVE-2023-2976](https://www.cve.org/CVERecord?id=CVE-2023-2976).
https://github.com/opensearch-project/k-NN/issues/972
=> Update Guava Version to 32.0.1

build.gradle
Backport https://github.com/opensearch-project/k-NN/commit/478d87c19a43dd2ebaaeae36b2599a86bed9b7bd from https://github.com/opensearch-project/k-NN/pull/1019
=> [Backport 1.3] Update Guava Version to 32.0.1

scripts/build.sh
Remove k-NN gcc requirements ceiling and not equals 8.3.1 version
https://github.com/opensearch-project/k-NN/issues/975
=> Remove k-NN gcc requirements ceiling and not equals 8.3.1 version

scripts/windowsScript.ps1
Fix OnDiskInvertedLists.cpp file path to apply patching on Windows OS
```
> Task :windowsPatches
Get-Content : Cannot find path
'C:\Users\Administrator\AppData\Local\Temp\2\tmp0ado2fyq\k-NN\jni\external\faiss\faiss\OnDiskInvertedLists.cpp'
because it does not exist.
At C:\Users\Administrator\AppData\Local\Temp\2\tmp0ado2fyq\k-NN\scripts\windowsScript.ps1:29 char:2
+ (Get-Content jni/external/faiss/faiss/OnDiskInvertedLists.cpp).replac ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (C:\Users\Admini...vertedLists.cpp:String) [Get-Content], ItemNotFoundEx
ception
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
You cannot call a method on a null-valued expression.
At …
```
=> Fix OnDiskInvertedLists file path for windows patching

src/main/java/org/opensearch/knn/plugin/script/KNNScoreScript.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoreScriptFactory.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java, src/test/java/org/opensearch/knn/index/KNNSettingsTests.java
Fixing the backward incompatible changes coming from core in ScoreScript class and index.store.hybrid.mmap.extensions setting
The change includes:
1. Fixing the backward incompatible changes in ScoreScript class. https://github.com/opensearch-project/OpenSearch/pull/9081
2. index.store.hybrid.mmap.extensions settings is deprecated. Hence it is adding warnings and failing the unit tests. Added a workaround which is already added in the [2.x branch](https://github.com/opensearch-project/k-NN/commit/67df3aee57601ceeab81cf8b159749422c155468). This will ensure that main is unblocked. Will work on fixing this deprecated settings in future PRs.
NA …
=> Fixing the backward incompatible changes coming from core in ScoreScript class and index.store.hybrid.mmap.extensions settings

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/test/java/org/opensearch/knn/index/KNNSettingsTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
Improved the logic to switch to exact search for restrictive filters search.
This change includes:
* adding 2 extra advanced K-NN settings on when to do exact search for users to tune.
This change doesn't include:
* switching to exact search based on how many distance calculation needs to be done. Once this PR flows I will discuss more on the github issue to see how we want to implement it.
For understanding the details of the change please refer this issue: https://github.com/opensearch-project/k-NN/issues/1049
The integration tests are failing as the new backward incompatible changes are not available in snapshot. https://github.com/opensearch-project/OpenSearch/pull/9081#issuecomment-1690751080
https://github.com/opensearch-project/k-NN/issues/1049
By submitting this pull request, I …
=> Improved the logic to switch to exact search for restrictive filters search.

src/main/java/org/opensearch/knn/plugin/script/KNNScoreScript.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoreScriptFactory.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java, src/test/java/org/opensearch/knn/index/KNNSettingsTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
Fixing the backward incompatible changes coming from core in ScoreScriptipt class(#1056)
This change includes:
1. Fixing the backward incompatible changes in ScoreScript class. https://github.com/opensearch-project/OpenSearch/pull/9081
Main branch PR: https://github.com/opensearch-project/k-NN/pull/1056
NA
=> [Backport 2.x] Fixing the backward incompatible changes coming from core in ScoreScriptipt class(#1056)

CHANGELOG.md, src/main/java/org/opensearch/knn/common/KNNConstants.java, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/test/java/org/opensearch/knn/index/KNNSettingsTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
Added max distance computation logic to enhance the switch to exact search in filtered Nearest Neighbor Search.
https://github.com/opensearch-project/k-NN/issues/1049
=> Added max distance computation logic to enhance the switch to exact search in filtered Nearest Neighbor Search.

.github/workflows/CI.yml
Fixed the github actions to use the image used by OpenSearch-build repo for building the distribution
https://github.com/opensearch-project/k-NN/issues/1042
=> Fixed the github actions to use the image used by OpenSearch-build repo for building the distribution

CHANGELOG.md, src/main/java/org/opensearch/knn/index/util/Faiss.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/KNNMethodContextTests.java, src/test/java/org/opensearch/knn/index/util/FaissTests.java, src/test/java/org/opensearch/knn/jni/JNIServiceTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Updates faiss engine to enable hnsw and faiss to work together. For HNSW, code_size must be equal to 8 (refer to
https://github.com/facebookresearch/faiss/issues/3027). Therefore, the index description string "HNSW32,PQXxY" does not work. Only "HNSW32,PQX" works. This causes a problem when producing the index description string here: https://github.com/opensearch-project/k-NN/blob/2.9/src/main/java/org/opensearch/knn/index/util/Faiss.java#L104. To change this, the PQ encoder for HNSW needs to be handled differently than PQ does for IVF (which this does work for). So they are split out in Faiss.java.
Additionally, adds several unit tests and integration tests in order to validate the functionality. For PQ with code_size of 8, the minimum number of training points to prevent failure is …
=> Update Faiss engine to allow PQ and HNSW

src/test/java/org/opensearch/knn/index/util/FaissTests.java
Related to #1077 failure. Change was introduced in #1074 . Adds locale as root when comparing strings to prevent unexpected string errors.
=> Fix locale in FaissTests

src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
Fixing the check for max distance computation happening to switch to exact search. The check got messed up in the older commits. Fixing the check. Also, fixed a log statment.
NA
=> Fixing the check for max distance computation happening to switch to exact search

CHANGELOG.md, src/main/java/org/opensearch/knn/index/util/Faiss.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/KNNMethodContextTests.java, src/test/java/org/opensearch/knn/index/util/FaissTests.java, src/test/java/org/opensearch/knn/jni/JNIServiceTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
=> [Backport 2.10] Update Faiss engine to allow PQ and HNSW

CHANGELOG.md, src/main/java/org/opensearch/knn/index/util/Faiss.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/KNNMethodContextTests.java, src/test/java/org/opensearch/knn/index/util/FaissTests.java, src/test/java/org/opensearch/knn/jni/JNIServiceTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
=> [Backport 2.x] Update Faiss engine to allow PQ and HNSW

benchmarks/perf-tool/release-configs/faiss-hnswpq/index.json, benchmarks/perf-tool/release-configs/faiss-hnswpq/method-spec.json, benchmarks/perf-tool/release-configs/faiss-hnswpq/test.yml, benchmarks/perf-tool/release-configs/faiss-hnswpq/train-index-spec.json
Adds HNSW PQ perf test config to release configs.
Ran on my own machine and got the following results:
```
"results": {
"test_took": 293816.24999604654,
"delete_model_took_total": 74.6723180054687,
"delete_index_took_total": 91.5388090070337,
"train_model_took_total": 98810.09195902152,
"create_index_took_total": 447.3603710066527,
"ingest_took_total": 67643.88565102126,
"refresh_index_store_kb_total": 969579.529296875,
"refresh_index_took_total": 25093.700887984596,
"query_took_total": 101655.0,
"query_took_p50": 10.0,
"query_took_p90": 11.0,
"query_took_p99": 12.0,
"query_took_p99.9": 13.0,
"query_took_p100": 99.0,
"query_client_time_total": 121304.0,
"query_client_time_p50": 12.0,
"query_client_time_p90": 13.0,
"query_client_time_p99": 14.0,
"query_client_time_p99.9": 41.0, …
```
=> Add HNSW PQ configuration to perf tests

.github/workflows/CI.yml
Adding get-ci-image-tag dynamic retrival on CI workflows
https://github.com/opensearch-project/opensearch-build/issues/3966
https://github.com/opensearch-project/k-NN/issues/1042
=> Adding get-ci-image-tag dynamic retrival on CI workflows

CHANGELOG.md, build.gradle
Upgrades bytebuddy version to match OpenSearch core
=> Upgrade bytebuddy version to match OpenSearch core

src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java, src/main/java/org/opensearch/knn/index/util/KNNEngine.java
OpenSearch core recently updated the lucene version, rendering some constants used in k-NN obsolete.  This PR updates to the new versions of those constants.
=> Change imports to align with core lucene upgrade

src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
Removed unnecessary call to find live docs during filtered search
NA
=> Removed unnecessary call to find live docs during filtered search

CHANGELOG.md, src/main/java/org/opensearch/knn/index/IndexUtil.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
Add ignore_unmapped support in KNNQueryBuilder
https://github.com/opensearch-project/k-NN/issues/1018
=> [Backport 2.x] Add ignore_unmapped support in KNNQueryBuilder

CHANGELOG.md, src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java, src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java, src/main/java/org/opensearch/knn/index/codec/util/KNNVectorSerializerFactory.java, src/main/java/org/opensearch/knn/plugin/stats/KNNGraphValue.java, src/main/java/org/opensearch/knn/plugin/stats/KNNStats.java, src/main/java/org/opensearch/knn/plugin/stats/StatNames.java, src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java, src/testFixtures/java/org/opensearch/knn/TestUtils.java
Backport of https://github.com/opensearch-project/k-NN/pull/1141
=> [Backport 2.x] Add graph creation stats to KNNStats API

.github/workflows/CI.yml
Switch from rockylinux8 to centos7 docker image for legacy support before deprecation
#1042
=> Switch from rockylinux8 to centos7 docker image for legacy support before deprecation

CHANGELOG.md, src/main/java/org/opensearch/knn/common/KNNConstants.java, src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java, src/test/java/org/opensearch/knn/index/NestedSearchIT.java, src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java
Call DiversifyingChildren[Byte|Float]KnnVectorQuery for nested field so that k number of parent document can be returned in search result
https://github.com/opensearch-project/k-NN/issues/1065
=> Add parent join support for lucene knn

.github/workflows/backwards_compatibility_tests_workflow.yml
Fixing the BWC test which is failing due to 2.10.0-snapshot present in the bwc versions
NA
=> Fixing the BWC test which is failing due to 2.10.0-snapshot present in the bwc versions

benchmarks/perf-tool/release-configs/faiss-hnsw/filtering/relaxed-filter/relaxed-filter-test.yml, benchmarks/perf-tool/release-configs/faiss-hnsw/filtering/restrictive-filter/restrictive-filter-test.yml, benchmarks/perf-tool/release-configs/faiss-hnsw/test.yml, benchmarks/perf-tool/release-configs/faiss-hnswpq/test.yml, benchmarks/perf-tool/release-configs/faiss-ivf/filtering/relaxed-filter/relaxed-filter-test.yml, benchmarks/perf-tool/release-configs/faiss-ivf/filtering/restrictive-filter/restrictive-filter-test.yml, benchmarks/perf-tool/release-configs/faiss-ivf/test.yml, benchmarks/perf-tool/release-configs/faiss-ivfpq/test.yml, benchmarks/perf-tool/release-configs/lucene-hnsw/filtering/relaxed-filter/relaxed-filter-test.yml, benchmarks/perf-tool/release-configs/lucene-hnsw/filtering/restrictive-filter/restrictive-filter-test.yml, benchmarks/perf-tool/release-configs/lucene-hnsw/test.yml, benchmarks/perf-tool/release-configs/nmslib-hnsw/test.yml, benchmarks/perf-tool/release-configs/run_all_tests.sh
Simply the process to run performance test for release
0. Update cluster setting with `"knn.algo_param.index_thread_qty" : 4`
1. Download hdf5 data
2. Modify test template with correct value of endpoint, port, path to json files, and path to hdf5 files manually.
3. Run knn-per-tool.py
4. Repeat step2 and step3 for 12 test cases
1. Download hdf5 data in k-NN/benchmakrs/perf-tool/dataset/
2. Run run_all_tests.sh --endpoint <your_endpoint>
N/A
=> Improvement in release perf test

.github/workflows/CI.yml
Make sure not hardcoding user name when switching to uid 1000 on CI.yml
https://github.com/opensearch-project/k-NN/issues/1042
=> Make sure not hardcoding user name when switching to uid 1000 on CI.yml

benchmarks/perf-tool/release-configs/faiss-hnsw/filtering/relaxed-filter/relaxed-filter-test.yml, benchmarks/perf-tool/release-configs/faiss-hnsw/filtering/restrictive-filter/restrictive-filter-test.yml, benchmarks/perf-tool/release-configs/faiss-hnsw/test.yml, benchmarks/perf-tool/release-configs/faiss-hnswpq/test.yml, benchmarks/perf-tool/release-configs/faiss-ivf/filtering/relaxed-filter/relaxed-filter-test.yml, benchmarks/perf-tool/release-configs/faiss-ivf/filtering/restrictive-filter/restrictive-filter-test.yml, benchmarks/perf-tool/release-configs/faiss-ivf/test.yml, benchmarks/perf-tool/release-configs/faiss-ivfpq/test.yml, benchmarks/perf-tool/release-configs/lucene-hnsw/filtering/relaxed-filter/relaxed-filter-test.yml, benchmarks/perf-tool/release-configs/lucene-hnsw/filtering/restrictive-filter/restrictive-filter-test.yml, benchmarks/perf-tool/release-configs/lucene-hnsw/test.yml, benchmarks/perf-tool/release-configs/nmslib-hnsw/test.yml
No much difference was found between the two configuration. Therefore, reduce the number of test run to make test to complete faster.
1 run = 46 minutes
3 runs = 2.3 hours
10 runs = 7.6 hours
  | 10 runs(base) | 10 runs | 3 runs | 1 run | Diff 10 runs(%) | Diff 3 runs(%) | Diff 1 run(%)
-- | -- | -- | -- | -- | -- | -- | --
Faiss_HNSW_PQ_Test | 61312 | 58170 | 57856 | 56119 | 5.12461 | 5.63674 | 8.46979
Faiss_HNSW_Relaxed_Filter_Test | 60404 | 62387 | 59828 | 61827 | -3.2829 | 0.95358 | -2.3558
Faiss_HNSW_Restrictive_Filter_Test | 59952 | 61615 | 60726 | 61266 | -2.77389 | -1.29103 | -2.19175
Faiss_HNSW_Test | 57546 | 58018 | 55960 | 56531 | -0.82021 | 2.75606 | 1.76381
Faiss_IVF | 57185 | 55504 | 58951 | 56165 | 2.93958 | -3.08822 | 1.78368
Faiss_IVF_PQ_Test | 57879 | 55794 | 58157 | …
=> Reduce number of test run from 10 to 3

CHANGELOG.md, benchmarks/osb/requirements.txt, benchmarks/perf-tool/requirements.txt
Upgrades the urllib dependency to version 1.26.17
https://github.com/opensearch-project/k-NN/issues/1231
=> Upgrade urllib to 1.26.17

.github/CODEOWNERS, MAINTAINERS.md
Adds ryanbogan as maintainer and codeowner for k-NN repository.
=> Add ryanbogan as maintainer and codeowner

CHANGELOG.md, DEVELOPER_GUIDE.md
Backport of https://github.com/opensearch-project/k-NN/pull/1222
https://github.com/opensearch-project/k-NN/issues/580
=> [Backport 2.x] Update developer guide to include M1 Setup

.github/workflows/CI.yml, .github/workflows/backwards_compatibility_tests_workflow.yml, .github/workflows/test_security.yml, build.gradle, src/main/java/org/opensearch/knn/indices/ModelDao.java, src/testFixtures/java/org/opensearch/knn/TestUtils.java
This updates the CI system to use jdk-21, which is latest LTS supported version. 
Coming from https://github.com/opensearch-project/OpenSearch/issues/10334
=> Update CI to use jdk-21

.github/workflows/backwards_compatibility_tests_workflow.yml, build.gradle, src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java, src/main/java/org/opensearch/knn/index/util/KNNEngine.java
Combination of https://github.com/opensearch-project/k-NN/pull/1211 and backport of https://github.com/opensearch-project/k-NN/pull/1147
CI will not pass unless both are combined on the branch.
=> Increment version to 2.12.0-SNAPSHOT and change imports to align with core lucene upgrade

CHANGELOG.md, jni/include/nmslib_wrapper.h, jni/tests/nmslib_wrapper_test.cpp
Ties `data` variable to lifetime of `IndexWrapper` by making it struct member as opposed to local constructor variable. This change reflects the structure of `IndexWrapper` before https://github.com/opendistro-for-elasticsearch/k-NN/commit/7640186417fda86d84e0146dd5291d7fe2a81f24.
Add unit test. The unit test sometimes reproduces the issue. However, it is difficult to reproduce deterministically. I was able to reproduce on my mac fairly consistently, but not able to reproduce on linux.
#1304 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#de …
=> Fix use-after-free bug in nmslib engine query path

DEVELOPER_GUIDE.md
When running OpenSearch with knn plugin on MAC M1, we need to build the JNI library such as faiss, nmslib manually, but if we don't use JDK for ARM, then we can see the error `mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')` when executing knn search. And if we start OpenSearch by running `./bin/opensearch` directly on MAC M1 and do not set the environment variable `JAVA_LIBRARY_PATH`, then OpenSearch cannot find the JNI library. We need to add more description about how to run OpenSearchon MAC M1 to make it clear for users.
https://github.com/opensearch-project/k-NN/issues/580
For more information on following Developer Certificate of Origin …
=> Add more description about running OpenSearch on MAC M1 to developer guide

CHANGELOG.md, benchmarks/osb/requirements.txt, benchmarks/perf-tool/requirements.txt, build.gradle
Updates Guava and urllib3 versions.
https://nvd.nist.gov/vuln/detail/CVE-2023-2976
https://nvd.nist.gov/vuln/detail/CVE-2023-45803
=> Update CVE-affected dependency versions

release-notes/opensearch-knn.release-notes-2.10.0.0.md
Fix the 2.10 release notes where the clear cache API feature was added to it by mistake.
=> Fix 2.10 Release Notes

src/test/java/org/opensearch/knn/plugin/action/RestClearCacheHandlerIT.java
Fix failing integration test. If there are any system indices in the cluster, the test will fail during validation as they are non-knn indices.
```
org.opensearch.knn.plugin.action.RestClearCacheHandlerIT > testClearCacheMultipleIndices FAILED
org.opensearch.client.ResponseException: method [POST], host [https://127.0.0.1:52190/], URI [/_plugins/_knn/clear_cache/_all], status line [HTTP/2.0 500 Internal Server Error]
{"error":{"root_cause":[{"type":"k_n_n_invalid_indices_exception","reason":"ClearCache request rejected. One or more indices have 'index.knn' set to false."}],"type":"k_n_n_invalid_indices_exception","reason":"ClearCache request rejected. One or more indices have 'index.knn' set to false."},"status":500}
``` 
By submitting this pull request, I confirm that my contribution is …
=> Fix Failing Clear Cache API Test

CHANGELOG.md, src/main/java/org/opensearch/knn/index/IndexUtil.java, src/main/java/org/opensearch/knn/training/VectorReader.java, src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java, src/test/java/org/opensearch/knn/index/IndexUtilTests.java, src/test/java/org/opensearch/knn/plugin/action/RestTrainModelHandlerIT.java, src/test/java/org/opensearch/knn/training/VectorReaderTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Manually backport #1318 into 2.x branch to replace failed auto backport PR #1338 
=> [Manually backport 2.x] Allow nested knn field mapping when train model

CHANGELOG.md, src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java, src/main/java/org/opensearch/knn/index/codec/KNN950Codec/KNN950PerFieldKnnVectorsFormat.java, src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java, src/main/java/org/opensearch/knn/index/util/KNNEngine.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
Since Lucene moved the max dimension limit to codec, we are able to change it in k-NN Lucene codec. This PR updates the Lucene engine dimension max limit to 16k which is consistent with other k-NN engines.
Closes https://github.com/opensearch-project/k-NN/issues/925
=> Increase Lucene max dimension limit to 16,000

CHANGELOG.md, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java, qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java, src/main/java/org/opensearch/knn/index/KNNMethod.java, src/main/java/org/opensearch/knn/index/KNNMethodContext.java, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/MethodComponent.java, src/main/java/org/opensearch/knn/index/MethodComponentContext.java, src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/LegacyFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java, src/main/java/org/opensearch/knn/index/util/AbstractKNNLibrary.java, src/main/java/org/opensearch/knn/index/util/IndexHyperParametersUtil.java, src/main/java/org/opensearch/knn/index/util/NativeLibrary.java, src/main/java/org/opensearch/knn/training/TrainingJob.java, src/test/java/org/opensearch/knn/KNNTestCase.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/IndexUtilTests.java, src/test/java/org/opensearch/knn/index/KNNMethodContextTests.java, src/test/java/org/opensearch/knn/index/KNNSettingsTests.java, src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/index/util/FaissTests.java, src/test/java/org/opensearch/knn/index/util/IndexHyperParametersUtilTests.java, src/test/java/org/opensearch/knn/jni/JNIServiceTests.java, src/test/java/org/opensearch/knn/training/TrainingJobTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Changed the default values for ef_search and ef_constrction for enabling better indexing and search latency for vector search
https://github.com/opensearch-project/k-NN/issues/1354
Manual Testing was performed by running `./gradlew run` on 2.11 branch. After this [this](https://gist.github.com/navneet1v/cc36b3c27646b2dcd8856167c1581ea5) script was executed with 2.11 arg.
Once it is completed, I ran the `./gradlew run --preserve-data` with updated code. This ensured that old indices are still available and shards are initialized. After this I ran the same script with 2.12 as the parameter.
Added new BWC test for rolling and restart upgrade to validate index creation and indexing of documents.
In both the testings validated(via logs) that for all the indices the older values of hyper …
=> Tune default values for ef_search and ef_construction for better indexing and search performance

CHANGELOG.md, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java, qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java, src/main/java/org/opensearch/knn/index/KNNMethod.java, src/main/java/org/opensearch/knn/index/KNNMethodContext.java, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/MethodComponent.java, src/main/java/org/opensearch/knn/index/MethodComponentContext.java, src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/LegacyFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java, src/main/java/org/opensearch/knn/index/util/AbstractKNNLibrary.java, src/main/java/org/opensearch/knn/index/util/IndexHyperParametersUtil.java, src/main/java/org/opensearch/knn/index/util/NativeLibrary.java, src/main/java/org/opensearch/knn/training/TrainingJob.java, src/test/java/org/opensearch/knn/KNNTestCase.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/IndexUtilTests.java, src/test/java/org/opensearch/knn/index/KNNMethodContextTests.java, src/test/java/org/opensearch/knn/index/KNNSettingsTests.java, src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/index/util/FaissTests.java, src/test/java/org/opensearch/knn/index/util/IndexHyperParametersUtilTests.java, src/test/java/org/opensearch/knn/jni/JNIServiceTests.java, src/test/java/org/opensearch/knn/training/TrainingJobTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Tuned default values for ef_search and ef_construction for better indexing and search performance (#1353)
Backport of https://github.com/opensearch-project/k-NN/pull/1353
auto backport failed: https://github.com/opensearch-project/k-NN/pull/1361 due to backward incompatible changes from core 3.0 to 2.x
https://github.com/opensearch-project/k-NN/issues/1354
=> [Backport 2.x] Tuned default values for ef_search and ef_construction for better indexing and search performance (#1353)

.github/workflows/CI.yml, DEVELOPER_GUIDE.md, jni/CMakeLists.txt, jni/patches/faiss/0001-Custom-patch-to-support-multi-vector.patch
Add patch to support multi vector in faiss
Introduced an extension point in the way of collecting search result in HNSW algorithm. `ResultCollectorFactory` is passed as part of a search parameter. For each search inside faiss library, it create a new `ResultCollector` using the factory. The `ResultCollector`'s `collect` method is used to collect search data.
This enable us to pass custom ResultCollector with which we can dedupe vector on its parent Id so that exact k result of original document can be returned for nested field.
* PR for patch file to make it easy to review. https://github.com/heemin32/faiss/pull/1/files
https://github.com/opensearch-project/k-NN/issues/1065 …
=> Add patch to support multi vector in faiss

jni/patches/faiss/0001-Custom-patch-to-support-multi-vector.patch
=> Initialize id_map as null

qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ModelIT.java, src/test/java/org/opensearch/knn/plugin/transport/GetModelResponseTests.java
=> Fix flaky tests

jni/CMakeLists.txt, jni/include/faiss_wrapper.h, jni/include/knn_extension/faiss/MultiVectorResultCollector.h, jni/include/knn_extension/faiss/MultiVectorResultCollectorFactory.h, jni/include/knn_extension/faiss/utils/BitSet.h, jni/include/knn_extension/faiss/utils/Heap.h, jni/include/org_opensearch_knn_jni_FaissService.h, jni/src/faiss_wrapper.cpp, jni/src/knn_extension/faiss/MultiVectorResultCollector.cpp, jni/src/knn_extension/faiss/MultiVectorResultCollectorFactory.cpp, jni/src/knn_extension/faiss/utils/BitSet.cpp, jni/src/org_opensearch_knn_jni_FaissService.cpp, jni/tests/faiss_wrapper_test.cpp, jni/tests/knn_extension/faiss/MultiVectorResultCollectorFactoryTest.cpp, jni/tests/knn_extension/faiss/MultiVectorResultCollectorTest.cpp, jni/tests/knn_extension/faiss/utils/BitSetTest.cpp, jni/tests/knn_extension/faiss/utils/HeapTest.cpp, src/main/java/org/opensearch/knn/jni/FaissService.java, src/main/java/org/opensearch/knn/jni/JNIService.java
With this PR, QueryIndex and QueryIndex_WithFilter JNI method can take a list of parentId to dedupe search result per parent. To do that, custom result collector is implemented which will be passed as HNSW search parameter to faiss library.
N/A
=> Add support of multi vector in jni

CHANGELOG.md, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ScriptScoringIT.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoreScriptFactory.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoreScriptLeafFactory.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringScriptEngine.java, src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java, src/test/java/org/opensearch/knn/plugin/script/KNNScriptScoringIT.java, src/test/java/org/opensearch/knn/plugin/script/PainlessScriptIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
This PR fixs the issue when trying perform a Script Score query in k-NN with `request_cache=true` not work as expected.
Details on issue debug: https://github.com/opensearch-project/k-NN/issues/1098#issuecomment-1874610636
Closes https://github.com/opensearch-project/k-NN/issues/1098
=> Fix script score queries not getting cached

CHANGELOG.md, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ScriptScoringIT.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoreScriptFactory.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoreScriptLeafFactory.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringScriptEngine.java, src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java, src/test/java/org/opensearch/knn/plugin/script/KNNScriptScoringIT.java, src/test/java/org/opensearch/knn/plugin/script/PainlessScriptIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Backport https://github.com/opensearch-project/k-NN/pull/1367 to 2.x branch.
=> [Backport 2.x] Fix script score queries not getting cached

src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoTransportActionTests.java
Recently, we have seen that TrainingJobRouteDecisionInfoTransportActionTests has been having failures on Windows (for example: https://github.com/jmazanec15/k-NN-1/actions/runs/7415192445/job/20177850505). The failures are related to an unintialized cluster state tryiing to be accessed after calling training. Still not sure why the cluster state is null after the test starts, but this does not have anything to do with the test itself. 
Most likely, the flakiness is the result of state sharing that happens with KNNSingleNodeTestCase. KNNSingleNodeTestCase inherits from [OpenSearchSingleNodeTestCase](https://github.com/opensearch-project/OpenSearch/blob/main/test/framework/src/main/java/org/opensearch/test/OpenSearchSingleNodeTestCase.java) which will start a node as a part of running each …
=> Refactor TrainingJobRouteDecisionInfo test to use KNNTestCase

CHANGELOG.md, src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java, src/test/java/org/opensearch/knn/index/AdvancedFilteringUseCasesIT.java, src/test/java/org/opensearch/knn/index/NestedSearchIT.java, src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java, src/testFixtures/java/org/opensearch/knn/NestedKnnDocBuilder.java
Enabled Filtering on Nested Vector fields with top level filters.
After this change, below use case for filtering is supported with vector search(both Lucene and Faiss). The change is BWC.:
1. When vector field is nested and filters are applied on non-nested fields.
2. When vector field is nested and filters are applied nested fields.
3. When vector field is nested and filters are applied on nested fields with nested path provided in filters.
4. When vector field is non-nested and filters are applied on nested fields with nested path provided in filters.
To ensure that any further changes in the filter code we are able to catch the bugs, I added a new IT test class `AdvancedFilteringUseCasesIT` which has integration tests for all the above use-cases.
**Context**
There was feature gap in …
=> Enabled Filtering on Nested Vector fields with top level filters

CHANGELOG.md, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
Throw proper exception to invalid k-NN query in some cases:
1. In case of field “vector” is missing, it will cause NullPointerException;
2. In case of the array of “vector” contains non-number object, it will cause cast exception;
After the PR, the response will be:
```
// Case 1
{
"error": {
"root_cause": [
{
"type": "illegal_argument_exception",
"reason": "[knn] requires 'vector' to be non-null"
}
],
"type": "illegal_argument_exception",
"reason": "[knn] requires 'vector' to be non-null"
},
"status": 400
}
```
```
// Case 2
{
"error": {
"root_cause": [
{
"type": "illegal_argument_exception",
"reason": "[knn] requires 'vector' to be an array of numbers"
}
],
"type": "illegal_argument_exception",
"reason": "[knn] requires 'vector' to be an array of numbers"
},
"status": 400
}
```
Closes …
=> Throw proper exception to invalid k-NN query

src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/main/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNIterator.java, src/main/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNIterator.java, src/test/java/org/opensearch/knn/common/Constants.java, src/test/java/org/opensearch/knn/index/NestedSearchIT.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java, src/test/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNIteratorTests.java, src/test/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNIteratorTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
When filter query is provided using Faiss engine, knn search can be run in exact search mode instead of ANN mode based on few conditions. One of the condition is when k is larger than the size of list of filtered IDs.
This PR handles multi-vector in the exact search mode with Faiss engine.
https://github.com/opensearch-project/k-NN/issues/1065
=> Handle multi-vector in exact search scenario

benchmarks/perf-tool/README.md, benchmarks/perf-tool/add-parent-doc-id-to-dataset.py, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
Add data generation script for nested field. The script is similar to `add-filters-to-dataset.py` but it adds parent id as attributes to an existing vector data so that the value can be used to construct document with nested field.
N/A
=> Add data generation script for nested field

CHANGELOG.md, src/main/java/org/opensearch/knn/index/query/KNNScorer.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
When using boost along with the `KNNQuery`, the boost is not applied.
=> Fix KNNScorer to apply boost

CHANGELOG.md, src/main/java/org/opensearch/knn/index/query/KNNQuery.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
The `equals` and `hashCode` implementations of `KNNQuery` and `KNNQueryBuilder` are missing some fields (`indexName` and `filterQuery` for `KNNQuery`, `filter` and `ignoreUnmapped` for `KNNQueryBuilder`) and are not using the correct array comparison/hash method. 
The error in the relevant unit test is as follows:
```
java.lang.AssertionError: expected: org.opensearch.knn.index.query.KNNQueryBuilder<{
"knn" : {
"myvector" : {
"vector" : [
1.0,
2.0,
3.0,
4.0
],
"k" : 1,
"filter" : {
"term" : {
"field" : {
"value" : "value",
"boost" : 1.0
}
}
},
"boost" : 1.0
}
}
}> but was: org.opensearch.knn.index.query.KNNQueryBuilder<{
"knn" : {
"myvector" : {
"vector" : [
1.0,
2.0,
3.0,
4.0
],
"k" : 1,
"filter" : {
"term" : {
"field" : {
"value" : "value",
"boost" : 1.0
}
}
},
"boost" : 1.0
}
}
}>
at …
```
=> Fix equals and hashCode methods for KNNQuery and KNNQueryBuilder

.github/workflows/test_security.yml, DEVELOPER_GUIDE.md, build.gradle
Remove references to admin:admin default security credentials in the developer guide.
https://github.com/opensearch-project/k-NN/issues/1359
=> Remove default admin credential references in DEVELOPER_GUIDE

src/testFixtures/java/org/opensearch/knn/ODFERestTestCase.java, src/testFixtures/java/org/opensearch/knn/TestUtils.java
Skip delete `.plugins-ml-config` system index during integ test.
This PR helps to resolve the error during k-NN build security enabled integ test in release Jenkins concurrent-search-test CI:
```
org.opensearch.client.ResponseException: method [DELETE], host [https://localhost:9200/], URI [/.plugins-ml-config], status line [HTTP/1.1 403 Forbidden]
{"error":{"root_cause":[{"type":"security_exception","reason":"no permissions for [] and User [name=admin, backend_roles=[admin], requestedTenant=null]"}],"type":"security_exception","reason":"no permissions for [] and User [name=admin, backend_roles=[admin], requestedTenant=null]"},"status":403}
at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:376)
```
With @peterzhuamazon 's help, the Jenkins’s CI build passed  with …
=> Skip delete .plugins-ml-config system index during integ test

DEVELOPER_GUIDE.md
Fixes markdown formatting in the developer guide, through accidental removal of ``` in #1415 
=> Fix markdown formatting in developer guide

CHANGELOG.md, src/test/java/org/opensearch/knn/plugin/action/RestDeleteModelHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestGetModelHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestSearchModelHandlerIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Refactors integration tests that directly access the model system index. End users should not be directly accessing the model system index. It is supposed to be an implementation detail. We have written restful integration tests that directly access the model system index in order to initialize the cluster state. However, we should not do this because users should not be able to interact with it through restful APIs. In fact, in some cluster configurations, it should not be possible.
That being said, some of this implementation detail leaks out through the interface. For instance, in k-NN stats we have a stat that is the model system index status. So, in order to test this, we do need direct access to the system index. Similarly, for search, we execute the search against the system index …
=> Refactor integ tests that access model index

CHANGELOG.md, src/test/java/org/opensearch/knn/plugin/action/RestDeleteModelHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestGetModelHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestSearchModelHandlerIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
=> [Backport 2.x] Refactor integ tests that access model index

CHANGELOG.md, src/test/java/org/opensearch/knn/indices/ModelDaoTests.java
Since `ModelDaoTests` extends `KNNSingleNodeTestCase`, a node is started at the beginning of each test and stopped at the end of each test.  The `TrainingJobClusterStateListenerClass` contains a `clusterChanged` method that is called each time a new cluster is started.  Within this method, a separate thread runs through all existing models and marks any that are stuck in training as failed.  This can result in a scenario that causes flaky tests.
In this scenario, a node is started at the beginning of a test, calling the `clusterChanged` method.  The test creates a model (or multiple), verifies the expected behavior, and then stops the node.  Meanwhile, the other thread is in the process of looping through any existing models and potentially updating their model state parameter.  If the …
=> Fix flaky model tests

CHANGELOG.md, jni/src/faiss_wrapper.cpp, jni/tests/faiss_wrapper_test.cpp
In IDSelectorBitmap initialization, we pass size of filtered id array which is not correct. It should be size of bitmap.
https://github.com/opensearch-project/k-NN/issues/1435
=> Pass correct value on IDSelectorBitmap initialization

scripts/build.sh
Update build script to build and include both the versions of JNI libraries (with and without SIMD optimization) in the final artifact by creating two subdirectories `lib` and `lib_simd`.
https://github.com/opensearch-project/opensearch-build/issues/4386
=> Update Build Script to build libraries with SIMD

.github/workflows/CI.yml, .github/workflows/test_security.yml, CHANGELOG.md, DEVELOPER_GUIDE.md, build.gradle, jni/CMakeLists.txt, jni/patches/faiss/0002-Custom-patch-to-support-sqfp16-neon.patch, jni/patches/faiss/0003-Custom-patch-to-support-AVX2-Linux-CI.patch, jni/tests/faiss_wrapper_test.cpp, src/main/java/org/opensearch/knn/common/KNNConstants.java, src/main/java/org/opensearch/knn/index/Parameter.java, src/main/java/org/opensearch/knn/index/util/Faiss.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/ParameterTests.java, src/test/java/org/opensearch/knn/index/util/FaissTests.java, src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
Backport 5f9511b from https://github.com/opensearch-project/k-NN/pull/1421
=> [Backport 2.x] Add support for Faiss SQFP16 Quantization and enable AVX2 Optimization

jni/CMakeLists.txt
Cherry-picked [db87edd](https://github.com/opensearch-project/k-NN/commit/db87eddd30c04e1353618c7dd4d1250b10f4e579) from https://github.com/opensearch-project/k-NN/pull/1449 
=> [Backport 2.x] Set Default value for SIMD_ENABLED in CMakeList

scripts/build.sh
This reverts commit d5b42375c29315175fd4491e22abec13a166e5cf.
=> Revert "Update Build Script to build libraries with SIMD"

CHANGELOG.md, release-notes/opensearch-knn.release-notes-2.12.0.0.md
Backport of https://github.com/opensearch-project/k-NN/pull/1463
=> [Backport 2.12] Add release notes for 2.12.0 release

src/test/java/org/opensearch/knn/KNNTestCase.java, src/test/java/org/opensearch/knn/index/KNNSettingsTests.java
This PR followed from https://github.com/opensearch-project/k-NN/issues/1392#issuecomment-1932717537 to disable warnings  check in k-NN tests case and remove warning Assertions in KNNSettingsTests
https://github.com/opensearch-project/k-NN/issues/1392, https://github.com/opensearch-project/k-NN/issues/1391, https://github.com/opensearch-project/k-NN/issues/1390, https://github.com/opensearch-project/k-NN/issues/1389
=> Disable warning checks in k-NN test case

src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
Current sqfp16 tests uses vector value outside of fp16 range which result in infinite value during faiss distance calculation. Because of this infinite distance, the search result is not returned once we update faiss commit number with 32f0e8cf92cd2275b60364517bb1cce67aa29a55. 
This fix the test so that vector value to be in fp16 range.
N/A
=> Use valid data for sqfp16 test

src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
Fix a bug in https://github.com/opensearch-project/k-NN/pull/1474 where invalid max/min value of fp16 is used
N/A
=> Fix a bug on sqfp16 test

CHANGELOG.md, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java
Fix the breaking change coming from https://github.com/apache/lucene/pull/12829 which is failing the build due to mismatch in FieldInfo parameters.
```
/__w/k-NN/k-NN/src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java:168: error: constructor FieldInfo in class FieldInfo cannot be applied to given types;
return new FieldInfo(
^
required: String,int,boolean,boolean,boolean,IndexOptions,DocValuesType,long,Map<String,String>,int,int,int,int,VectorEncoding,VectorSimilarityFunction,boolean,boolean
found: String,int,boolean,boolean,boolean,IndexOptions,DocValuesType,long,Map<String,String>,int,int,int,int,VectorEncoding,VectorSimilarityFunction,boolean
reason: actual and formal argument lists differ in length
```
By submitting this pull request, I confirm that my contribution is …
=> Fix FieldInfo Parameters Mismatch

benchmarks/perf-tool/add-parent-doc-id-to-dataset.py, benchmarks/perf-tool/okpt/test/steps/steps.py, benchmarks/perf-tool/release-configs/faiss-hnsw/nested/simple/index.json, benchmarks/perf-tool/release-configs/lucene-hnsw/nested/simple/index.json, benchmarks/perf-tool/release-configs/lucene-hnsw/nested/simple/simple-nested-test.yml, benchmarks/perf-tool/release-configs/run_all_tests.sh
Because the number of items inside nested field is too big(1000, 10001), if it is included in `source`, the query latency becomes around 1s. To have fair comparison with other test case, excluding nested field from being stored in `source`.
Dataset | Train size | Dimensions | Distance | Format | K
-- | -- | -- | -- | -- | --
sift | 1,000,000(Not document number but total nested fields of entire document) | 128 | L2 | hdf5 | 100
Total Queries: 10,000
Config item | Value
-- | --
Leader Nodes | 3
Leader Node Type | c5.xlarge
Leader Node Disk Space | 20
Data Nodes | 3
Data Node Type | r5.4xlarge
Data Node Disk Space | 500
Primary Shard Count | 24
Replica Count | 1
AZ | us-east-1
Config item | Value
-- | --
OS | Amazon Linux
Instance Type | c5.9xlarge
Count | 1
EBS Size | 800G
AZ | us-east-1 …
=> Update performance test with nested field

.github/workflows/backwards_compatibility_tests_workflow.yml
Increase bwc version from 2.12.0-SNAPSHOT to 2.13.0-SNAPSHOT
=> Increment 2.12.0-SNAPSHOT to 2.13.0-SNAPSHOT in BWC workflow

.github/workflows/backwards_compatibility_tests_workflow.yml, CHANGELOG.md, jni/include/faiss_wrapper.h, jni/include/jni_util.h, jni/include/org_opensearch_knn_jni_FaissService.h, jni/src/faiss_wrapper.cpp, jni/src/jni_util.cpp, jni/src/org_opensearch_knn_jni_FaissService.cpp, jni/tests/faiss_wrapper_test.cpp, jni/tests/test_util.cpp, jni/tests/test_util.h, src/main/java/org/opensearch/knn/index/query/FilterIdsSelector.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/main/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNIterator.java, src/main/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNIterator.java, src/main/java/org/opensearch/knn/jni/FaissService.java, src/main/java/org/opensearch/knn/jni/JNIService.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategyTests.java, src/test/java/org/opensearch/knn/index/query/FilterIdsSelectorTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java, src/test/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNIteratorTests.java, src/test/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNIteratorTests.java, src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
Rebase commits to feature/radius-search branch, since I don't have permission to directly push code to this feature branch.
=> Rebase commits to feature/radius-search branch

CHANGELOG.md, jni/src/faiss_wrapper.cpp, jni/tests/faiss_wrapper_test.cpp, jni/tests/test_util.cpp, jni/tests/test_util.h
Passes flag to disable sdc table for the HNSWPQ indices. This table is only used by HNSWPQ during graph creation to compare nodes already present in graph. When we call load index, the graph is read only. Hence, we wont be doing any ingestion and so the table can be disabled to save some memory.
Along with this, added a unit test and a couple test helper methods for generating random data.
#1507 partial
Faiss issue: https://github.com/facebookresearch/faiss/issues/3246.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of- …
=> Disable sdc table for HNSWPQ read-only indices

.github/workflows/CI.yml, .github/workflows/test_security.yml, jni/CMakeLists.txt, jni/patches/faiss/0003-Enable-precomp-table-to-be-shared-ivfpq.patch
First of 3 PRs to share table amongst IVFPQ-l2 indices coming from #1507. This PR introduces the faiss patch change. In future release, we will get rid of this patch when we can achieve this functionality with faiss. Related issue here: https://github.com/facebookresearch/faiss/issues/3271. Will merge into feature branch and once all 3 are merged, will merge into main.
Patch is built from: https://github.com/jmazanec15/faiss/pull/1/commits/c5ca07299b427dedafc738b98bd20f8f286f6783. For convenience, I opened up a PR on my faiss clone for review: https://github.com/jmazanec15/faiss/pull/1. Please feel free to leave comments there.
In addition, modified different locations to apply patch.
#1507 - partial
By submitting this pull request, I confirm that my contribution is made under the terms …
=> Introduce faiss patch to share ivfpq precomp table

scripts/build.sh
Raise gcc version requirement to 9.0.0 for SIMD Neon support on ARM64
Part of https://github.com/opensearch-project/opensearch-build/issues/4386
=> Raise gcc version requirement to 9.0.0 for SIMD Neon support on ARM64

CHANGELOG.md, src/main/java/org/opensearch/knn/index/SpaceType.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/SpaceTypeTests.java
Switches the similarity function for inner product from Lucene's dot product to maximum inner product. This will allow the filter exact scoring to match results returned by faiss in ANN method.
(Retrying #1530 due to GH issue)
#1396 #1525 
=> Switch spacetype similarity function to MAXIMUM_INNER_PRODUCT

benchmarks/osb/requirements.txt
Fix jinja2 dependency CVE by bumping it from 2.11.3 to 3.1.3
https://github.com/opensearch-project/k-NN/issues/1385
=> Bump jinja2 dependency from 2.11.3 to 3.1.3

CHANGELOG.md, src/main/java/org/opensearch/knn/common/KNNValidationUtil.java, src/main/java/org/opensearch/knn/common/KNNVectorUtil.java, src/main/java/org/opensearch/knn/index/SpaceType.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java, src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtil.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringUtil.java, src/test/java/org/opensearch/knn/common/KNNVectorUtilTests.java, src/test/java/org/opensearch/knn/index/OpenSearchIT.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceFactoryTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringUtilTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Validate the vector passed by the user during querying or indexing, if the vector is zero vector and the space type of index is cosine, an exception will be thrown.
**Examples**
1. When we use cosine space type and index a zero vector through bulk api, the response returned will be as follows:
```
{
"took": 2,
"errors": true,
"items": [
{
"index": {
"_index": "products-shirts",
"_id": "1",
"status": 400,
"error": {
"type": "mapper_parsing_exception",
"reason": "failed to parse field [item_vector] of type [knn_vector] in document with id '1'. Preview of field's value: 'null'",
"caused_by": {
"type": "illegal_argument_exception",
"reason": "zero vector is not supported when space type is [cosinesimil]"
}
}
}
}
]
}
```
2. If we use cosine metric and query index is a zero vector, the response …
=> Validate zero vector when using cosine metric

qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/AbstractRollingUpgradeTestCase.java, src/main/java/org/opensearch/knn/indices/ModelDao.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/NmslibIT.java, src/test/java/org/opensearch/knn/index/OpenSearchIT.java, src/test/java/org/opensearch/knn/jni/JNIServiceTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Fix the following AppSec findings:
- CWE-22 is used to identify an "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"
weakness. 
- CWE-476 is used to identify a "NULL Pointer Dereference" weakness. 
=> Fix AppSec Findings CWE-22 and CWE-476

.github/workflows/CI.yml, .github/workflows/test_security.yml, CHANGELOG.md, jni/CMakeLists.txt, jni/patches/nmslib/0001-Initialize-maxlevel-during-add-from-enterpoint-level.patch
Adds patch to fix the segfault happening in nmslib. For more information on the patch, see https://github.com/nmslib/nmslib/issues/544.
Existing tests will cover this change. The issue can only be reproduced at large scales. I can confirm the patch has remedied seeing this issue in large OpenSearch clusters.
#1406 
=> Add patch to fix arm segfault in nmslib during ingestion

jni/include/faiss_wrapper.h, jni/include/org_opensearch_knn_jni_FaissService.h, jni/src/faiss_wrapper.cpp, jni/src/org_opensearch_knn_jni_FaissService.cpp, jni/tests/faiss_wrapper_test.cpp, src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategy.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/main/java/org/opensearch/knn/jni/FaissService.java, src/main/java/org/opensearch/knn/jni/JNIService.java, src/main/java/org/opensearch/knn/training/TrainingJob.java, src/test/java/org/opensearch/knn/index/KNNCreateIndexFromModelTests.java, src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryAllocationTests.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategyTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java, src/test/java/org/opensearch/knn/jni/JNIServiceTests.java, src/test/java/org/opensearch/knn/training/TrainingJobTests.java
Adds the set of JNI functions mentioned in https://github.com/opensearch-project/k-NN/issues/1507#issue-2169945763 to allow state to be shared between IVFPQ-l2 based indices. In addition, one more method is added, IsIndexIVFPQL2. This method needs to be added so that from java side we can confirm a particular index needs the shared state or not.
These functions are added assuming that the only state that can be shared is for IVFPQ-l2 index types. In the future, we will generalize this.
Adds unit tests for jni as well as java to test functionality.
#1507 - partial …
=> Add ability to share IVFPQ-l2 state in JNI

CHANGELOG.md, scripts/build.sh
Update k-NN build artifact script to enable SIMD on ARM for Faiss because CentOS is supporting gcc version 9.3.x
```
gcc --version
gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
=> Update k-NN build artifact script to enable SIMD on ARM for Faiss

CHANGELOG.md, src/main/java/org/opensearch/knn/index/util/Lucene.java, src/test/java/org/opensearch/knn/index/LuceneEngineIT.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/index/util/LuceneTests.java
Enabled Inner Product Space Type support for Lucene Engine. Before this change, with IP was not supported with Lucene Engine as it has the potential to give negative scores.
IT and Unit tests are added to validate the scores when dot product is negative and +ve both.
```
PUT hotels-index
{
"settings": {
"index": {
"knn": true,
"number_of_shards": 1,
"number_of_replicas": 0
}
},
"mappings": {
"location": {
"dimension": 2,
"method": {
"name": "hnsw",
"space_type": "innerproduct",
"engine": "lucene"
}
}
}
}
}
```
```
POST /_bulk?refresh
{ "index": { "_index": "hotels-index", "_id": "3" } }
{ "location": [1, 0], "parking" : "false", "rating" : 5 }
{ "index": { "_index": "hotels-index", "_id": "4" } }
{ "location": [-1, 0], "parking" : "false", "rating" : …
```
=> Enabled Inner Product Space Type support for Lucene Engine

src/main/java/org/opensearch/knn/index/IndexUtil.java, src/main/java/org/opensearch/knn/index/KNNIndexShard.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryEntryContext.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategy.java, src/main/java/org/opensearch/knn/index/memory/SharedIndexState.java, src/main/java/org/opensearch/knn/index/memory/SharedIndexStateManager.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/IndexUtilTests.java, src/test/java/org/opensearch/knn/index/KNNIndexShardTests.java, src/test/java/org/opensearch/knn/index/memory/SharedIndexStateManagerTests.java, src/test/java/org/opensearch/knn/index/memory/SharedIndexStateTests.java, src/test/java/org/opensearch/knn/recall/RecallTestsIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java, src/testFixtures/java/org/opensearch/knn/TestUtils.java
Last PR in series to fix #1507 
Adds the ability to share index state amongst indices during index load operations into the plugins memory management system. Introduces a manager of the shared state that will properly manage the lifecycle of the shared state.
Additionally, there was a bug in clear cache that had to be fixed to get this change working as well. Previously, only one index file per clear cache would be freed. This fixes that logic to clear everything.
Added unit tests and an integration test to confirm functionality. In addition, modified recall integration tests to get more coverage on the different algo configs. Along with this, had to fix a few things around the computation of recall for non-l2 space types.
Note - the addition of these integration tests will increase the …
=> Integrate index state sharing into mem management

CHANGELOG.md, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/FaissSQIT.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
Faiss SQfp16 Range Validation for Faiss IVF Models and to clip out of range values to fp16 range when the `clip` encoder parameter is set to `true`. 
https://github.com/opensearch-project/k-NN/issues/1138
=> SQFP16 Range Validation for Faiss IVF Models

CHANGELOG.md, release-notes/opensearch-knn.release-notes-2.13.0.0.md
Add release notes for 2.13.0 release 
=> Add release notes for 2.13.0 release

build.gradle
Upgrade byte-buddy version to 1.14.9
Reference: https://github.com/opensearch-project/OpenSearch/blob/d4e1ab135dfcb058b476fce09a669f4be5854702/buildSrc/version.properties#L60
[https://github.com/opensearch-project/k-NN/issues/1566](https://github.com/opensearch-project/k-NN/issues/1566)
=> Upgrade byte-buddy version to 1.14.9

CHANGELOG.md, src/main/java/org/opensearch/knn/index/query/KNNWeight.java
Currently, when performing KNN exact search, we consistently set the HitQueue size to k. However, there may be instances where the number of candidates is actually lower than k.
=> Make the HitQueue size more appropriate for exact search

CHANGELOG.md, jni/include/org_opensearch_knn_jni_FaissService.h, jni/src/org_opensearch_knn_jni_FaissService.cpp, micro-benchmarks/README.md, micro-benchmarks/build.gradle, micro-benchmarks/src/main/java/org/opensearch/knn/TransferVectorsBenchmarks.java, micro-benchmarks/src/main/resources/log4j2.properties, settings.gradle, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/jni/FaissService.java, src/main/java/org/opensearch/knn/jni/JNIService.java
Add micro-benchmark module in k-NN plugin for benchmark streaming vectors to JNI layer functionality.
This is first of many PR that will be raised for Issue: https://github.com/opensearch-project/k-NN/issues/1506.
The benchmark results that will be used in #1506 will come from this change. Hence adding it upfront.
Along with this change I am adding a new interface in JNILayer: transferVectorsV2, which is actually getting benchmarked. This interface is experimental and will changed once I start the feature development. Right now I have marked the interface as experimental. 
Micro-benchmark is a new module which is getting added in k-NN plugin that will host some client code to run the performance benchmarks. This module will help us do the benchmarking of a specific internal piece of …
=> Add micro-benchmark module in k-NN plugin for benchmark streaming vectors to JNI layer functionality.

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNVectorDVLeafFieldData.java, src/main/java/org/opensearch/knn/index/KNNVectorScriptDocValues.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/KNNVectorScriptDocValuesTests.java, src/test/java/org/opensearch/knn/index/LuceneEngineIT.java, src/test/java/org/opensearch/knn/index/NmslibIT.java, src/test/java/org/opensearch/knn/index/OpenSearchIT.java, src/test/java/org/opensearch/knn/index/VectorDataTypeTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringUtilTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScriptScoringIT.java, src/test/java/org/opensearch/knn/plugin/script/PainlessScriptIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java, src/testFixtures/java/org/opensearch/knn/KNNResult.java
Today, script score is not supported if using lucene engine and doc value is disabled, because k-NN plugin uses doc value to execute exact query with script score. But actually, we can use `ByteVectorValues/FloatVectorValues` to execute this type of query.
In addition to , I think that we can totally disable doc value when using lucene engine, vector values can replace the function of doc value. Further, we can use `FlatVectorsFormat` to store vector values and implement our own native index functionality, so that we can avoid extra de/serialization and unify the script doc value interface. Any thoughts?
Btw, This PR has not added relevant tests yet. 
For more information on …
=> Support script score when doc value is disabled

jni/include/faiss_wrapper.h, jni/include/nmslib_wrapper.h, jni/include/org_opensearch_knn_jni_FaissService.h, jni/include/org_opensearch_knn_jni_NmslibService.h, jni/src/faiss_wrapper.cpp, jni/src/nmslib_wrapper.cpp, jni/src/org_opensearch_knn_jni_FaissService.cpp, jni/src/org_opensearch_knn_jni_NmslibService.cpp, jni/tests/faiss_wrapper_test.cpp, jni/tests/nmslib_wrapper_test.cpp, src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java, src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java, src/main/java/org/opensearch/knn/jni/FaissService.java, src/main/java/org/opensearch/knn/jni/JNIService.java, src/main/java/org/opensearch/knn/jni/NmslibService.java, src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryAllocationTests.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategyTests.java, src/test/java/org/opensearch/knn/jni/JNIServiceTests.java, src/test/java/org/opensearch/knn/training/TrainingJobTests.java, src/testFixtures/java/org/opensearch/knn/TestUtils.java
Integrating storeVectors interfaces with createIndex and createIndexTemplate functions.
**This PR includes:**
1. I have changed the interface of createIndex and createIndexTemplate api to start using vectorAddress and dim, instead of vectors array.
2. As of now all the vectors are still getting passed to native memory at once. In the upcoming PR I will make the change to send the vectors in chunks, after updating the RFC.
3. I have remove the freeVector function from the code and started using JNICommons function. 
4. The transfer vector function is still there and will be removed in upcoming PRs after doing more testing.
**Critical decision**
As we have started sending vectorsAddress to Native layer as compared to vectordata, one of the critical code part here is who should free up the …
=> Integrating storeVectors interfaces with createIndex and createIndexTemplate functions.

CHANGELOG.md, src/main/java/org/opensearch/knn/index/SpaceType.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/index/util/Faiss.java, src/main/java/org/opensearch/knn/index/util/KNNEngine.java, src/main/java/org/opensearch/knn/index/util/KNNLibrary.java, src/main/java/org/opensearch/knn/index/util/Lucene.java, src/main/java/org/opensearch/knn/index/util/Nmslib.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/LuceneEngineIT.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java, src/test/java/org/opensearch/knn/index/util/AbstractKNNLibraryTests.java, src/test/java/org/opensearch/knn/index/util/NativeLibraryTests.java, src/test/java/org/opensearch/knn/plugin/stats/suppliers/LibraryInitializedSupplierTests.java
This PR allows user to use `score` as threshold to search vectors, the search result contains all docs which score higher than the `score` for Lucene and Faiss engines ANN search.
During index mapping and indexing stages no behavior change. Some query examples:
* Faiss engine with L2 space type
```
curl --location --request GET 'http://localhost:9200/target-index-faiss/_search' \
--header 'Content-Type: application/json' \
--data '{
"size":12,  
"query": {
"knn": {
"my_vector1": {
"vector": [7.5, 8.5],
"score": 0.5
}
}
}
}'
// Query results
{
"took": 4,
"_shards": {
"total": 1,
"successful": 1,
"skipped": 0,
"failed": 0
},
"hits": {
"total": {
"value": 1,
"relation": "eq"
},
"max_score": 0.7462686,
"hits": [
{
"_index": "target-index-faiss",
"_id": "1",
"_score": …
```
=> Support score type threshold in radial search

scripts/build.sh
Fix find command to look in correct place. This broke because micro-benchmarks ends up producing a zip in the build/distributions folder.
Locally:
Without fix:
```
$ find "$(pwd)" -path \*build/distributions/*.zip
<PATH>/k-NN-1/micro-benchmarks/build/distributions/micro-benchmarks-2.14.0.0-SNAPSHOT.zip
<PATH>/k-NN-1/build/distributions/opensearch-knn-3.0.0.0-SNAPSHOT.zip
```
With fix
```
$ find "$(pwd)/build/distributions" -path \*.zip
<PATH>/k-NN-1/build/distributions/opensearch-knn-3.0.0.0-SNAPSHOT.zip
```
#1591  #1585 …
=> Fix script to pick up correct zip

src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80BinaryDocValues.java, src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesReader.java, src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecServiceTests.java
Update KNN80BinaryDocValues reader count live docs and use live docs as initial capacity to initialize vector address.
I have also added a fix for UTs which were failing. https://github.com/opensearch-project/k-NN/issues/1593
**Older Prs:**
https://github.com/opensearch-project/k-NN/pull/1588
https://github.com/opensearch-project/k-NN/pull/1583
https://github.com/opensearch-project/k-NN/pull/1586
https://github.com/opensearch-project/k-NN/issues/1506
=> Update KNN80BinaryDocValues reader count live docs and use live docs as initial capacity to initialize vector address

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNVectorDVLeafFieldData.java, src/main/java/org/opensearch/knn/index/KNNVectorScriptDocValues.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/KNNVectorScriptDocValuesTests.java, src/test/java/org/opensearch/knn/index/LuceneEngineIT.java, src/test/java/org/opensearch/knn/index/NmslibIT.java, src/test/java/org/opensearch/knn/index/OpenSearchIT.java, src/test/java/org/opensearch/knn/index/VectorDataTypeTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringUtilTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScriptScoringIT.java, src/test/java/org/opensearch/knn/plugin/script/PainlessScriptIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java, src/testFixtures/java/org/opensearch/knn/KNNResult.java
backport [1573](https://github.com/opensearch-project/k-NN/pull/1573)
=> [Backport 2.x] Support script score when doc value is disabled (#1573)

jni/src/faiss_wrapper.cpp, jni/src/nmslib_wrapper.cpp, jni/tests/faiss_wrapper_test.cpp, jni/tests/nmslib_wrapper_test.cpp, src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java, src/main/java/org/opensearch/knn/jni/FaissService.java, src/main/java/org/opensearch/knn/jni/JNIService.java, src/main/java/org/opensearch/knn/jni/NmslibService.java, src/test/java/org/opensearch/knn/jni/JNIServiceTests.java, src/testFixtures/java/org/opensearch/knn/TestUtils.java
Move free vectorAddress from Java to JNI layer to reduce the memory footprint for Nmslib.
Earlier we were freeing up memory in the Java layer where the thought process was as Java layer has init the memory location it should free up the space. 
But due to limitations provided here: https://github.com/opensearch-project/k-NN/issues/1600 for nmslib doing that can triple the memory footprint for index creation. Hence, we are freeing up the memory in the JNI layer.
This code will be removed once we do the long term fix via #1600 
```
(base) 13:22 ~/workplace/k-NN/jni (stream-vectors-v2)$ ./bin/jni_test 
Running main() from /Users/navneev/workplace/k-NN/jni/googletest-src/googletest/src/gtest_main.cc
[==========] Running 22 tests from 20 test suites.
[----------] Global test environment …
```
=> Move free vectorAddress from Java to JNI layer to reduce the memory footprint for Nmslib.

src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/LuceneEngineIT.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
Rename radial search parameters score and distance to min_score and max_distance
Part of  https://github.com/opensearch-project/k-NN/issues/814
=> Rename radial search parameters score and distance to min_score and max_distance

.github/workflows/CI.yml, jni/include/jni_util.h, jni/patches/faiss/0001-Add-missing-headers-for-gcc.patch
This PR will fix the failing Windows CI on 1.3 by including the following changes:
- Manually installing ZLIB (cherry picked from commit https://github.com/opensearch-project/k-NN/commit/231ad934e6b0f4e62ee0ca68bcb160534262d401)
- Added a git patch for the CI to fix the [header dependency issues due to GCC 13](https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes)
=> Fix Windows CI on 1.3

src/main/java/org/opensearch/knn/common/KNNConstants.java, src/main/java/org/opensearch/knn/index/query/RNNQueryFactory.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
This PR set up Lucene engine traversalSimilarity value to 0.95 * resultSimilarity(min_score) based on benchmark result https://github.com/opensearch-project/k-NN/issues/814#issuecomment-2060195145 
Part of https://github.com/opensearch-project/k-NN/issues/814
=> Use 0.95 as default ratio for lucene radial search traversal similarity

build.gradle, jni/CMakeLists.txt
Creates a new shared non-jni library that the jni libraries can depend on. This is to resolve a build issue on windows that is coming from nmslib not being able to find symbols in the jni common library. The net result will be that we add one more shared library.
In addition, I removed all the CPack code from CMakeLists because we dont use it.
#1610 
#1591 
=> Separate common lib jni and non-jni into 2 libs

CHANGELOG.md, jni/CMakeLists.txt
There is currently a bug when attempting to run k-NN plugin with arm64 and simd disabled, where the `cmake` command fails and integration tests cannot be run.  This PR adds a check similar to the existing aarch64 check that allows the command to complete successfully.
=> Add arm64 check when SIMD is disabled

src/test/java/org/opensearch/knn/index/FaissIT.java
- Increase `nprobes` to 4 for improving the ivf search accuracy which will fix the failing sqfp16 ivf integ test.
```
^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
13 warnings
Apr 19, 2024 2:55:22 AM sun.util.locale.provider.LocaleProviderAdapter <clinit>
WARNING: COMPAT locale provider will be removed in a future release
REPRODUCE WITH: ./gradlew ':integTest' --tests "org.opensearch.knn.index.FaissIT.testIVFSQFP16_whenIndexedAndQueried_thenSucceed" -Dtests.seed=704AA6389C8616FD -Dtests.security.manager=false -Dtests.locale=ca -Dtests.timezone=Africa/Harare -Druntime.java=21
Suite: Test class …
```
=> Fix flaky faiss integration tests

scripts/build.sh
Update gcc restrictions to version 12.0.0
https://github.com/opensearch-project/opensearch-build/issues/4379#issuecomment-2067191682
=> Update gcc restrictions to version 12.0.0

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNVectorScriptDocValues.java, src/main/java/org/opensearch/knn/index/VectorDataType.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java, src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java, src/test/java/org/opensearch/knn/index/AdvancedFilteringUseCasesIT.java, src/test/java/org/opensearch/knn/index/KNNMapperSearcherIT.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Fixes bug where we were not creating stored field type for knn_vector even when the mapping parameter is passed. To do this, we create a stored field from the bytes of the vectors. Then, implemented `valueForDisplay` in order to ensure that the vectors are displayed properly.
Example:
```
Request:
{
"stored_fields": ["test_vector"],
"query": {
"match_all": {}
}
}
Response:
{
"took":248,
"timed_out":false,
"_shards":{
"total":1,
"successful":1,
"skipped":0,
"failed":0
},
"hits":{
"total":{
"value":1,
"relation":"eq"
},
"max_score":1.0,
"hits":[
{
"_index":"test_index",
"_id":"1",
"_score":1.0,
"fields":{"test_vector":[[-128,0,1,127]]}
}
]
}
}
```
Along with this, clean up the field mapper implementations.
Add relevant uTs and iTs to ensure functionality is working as expected.
#1606 
By …
=> Add stored fields for knn_vector type

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNVectorScriptDocValues.java, src/main/java/org/opensearch/knn/index/VectorDataType.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java, src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java, src/test/java/org/opensearch/knn/index/AdvancedFilteringUseCasesIT.java, src/test/java/org/opensearch/knn/index/KNNMapperSearcherIT.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
(Backport #1630 to 2.x)
Fixes bug where we were not creating stored field type for knn_vector even when the mapping parameter is passed. Along with this, clean up the field mapper implementations.
Add relevant uTs and iTs to ensure functionality is working as expected.
(cherry picked from commit 699510d61dd8c583653118be172fb60a00463760)
=> [Backport 2.x] Add stored fields for knn_vector type (#1630)

.github/workflows/CI.yml, .github/workflows/backwards_compatibility_tests_workflow.yml, .github/workflows/test_security.yml, .gitignore, CHANGELOG.md, jni/CMakeLists.txt, jni/cmake/init-faiss.cmake, jni/cmake/init-nmslib.cmake, jni/cmake/macros.cmake
By commiting the patch changes (via `git am` instead of `git apply`), this commit prevents the libraries to be built from scratch every time cmake is ran. This will save additional build time.
from cmake, this looks like:
```
-- Applying custom patches.
Applying: Add IDGrouper for HNSW
Using index info to reconstruct a base tree...
M	faiss/CMakeLists.txt
M	faiss/Index.h
M	faiss/IndexHNSW.cpp
M	faiss/IndexIDMap.cpp
M	faiss/IndexIDMap.h
M	faiss/impl/HNSW.cpp
M	faiss/impl/ResultHandler.h
M	tests/CMakeLists.txt
Falling back to patching base and 3-way merge...
Auto-merging tests/CMakeLists.txt
Auto-merging faiss/impl/HNSW.cpp
Auto-merging faiss/IndexIDMap.cpp
Auto-merging faiss/Index.h
No changes -- Patch already applied.
Applying: Enable precomp table to be shared ivfpq
Using index info to …
```
=> Skip rebuild from scratch after cmake is ran

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNVectorScriptDocValues.java, src/main/java/org/opensearch/knn/index/VectorDataType.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java, src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java, src/test/java/org/opensearch/knn/index/AdvancedFilteringUseCasesIT.java, src/test/java/org/opensearch/knn/index/KNNMapperSearcherIT.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
backport #1630 to 2.13. Fix stored fields bug
=> [Backport 2.13] Add stored fields for knn_vector type

CHANGELOG.md, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
Changes the check for ignore_unmapped to compare against currentFieldName so ignore_unmapped is not always set to true.
https://github.com/opensearch-project/k-NN/issues/1629
=> Ensure ignore_unmapped is set to correct value

DEVELOPER_GUIDE.md
All gradle commands require `-PcustomDistributionUrl` on Mac M series machines. The updates reflect this to avoid confusion on initial setup on Mac
- Adds clarifications for developing on Mac M series
- Minor misc updates
Does not have any issues associated with it
=> Updates Developer guide

CHANGELOG.md, jni/CMakeLists.txt, jni/cmake/init-faiss.cmake, jni/include/faiss_wrapper.h, jni/include/org_opensearch_knn_jni_FaissService.h, jni/patches/faiss/0003-Custom-patch-to-support-range-search-params.patch, jni/src/faiss_wrapper.cpp, jni/src/org_opensearch_knn_jni_FaissService.cpp, jni/tests/faiss_wrapper_test.cpp, src/main/java/org/opensearch/knn/common/KNNConstants.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/main/java/org/opensearch/knn/jni/FaissService.java, src/main/java/org/opensearch/knn/jni/JNIService.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/LuceneEngineIT.java, src/test/java/org/opensearch/knn/index/NestedSearchIT.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
This PR will allow user to use filter and nested field in faiss engine radial search by reusing existing logics from top-k search. 
* The custom patch for range_search is reused from [faiss search patch](https://github.com/opensearch-project/k-NN/blame/main/jni/patches/faiss/0001-Custom-patch-to-support-multi-vector.patch#L136-L158). Please check [this](https://github.com/junqiu-lei/faiss/commit/b36a28778a493df46a7f40b03cc5b426e94a4ba1) commit for the patch updated code in faiss.
* In jni faiss_wrapper.cpp, the params set up process is reused from existing search function.
* IT tests added for both nested field and filter queries.
Part of #814  
For more information on …
=> Support filter and nested field in faiss engine radial search

CHANGELOG.md, jni/CMakeLists.txt, jni/cmake/init-faiss.cmake, jni/include/faiss_wrapper.h, jni/include/org_opensearch_knn_jni_FaissService.h, jni/patches/faiss/0003-Custom-patch-to-support-range-search-params.patch, jni/src/faiss_wrapper.cpp, jni/src/org_opensearch_knn_jni_FaissService.cpp, jni/tests/faiss_wrapper_test.cpp, src/main/java/org/opensearch/knn/common/KNNConstants.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/main/java/org/opensearch/knn/index/query/RNNQueryFactory.java, src/main/java/org/opensearch/knn/jni/FaissService.java, src/main/java/org/opensearch/knn/jni/JNIService.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/LuceneEngineIT.java, src/test/java/org/opensearch/knn/index/NestedSearchIT.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
Backport #1652 and #1619 to 2.x branch.
=> [backport 2.x] Support filter and nested field in faiss engine radial search (#1652) and use default traversal ratio for lucene (#1619) 

CHANGELOG.md, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java, src/main/java/org/opensearch/knn/plugin/KNNPlugin.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtil.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtilTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScriptScoringIT.java
Previously, an exception would be thrown when attempting to use script score with a model-based index.  Since the expected dimensions for a model-based index field are set to -1, there would be a mismatch between the actual dimension of the float array and the expected dimension.  This PR retrieves the expected dimensions from the model metadata for model-based indices, thus enabling script score to work as intended.
https://github.com/opensearch-project/k-NN/issues/1554
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of …
=> Enable script score to work with model based indices

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNVectorDVLeafFieldData.java, src/main/java/org/opensearch/knn/index/KNNVectorScriptDocValues.java, src/test/java/org/opensearch/knn/index/KNNVectorScriptDocValuesTests.java, src/test/java/org/opensearch/knn/index/VectorDataTypeTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringUtilTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScriptScoringIT.java, src/test/java/org/opensearch/knn/plugin/script/PainlessScriptIT.java
Reverts https://github.com/opensearch-project/k-NN/pull/1573 due to a bug causing cluster crashes: https://github.com/opensearch-project/k-NN/issues/1647
=> Revert 'Support script score when doc value is disabled'

jni/cmake/init-faiss.cmake
This fixes a bug where we set BLA_STATIC after we find the package, leading OpenBlas to be dynamically linked instead of statically linked. In 2.13 it was the other way around: https://github.com/opensearch-project/k-NN/blob/2.13/jni/CMakeLists.txt#L126-L157
Bug was introduced in https://github.com/opensearch-project/k-NN/pull/1636
Related https://github.com/opensearch-project/opensearch-build/issues/4379#issuecomment-2083623882. This may resolve the issue with binutils because we are statically linking.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRI …
=> Ensure blas is statically linked

scripts/build.sh
Ensure gcc is newer >= 11.2.1 < 12.0.0 when building knn lib
https://github.com/opensearch-project/opensearch-build/issues/4379#issuecomment-2083623882
https://github.com/opensearch-project/opensearch-build/issues/4379#issuecomment-2084133839
=> Ensure gcc is newer >= 11.2.1 < 12.0.0 when building knn lib

scripts/build.sh
Revert #1634 #1664 to switch back to CentOS7
https://github.com/opensearch-project/opensearch-build/issues/4379
=> Revert #1634 #1664 to switch back to CentOS7

.github/CODEOWNERS, MAINTAINERS.md
Add Yuncheng Lu as maintainer to k-NN repository
=> Add Yuncheng Lu as maintainer

.github/workflows/CI.yml
Fix build CI failure for MacOS. The github CI runner for `macos-latest` changed to use ARM platform recently, updating to use `macos-12` with x86_64 architecture to pass the CI.
#1660
=> Fix build CI failure on MacOS

CHANGELOG.md, src/main/java/org/opensearch/knn/indices/ModelMetadata.java, src/main/java/org/opensearch/knn/indices/ModelUtil.java, src/main/java/org/opensearch/knn/plugin/rest/RestTrainModelHandler.java, src/test/java/org/opensearch/knn/indices/ModelMetadataTests.java, src/test/java/org/opensearch/knn/plugin/action/RestTrainModelHandlerIT.java
When commas are present in the model description, the model metadata is not parsed correctly, resulting in an exception being thrown when ingesting data to or searching on a model-based index.  This PR throws an IllegalArgumentException if the user attempts to create a model with a comma in the model description.
https://github.com/opensearch-project/k-NN/issues/1337
https://github.com/opensearch-project/k-NN/issues/1479
=> Block commas in model description

CHANGELOG.md, src/main/java/org/opensearch/knn/indices/ModelMetadata.java, src/main/java/org/opensearch/knn/indices/ModelUtil.java, src/main/java/org/opensearch/knn/plugin/rest/RestTrainModelHandler.java, src/test/java/org/opensearch/knn/indices/ModelMetadataTests.java, src/test/java/org/opensearch/knn/plugin/action/RestTrainModelHandlerIT.java
Backport of https://github.com/opensearch-project/k-NN/pull/1692
=> [Backport 2.x] Block commas in model description

jni/tests/faiss_wrapper_test.cpp
Due to random test dataset with vector range of -500 to 500 with 2 dimensions, it could potentially cause 0 hit if radius value isn't set high enough in JNI layer FAISS wrapper tests.
This PR is reducing the test random vector to -50 to 50 and using radius of 20,000, which can cover the potentially longest L2^2 radius calculated by (50 - (-50))^2 + (50 - (-50))^2 = 20,000.
Credit to @shatejas for finding this flaky test.
=> Fix flaky test in FAISS JNI range search

.github/CODEOWNERS, MAINTAINERS.md
Add Yuncheng Lu as maintainer to k-NN repository
(cherry picked from commit ef962ecace122af12cad6b0554a9b09c2d8a58dd)
=> Add luyuncheng as maintainer (#1628)

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNVectorDVLeafFieldData.java, src/main/java/org/opensearch/knn/index/KNNVectorScriptDocValues.java, src/test/java/org/opensearch/knn/index/KNNVectorScriptDocValuesTests.java, src/test/java/org/opensearch/knn/index/VectorDataTypeTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringUtilTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScriptScoringIT.java, src/test/java/org/opensearch/knn/plugin/script/PainlessScriptIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
The function was initially introduced in #1573, but was later reverted due to #1647. The root cause of the issue can be found in [this comment](https://github.com/opensearch-project/k-NN/issues/1647#issuecomment-2084495122). This PR reintroduces the function and fixes misusing DISI.
=> Support script score when doc value is disabled and fix misusing DISI

CHANGELOG.md, jni/patches/faiss/0001-Custom-patch-to-support-multi-vector.patch, src/test/java/org/opensearch/knn/index/NestedSearchIT.java
Update threshold value after new result is added
Because the threshold is not updated after inserting a new value to the result list, new value got inserted in the result regardless of its size.
https://github.com/opensearch-project/k-NN/issues/1714
=> Update threshold value after new result is added

.github/workflows/backwards_compatibility_tests_workflow.yml
Updating the BWC test config after 2.14 release.
This will ensure that BWC tests start to succeed when a PR is raised on the main branch
NA
=> Updating the BWC test config after 2.14 release

src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
Refractor createParseField function in mappers for code reusability. 
I added 2 functions for creating all the indexable fields required for floats and then same for byte vector too. These functions can be overriden by the individual mappers if needed. Lucene Fields Mapper overrides them
https://github.com/opensearch-project/k-NN/issues/1632
=> Refactor createParseField function in mappers for code reusability

.github/workflows/backwards_compatibility_tests_workflow.yml, CHANGELOG.md, benchmarks/perf-tool/requirements.txt, jni/patches/faiss/0001-Custom-patch-to-support-multi-vector.patch, jni/tests/faiss_wrapper_test.cpp, src/main/java/org/opensearch/knn/index/KNNMethod.java, src/main/java/org/opensearch/knn/index/KNNMethodContext.java, src/main/java/org/opensearch/knn/index/KNNVectorDVLeafFieldData.java, src/main/java/org/opensearch/knn/index/KNNVectorScriptDocValues.java, src/main/java/org/opensearch/knn/index/MethodComponent.java, src/main/java/org/opensearch/knn/index/Parameter.java, src/main/java/org/opensearch/knn/index/util/AbstractKNNLibrary.java, src/main/java/org/opensearch/knn/index/util/Faiss.java, src/main/java/org/opensearch/knn/index/util/KNNEngine.java, src/main/java/org/opensearch/knn/index/util/KNNLibrary.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringUtil.java, src/main/java/org/opensearch/knn/plugin/transport/TrainingModelRequest.java, src/main/java/org/opensearch/knn/training/VectorSpaceInfo.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/KNNMethodTests.java, src/test/java/org/opensearch/knn/index/KNNVectorScriptDocValuesTests.java, src/test/java/org/opensearch/knn/index/NestedSearchIT.java, src/test/java/org/opensearch/knn/index/ParameterTests.java, src/test/java/org/opensearch/knn/index/VectorDataTypeTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringUtilTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScriptScoringIT.java, src/test/java/org/opensearch/knn/plugin/script/PainlessScriptIT.java, src/test/java/org/opensearch/knn/plugin/stats/suppliers/LibraryInitializedSupplierTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Merging main to feature branch
=> Updating feature branch with latest changes on main

CHANGELOG.md, DEVELOPER_GUIDE.md
The current `DEVELOPER_GUIDE.md` M-series instructions did not work for me or @MrFlap. These updated instructions use gcc/g++ instead of clang to build and link the external kNN libraries. The project builds for me (m3 chip) and Andrew (m2 chip). 
Resolves linking issues with m-series macbook chips when building kNN locally. 
=> Update dev guide to fix clang linking issue on arm

jni/CMakeLists.txt, jni/cmake/init-nmslib.cmake, jni/include/commons.h, jni/include/nmslib_wrapper.h, jni/include/org_opensearch_knn_jni_NmslibService.h, jni/patches/nmslib/0002-Adds-ability-to-pass-ef-parameter-in-the-query-for-h.patch, jni/src/commons.cpp, jni/src/faiss_wrapper.cpp, jni/src/nmslib_wrapper.cpp, jni/src/org_opensearch_knn_jni_NmslibService.cpp, jni/tests/commons_test.cpp, jni/tests/nmslib_wrapper_test.cpp, jni/tests/nmslib_wrapper_unit_test.cpp, src/main/java/org/opensearch/knn/index/util/Nmslib.java, src/main/java/org/opensearch/knn/jni/JNIService.java, src/main/java/org/opensearch/knn/jni/NmslibService.java, src/test/java/org/opensearch/knn/index/NmslibIT.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
Integrates NMSLIB with ef_search
```
curl -XGET "http://localhost:9200/nmslib-hnsw-index/_search" -H 'Content-Type: application/json' -d'
{
"query": {
"knn": {
"nmslib_vector": {
"vector": [2, 3, 5],
"k": 2,
"method_parameters" : {
"ef_search" : 200
}
}
}
}
}'
```
```
{
"took": 6,
"_shards": {
"total": 1,
"successful": 1,
"skipped": 0,
"failed": 0
},
"hits": {
"total": {
"value": 2,
"relation": "eq"
},
"max_score": 0.11918951,
"hits": [
{
"_index": "nmslib-hnsw-index",
"_id": "3",
"_score": 0.11918951,
"_source": {
"nmslib_vector": [
3.5,
4.5,
3.3
],
"price": 12.9
}
},
{
"_index": "nmslib-hnsw-index",
"_id": "2",
"_score": 0.10706638,
"_source": {
"nmslib_vector": [
2.5,
3.5,
2.2
],
"price": 7.1
}
}
]
}
}
```
https://github.com/opensearch-project/k-NN/issues/1537
By …
=> Introduces query parameter ef_search for NMSLIB

src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java, src/main/java/org/opensearch/knn/index/query/parser/MethodParametersParser.java, src/main/java/org/opensearch/knn/index/util/Lucene.java, src/test/java/org/opensearch/knn/index/LuceneEngineIT.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java, src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Lucene queries use `k` as `efsearch`. So we take the max of two to pass is the right `k` value to Lucene. The `size` parameter will dictate the number of the hits
```
curl -XGET "http://localhost:9200/lucene-hnsw-index/_search" -H 'Content-Type: application/json' -d'
{
"size": 1,
"query": {
"knn": {
"lucene_vector": {
"vector": [2.5, 3.5, 2.2],
"k": 3,
"method_parameters": {
"ef_search": 5
}
}
}
}
}'
```
```
{
"took": 4,
"_shards": {
"total": 1,
"successful": 1,
"skipped": 0,
"failed": 0
},
"hits": {
"total": {
"value": 4,
"relation": "eq"
},
"max_score": 1,
"hits": [
{
"_index": "lucene-hnsw-index",
"_id": "2",
"_score": 1,
"_source": {
"lucene_vector": [
2.5,
3.5,
2.2
],
"price": 7.1
}
}
]
}
}
```
[#1537](https://github.com/opensearch-project/k-NN/issues/1537)
By …
=> Adds ef_search support for Lucene kNN queries

jni/include/faiss_wrapper.h, jni/include/org_opensearch_knn_jni_FaissService.h, jni/src/faiss_wrapper.cpp, jni/src/org_opensearch_knn_jni_FaissService.cpp, jni/tests/faiss_wrapper_test.cpp, jni/tests/faiss_wrapper_unit_test.cpp, src/main/java/org/opensearch/knn/index/query/KNNQuery.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/main/java/org/opensearch/knn/index/query/RNNQueryFactory.java, src/main/java/org/opensearch/knn/jni/FaissService.java, src/main/java/org/opensearch/knn/jni/JNIService.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java, src/test/java/org/opensearch/knn/index/query/RNNQueryFactoryTests.java
This PR is adding the ability for Faiss engine to support radial search with `ef_search` parameter in query request.
```
GET /target-index-faiss/_search HTTP/1.1
Host: localhost:9200
Content-Type: application/json
Content-Length: 198
{
"query": {
"knn": {
"my_vector1": {
"vector": [5.5, 8.5],
"min_score": 0.3,
"method_parameters": {
"ef_search" : 10000
}
}
}
}
}
```
Part of https://github.com/opensearch-project/k-NN/issues/1537 
=> Support ef_search parameter in radial search Faiss engine

src/main/java/org/opensearch/knn/plugin/transport/UpdateModelGraveyardTransportAction.java, src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java, src/test/java/org/opensearch/knn/indices/ModelDaoTests.java, src/test/java/org/opensearch/knn/plugin/transport/UpdateModelGraveyardTransportActionTests.java
Optimizes the logic and testing for blocking model deletion when it is in use by an index.
This PR contains minor changes, no new functionality added
=> Optimize logic and tests for blocking model deletion when in use

src/main/java/org/opensearch/knn/index/VectorQueryType.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/index/util/DefaultHnswContext.java, src/main/java/org/opensearch/knn/index/util/EngineSpecificMethodContext.java, src/main/java/org/opensearch/knn/index/util/Lucene.java, src/main/java/org/opensearch/knn/index/util/LuceneHNSWContext.java, src/main/java/org/opensearch/knn/index/util/QueryContext.java, src/main/java/org/opensearch/knn/validation/ParameterValidator.java, src/test/java/org/opensearch/knn/index/LuceneEngineIT.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java, src/test/java/org/opensearch/knn/index/util/AbstractKNNLibraryTests.java
Add IllegalArgumentException for Lucene radial search with ef_search parameter. Context at https://github.com/opensearch-project/k-NN/issues/1537#issuecomment-2168724430
Part of https://github.com/opensearch-project/k-NN/issues/1537
=> Add IllegalArgumentException for Lucene radial search with ef_search

jni/tests/faiss_wrapper_test.cpp
Fix memory leak on test code
https://github.com/opensearch-project/k-NN/issues/1772
```
==30963== HEAP SUMMARY:
==30963==     in use at exit: 394,772 bytes in 41 blocks
==30963==   total heap usage: 589,824 allocs, 589,783 frees, 983,712,368 bytes allocated
==30963== 
==30963== 72 bytes in 1 blocks are definitely lost in loss record 8 of 33
==30963==    at 0x48657B8: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-arm64-linux.so) …
```
=> Fix memory leak on test code

src/main/java/org/opensearch/knn/index/util/DefaultIVFContext.java, src/test/java/org/opensearch/knn/index/query/InvalidSearchQueryIT.java, src/test/java/org/opensearch/knn/index/query/parser/MethodParametersParserTests.java
Adds invalid parameter integration test
=> Adds integration test for invalid method parameters

CHANGELOG.md, jni/include/faiss_wrapper.h, jni/include/org_opensearch_knn_jni_FaissService.h, jni/src/faiss_wrapper.cpp, jni/src/org_opensearch_knn_jni_FaissService.cpp, jni/tests/faiss_wrapper_test.cpp, jni/tests/faiss_wrapper_unit_test.cpp, src/main/java/org/opensearch/knn/index/VectorQueryType.java, src/main/java/org/opensearch/knn/index/query/KNNQuery.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/main/java/org/opensearch/knn/index/query/RNNQueryFactory.java, src/main/java/org/opensearch/knn/index/util/EngineSpecificMethodContext.java, src/main/java/org/opensearch/knn/index/util/Lucene.java, src/main/java/org/opensearch/knn/index/util/LuceneHNSWContext.java, src/main/java/org/opensearch/knn/index/util/QueryContext.java, src/main/java/org/opensearch/knn/jni/FaissService.java, src/main/java/org/opensearch/knn/jni/JNIService.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/LuceneEngineIT.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java, src/test/java/org/opensearch/knn/index/query/RNNQueryFactoryTests.java, src/test/java/org/opensearch/knn/index/util/AbstractKNNLibraryTests.java
Manually backport https://github.com/opensearch-project/k-NN/pull/1790 to 2.x branch, cherry picked from commit e7d7ec81ec223ed4f54d5f9e8eeff1e776e8662e
=> [backport 2.x] Support ef_search parameter in radial search faiss engine (#1790)

.github/workflows/CI.yml, .github/workflows/test_security.yml
Build CI recently occurred one error, this is due to github action runner env upgrade node 20 https://github.blog/changelog/2024-05-17-updated-dates-for-actions-runner-using-node20-instead-of-node16-by-default/
```
/__e/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
``` 
Example: https://github.com/opensearch-project/k-NN/actions/runs/9811145501/job/27093445183 …
=> Fix linux build CI error due to action runner env upgrade node 20

CHANGELOG.md, src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java
Fixing the arithmetic to find the number of vectors to stream from java to jni layer.
NA
=> Fixing the arithmetic to find the number of vectors to stream from java to jni layer.

src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
Setting locale to Locale.ROOT while using String.format to ensure that UTs doesn't fail when validating the exception messages.
So the idea here is whenever we use String.format we should ensure that we are using the Locale.ROOT to set the locale of the string, otherwise if you are validating the exception messages then the string comparison can fail and lead to flaky tests.
To reproduce the issue run the below command on the main branch of K-NN plugin.
```
./gradlew ':test' --tests "org.opensearch.knn.index.query.KNNQueryBuilderInvalidParamsTests" -Dtests.seed=EF1B1919EE6D650B  -Dtests.locale=ar-IQ -Dtests.timezone=America/Managua
```
NA …
=> Setting locale to Locale.ROOT while using String.format to ensure that UTs doesn't fail when validating the exception messages

src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
Setting locale to Locale.ROOT while using String.format to ensure that UTs doesn't fail when validating the exception messages (#1812)
Backport of PR: https://github.com/opensearch-project/k-NN/pull/1812
NA
=> [Backport 2.x] Setting locale to Locale.ROOT while using String.format to ensure that UTs doesn't fail when validating the exception messages (#1812)

CHANGELOG.md, DEVELOPER_GUIDE.md, jni/CMakeLists.txt, jni/patches/faiss/0001-Custom-patch-to-support-multi-vector.patch, jni/patches/faiss/0002-Enable-precomp-table-to-be-shared-ivfpq.patch
- Bump faiss submodule commit to [33c0ba5](https://github.com/facebookresearch/faiss/commit/33c0ba5d002a7cd9761513f06ecc9822079d4a2f) and update patches
- Bump up cmake minimum required version to 3.24.0 to match with Faiss requirements.
https://github.com/opensearch-project/k-NN/issues/1659
=> Bump faiss commit to 33c0ba5

.github/workflows/backwards_compatibility_tests_workflow.yml
Fixing BWC tests as 2.15.0 is already launched
NA
=> Fixing BWC tests as 2.15.0 is already launched

jni/cmake/init-faiss.cmake, jni/patches/faiss/0004-Custom-patch-to-support-binary-vector.patch
Add faiss custom patch to support search parameter in binary index
Please see the patch as plain file at https://github.com/heemin32/faiss/commit/4d374aa47d4415cbda04b299788988f4ff6e5da0
N/A
=> Add faiss custom patch to support search parameter in binary index

jni/tests/faiss_wrapper_unit_test.cpp
Rename MockIndex to FaissMockIndex in faiss_wrapper_unit_test.cpp to avoid interference during unit tests. Also, rename MockIDMap to FaissMockIdMap for consistency. The MockIndex class is defined in tests/mocks/faiss_index_mock.h
N/A
=> Avoid conflict of mock class name to fix test failure

CHANGELOG.md, jni/patches/faiss/0001-Custom-patch-to-support-multi-vector.patch
Release memory properly for an array type.
There is no immediate impact on user.
k-nn plugin is only making single query at a time and hitting the line 453(single query at at time), but not 530 and 531(multi query at a time). Because the heap_group_ids is array of primitive type(int64_t), there is no difference between `delete` and `delete[]` as I believe no one replaced the behavior of `operator delete[](void*)` for int64_t. However, it is recommended to call `delete[]` for a memory allocation of array type because `delete[]` method of an object can be replaced by user to behave differently.
https://isocpp.org/wiki/faq/freestore-mgmt#delete-array-built-ins
N/A
For more …
=> Release memory properly for an array type

CHANGELOG.md, src/main/java/org/opensearch/knn/index/VectorDataType.java, src/main/java/org/opensearch/knn/index/codec/transfer/VectorTransfer.java, src/main/java/org/opensearch/knn/index/codec/transfer/VectorTransferByte.java, src/main/java/org/opensearch/knn/index/codec/transfer/VectorTransferFloat.java, src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java, src/main/java/org/opensearch/knn/index/codec/util/KNNVectorAsArraySerializer.java, src/main/java/org/opensearch/knn/index/codec/util/KNNVectorAsCollectionOfFloatsSerializer.java, src/main/java/org/opensearch/knn/index/codec/util/KNNVectorSerializer.java, src/main/java/org/opensearch/knn/index/codec/util/KNNVectorSerializerFactory.java, src/main/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNIterator.java, src/test/java/org/opensearch/knn/index/codec/transfer/VectorTransferByteTests.java, src/test/java/org/opensearch/knn/index/codec/transfer/VectorTransferFloatTests.java, src/test/java/org/opensearch/knn/index/codec/util/KNNCodecUtilTests.java, src/test/java/org/opensearch/knn/index/codec/util/KNNVectorSerializerTests.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java
Avoids copy during serialization and deserialization by switching from requiring byte streams to only requiring byte refs. From [KNNCodecUtil](https://github.com/opensearch-project/k-NN/blob/2.15.0.0/src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java#L57-L62), we can see that we convert byte ref to byte stream just to convert it back in the [KNNVectorSerializer](https://github.com/opensearch-project/k-NN/blob/2.15.0.0/src/main/java/org/opensearch/knn/index/codec/util/KNNVectorAsCollectionOfFloatsSerializer.java#L29-L39) logic - in other words, it is not necessary. This can speed up operations by 15-20% for exact search (see #1736).
This will not have impact on KnnVectorsFormat structures. Those will use lucenes vector serde which is already optimized. This change is meant …
=> Switch from byte stream to byte ref for serde

CHANGELOG.md, src/main/java/org/opensearch/knn/index/VectorDataType.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtil.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringUtil.java, src/test/java/org/opensearch/knn/index/VectorDataTypeTests.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtilTests.java
Add script scoring support for knn field with binary data type
1. Refactored linear space type(Non hamming) to remove code duplication
2. Blocked linear space type from being called against binary data type
3. Added KNNField with binary data type support for hamming space type
4. There is inefficiency on converting byte to float and back to byte for score script with binary data type which we might want to improve in the future. https://github.com/opensearch-project/k-NN/issues/1827
```
PUT /my-knn-index-1
{
"settings": {
"index": {
"knn": true
}
},
"mappings": {
"my_vector": {
"dimension": 8,
"data_type": "binary",
"method": {
"name": "hnsw",
"engine": "faiss"
}
}
}
}
}
```
```
POST /_bulk?refresh=true
{ "index": { "_index": "my-knn-index-1", "_id": …
```
=> Add script scoring support for knn field with binary data type

.github/workflows/CI.yml, .github/workflows/test_security.yml, CHANGELOG.md, jni/cmake/init-faiss.cmake, jni/cmake/init-nmslib.cmake
As more custom patches are added, it fails to re-apply same patches if more than one patch touch the same file. This lead to consistent build failure whenever we build jni library more than once. The workaround with the failure is removing both git rebase-apply folder and external/faiss folder and build from scratch which is inconvenient and increase development time.
To resolve the issue, changed the cmake file to apply custom patch only once by comparing the patch-id of the last commit.
Also, removed `submodule: true` option in CI as it seems it is not needed anymore after we upgraded linux image for CI build.
N/A
For more information on following Developer Certificate of …
=> Apply custom patch only once by comparing the patch-id of the last commit

CHANGELOG.md, src/main/java/org/opensearch/knn/plugin/script/KNNScoringUtil.java, src/main/resources/org/opensearch/knn/plugin/script/knn_allowlist.txt, src/test/java/org/opensearch/knn/common/KNNValidationUtilTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringUtilTests.java
Add painless script support for hamming with binary vector data type
Changes are
1. Moved all painless script method to the bottom of the class for better readability.
2. Added a validation on all existing painless method to block binary vector
3. Added a painless method for hamming with binary vector
N/A
=> Add painless script support for hamming with binary vector data type

.gitignore, build.gradle, jni/cmake/init-faiss.cmake, jni/cmake/init-nmslib.cmake, scripts/build.sh
This PR is a continuation of https://github.com/opensearch-project/k-NN/pull/1833 to fix build failure when patch is applied more than once. 
The previous PR resolved an issue for manual build where it uses `git am` and the Cmake system skips applying patches by comparing patch id.  However the build script which runs in CI build system still fails because it uses `git apply` which does not commit the patch and we cannot use patch-id to determine if patches are already applied or not.
Therefore introduced a new parameter, `build.lib.apply_patches` to disable patching for the second run of :cmakeJniLib task inside build script.
The alternative is making the build script to use `git am` by setting git user.name and user.email. This approach will provide more control when setting user.name …
=> Fix build failure due to patch conflict

src/main/java/org/opensearch/knn/index/IndexUtil.java, src/main/java/org/opensearch/knn/index/KNNMethod.java, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/LegacyFieldMapper.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/test/java/org/opensearch/knn/index/IndexUtilTests.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
Did a manual test on following items. Will raise a new PR implementing this as integ test.
1. Can create binary index using Faiss HNSW
2. Can create binary index with knn index as false
3. Cannot create binary index using Lucene
4. Cannot create binary index using Nmslib
5. Cannot run training API on binary index
6. Cannot create binary index using encoding(sq)
7. Cannot run range query on binary index
8. Can run knn query on binary index
9. Can run knn query with nested field on binary index
10. Can run knn query with filtering on binary index
11. Can run knn query with filtering on nested field with binary index
12. Can run script scoring with hamming on binary index
13. Cannot run script scoring with hamming on non binary index
14. Cannot run script scoring with non hamming on binary …
=> Fix few bugs on binary index with Faiss HNSW

jni/include/jni_util.h, jni/src/faiss_wrapper.cpp, jni/src/jni_util.cpp, jni/tests/faiss_wrapper_test.cpp, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/SpaceType.java, src/main/java/org/opensearch/knn/index/util/Faiss.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpaceFactory.java, src/test/java/org/opensearch/knn/index/SpaceTypeTests.java, src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/index/mapper/MethodFieldMapperTests.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryAllocationTests.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategyTests.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java, src/test/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNByteIteratorTests.java, src/test/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNByteIteratorTests.java, src/test/java/org/opensearch/knn/jni/JNIServiceTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceFactoryTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScriptScoringIT.java
Switch space type name from hammingbit to hamming for binary index
Note that hammingbit in script scoring for long and base64 exist before 2.16.
Before this PR the hamming space type name looks like
```
ANN: hammingbit
Script Scoring: hammingbit(long, base64, knn binary field)
Painless: hamming
```
After this PR the hamming space type will look like
```
ANN: hamming
Script Scoring: hammingbit(long, base64), hamming(knn binary field)
Painless: hamming
```
N/A
=> Switch space type name from hammingbit to hamming for binary index

src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriter.java, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormat.java, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReader.java, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/UnitTestCodec.java, src/main/resources/META-INF/services/org.apache.lucene.codecs.Codec, src/main/resources/META-INF/services/org.apache.lucene.codecs.KnnVectorsFormat, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriterTests.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormatTests.java
Introduced NativeEngineKNNVectorsFormat as a KNNVectorsFormat for Native engines(faiss and nmslib). This PR doesn't change any code path or do the integration of the new format in the actual flow. This is more of a base work I am adding for next step of changes which are coming. 
**Changes include:**
1. Introduce the NativeEngineKNNVectorsFormat, readers and writers.
2. Added the unit test for this new format.
3. Currently the format is only writing the FlatVectors and not building the hnsw vector files. I will add this change in next few PRs.
4. Not adding the backport label on this PR. I will add the backport label once 2.16 is released, as this change is not intended for 2.16 version of Opensearch.
https://github.com/opensearch-project/k-NN/issues/1853
By submitting this pull request, …
=> Introduce NativeEngineKNNVectorsFormat as a KNNVectorsFormat for Native engines

CHANGELOG.md, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/LuceneEngineIT.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
Changing behavior of the k-NN query with filters. Changes related to following areas:
- false negative scenario when query return an error instead of legit results
- more user friendly response in case filter has only one clause with non-existent field, return 0 total hits instead of 400 error
Today in scenario when filter refers to filed that does not exist query return 400 error and exception in the response body. 
```
{
"error": {
"root_cause": [
{
"type": "query_shard_exception",
"reason": "failed to create query: Rewrite first",
"index": "test-index-knn1",
"index_uuid": "E5XiPqWQTuiQBsKTz2bEqw"
}
],
"type": "search_phase_execution_exception",
"reason": "all shards failed",
"phase": "query",
"grouped": true,
"failed_shards": [
{
"shard": 0,
"index": "test-index-knn1",
"node": …
```
=> Corrected search logic for scenario with non-existent fields in filter

CHANGELOG.md, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/LuceneEngineIT.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
Backport 43b072745d5b08d10d135b693645c2343a3a605f from https://github.com/opensearch-project/k-NN/pull/1874
=> [Backport 2.x] Corrected search logic for scenario with non-existent fields in filter (#1874)

src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
Per https://github.com/opensearch-project/OpenSearch/pull/9392, mmap will be a default setting for all lucene segment files in 3.0
Resolves #1892
=> Remove additionalSettings in KNN plugin

.idea/copyright/SPDX_ALv2.xml, src/main/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParser.java, src/test/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParserTests.java
Fixes file so it gives 
```
/*
* Copyright OpenSearch Contributors
* SPDX-License-Identifier: Apache-2.0
*/
```
instead of 
```
/*
* Copyright OpenSearch Contributors
* SPDX-License-Identifier: Apache-2.0
* 
*/
Related #1824 
=> Fix idea xml file

TRIAGING.md
Adds a triaging markdown file for a new triage meeting we are proposing for k-NN and neural search bi-weekly (please help check if I missed any copy/paste errors).
See security for details: https://github.com/opensearch-project/security/blob/main/TRIAGING.md
Highlights:
- Hosted by Amazon Chime
- 5 pm PST bi-weekly on Tuesdays
- scope: neural-search and k-NN - reason for combining is because there is a lot of maintainer overlap
Feedback is welcome. Whatever process decided upon is not set in stone forever and can be adjusted as we go. 
Will open up a similar PR in neural-search …
=> Add triage.md based off of security

.github/workflows/CI.yml, .github/workflows/backwards_compatibility_tests_workflow.yml, .github/workflows/test_security.yml
Minor change that will make it so CI is not run if we are not touching a file that is involved in CI. This should make it easier to create and merge PRs not involving source code. 
Docs on GHA paths: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore.
=> Limit tests run based on changed path

CHANGELOG.md, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriter.java, src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java, src/main/java/org/opensearch/knn/index/vectorvalues/KNNBinaryVectorValues.java, src/main/java/org/opensearch/knn/index/vectorvalues/KNNByteVectorValues.java, src/main/java/org/opensearch/knn/index/vectorvalues/KNNFloatVectorValues.java, src/main/java/org/opensearch/knn/index/vectorvalues/KNNVectorValues.java, src/main/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesFactory.java, src/main/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesIterator.java, src/main/java/org/opensearch/knn/index/vectorvalues/VectorValueExtractorStrategy.java, src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80BinaryDocValuesTests.java, src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriterTests.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java, src/test/java/org/opensearch/knn/index/codec/util/BinaryDocValuesSubTests.java, src/test/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesFactoryTests.java, src/test/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesTests.java, src/test/java/org/opensearch/knn/index/vectorvalues/TestVectorValues.java, src/test/java/org/opensearch/knn/index/vectorvalues/VectorValueExtractorStrategyTests.java
Added KNNVectorValues interface to iterate on different types of Vector values during indexing and search.
After adding this interface, the other parts of plugin code can reuse this new VectorValues to get and instance for iterating over the vector.
I also went ahead and put all code related to VectorValues generation for test in 1 class. This will help any UT code to get any type of Vector Values very easily.
1. Added the interface for iterating over the docIds for KNNVectorValues
2. Added the interface to retrieve the vectors and other information from KNNVectorValues.
3. Added the strategies to extract the vector from iterators.
4. Added relevant unit test for the code. For all these interfaces I tried to keep UTs less and use the VectorValues to do all the UTs. This will keep the UTs …
=> Introduce KNNVectorValues interface to iterate on different types of Vector values during indexing and search

CHANGELOG.md, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriter.java, src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java, src/main/java/org/opensearch/knn/index/vectorvalues/KNNBinaryVectorValues.java, src/main/java/org/opensearch/knn/index/vectorvalues/KNNByteVectorValues.java, src/main/java/org/opensearch/knn/index/vectorvalues/KNNFloatVectorValues.java, src/main/java/org/opensearch/knn/index/vectorvalues/KNNVectorValues.java, src/main/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesFactory.java, src/main/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesIterator.java, src/main/java/org/opensearch/knn/index/vectorvalues/VectorValueExtractorStrategy.java, src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80BinaryDocValuesTests.java, src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriterTests.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java, src/test/java/org/opensearch/knn/index/codec/util/BinaryDocValuesSubTests.java, src/test/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesFactoryTests.java, src/test/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesTests.java, src/test/java/org/opensearch/knn/index/vectorvalues/TestVectorValues.java, src/test/java/org/opensearch/knn/index/vectorvalues/VectorValueExtractorStrategyTests.java
Introduced KNNVectorValues interface to iterate on different types of Vector values during indexing and search 
Main branch PR: (#1897)
=> [Backport 2.x] Introduced KNNVectorValues interface to iterate on different types of Vector values during indexing and search (#1897)

.github/workflows/CI.yml, .github/workflows/backwards_compatibility_tests_workflow.yml, .github/workflows/maven-publish.yml, CHANGELOG.md
Removed JDK 11 and 17 version from CI runs as main branch is moved to higher versions of JDK. I didn't make changes in the target and source compatibility because there is some other issues I am seeing for micro-benchmarks module. Will try to resolve it and then raise another PR for the same.
Ref: https://github.com/opensearch-project/k-NN/issues/1729
=> Removed JDK 11 and 17 version from CI runs

CHANGELOG.md, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
Fix a flaky unit test:testMultiFieldsKnnIndex, which was failing due to inconsistent merge behaviors
```
./gradlew ':test' --tests "org.opensearch.knn.index.codec.KNN990Codec.KNN990CodecTests.testMultiFieldsKnnIndex" -Dtests.seed=F72B6D8EB481B0BB
```
The log shows that refresh and merges happening multiple times, resulting in 4 files, 2 from old segments and 2 files from new merged segment.
```
2> INFO: Using MemorySegmentIndexInput and native madvise support with Java 21 or later; to disable start with -Dorg.apache.lucene.store.MMapDirectory.enableMemorySegments=false
1> [2024-08-02T03:53:40,805][WARN ][o.o.k.i.c.K.KNN80DocValuesConsumer] [testMultiFieldsKnnIndex] Refresh operation complete in 60 ms
1> [2024-08-02T03:53:40,926][WARN ][o.o.k.i.c.K.KNN80DocValuesConsumer] …
```
=> Fix a flaky unit test:testMultiFieldsKnnIndex, which was failing due to inconsistent merge behaviors

CHANGELOG.md, src/main/java/org/opensearch/knn/plugin/script/KNNAllowlistExtension.java, src/test/java/org/opensearch/knn/integ/PainlessScriptFieldsIT.java, src/test/java/org/opensearch/knn/integ/PainlessScriptHelper.java, src/test/java/org/opensearch/knn/integ/PainlessScriptIT.java, src/test/java/org/opensearch/knn/integ/PainlessScriptScoreIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Include script_fields context to existing supported context for knn methods like script_score. script_fields can be used to retrieve painless scripting evaluation.
#1878 
=> Add script_fields context  to KNNAllowlist

CHANGELOG.md, src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldType.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtil.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java, src/test/java/org/opensearch/knn/index/mapper/MethodFieldMapperTests.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java, src/test/java/org/opensearch/knn/integ/KNNScriptScoringIT.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceFactoryTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtilTests.java
Refactor KNNVectorFieldType from KNNVectorFieldMapper to a separate class for better readability. This change doesn't change any functionality, it's just Mapper class was becoming too big and refactoring this class out helps reducing the size of the file and things to look at once.
NA
=> Refactor KNNVectorFieldType from KNNVectorFieldMapper to a separate class for better readability.

CHANGELOG.md, src/main/java/org/opensearch/knn/common/featureflags/KNNFeatureFlags.java, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java, src/main/java/org/opensearch/knn/index/query/KNNScorer.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/main/java/org/opensearch/knn/index/query/nativelib/DocAndScoreQuery.java, src/main/java/org/opensearch/knn/index/query/nativelib/NativeEngineKnnVectorQuery.java, src/test/java/org/opensearch/knn/common/featureflags/KNNFeatureFlagsTests.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java, src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java, src/test/java/org/opensearch/knn/index/query/nativelib/DocAndScoreQueryTests.java, src/test/java/org/opensearch/knn/index/query/nativelib/NativeEngineKNNVectorQueryIT.java, src/test/java/org/opensearch/knn/index/query/nativelib/NativeEngineKNNVectorQueryTests.java
All integration tests are passing. Cannot support radial currently since k is not significant, there are ways to do it but since its not planned for 2.17 this should work
Resolves #[1845](https://github.com/opensearch-project/k-NN/issues/1845)
=> Introduces NativeEngineKNNQuery which executes ANN on rewrite

CHANGELOG.md, jni/include/faiss_index_service.h, jni/src/faiss_index_service.cpp
Previously, the iterative index insertion feature only allocated memory for HNSW indices. New functionality for other indices needs to be implemented.
This branch adds a method to allocate an index and adds logic for HNSWSQ indices. The following benchmark was run on a 4gb docker container for COHERE with 1m vectors on HNSWSQ.
|                                                         Metric |                 Task |       Value |   Unit |
|---------------------------------------------------------------:|---------------------:|------------:|-------:|
|                                                 Min Throughput |   custom-vector-bulk |      754.72 | docs/s |
|                                                Mean Throughput |   custom-vector-bulk |     1420.79 | docs/s |
| …
=> Index Initialization Alloc Method

CHANGELOG.md, src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java, src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java, src/test/java/org/opensearch/knn/index/codec/util/KNNCodecUtilTests.java
Backport of https://github.com/opensearch-project/k-NN/pull/1844
=> [Backport 2.x] Fix graph merge stats size calculation

CHANGELOG.md, src/main/java/org/opensearch/knn/common/featureflags/KNNFeatureFlags.java, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java, src/main/java/org/opensearch/knn/index/query/KNNScorer.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/main/java/org/opensearch/knn/index/query/nativelib/DocAndScoreQuery.java, src/main/java/org/opensearch/knn/index/query/nativelib/NativeEngineKnnVectorQuery.java, src/test/java/org/opensearch/knn/common/featureflags/KNNFeatureFlagsTests.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java, src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java, src/test/java/org/opensearch/knn/index/query/nativelib/DocAndScoreQueryTests.java, src/test/java/org/opensearch/knn/index/query/nativelib/NativeEngineKNNVectorQueryIT.java, src/test/java/org/opensearch/knn/index/query/nativelib/NativeEngineKNNVectorQueryTests.java
Signed-off-by: Tejas Shah <shatejas@amazon.com>
(cherry picked from commit df7627c6e580843beb2361f5c2ec3519efd52280)
Backport PR 
- https://github.com/opensearch-project/k-NN/pull/1877 
=> [Backport 2.x] Introduces NativeEngineKNNQuery which executes ANN on rewrite (#1877)

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/mapper/FlatVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java, src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java
Integrate Lucene Vector field with native engines, to use KNNVectorFormat during segment creation
1. With this change I added the capability to use Lucene based vector field to for native engines. This feature is currently added behind a cluster setting to ensure that 2.x and main branch builds don't break. Once the code for adding the vector data structures is added for new KNNVectorsFormat this setting will be removed and new ITs will also be added.
2. There is a loose attribute with name isIndexKNN added which will be refactored once this PR https://github.com/opensearch-project/k-NN/pull/1939 is merged with FlatVectorsMapper class.
3. If `index.knn` is false then we will use DocValuesBased Vector Field. Because if we use the Lucene based vector field then KNNCodec will not be …
=> Integrate Lucene Vector field with native engines to use KNNVectorFormat during segment creation

CHANGELOG.md, src/main/java/org/opensearch/knn/common/FieldInfoExtractor.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/main/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNByteIterator.java, src/main/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNIterator.java, src/main/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNByteIterator.java, src/main/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNIterator.java, src/main/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesFactory.java, src/main/java/org/opensearch/knn/indices/ModelUtil.java, src/test/java/org/opensearch/knn/common/FieldInfoExtractorTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java, src/test/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNByteIteratorTests.java, src/test/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNIteratorTests.java, src/test/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNByteIteratorTests.java, src/test/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNIteratorTests.java, src/test/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesFactoryTests.java, src/test/java/org/opensearch/knn/indices/ModelUtilTests.java
Integrate KNNVectorValues with vector ANN Search flow. I have not integrated KNNVectorValues in ScriptScore as currently I am doing more deep-dive to see if we really need it. Will followup on that in next PR.
1. While doing exact search during Efficient filtering I have switched from using BinaryDocValues to KNNVectorValues.
2. Added some utility functions which are also part of this PR: https://github.com/opensearch-project/k-NN/pull/1950. Whichever PR gets merged first the conflicts can be resolved based on that PR.
Resolves #1853  …
=> Integrate KNNVectorValues with vector ANN Search flow

CHANGELOG.md, src/main/java/org/opensearch/knn/common/FieldInfoExtractor.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/main/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNByteIterator.java, src/main/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNIterator.java, src/main/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNByteIterator.java, src/main/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNIterator.java, src/main/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesFactory.java, src/main/java/org/opensearch/knn/indices/ModelUtil.java, src/test/java/org/opensearch/knn/common/FieldInfoExtractorTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java, src/test/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNByteIteratorTests.java, src/test/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNIteratorTests.java, src/test/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNByteIteratorTests.java, src/test/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNIteratorTests.java, src/test/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesFactoryTests.java, src/test/java/org/opensearch/knn/indices/ModelUtilTests.java
[Backport 2.x] Integrate KNNVectorValues with vector ANN Search flow #1952
NA
=> [Backport 2.x] Integrate KNNVectorValues with vector ANN Search flow #1952

src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java, src/test/java/org/opensearch/knn/KNNTestCase.java, src/test/java/org/opensearch/knn/common/FieldInfoExtractorTests.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
Fixing the dimension for the vector when using Lucene field in ModelFieldMapper. To ensure that bug doesn't happen again I have added UTs for the same.
This bug is not in production as the feature is not launched. Hence I am also not adding any entry in changelog.
NA
=> Fixing the dimension for the vector when using Lucene field in ModelFieldMapper

src/main/java/org/opensearch/knn/common/featureflags/KNNFeatureFlags.java
We saw increase in query latency in nightly runs. This disables query rewrite to figure out the root cause
=> Disables rewrite code path to debug latency issues

src/main/java/org/opensearch/knn/common/FieldInfoExtractor.java, src/main/java/org/opensearch/knn/common/KNNConstants.java, src/main/java/org/opensearch/knn/index/engine/AbstractKNNMethod.java, src/main/java/org/opensearch/knn/index/engine/KNNLibraryIndexingContext.java, src/main/java/org/opensearch/knn/index/engine/KNNLibraryIndexingContextImpl.java, src/main/java/org/opensearch/knn/index/engine/MethodComponent.java, src/main/java/org/opensearch/knn/index/engine/faiss/AbstractFaissMethod.java, src/main/java/org/opensearch/knn/index/engine/faiss/FaissFlatEncoder.java, src/main/java/org/opensearch/knn/index/engine/faiss/FaissHNSWMethod.java, src/main/java/org/opensearch/knn/index/engine/faiss/FaissHNSWPQEncoder.java, src/main/java/org/opensearch/knn/index/engine/faiss/FaissIVFMethod.java, src/main/java/org/opensearch/knn/index/engine/faiss/FaissIVFPQEncoder.java, src/main/java/org/opensearch/knn/index/engine/faiss/FaissSQEncoder.java, src/main/java/org/opensearch/knn/index/engine/faiss/MethodAsMapBuilder.java, src/main/java/org/opensearch/knn/index/engine/faiss/QFrameBitEncoder.java, src/main/java/org/opensearch/knn/index/engine/qframe/QuantizationConfig.java, src/main/java/org/opensearch/knn/index/engine/qframe/QuantizationConfigParser.java, src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/test/java/org/opensearch/knn/index/engine/AbstractKNNLibraryTests.java, src/test/java/org/opensearch/knn/index/engine/AbstractKNNMethodTests.java, src/test/java/org/opensearch/knn/index/engine/MethodComponentTests.java, src/test/java/org/opensearch/knn/index/engine/faiss/FaissTests.java, src/test/java/org/opensearch/knn/index/engine/faiss/QFrameBitEncoderTests.java, src/test/java/org/opensearch/knn/index/engine/qframe/QuantizationConfigParserTests.java, src/test/java/org/opensearch/knn/integ/QFrameworkIT.java
Adds support for parsing qframework for faiss in the interface for IVF and HNSW. Does not yet integrate them with the framework.
=> Add support for qframework from interface

src/main/java/org/opensearch/knn/index/engine/qframe/QuantizationConfigParser.java, src/test/java/org/opensearch/knn/index/engine/faiss/FaissTests.java, src/test/java/org/opensearch/knn/index/engine/qframe/QuantizationConfigParserTests.java
Fixes String for to/from csv parsing to not use String.format. This will ensure we do not run into Locale issues. 
=> Fix string for qframe parser key to not use String.format

CHANGELOG.md, src/main/java/org/opensearch/knn/common/FieldInfoExtractor.java, src/main/java/org/opensearch/knn/index/query/BaseQueryFactory.java, src/main/java/org/opensearch/knn/index/query/ExactSearcher.java, src/main/java/org/opensearch/knn/index/query/KNNQuery.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/main/java/org/opensearch/knn/index/query/ResultUtil.java, src/main/java/org/opensearch/knn/index/query/nativelib/NativeEngineKnnVectorQuery.java, src/main/java/org/opensearch/knn/index/query/rescore/RescoreContext.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java, src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java, src/test/java/org/opensearch/knn/index/query/ResultUtilTests.java, src/test/java/org/opensearch/knn/index/query/nativelib/NativeEngineKNNVectorQueryTests.java, src/test/java/org/opensearch/knn/index/query/rescore/RescoreContextTests.java, src/test/java/org/opensearch/knn/integ/NestedSearchIT.java
Implements re-scoring. It uses the rescoring context in the query builder to execute a two-phased search. First, it oversamples the ANN index and then reduces the results down to the oversample factor, and then rescores and returns.
Shared code for exact search was pulled out into a class called exact searcher. Rescore search functionality is included in a class called RescoreSearcher. A few sanity integ tests have been added along with existing ones, but intend to add more once quantization framework is integrated.  …
=> k-NN query rescore support for native engines

.github/workflows/CI.yml, .github/workflows/test_security.yml, CHANGELOG.md, DEVELOPER_GUIDE.md, build.gradle
Parallelize `make` to reduce the build time when we are building the plugin or the JNI libraries for the first time. 
=> Parallelize make to reduce build time

src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexWriter.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/QuantizationIndexUtils.java, src/main/java/org/opensearch/knn/index/quantizationservice/KNNVectorQuantizationTrainingRequest.java, src/main/java/org/opensearch/knn/index/quantizationservice/QuantizationService.java, src/main/java/org/opensearch/knn/quantization/models/quantizationState/MultiBitScalarQuantizationState.java, src/main/java/org/opensearch/knn/quantization/models/quantizationState/OneBitScalarQuantizationState.java, src/test/java/org/opensearch/knn/index/codec/nativeindex/DefaultIndexBuildStrategyTests.java, src/test/java/org/opensearch/knn/index/codec/nativeindex/MemOptimizedNativeIndexBuildStrategyTests.java, src/test/java/org/opensearch/knn/index/codec/nativeindex/QuantizationIndexUtilsTests.java, src/test/java/org/opensearch/knn/index/quantizationservice/QuantizationServiceTests.java, src/test/java/org/opensearch/knn/quantization/quantizationState/QuantizationStateTests.java
This PR contains some code structure Modification feedback on Package name and 
Align dimensions to the nearest multiple of 8 in QuantizationState, This will be case when float vector is not multiple of 8 and we want same experience as current float vector ingestion.
=> Align dimensions to the nearest multiple of 8 in QuantizationState

src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormatTests.java
Adds graph build time. This was missed in the initial PR
=> Adds graph build time metrics in NativeEngines990KnnVectorsWriter

src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormat.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormatTests.java
Fixing the format name for NativeEngines990KnnVectorsFormat
NA
=> Fixing the format name for NativeEngines990KnnVectorsFormat

CHANGELOG.md, src/main/java/org/opensearch/knn/common/featureflags/KNNFeatureFlags.java, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java, src/test/java/org/opensearch/knn/common/featureflags/KNNFeatureFlagsTests.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryAllocationTests.java
- Adds in a force evict mechanism before entry to prevent memory overflow for native memory usage within the cache
- This solution works in tandem with `jemalloc` enabled. In case of default `malloc`, there are potential delays with memory free up operations leading to similar scenarios
- The solution has been tested and benchmarked - described in the Testing section below
- The problem stems from the behavior of the cache where in entries of the cache might not be cleaned up as soon as they are evictable
- This delay between new entry and cleanup can, in our case, cause the memory to overflow - leading to a node failure
- This solution aims at maintaining an additional recency list within the cache manager
- On every `get` call - 
- in case of a cache hit - it just marks the key as …
=> Fix memory overflow caused by cache behavior

CHANGELOG.md, src/main/java/org/opensearch/knn/common/featureflags/KNNFeatureFlags.java, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java, src/test/java/org/opensearch/knn/common/featureflags/KNNFeatureFlagsTests.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryAllocationTests.java
Signed-off-by: Kunal Kotwani <kkotwani@amazon.com>
(cherry picked from commit d4af93edfb45878fdb0a442f4ac07e091b5ad14b)
- Backports #2015 to `2.x`
Resolves backport for #2015
=> [Backport 2.x] Fix memory overflow caused by cache behavior (#2015)

CHANGELOG.md, release-notes/opensearch-knn.release-notes-2.17.0.0.md
Backport https://github.com/opensearch-project/k-NN/pull/2037/commits/b093e93ddfa955550fd66d6142977a5836453629 from #2037 
=> [Backport 2.17] Add release notes for 2.17

release-notes/opensearch-knn.release-notes-2.17.0.0.md, src/main/java/org/opensearch/knn/index/KNNIndexShard.java, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/KNN990QuantizationStateReader.java, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReader.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexWriter.java, src/main/java/org/opensearch/knn/index/engine/KNNMethodConfigContext.java, src/main/java/org/opensearch/knn/index/mapper/CompressionLevel.java, src/main/java/org/opensearch/knn/index/mapper/KNNMappingConfig.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldType.java, src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/Mode.java, src/main/java/org/opensearch/knn/index/mapper/ModeBasedResolver.java, src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/plugin/rest/RestTrainModelHandler.java, src/main/java/org/opensearch/knn/plugin/transport/TrainingModelRequest.java, src/main/java/org/opensearch/knn/training/TrainingJob.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/KNN990QuantizationStateReaderTests.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormatTests.java, src/test/java/org/opensearch/knn/index/engine/KNNMethodContextTests.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java, src/test/java/org/opensearch/knn/integ/QFrameworkIT.java, src/test/java/org/opensearch/knn/plugin/transport/TrainingModelRequestTests.java
Adds mode and compression based parameter resolution. With this, if a user specifies the mode and/or compression params, we will create a default configuration with the aim of meeting those hints.
Currently, it does not contain support for overriding any of the parameters. This will be taken in a future commit.
Still working on tests, but figured it would be good to get the PR out. Heres what I still need to do:
#1949 
=> Introduce mode and compression param resolution

release-notes/opensearch-knn.release-notes-2.17.0.0.md, src/main/java/org/opensearch/knn/common/KNNConstants.java, src/main/java/org/opensearch/knn/index/SpaceType.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java, src/main/java/org/opensearch/knn/index/mapper/ModeBasedResolver.java, src/main/java/org/opensearch/knn/index/mapper/OriginalMappingParameters.java, src/main/java/org/opensearch/knn/index/util/IndexUtil.java, src/main/java/org/opensearch/knn/plugin/rest/RestTrainModelHandler.java, src/main/java/org/opensearch/knn/plugin/transport/TrainingModelRequest.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/index/mapper/OriginalMappingParametersTests.java
Add spaceType as a top level parameter while creating vector field. With this change a user can change the spaceType for the vector field without defining the `method` parameter in the mapping. With this change Disk based vector search OOB experience is improved.
Tests will be added in followup PRs
I have performed manual testing by running following create index request.
Success
```
{
"settings": {
"index": {
"number_of_shards": 1,
"number_of_replicas": 0,
"refresh_interval": "1s",
"knn": true
}
},
"mappings": {
"my_vector2": {
"dimension": 4,
"mode": "on_disk",
"compression_level": "32x",
"space_type": "innerproduct"
}
}
}
}
```
Success and hits the legacy method and use the innerproduct space type
```
{
"settings": {
"index": {
"number_of_shards": …
```
=> Add spaceType as a top level parameter while creating vector field.

src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/DefaultIndexBuildStrategy.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/MemOptimizedNativeIndexBuildStrategy.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexBuildStrategy.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexWriter.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/model/BuildIndexParams.java, src/main/java/org/opensearch/knn/index/quantizationservice/KNNVectorQuantizationTrainingRequest.java, src/main/java/org/opensearch/knn/index/quantizationservice/QuantizationService.java, src/main/java/org/opensearch/knn/index/vectorvalues/KNNVectorValues.java, src/test/java/org/opensearch/knn/index/codec/nativeindex/DefaultIndexBuildStrategyTests.java, src/test/java/org/opensearch/knn/index/codec/nativeindex/MemOptimizedNativeIndexBuildStrategyTests.java, src/test/java/org/opensearch/knn/index/quantizationservice/QuantizationServiceTests.java, src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java
Fix the force merge with Quantization failures when a segment has deleted docs in it.
When documents are deleted from the segment and segments are force merged, the FlatVectorValues are getting merged to 1 vectorValues but that `vectorvalue.getLiveDocs()` doesn't provide correct live docs but it provides the `cost` which includes the deleted docs too. 
Due to this when we are doing quantization, we are hitting the vectors which are not present and leading to NPE. 
```
org.apache.lucene.index.MergePolicy$MergeException: java.lang.IllegalStateException: this writer hit an unrecoverable error; cannot merge
at org.opensearch.index.engine.InternalEngine$EngineMergeScheduler$2.doRun(InternalEngine.java:2494) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
at …
```
=> Fix the force merge with Quantization failures when a segment has deleted docs in it

src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/integ/TopLevelSpaceTypeParameterIT.java
Add tests for top level spaceType parameter with different combinations
NA
=> Add tests for top level spaceType parameter with different combinations

src/main/java/org/opensearch/knn/index/mapper/KNNMappingConfig.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/index/query/nativelib/NativeEngineKnnVectorQuery.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
- Adds a debug log for time spent rescoring
=> Throws and exception for radial search when mapping is for on-disk mode

src/main/java/org/opensearch/knn/index/codec/nativeindex/DefaultIndexBuildStrategy.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/MemOptimizedNativeIndexBuildStrategy.java, src/main/java/org/opensearch/knn/index/codec/transfer/OffHeapBinaryVectorTransfer.java, src/main/java/org/opensearch/knn/index/codec/transfer/OffHeapByteVectorTransfer.java, src/main/java/org/opensearch/knn/index/codec/transfer/OffHeapFloatVectorTransfer.java, src/main/java/org/opensearch/knn/index/codec/transfer/OffHeapVectorTransfer.java, src/main/java/org/opensearch/knn/index/codec/transfer/OffHeapVectorTransferFactory.java, src/test/java/org/opensearch/knn/index/codec/nativeindex/DefaultIndexBuildStrategyTests.java, src/test/java/org/opensearch/knn/index/codec/nativeindex/MemOptimizedNativeIndexBuildStrategyTests.java, src/test/java/org/opensearch/knn/index/codec/transfer/OffHeapVectorTransferFactoryTests.java, src/test/java/org/opensearch/knn/index/codec/transfer/OffHeapVectorTransferTests.java
The array list buffer was unnecessarily allocated a large memory irrespective of the number of vectors to transfer. This change considers total vectors
Attached below is the heap usage for the duration of `BinaryIndexIT.testFaissHnswBinary_when1000Data_thenCreateIngestQueryWorks` test
[transferLimitNotCapped.log](https://github.com/user-attachments/files/16920119/transferLimitNotCapped.log): This is the current code in main. The max heap usage is 1.8 gb
[transferLimitCapped.log](https://github.com/user-attachments/files/16920120/transferLimitCapped.log): This is code with the current PR. The max heap usage is 1.2 gb
[NoPreallocation.log](https://github.com/user-attachments/files/16920121/NoPreallocation.log): This is without allocating the transferLimit as a size for arraylist. The max …
=> Bounds the transferLimit in OffheapVectorTransfer

src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java
Fixing KNNMethodContext resolution when documents are ingested and a flaky test
1. When mode and compression is provided and documents are ingested, the rescore parameter was not getting passed in during search, as in the FieldMapper mergeBuilder Mode and compression attributes were not getting set.
2. There was a flaky test `testDeletedDocsWithSegmentMerge_whenValid_ThenSucceed`. It was added in the PR: https://github.com/opensearch-project/k-NN/pull/2046 to test that merges are happening without any failures. But as this test was doing search at the end it is not necessary that search will always give consistent results as the documents are deleted. Hence the correct test for this is ensuring the index is green after the merge. The flakiness was observed here: …
=> [BugFix] Fixing KNNMethodContext resolution when documents are ingested and a flaky test

src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java
Signed-off-by: Navneet Verma <navneev@amazon.com>
(cherry picked from commit 8f6b177986ab89676fcca2b1fdedad580896b8c3)
Backport of #2072 
=> [Backport 2.x] [BugFix] Fixing KNNMethodContext resolution when documents are ingested and a flaky test (#2072)

src/main/java/org/opensearch/knn/index/codec/nativeindex/QuantizationIndexUtils.java, src/main/java/org/opensearch/knn/quantization/models/quantizationOutput/BinaryQuantizationOutput.java, src/main/java/org/opensearch/knn/quantization/models/quantizationOutput/QuantizationOutput.java, src/main/java/org/opensearch/knn/quantization/quantizer/MultiBitScalarQuantizer.java, src/main/java/org/opensearch/knn/quantization/quantizer/OneBitScalarQuantizer.java, src/test/java/org/opensearch/knn/index/codec/nativeindex/DefaultIndexBuildStrategyTests.java, src/test/java/org/opensearch/knn/index/codec/nativeindex/MemOptimizedNativeIndexBuildStrategyTests.java, src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java, src/test/java/org/opensearch/knn/quantization/output/BinaryQuantizationOutputTests.java
This PR addresses a critical issue that was identified during benchmarking, where the recall performance unexpectedly dropped below 1. The root cause of the issue was traced to two main problems in the quantization and vector handling process:
1. Bit Packing of Quantized Vector:  The quantized vector was not correctly updated during the bit-packing process. Instead, the same vector values were being reused, resulting in incorrect quantization of subsequent vectors.
2. Vector Transfer to JNI: When transferring vectors to the JNI layer, vectors were passed by reference, causing all the vectors in the VectorTransfer list to reference the same object. This led to unintended behavior where all vectors became identical, severely affecting the recall accuracy.
Performed Benchmarking with NQ Data …
=> Re-Call Issue Fix with Binary Quantized Vectors

release-notes/opensearch-knn.release-notes-2.17.0.0.md, src/main/java/org/opensearch/knn/common/KNNConstants.java, src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java, src/main/java/org/opensearch/knn/index/util/IndexUtil.java, src/main/java/org/opensearch/knn/indices/ModelDao.java, src/main/java/org/opensearch/knn/indices/ModelMetadata.java, src/main/java/org/opensearch/knn/indices/ModelUtil.java, src/main/java/org/opensearch/knn/training/TrainingJob.java, src/main/java/org/opensearch/knn/training/TrainingJobRunner.java, src/main/resources/mappings/model-index.json, src/test/java/org/opensearch/knn/index/KNNCreateIndexFromModelTests.java, src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/indices/ModelCacheTests.java, src/test/java/org/opensearch/knn/indices/ModelDaoTests.java, src/test/java/org/opensearch/knn/indices/ModelMetadataTests.java, src/test/java/org/opensearch/knn/indices/ModelTests.java, src/test/java/org/opensearch/knn/indices/ModelUtilTests.java, src/test/java/org/opensearch/knn/plugin/transport/GetModelResponseTests.java, src/test/java/org/opensearch/knn/plugin/transport/RemoveModelFromCacheTransportActionTests.java, src/test/java/org/opensearch/knn/plugin/transport/TrainingModelRequestTests.java, src/test/java/org/opensearch/knn/plugin/transport/UpdateModelGraveyardTransportActionTests.java, src/test/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataRequestTests.java, src/test/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataTransportActionTests.java, src/test/java/org/opensearch/knn/training/TrainingJobRunnerTests.java, src/test/java/org/opensearch/knn/training/TrainingJobTests.java
Backport of https://github.com/opensearch-project/k-NN/pull/2005, including fix from https://github.com/opensearch-project/k-NN/pull/2062
=> [Backport 2.x]  Add model version to model metadata and change model metadata reads to be from cluster metadata

src/main/java/org/opensearch/knn/index/query/ExactSearcher.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/main/java/org/opensearch/knn/index/query/SegmentLevelQuantizationInfo.java, src/main/java/org/opensearch/knn/index/query/SegmentLevelQuantizationUtil.java, src/main/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNIterator.java, src/main/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNIterator.java, src/main/java/org/opensearch/knn/index/query/nativelib/NativeEngineKnnVectorQuery.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java, src/test/java/org/opensearch/knn/index/query/nativelib/NativeEngineKNNVectorQueryTests.java
[Bug-Fix] Fix efficient filtering of vector search when quantization is used
When efficient filtering happens then at per segment level k-NN plugin takes a decision to either do filtered ANN search or Exact search. But when quantization is present then the first pass search happens on the quantized vectors. Currently only ANN search happens with quantized vectors and not exact search. This can lead of different scores for a shard for first pass search if its segments takes different route to do the filtered search.
This PR adds the capability to do quantized exact search when exact search happens during filtered vector search. The way it is achieved is, by passing the segment level quantization information to KNNIterators which iterates over the vectors. It also add a capability now where …
=> [Bug-Fix] Fix efficient filtering of vector search when quantization is used

jni/src/faiss_wrapper.cpp, release-notes/opensearch-knn.release-notes-2.17.0.0.md
Use correct type for binary vector in ivf training
N/A
=> Use correct type for binary vector in ivf training

release-notes/opensearch-knn.release-notes-2.17.0.0.md, scripts/windowsScript.ps1
In the CI, we uses MINGW64. With MINGW32, the hamming distance calculation is not correct which result in bad recall for binary vector in window platform.
N/A
=> Switch MINGW32 to MINGW64

qa/restart-upgrade/build.gradle, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/QueryANNIT.java
This is done to make sure that KNN80DocsValueConsumer code path is hit
=> Adds index and query BWC tests for missing engines

src/main/java/org/opensearch/knn/index/engine/MethodComponent.java, src/main/java/org/opensearch/knn/index/engine/faiss/FaissMethodResolver.java, src/main/java/org/opensearch/knn/index/mapper/CompressionLevel.java, src/main/java/org/opensearch/knn/index/query/rescore/RescoreContext.java, src/main/java/org/opensearch/knn/index/util/IndexHyperParametersUtil.java, src/test/java/org/opensearch/knn/index/engine/MethodComponentTests.java, src/test/java/org/opensearch/knn/index/engine/faiss/FaissMethodResolverTests.java, src/test/java/org/opensearch/knn/index/mapper/CompressionLevelTests.java, src/test/java/org/opensearch/knn/index/query/rescore/RescoreContextTests.java, src/test/java/org/opensearch/knn/index/util/IndexHyperParametersUtilTests.java
This PR contains changes to change default hyper parameter in case of Binary Quantization from 100 to 256 for ef Search and ef Construction and also changes the default oversampling factor from 2.x to 3.x.
https://github.com/opensearch-project/k-NN/issues/1949
=> Improving Defaults Hyper Parameter for Binary Quantization Indexes

qa/restart-upgrade/build.gradle, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/QueryANNIT.java
This is done to make sure that KNN80DocsValueConsumer code path is hit
Signed-off-by: Tejas Shah <shatejas@amazon.com>
(cherry picked from commit e3200260e7360f6ff90600535ac759d11cb1fefb)
Backport of https://github.com/opensearch-project/k-NN/pull/2035
=> [Backport 2.x] Adds index and query BWC tests for missing engines (#2035)

CHANGELOG.md, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java
- Add short circuit if no live docs are in segments
- Fixed stop watch bug
=> Add short circuit if no live docs are in segments

src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterFlushTests.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterMergeTests.java, src/test/java/org/opensearch/knn/index/vectorvalues/TestVectorValues.java
Had to separate out the common code in NativeEngines990KnnVectorsWriter to make it easy to write tests. Mocking was difficult to do with the functional interfaces and it was throwing NPE in the test especially with the mock of NativeIndexWriter::flush and NativeIndexWriter::merge where it wasn't able to recognize the mocked writer.
=> Adds Unit tests for NativeEngines990KnnVectorsWriter

src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormatTests.java
Previosuly we were not creating hnsw file on segment flush for faiss engine. After successfully integrating hnsw file creation, we forgot to update unit test. In this PR, we will confirm that required files are being created based on field type.
=> Fix native engine vector format test

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormat.java, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java, src/test/java/org/opensearch/knn/index/OpenSearchIT.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormatTests.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterFlushTests.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterMergeTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Added new updatable index setting "build_vector_data_structure_threshold", which will be considered when to build relevant vector data structure or not for native engines before creating and merging segments. The default value is chosen to be 0 to make it backward compatible. This is applicable only for native engines, and, it is no-op for lucene. 
We also don't need a feature flag since implementation is behind NativeEngines990KnnVectorsFormat. Hence, only index that are created 2.17 and above will have the ability to pause building graph while indexing or merging based on this updatable index setting.
In this PR, we introduced a setting to decide when to build the graph with min as -1 ( no graph will be built ) and Integer.MAX_Value - 2 ( as max value up to which user can provide ). …
=> Introduce new setting to configure when to build graph during segment creation

src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java
Removes a comment in ModeAndCompressionIT describing why a test was ignored temporarily.  Currently, the functionality has been fixed and the test is passing.
=> Remove outdated comment in integration tests

src/main/java/org/opensearch/knn/index/query/rescore/RescoreContext.java
Changes minimum oversample factor from 0 to 1. Having an oversample factor that will return less results than the second pass needs to return will always result in less than k results being returned. This is a bug.
From a bwc perspective, we could check if index is created on 2.17 for validation. However, given this is a bug, I think its better to document it as 1.0f and not look at index versioning. 
#2112 
=> Change min oversample to 1

src/main/java/org/opensearch/knn/quantization/models/quantizationState/QuantizationStateCache.java
Adds a log statement when a quantization state is evicted from the cache because the cache is full.  This can help users determine if cache thrashing is happening or if the cache is consistently full.
=> Add log message for quantization state cache eviction due to full cache

CHANGELOG.md, src/main/java/org/opensearch/knn/plugin/KNNPlugin.java, src/main/java/org/opensearch/knn/plugin/search/KNNConcurrentSearchRequestDecider.java, src/test/java/org/opensearch/knn/integ/search/ConcurrentSegmentSearchIT.java, src/test/java/org/opensearch/knn/plugin/search/KNNConcurrentSearchRequestDeciderTests.java, src/testFixtures/java/org/opensearch/knn/KNNJsonIndexMappingsBuilder.java
This allows knn queries to enable concurrency when `index.search.concurrent_segment_search.mode` or `search.concurrent_segment_search.mode` in `auto` mode. Without this the default behavior of auto mode is non-concurrent search
More details in https://github.com/opensearch-project/OpenSearch/issues/15259
- Manually tested with debugger to make sure `ConcurrentQueryPhaseSearcher` is used
- Unit test and sanity IntegTest added
**Baseline (no settings update)**
50th percentile latency,prod-queries,58.86101468404134,ms
90th percentile latency,prod-queries,85.32014465332031,ms
99th percentile latency,prod-queries,95.10733413696289,ms
**Concurrent_segment_search.mode: auto**
50th percentile latency,prod-queries,45.04893729613377,ms
90th percentile latency,prod-queries,48.14952836545217,ms
99th …
=> Integrates KNN plugin with ConcurrentSearchRequestDecider interface

.github/workflows/CI.yml, .github/workflows/backwards_compatibility_tests_workflow.yml, .github/workflows/test_security.yml, CHANGELOG.md, DEVELOPER_GUIDE.md, build.gradle, jni/cmake/init-faiss.cmake, scripts/build.sh, src/main/java/org/opensearch/knn/common/KNNConstants.java, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/jni/FaissService.java, src/main/java/org/opensearch/knn/jni/PlatformUtils.java, src/main/plugin-metadata/plugin-security.policy, src/test/java/org/opensearch/knn/jni/PlatformUtilTests.java
This change adds support to speed up vector search and indexing in faiss using AVX512 hardware accelerator.
Resolves #2056 
=> Add changes for AVX-512 support in k-NN. 

CHANGELOG.md, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterFlushTests.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterMergeTests.java
quantization isn't needed
An attempt to address the regression seen in force-merge time for cohere-10m dataset. 
The perf for force merge showed improvements in 1m dataset
 | number of index segments | force merge time (minutes) | force merge segments
-- | -- | -- | --
2.17 code | 75 | 15.68263 | 3
Current PR | 92 | 12.51252 | 3
https://github.com/opensearch-project/k-NN/issues/2134
=>  Makes sure KNNVectorValues aren't recreated unnecessarily when

src/main/java/org/opensearch/knn/plugin/rest/RestTrainModelHandler.java
Adds space_type as an acceptable field in the train API, which is consistent with the documentation
=> Add space_type as acceptable field in train API

CHANGELOG.md, src/main/java/org/opensearch/knn/index/mapper/CompressionLevel.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldType.java, src/main/java/org/opensearch/knn/index/query/rescore/RescoreContext.java, src/test/java/org/opensearch/knn/index/mapper/CompressionLevelTests.java
This PR contains changes to update oversampling factor in Rescore Context based on Dimension. If Dimension is less than or equal to 1000 then update to 5x Oversampling factor else it will be defaulted to 3x for 32x and 16x compression and 2x for 8x compression.
=> Update Default Rescore Context based on Dimension

CHANGELOG.md, src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesProducer.java, src/test/java/org/opensearch/knn/index/OpenSearchIT.java, src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesProducerTests.java
KNN80DocValuesProducer should consider adding files from fields that has BinaryDocValues and doesn't have vector values in producer. By default, k-NN field types post 2.17 don't create BinaryDocValues for knn field anymore. However, users can set doc_values = true, to create BinaryDocValues explicitly like any other field, though it is not used for approximate search. Hence, we want to avoid considering fields that is created using NativeEngines990KnnVectorsFormat. Checking doc Type not equal to BinayDocValues and field doesn't have vectors will make sure we don't accidentally add native engine files that are created from NativeEngines990KnnVectorsFormat.
For more information …
=> KNN80DocValues should only be considered for BinaryDocValues fields

release-notes/opensearch-knn.release-notes-2.17.0.0.md, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterFlushTests.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterMergeTests.java, src/test/java/org/opensearch/knn/index/vectorvalues/TestVectorValues.java
[Backport 2.17] Makes sure KNNVectorValues aren't recreated unnecessarily when quantization isn't needed (#2133)
Signed-off-by: Tejas Shah <shatejas@amazon.com>
(cherry picked from commit e33afa5de5f8658ad7fbe71125707436e81cc5b8)
Backport PR for https://github.com/opensearch-project/k-NN/pull/2133
=> [Backport 2.17] Makes sure KNNVectorValues aren't recreated unnecessarily when quantization isn't needed (#2133)

jni/cmake/init-nmslib.cmake, jni/patches/nmslib/0003-Adding-two-apis-using-stream-to-load-save-in-Hnsw.patch
[Describe what this change achieves]
=> Added NMSLIB patched allowing load/write APIs with a stream object.

CHANGELOG.md, src/main/java/org/opensearch/knn/index/query/ResultUtil.java
This PR optimizes the reduceToTopK method by eliminating unnecessary pre-filling of the priority queue, reducing redundant peek() calls, and adding null safety checks for better performance.
Closes https://github.com/opensearch-project/k-NN/issues/2145
=> Optimize reduceToTopK in ResultUtil by removing pre-filling and reducing peek calls

CHANGELOG.md, src/main/java/org/opensearch/knn/index/query/ExactSearcher.java, src/main/java/org/opensearch/knn/index/query/iterators/ByteVectorIdsKNNIterator.java, src/main/java/org/opensearch/knn/index/query/iterators/KNNIterator.java, src/main/java/org/opensearch/knn/index/query/iterators/NestedByteVectorIdsKNNIterator.java, src/main/java/org/opensearch/knn/index/query/iterators/NestedVectorIdsKNNIterator.java, src/main/java/org/opensearch/knn/index/query/iterators/VectorIdsKNNIterator.java, src/test/java/org/opensearch/knn/index/query/iterators/ByteVectorIdsKNNIteratorTests.java, src/test/java/org/opensearch/knn/index/query/iterators/NestedByteVectorIdsKNNIteratorTests.java, src/test/java/org/opensearch/knn/index/query/iterators/NestedVectorIdsKNNIteratorTests.java, src/test/java/org/opensearch/knn/index/query/iterators/VectorIdsKNNIteratorTests.java
Update VectorIterator, ByteIterator, NestedVectorIterator, NestedByteIterator to iterate even if there are no filters provided.
Currently this is used by exact search to score either topK docs or all docs when filter is provided by users.
However, in future we will be allowing exact search even if there are no filters. Hence, decouple filter
and make it option to support both cases.
Pre-requisite for  #1942 
=> KNNIterators should support with and without filters

CHANGELOG.md, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterFlushTests.java
- Update unit test to include empty field in multi field scenario. This was added as part of #2007 to feature branch due to feedback https://github.com/opensearch-project/k-NN/pull/2007#discussion_r1761671765 . Now moving this as separate PR since it is independent of that feature.
- Also updated iterator to use stream from collection instead of IntStream since index was not used in that iterator.
- Refactor if/else to reduce nesting
=> Minor refactoring and refactored some unit test

src/main/java/org/opensearch/knn/index/query/ExactSearcher.java, src/main/java/org/opensearch/knn/index/query/iterators/BinaryVectorIdsKNNIterator.java, src/main/java/org/opensearch/knn/index/query/iterators/ByteVectorIdsKNNIterator.java, src/main/java/org/opensearch/knn/index/query/iterators/NestedBinaryVectorIdsKNNIterator.java, src/test/java/org/opensearch/knn/index/query/iterators/BinaryVectorIdsKNNIteratorTests.java, src/test/java/org/opensearch/knn/index/query/iterators/NestedBinaryVectorIdsKNNIteratorTests.java, src/test/java/org/opensearch/knn/integ/FilteredSearchByteIT.java, src/test/java/org/opensearch/knn/integ/NestedSearchByteIT.java
Fix Faiss efficient filter exact search using byte vector datatype
https://github.com/opensearch-project/k-NN/issues/2168
=> Fix Faiss efficient filter exact search using byte vector datatype

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/mapper/CompressionLevel.java, src/main/java/org/opensearch/knn/index/query/nativelib/NativeEngineKnnVectorQuery.java, src/main/java/org/opensearch/knn/index/query/rescore/RescoreContext.java, src/test/java/org/opensearch/knn/index/KNNSettingsTests.java, src/test/java/org/opensearch/knn/index/mapper/CompressionLevelTests.java, src/test/java/org/opensearch/knn/index/query/nativelib/NativeEngineKNNVectorQueryTests.java
Issue:- During rescoring at the shard level in a multi-segment case, the recall of the search results drops to zero.
Fix :- To address the issue of reduced recall during shard-level rescoring in multi-segment cases, we are introducing an index-level setting that allows users to enable or disable shard-level rescoring. This setting gives finer control over whether rescoring should be performed at the shard level or if the system should rely on a more global rescoring process across all segments. By disabling shard-level rescoring, the recall issue is mitigated, as the rescoring process will take into account the complete set of results from all segments, rather than focusing on top k results. 
Oversampling Update :- With this change we are updating default oversampling factor as well. For …
=>  Adding Support to Enable/Disble Share level Rescoring and Update Oversampling Factor

src/test/java/org/opensearch/knn/integ/BinaryIndexIT.java
Add integration test for binary vector values
Part of #1942 
=> Add integration test for binary vector values

CHANGELOG.md, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/test/java/org/opensearch/knn/index/OpenSearchIT.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriterTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java, src/test/java/org/opensearch/knn/integ/BinaryIndexIT.java
Add exact search if no native engine files are available . This PR is part of issue where users will have option to decide when to build graph, which helps them to reduce build time. When graph is not available, plugin will return empty results. With this PR, exact search will be performed when only no engine file is available in segment.
We also don't need version check or feature flag because, option to not build vector data structure will only be available post 2.17. If an index is created using pre 2.17 version, segment will always have engine files and this feature will never be called during search.
Part of #1942 
For more information on following Developer Certificate …
=> Add exact search if no native engine files are available

CHANGELOG.md, DEVELOPER_GUIDE.md
This PR is to fix the sed command listed in DEVELOPER_GUIDE.md to append a new line after addition.
In the guide, it is recommended to use sed command to append a new line having libomp related CXX arguments in Mac.
However, since the added new line does not end with '\n' making its following sentence to be located right behind the closing parenthesis, resulting in CMake processing failure.
```
In DEVELOPER_GUIDE.md
...
// In case of linking issues with the external libraries and clang, you can try setting the CMAKE compiler to gcc/g++ instead through the following commands:
export CC=gcc
export CXX=g++
sed -i '' '/set(CMAKE_CXX_STANDARD_REQUIRED True)/a\'$'\n''set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Xclang -fopenmp -L/opt/homebrew/opt/libomp/lib -I/opt/homebrew/opt/libomp/include -lomp …
```
=> Fix sed command in DEVELOPER_GUIDE.md to append a new line character '\n'.

src/main/java/org/opensearch/knn/index/query/ExactSearcher.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/main/java/org/opensearch/knn/index/query/RNNQueryFactory.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/OpenSearchIT.java, src/test/java/org/opensearch/knn/index/query/ExactSearcherTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java, src/test/java/org/opensearch/knn/integ/BinaryIndexIT.java
When threshold value is set, knn plugin will not be creating graph. Hence, when search request is trigged during that time, exact search will return valid results. However, radial search was never included as part of exact search. This will break radial search when threshold is added and radial search is requested. In this commit, new method
is introduced to accept min score and return documents that are greater than min score, similar to how radial search is performed by native engines. This search is independent of engine, but, radial search is supported only for FAISS engine out of all native engines.
Part of #1942 
For more information on following Developer Certificate …
=> Add support for radial search in exact search

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/mapper/CompressionLevel.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/main/java/org/opensearch/knn/index/query/nativelib/NativeEngineKnnVectorQuery.java, src/main/java/org/opensearch/knn/index/query/rescore/RescoreContext.java, src/test/java/org/opensearch/knn/index/KNNSettingsTests.java, src/test/java/org/opensearch/knn/index/mapper/CompressionLevelTests.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java, src/test/java/org/opensearch/knn/index/query/nativelib/NativeEngineKNNVectorQueryTests.java, src/test/java/org/opensearch/knn/index/query/rescore/RescoreContextTests.java
**Change1**
Problem
In Disk Vector Mode, while calculating the score for a binary quantized vector, the system was incorrectly using Inner Product as the similarity function. However, for binary quantized vectors, the correct distance metric should be Hamming Distance.
Impact:
This incorrect scoring mechanism led to poor results, particularly in cases with multiple segments. During the process of reducing to the top k candidates, the best candidates (those with the most relevant results) were being filtered out. As a result, the recall was zero, meaning no relevant results were being returned, which critically affected the accuracy of search results.
Expected Behavior:
The system should use Hamming Distance for binary quantized vectors, ensuring that the correct similarity metric is …
=> Score Fix for Binary Quantized Vector and Setting Default value in case of shard level rescoring is disabled for oversampling factor

CHANGELOG.md, src/main/java/org/opensearch/knn/index/query/rescore/RescoreContext.java
Backport https://github.com/opensearch-project/k-NN/commit/01d7981c8a9ddab24188b08ae9c7ace2ba1e2ac5 from https://github.com/opensearch-project/k-NN/pull/2183
=> Java Docs Fix for 2.x in Linux Machine

CHANGELOG.md, src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/KNN9120Codec.java, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriter.java, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java, src/main/java/org/opensearch/knn/index/codec/KNNCodecVersion.java, src/main/java/org/opensearch/knn/index/codec/params/KNNScalarQuantizedVectorsFormatParams.java, src/main/resources/META-INF/services/org.apache.lucene.codecs.Codec, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriterTests.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterFlushTests.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterMergeTests.java, src/test/java/org/opensearch/knn/index/codec/params/KNNScalarQuantizedVectorsFormatParamsTests.java
Fix lucene codec after lucene version bumped to 9.12 Currently the version bump has happened only for main branch hence we are not doing any backport here.
This change includes:
1. Bumping up the Lucene Codec to 912.
2. New KNN9120Codec class added.
3. Changes in the NativeEngineFieldVectorsWriter to pass the FlatFieldVectorsWriter since in Lucene 912, the capability of FlatFieldVectorsWriter adding the vectorValue to a passed VectorFieldWriter, the VectorFieldWriters who are using the FlatFieldVectorsWriter have to call the addValue function of FlatFieldVectorsWriter. Ref: https://github.com/apache/lucene/pull/13538
4. Set Compress flag for Lucene SQ bits > 4 to false. Ref: https://github.com/apache/lucene/blob/branch_9_12/lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99Sca …
=> Fix lucene codec after lucene version bumped to 9.12

CHANGELOG.md
Moves changelog content to 2.x
=> Fix changelog so changes for 2.x are in 2.x

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormat.java, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java, src/main/java/org/opensearch/knn/index/query/ExactSearcher.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/main/java/org/opensearch/knn/index/query/RNNQueryFactory.java, src/main/java/org/opensearch/knn/index/query/nativelib/NativeEngineKnnVectorQuery.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/OpenSearchIT.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriterTests.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterFlushTests.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterMergeTests.java, src/test/java/org/opensearch/knn/index/query/ExactSearcherTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java, src/test/java/org/opensearch/knn/integ/BinaryIndexIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Added new updatable index setting "approximate_threshold", which will be
considered when to build graph or not for native engines. This is noop for lucene. 
When graph is not available, plugin will return empty results. With this change, exact search will be performed when only no engine file is available in segment. 
Radial search was never included as part of exact search. This will break radial search when threshold
is added and radial search is requested. Hence, introduce exact search during radial search similar to Approx search.
#1942  …
=> Add support to build vector data structures greedily and perform exact search when there are no engine files

jni/patches/faiss/0001-Custom-patch-to-support-multi-vector.patch, jni/patches/faiss/0002-Enable-precomp-table-to-be-shared-ivfpq.patch
Bump Faiss commit from `33c0ba5` to `4eecd91` to include AVX512 optimizations added to ScalarQuantizer
=> Bump Faiss commit from 33c0ba5 to 4eecd91

build.gradle
Bump byte-buddy to 1.15.4 to fix build failure and keep it [consistent with core](https://github.com/opensearch-project/OpenSearch/pull/16257/files#diff-ffefe72fc1ee096585e9d66d31384a4c489667cdc2e4a752e9c3183eaad6621fR65)
https://github.com/opensearch-project/k-NN/actions/runs/11296486595/job/31421473604?pr=2203
```
> Conflict found for the following module:
For more on this, please refer to https://docs.gradle.org/8.4/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
- net.bytebuddy:byte-buddy between versions 1.15.4 and 1.14.9
```
For more information on following Developer Certificate of Origin and signing off your commits, please …
=> Bump byte-buddy to 1.15.4

.github/CODEOWNERS, MAINTAINERS.md
Adding shatejas as the maintainer. The approval was taken from the maintainer of k-NN repo over email. 
Process followed: https://github.com/opensearch-project/.github/blob/main/ADMINS.md#addremove-maintainers
NA
=> Adding shatejas as the maintainer

src/main/java/org/opensearch/knn/index/query/KNNQuery.java, src/main/java/org/opensearch/knn/index/query/nativelib/NativeEngineKnnVectorQuery.java, src/test/java/org/opensearch/knn/index/query/nativelib/NativeEngineKNNVectorQueryTests.java
Minor code fixes which includes:
* Passing correct score mode in NativeEnginekNNVectorQuery. NativeEnginekNNVectorQuery was always passing `ScoreMode.COMPLETE` ideally it should be the score mode which was passed to createWeight function. 
* Ensuring visitor is called in KnnQuery.
Both these fixes doesn't impact any query performance or fixes a bug, but these were inconsistencies in the code.
NA
=> Minor code fixes to remove code inconsistencies.

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNIndexShard.java, src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesProducer.java, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReader.java, src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java, src/main/java/org/opensearch/knn/index/codec/util/NativeMemoryCacheKeyHelper.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryEntryContext.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategy.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/main/java/org/opensearch/knn/jni/JNIService.java, src/main/java/org/opensearch/knn/plugin/KNNPlugin.java, src/test/java/org/opensearch/knn/index/KNNIndexShardTests.java, src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesProducerTests.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormatTests.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryAllocationTests.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryCacheManagerTests.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryEntryContextTests.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategyTests.java, src/testFixtures/java/org/opensearch/knn/TestUtils.java
Signed-off-by: Dooyong Kim <kdooyong@amazon.com>
backporting from https://github.com/opensearch-project/k-NN/pull/2182
=> [Backport 2.x] Remove FileWatcher from KNN (#2182)

qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ClearCacheIT.java, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java, qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/ClearCacheIT.java, qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java, release-notes/opensearch-knn.release-notes-2.18.0.0.md, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormat.java, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/UnitTestCodec.java, src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java, src/test/java/org/opensearch/knn/index/KNNCircuitBreakerIT.java, src/test/java/org/opensearch/knn/index/KNNESSettingsTestIT.java, src/test/java/org/opensearch/knn/index/KNNIndexShardTests.java, src/test/java/org/opensearch/knn/index/NmslibIT.java, src/test/java/org/opensearch/knn/index/OpenSearchIT.java, src/test/java/org/opensearch/knn/plugin/action/RestClearCacheHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestKNNWarmupHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNStatsHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNWarmupHandlerIT.java, src/test/java/org/opensearch/knn/plugin/transport/ClearCacheTransportActionTests.java, src/test/java/org/opensearch/knn/plugin/transport/KNNWarmupTransportActionTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
After comparing indexing and search performance, we are updating default value to be 15000.
Updated bwc rolling upgrade test and restart test to reset threshold to 0 to build graph always. Few tests checks
for graph in cache and having 15K will break that test. Hence, when new cluster comes up, we will update the setting to 0, force merge if require, before doing any new indexing.
#1942 
=> Update approximate_threshold to 15K documents

qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ClearCacheIT.java, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java, qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/ClearCacheIT.java, qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java, release-notes/opensearch-knn.release-notes-2.18.0.0.md, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormat.java, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/UnitTestCodec.java, src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java, src/test/java/org/opensearch/knn/index/KNNCircuitBreakerIT.java, src/test/java/org/opensearch/knn/index/KNNESSettingsTestIT.java, src/test/java/org/opensearch/knn/index/KNNIndexShardTests.java, src/test/java/org/opensearch/knn/index/NmslibIT.java, src/test/java/org/opensearch/knn/index/OpenSearchIT.java, src/test/java/org/opensearch/knn/plugin/action/RestClearCacheHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestKNNWarmupHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNStatsHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNWarmupHandlerIT.java, src/test/java/org/opensearch/knn/plugin/transport/ClearCacheTransportActionTests.java, src/test/java/org/opensearch/knn/plugin/transport/KNNWarmupTransportActionTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Manually cherry-picking https://github.com/opensearch-project/k-NN/commit/eb0a3c7454cb33346f135161beb21f46f43b8457 to 2.x
=> [Backport 2.x] Update approximate_threshold to 15K documents (#2229)

qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java
update warmup rolling upgrade scenario to check only warm up is succeeded or not
=> update warmup rolling upgrade scenario

qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java, release-notes/opensearch-knn.release-notes-2.18.0.0.md, src/main/java/org/opensearch/knn/index/engine/EngineResolver.java, src/main/java/org/opensearch/knn/index/engine/KNNEngine.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java, src/test/java/org/opensearch/knn/index/KNNIndexShardTests.java, src/test/java/org/opensearch/knn/index/NmslibIT.java, src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java, src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java, src/test/java/org/opensearch/knn/index/engine/EngineResolverTests.java, src/test/java/org/opensearch/knn/index/engine/KNNEngineTests.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java, src/test/java/org/opensearch/knn/jni/JNIServiceTests.java, src/test/java/org/opensearch/knn/plugin/transport/GetModelResponseTests.java, src/test/java/org/opensearch/knn/plugin/transport/TrainingModelRequestTests.java
Since faiss supports more features than nmslib, and, we had seen data points that there are more number of vector search users are interesed in faiss, we will be updating default engine to be faiss. This will benefit users who preffered to use defaults while working with vector search.
=> Update default engine to FAISS

CHANGELOG.md, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ClearCacheIT.java, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java, qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/ClearCacheIT.java, qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
With https://github.com/opensearch-project/k-NN/pull/2229 , starting 2.18 no graphs will be built if number of document is less than 15K by using default knn index settings. Hence, select index settings based on cluster version, where starting 2.18 it will have "index.knn.advancend.approximate_threshold" set to 0, and uses old defaults for any other cluster that are before 2.18.
#1942 
=> Select index settings based on cluster version

CHANGELOG.md, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ClearCacheIT.java, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java, qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/ClearCacheIT.java, qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Backport https://github.com/opensearch-project/k-NN/commit/cbf90f5a456108fa49ffb85020f3edf7e307420e to 2.x
=> [Backport 2.x] Update bwc test to update index setting (#2236)

scripts/build.sh
Current plugin build script is not enabled with parallel compile, only using one single core to build the whole libraries.
This PR is to add an option for user to specify the number of cpus for building. 
N/A
=> Added 'j' option to use multiple cpus to build JNI library.

.github/workflows/delete_backport_branch.yml
- Fixes backport branch deletion
Resolves #2128
=> Fix backport branch deletion on merge

.github/workflows/backwards_compatibility_tests_workflow.yml
Fixing the BWC and rolling upgrade test after 2.18 release
NA
=> Fixing the BWC and rolling upgrade test after 2.18 release

CHANGELOG.md, jni/CMakeLists.txt, src/test/java/org/opensearch/knn/index/memory/NativeMemoryCacheManagerTests.java
This PR bumped up C++ version in JNI from c++11 to c++17.
https://github.com/opensearch-project/k-NN/issues/2251
=> Bump up C++ version in JNI from c++11 to c++17.

.github/workflows/CI.yml, CHANGELOG.md, build.gradle
Received following conflict
```
> Conflicts found for the following modules:
- net.bytebuddy:byte-buddy between versions 1.15.10 and 1.15.4
- org.objenesis:objenesis between versions 3.3 and 3.2
```
Fixed by upgrading to new version
```
macos-12 is deprecated, upgrade to macos-13
```
Also install libomp since it is missing in macos-13
Fixed by updating runner to use macos-13 image
=> Upgrade bytebuddy and objenesis version to match OpenSearch core and, update github ci runner for macos

CHANGELOG.md, src/main/java/org/opensearch/knn/common/FieldInfoExtractor.java, src/main/java/org/opensearch/knn/index/KNNVectorDVLeafFieldData.java, src/main/java/org/opensearch/knn/index/query/ExactSearcher.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/test/java/org/opensearch/knn/common/FieldInfoExtractorTests.java, src/test/java/org/opensearch/knn/index/query/ExactSearcherTests.java
Added null checks for fieldInfo in ExactSearcher to avoid NPE while running exact search for segments with no vector field
Ensured that in ExactSearcher class, if fieldInfo is null for a field no results are returned. This is similar to what we have to ANNSearch ref: https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/query/KNNWeight.java#L232-L236.
Resolves #2277
=> Added null checks for fieldInfo in ExactSearcher to avoid NPE while running exact search for segments with no vector field

.idea/runConfigurations/Debug_OpenSearch.xml, DEVELOPER_GUIDE.md
Small QoL change to add an IntelliJ debug config similar to what is found for opensearch core [here](https://github.com/opensearch-project/OpenSearch/blame/main/.idea/runConfigurations/Debug_OpenSearch.xml). With this if you have the `k-NN` plugin repo open in `IntelliJ` you can go to `Run > Debug` and select `Debug OpenSearch` to start the IntelliJ debugger.
=> Add simple IntelliJ debugger config

.github/workflows/CI.yml, .github/workflows/test_security.yml
Fixing the CI actions failures due to AL2 with older glibc. Ref:https://github.com/opensearch-project/opensearch-build/issues/5178
NA
=> Fixing the CI actions failures due to AL2 with older glibc

CHANGELOG.md, build.gradle
Upgrade jsonpath from 2.8.0 to 2.9.0
https://github.com/opensearch-project/k-NN/issues/2321
=> Upgrade jsonpath from 2.8.0 to 2.9.0

CHANGELOG.md, src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java, src/main/java/org/opensearch/knn/index/query/lucene/LuceneEngineKnnVectorQuery.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java, src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java, src/test/java/org/opensearch/knn/index/query/lucene/LuceneEngineKnnVectorQueryTests.java
- Optimizes Lucene kNN query execution path in case of rewrites
- The caveat here is that the rewrites would be deferred until weight creation. Any underlying changes to Lucene `rewrite` method would potentially be skipped with this execution mechanism. 
- Opensearch docker container on a M1 Macbook Pro - Image ID: [e1d9151cce32](https://hub.docker.com/layers/opensearchproject/opensearch/latest/images/sha256-e1d9151cce329062fdb68e3bd74072df9ab8b97ce5e803cb53576269cb02c0a6?context=explore)
- Single node, default config
- Load Gen: OSB vectorsearch workload running on local node hosting the docker container
- Dataset: sift-128-euclidean.hdf5 (Params: https://github.com/opensearch-project/opensearch-benchmark-workloads/blob/main/vectorsearch/params/faiss-sift-128-l2.json)
- Num docs: 1M, num …
=> Adds in lazy execution for Lucene kNN queries

CHANGELOG.md, src/main/java/org/opensearch/knn/plugin/rest/RestTrainModelHandler.java, src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java, src/test/java/org/opensearch/knn/plugin/action/RestTrainModelHandlerIT.java
Backport 2.x PR for this Pull Request: https://github.com/opensearch-project/k-NN/pull/2290
Backport 2.x PR for this Pull Request: https://github.com/opensearch-project/k-NN/pull/2290
- [N/A] New functionality includes testing.
- [N/A] New functionality has been documented.
- [N/A] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [N/A] Commits are signed per the DCO using `--signoff`.
- [N/A] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).
For more information on following Developer Certificate of Origin and …
=> [Backport 2.x] Allow method parameter override for training based indices

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNVectorSimilarityFunction.java, src/main/java/org/opensearch/knn/index/VectorDataType.java, src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java, src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/KNN9120BinaryVectorScorer.java, src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/KNN9120HnswBinaryVectorsFormat.java, src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/KNN9120PerFieldKnnVectorsFormat.java, src/main/java/org/opensearch/knn/index/codec/KNNCodecVersion.java, src/main/java/org/opensearch/knn/index/codec/params/KNNVectorsFormatParams.java, src/main/java/org/opensearch/knn/index/engine/lucene/LuceneHNSWMethod.java, src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java, src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java, src/main/resources/META-INF/services/org.apache.lucene.codecs.KnnVectorsFormat, src/test/java/org/opensearch/knn/index/VectorDataTypeTests.java, src/test/java/org/opensearch/knn/index/engine/KNNMethodContextTests.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/integ/BinaryIndexIT.java, src/test/java/org/opensearch/knn/integ/BinaryIndexInvalidMappingIT.java, src/test/java/org/opensearch/knn/integ/FilteredSearchBinaryIT.java, src/test/java/org/opensearch/knn/integ/NestedSearchBinaryIT.java
Add binary vector support for Lucene engine. For testing I parameterized `BinaryIndexIT.java` to run with both `FAISS` and `LUCENE` engines.
Resolves #1857
=> Add binary index support for Lucene engine

src/main/java/org/opensearch/knn/index/query/BaseQueryFactory.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java, src/main/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParser.java
Change the type of the `expandNested` variable from `boolean` to `Boolean`. This modification allows the neural search to pass the `expandNestedDocs` parameter as-is (`null`, `true`, or `false`), instead of converting `null` or `false` to `false` and `true` to `true`.
https://github.com/opensearch-project/neural-search/blob/main/src/main/java/org/opensearch/neuralsearch/query/NeuralQueryBuilder.java#L315
N/A
=> Switch type of expandNested from boolean to Boolean

CHANGELOG.md, qa/restart-upgrade/build.gradle, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/AbstractRestartUpgradeTestCase.java, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ModelIT.java, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/PainlessScriptScoringIT.java, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ScriptScoringIT.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/test/java/org/opensearch/knn/index/OpenSearchIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Before 2.17.0, non knn index are allowed to create knn_vector fields with model id and method params, however this is not allowed from 2.17.0. Hence, to maintain backward compatibility we will not add validation for any indices created before 2.17.0.
=> Allow validation for non knn index only after 2.17.0

qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/AbstractRestartUpgradeTestCase.java, qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/AbstractRollingUpgradeTestCase.java, qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java, src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java, src/test/java/org/opensearch/knn/index/KNNESSettingsTestIT.java, src/test/java/org/opensearch/knn/index/OpenSearchIT.java, src/test/java/org/opensearch/knn/integ/ExpandNestedDocsIT.java, src/test/java/org/opensearch/knn/integ/KNNScriptScoringIT.java, src/test/java/org/opensearch/knn/integ/PainlessScriptScoreIT.java, src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNStatsHandlerIT.java, src/test/java/org/opensearch/knn/recall/RecallTestsIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Update knn index default to always do approximate search in test cases
Resolves #2329 
=> Update knn index default to always do approximate search in test

CHANGELOG.md, jni/src/faiss_wrapper.cpp
Release query vector memory after execution
=> Release query vector memory after execution

qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/AbstractRestartUpgradeTestCase.java, qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/AbstractRollingUpgradeTestCase.java, qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java, src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java, src/test/java/org/opensearch/knn/index/KNNESSettingsTestIT.java, src/test/java/org/opensearch/knn/index/OpenSearchIT.java, src/test/java/org/opensearch/knn/integ/ExpandNestedDocsIT.java, src/test/java/org/opensearch/knn/integ/KNNScriptScoringIT.java, src/test/java/org/opensearch/knn/integ/PainlessScriptScoreIT.java, src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNStatsHandlerIT.java, src/test/java/org/opensearch/knn/recall/RecallTestsIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Backport dc369e6d73 from #2332 
=> [Backport 2.x] Update knn index default to always do approximate search in test (#2332)

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/query/nativelib/NativeEngineKnnVectorQuery.java, src/main/java/org/opensearch/knn/index/query/rescore/RescoreContext.java, src/test/java/org/opensearch/knn/index/KNNSettingsTests.java, src/test/java/org/opensearch/knn/index/query/nativelib/NativeEngineKNNVectorQueryTests.java, src/test/java/org/opensearch/knn/index/query/rescore/RescoreContextTests.java
Fix shard level rescoring disabled index setting flag(`index.knn.disk.vector.shard_level_rescoring_disabled`) to enable shard level rescoring.
=> Fix shard level rescoring disabled setting flag

CHANGELOG.md, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/LuceneEngineIT.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
This change is to resolve issue #2339.  This PR addresses it by changing some flawed logic in the rewrite function of the KNNQueryBuilder class, introduced in this PR: https://github.com/opensearch-project/k-NN/pull/1874. What was happening before was the filter for the KNNQueryBuilder object was being rewritten upon contact with first shard, and since this instance is getting shared across all shards, other shards are using the rewritten filter from the first shard. 
What this causes is, if shard id 0 has no documents and shard id 1 has 1 document, if query lands on shard 0, the filter is rewritten to return none, as shard id 0 has no documents, so the filter is adjusted. However, since we were changing the filter in the KNN query object, rather than creating a new rewritten object for …
=> Ensure consistent filter query in KNNQueryBuilder across multiple shards

CHANGELOG.md, src/main/java/org/opensearch/knn/index/query/FilterIdsSelector.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java, src/test/java/org/opensearch/knn/integ/FilteredSearchANNSearchIT.java
Backport https://github.com/opensearch-project/k-NN/commit/6f5313f70ac0c95ce777b2ec5a641b0951702e4d from https://github.com/opensearch-project/k-NN/pull/2320
Because of auto backport failure, create another pull request to manual backport this commit into 2.x
=> [Manual Backport 2.x] Add check to directly use ANN Search when filters match all docs.

CHANGELOG.md, src/main/java/org/opensearch/knn/common/KNNVectorUtil.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/DefaultIndexBuildStrategy.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/MemOptimizedNativeIndexBuildStrategy.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexWriter.java, src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java, src/test/java/org/opensearch/knn/common/KNNVectorUtilTests.java, src/test/java/org/opensearch/knn/index/codec/util/KNNCodecUtilTests.java
Added the fix for NPE happening during merges when all vector fields docs are deleted in the segments getting merged.
Where there are a lot of deleted docs and we are trying to merge the segments, we are seeing the NPE exception coming as there were not docs containing vector and we are trying to iterate over vector values.
The issue is not always reproducible hence adding an IT is not possible here. Also with the changes add in 2.18 related to threshold based graph creation, the issue is now only limited to indices created <=2.16 version of Opensearch using BDV.
Attaching a script here(author: @jmazanec15 ) that helped in reproducing the issue. 
[merge-failure-2.sh.zip](https://github.com/user-attachments/files/18304323/merge-failure-2.sh.zip)
NA
By submitting this pull request, I …
=> Added the fix for NPE happening during merges when all vector fields docs are deleted in the segments getting merged

.github/CODEOWNERS, MAINTAINERS.md
Adding @0ctopus13prime as the maintainer for the k-NN repo
NA
- ~[ ] New functionality includes testing.~
- ~[ ] New functionality has been documented.~
- ~[ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~
- ~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~
=> Adding @0ctopus13prime as the maintainer for the k-NN repo

.github/CODEOWNERS, MAINTAINERS.md
Adding @0ctopus13prime as the maintainer for the k-NN repo and during backport I realized that main and 2.x branch was not in sync for other maintainers. I fixed it during this backport.
Backport of (#2364) with conflict fixes
NA
=> Adding @0ctopus13prime as the maintainer for the k-NN repo (#2364)

CHANGELOG.md, jni/patches/faiss/0002-Enable-precomp-table-to-be-shared-ivfpq.patch
Bump Faiss commit from `1f42e81` to `0cbc2a8` to include https://github.com/facebookresearch/faiss/commit/0cbc2a885cde923d80c4bf9c9d6f4d81665f3f64 and https://github.com/facebookresearch/faiss/commit/3beb07b198a83450d6ed65c7bf9f4e36ef2a97c9
=> Bump Faiss commit from 1f42e81 to 0cbc2a8

CHANGELOG.md, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/test/java/org/opensearch/knn/index/KNNESSettingsTestIT.java
This change prevents customers to update index.knn setting after creating an index. Previously, there was a loophole to migrate a live k-nn index from hot to UW by closing the index, setting index.knn to false, opening the index, and migrating to UW. However, migrating k-nn indices to UW nodes is not supported. Thus, this PR updates index.knn to be FINAL and immutable after index creation.
Resolves #2334 
=> [Backport 2.x] Fixed a bug to prevent updating index.knn setting after index creation

src/test/java/org/opensearch/knn/index/memory/NativeMemoryCacheManagerTests.java, src/test/java/org/opensearch/knn/quantization/models/quantizationState/QuantizationStateCacheTests.java
While looking into my backport PR's [test failure](https://github.com/opensearch-project/k-NN/actions/runs/12754493243/job/35548447356) I found that the new setUp/tearDown flow conflicts with the existing NativeMemoryCacheTests class cleanup. This is what caused the odd failure. This new revision scopes down the change to the setup/teardown flow and overall keeps things more simple.
#2308 
#2390 (manual backport)
=> Fix sequence of NativeMemory/QuantizationState cache test setup/teardown

CHANGELOG.md, qa/restart-upgrade/build.gradle, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java, qa/rolling-upgrade/build.gradle, qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java
Added backward compatibility tests for Lucene engine
Signed-off-by: Sahil Buddharaju <sahilbud@amazon.com>
Co-authored-by: Sahil Buddharaju <sahilbud@amazon.com>
(cherry picked from commit f50a8f5383935435784711c124715efcff871b48)
Manual backport PR for PR (#2313)
- [N/A] New functionality includes testing.
- [N/A] New functionality has been documented.
- [N/A] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [N/A] Commits are signed per the DCO using `--signoff`.
- [N/A] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> [Backport 2.x] Add BWC tests for Lucene Engine (#2313)

CHANGELOG.md, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
Add WithFieldName implementation to KNNQueryBuilder as an extension of [PR 15705](https://github.com/opensearch-project/OpenSearch/pull/15705).
Resolves #2385 
=> Add WithFieldName implementation to KNNQueryBuilder

CHANGELOG.md, src/main/java/org/opensearch/knn/index/engine/AbstractKNNMethod.java, src/main/java/org/opensearch/knn/index/engine/KNNLibraryIndexingContext.java, src/main/java/org/opensearch/knn/index/engine/KNNLibraryIndexingContextImpl.java, src/main/java/org/opensearch/knn/index/engine/faiss/AbstractFaissMethod.java, src/main/java/org/opensearch/knn/index/engine/faiss/Faiss.java, src/main/java/org/opensearch/knn/index/engine/faiss/FaissHNSWMethod.java, src/main/java/org/opensearch/knn/index/engine/faiss/FaissIVFMethod.java, src/main/java/org/opensearch/knn/index/mapper/FlatVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldType.java, src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/NormalizeVectorTransformer.java, src/main/java/org/opensearch/knn/index/mapper/VectorTransformer.java, src/main/java/org/opensearch/knn/index/mapper/VectorTransformerFactory.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/mapper/NormalizeVectorTransformerTests.java, src/test/java/org/opensearch/knn/index/mapper/VectorTransformerFactoryTests.java, src/test/java/org/opensearch/knn/recall/RecallTestsIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
FAISS engine doesn't support cosine similarity natively. However we can use inner product to achieve the same, because, when vectors are normalized then inner product will be same as cosine similarity. Hence, before ingestion, normalize the input vector, and add it to faiss index with type as inner product, and, before search, normalize query vector if space type is cosine and engine is faiss.
Since we will be storing normalized vector in segments, we don't have to normalize whenever segments are merged. This will keep force merge time and search at competitive, provided we will face additional latency during indexing (one time where we normalize). To avoid this additional latency, customers can normalize their data set and create inner product.
This also adds support to radial search, …
=> Add cosine similarity support for faiss engine

CHANGELOG.md, src/main/java/org/opensearch/knn/index/mapper/CompressionLevel.java, src/main/java/org/opensearch/knn/index/query/nativelib/NativeEngineKnnVectorQuery.java, src/main/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParser.java, src/main/java/org/opensearch/knn/index/query/rescore/RescoreContext.java, src/test/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParserTests.java, src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java
This change adds a flag to RescoreContext for tracking if rescore has been disabled by the KNN query parameters.  This flag is set to not skip rescore by default, and is only set to skip rescore if `"rescore": false` is in the KNN query.  UTs were added for the KNNQueryBuilderParser that covers the different cases for rescore.  The below steps were also run with a debugging cluster to verify that the rescore was being run/skipped correctly based on the query parameters.  
```
curl -X PUT "localhost:9200/test_index" -H 'Content-Type: application/json' -d'
{
"settings" : {
"index": {
"knn": true
}
},
"mappings": {
"test_field1": {
"dimension": 8,
"space_type": "innerproduct",
"data_type": "float",
"mode": "on_disk",
"compression_level": "16x" …
```
=> Fix setting rescore as false in on_disk knn_vector query

qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java
- Mutes `testKNNWarmupCustomLegacyFieldMapping` after confirmation with the test author on the impact
- Re-running the test with the same seed is unable to reproduce the issue
- RCA is taking longer - unblocking the CI/merges for 2.19 in the meanwhile
Mutes #2415 
=> Mute testKNNWarmupCustomLegacyFieldMapping

CHANGELOG.md, DEVELOPER_GUIDE.md, build.gradle, qa/build.gradle
- Upgrades min JDK compatibility to JDK 21 in line with OpenSearch core
Resolves N/A
=> Upgrade min JDK compatibility to JDK 21

CHANGELOG.md, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriter.java, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriterTests.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterFlushTests.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterMergeTests.java
Manual backport #2408 to 2.x branch because of the merge conflicts in [CHANGELOG.md](https://github.com/opensearch-project/k-NN/compare/2.x...weiwang118:k-NN:backport/backport-2408-to-2.x?expand=1#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed)
=> [Manual backport 2.x]Remove DocsWithFieldSet reference from NativeEngineFieldVectorsWriter

CHANGELOG.md, src/main/java/org/opensearch/knn/common/KNNConstants.java, src/main/java/org/opensearch/knn/index/engine/KNNEngine.java, src/main/java/org/opensearch/knn/index/engine/nmslib/Nmslib.java, src/main/java/org/opensearch/knn/index/engine/nmslib/NmslibHNSWMethod.java, src/main/java/org/opensearch/knn/index/engine/nmslib/NmslibMethodResolver.java, src/main/java/org/opensearch/knn/jni/JNIService.java, src/main/java/org/opensearch/knn/jni/NmslibService.java, src/test/java/org/opensearch/knn/index/NmslibIT.java, src/test/java/org/opensearch/knn/index/engine/nmslib/NmslibMethodResolverTests.java
- Backports #2427 to `2.x`
N/A
=> [Backport 2.x] Deprecate nmslib engine

CHANGELOG.md, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldType.java, src/test/java/org/opensearch/knn/index/OpenSearchIT.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldTypeTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Backport of #2314 
Fix Sign-Off Issues/Test Failures in #2394 
This change implements valueFetcher in KNNVectorFieldType so search can support using the "fields" parameter when used with the knn_vector field type.  ITs for this change were added to OpenSearchIT after the change was tested manually.  
Resolves #1633
=> [Backport 2.x] Add support for search using the "fields" parameter with knn_vector field

CHANGELOG.md, src/main/java/org/opensearch/knn/index/mapper/CompressionLevel.java, src/main/java/org/opensearch/knn/index/query/nativelib/NativeEngineKnnVectorQuery.java, src/main/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParser.java, src/main/java/org/opensearch/knn/index/query/rescore/RescoreContext.java, src/test/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParserTests.java, src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java
Backport of #2399 
Skip Flaky BWC in #2417 
This change adds a flag to RescoreContext for tracking if rescore has been disabled by the KNN query parameters. This flag is set to not skip rescore by default, and is only set to skip rescore if `"rescore": false` is in the KNN query. UTs were added for the KNNQueryBuilderParser that covers the different cases for rescore. The below steps were also run with a debugging cluster to verify that the rescore was being run/skipped correctly based on the query parameters.
Resolves #2360  …
=> [Backport 2.x] Fix setting rescore as false in on_disk knn_vector query

CHANGELOG.md, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/FaissSQIT.java, src/main/java/org/opensearch/knn/index/engine/AbstractKNNMethod.java, src/main/java/org/opensearch/knn/index/engine/KNNLibraryIndexingContext.java, src/main/java/org/opensearch/knn/index/engine/KNNLibraryIndexingContextImpl.java, src/main/java/org/opensearch/knn/index/engine/TrainingConfigValidationInput.java, src/main/java/org/opensearch/knn/index/engine/TrainingConfigValidationOutput.java, src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportAction.java, src/main/java/org/opensearch/knn/plugin/transport/TrainingModelRequest.java, src/main/java/org/opensearch/knn/training/TrainingJob.java, src/test/java/org/opensearch/knn/index/FaissIT.java, src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java, src/test/java/org/opensearch/knn/integ/KNNScriptScoringIT.java, src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java, src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java, src/test/java/org/opensearch/knn/plugin/action/RestTrainModelHandlerIT.java, src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportActionTests.java, src/test/java/org/opensearch/knn/plugin/transport/TrainingModelRequestTests.java, src/test/java/org/opensearch/knn/recall/RecallTestsIT.java, src/test/java/org/opensearch/knn/training/TrainingJobTests.java
Previously, a consistent feedback we get around PQ and IVF is that there is limited visibility into the failure cases. Part of this is because the errors are thrown on the Faiss side and we don't return stack traces in Rest response. So, this makes it difficult to use PQ and IVF. Thus, this PR provides improved error messages by adding explicit checks for the most common errors:
[ ] For PQ, explicitly check in OpenSearch an invalid configuration where m does not divide dimension
[ ] For PQ/IVF, check the number of training points matches the minimum clustering criteria defined in faiss
[ ] If there is not enough memory, explicitly say that there is not enough memory.
Adding these 3 checks will cover 90% of the training failures that occur. 
Resolves #2268 
By submitting this pull request, …
=> Added more detailed error messages for KNN model training

CHANGELOG.md, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
- KNN indices can be created with both `model_id` and `dimension` parameters simultaneously
- This is incorrect as dimensions should come from either:
- The training index (when using `model_id`)
- OR user-defined dimensions (when using `dimension` parameter)
- Raise an exception when both `model_id` and `dimension` parameters are present in the index creation request
- Applies to all indices created on or after version 2.19
```
wumr@88665a07f65b ~ %  curl -XPUT "http://localhost:9200/my-knn-index-1" -H 'Content-Type: application/json' -d'                                                                                                                                                           
{
"settings": {
"index": {
"knn":true
}
},
"mappings": {
"my_vector1": {
"type": …
```
=> Fixing bug where mapping accepts both dimension and model-id

CHANGELOG.md, src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryEntryContext.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategy.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryCacheManagerTests.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryEntryContextTests.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategyTests.java
Fixes https://github.com/opensearch-project/k-NN/issues/2265 
Refactors the graph load into a 2 step approach detailed here - https://github.com/opensearch-project/k-NN/issues/2265#issuecomment-2518306522 
This will help to move out the opening of indexInput file outside of the synchronized block so that the graphfile can be downloaded in parallel even if the graph load and createIndexAllocation are inside synchronized block.
Resolves #2265  
=> Concurrency optimization for graph native loading update

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/test/java/org/opensearch/knn/index/RestoreSnapshotIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
This PR builds on another [PR](https://github.com/opensearch-project/OpenSearch/pull/16957). In the other PR we added a new Setting property `UnmodifiableOnRestore` to prevent settings from being modified on restore. So in this PR we're adding that new `UnmodifiableOnRestore` property to the `index.knn` setting to prevent it from being modified or removed on restore snapshot.
Resolves Issue #2334 
Also resolves Issue 17019 in Core Opensearch repository https://github.com/opensearch-project/OpenSearch/issues/17019 …
=> Add UnmodifiableOnRestore property to index.knn setting

scripts/build.sh
Properly set gcc version lock on x64 and arm64 for avx512_spr support
https://github.com/opensearch-project/opensearch-build/issues/5152
Closes https://github.com/opensearch-project/opensearch-build/issues/5226
- ~~[ ] New functionality includes testing.~~
- ~~[ ] New functionality has been documented.~~
- ~~[ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~~
- ~~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~~ …
=> Properly set gcc version lock on x64 and arm64 for avx512_spr support

CHANGELOG.md, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Resolves a bug which is running into NullPointerException when we are [computing](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/query/KNNWeight.java#L425-L427) P * Dimension <= Max_distance_computations for faiss efficient filters using byte vectors.
This is a short term solution, created a separate github issue #2447 to refactor and handle different vector datatypes without branching, to improve the code quality and avoid running into bugs like these.  
Resolves https://github.com/opensearch-project/k-NN/issues/2310 …
=> Fix Faiss byte vector efficient filter bug

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNVectorDVLeafFieldData.java, src/main/java/org/opensearch/knn/index/KNNVectorScriptDocValues.java, src/main/java/org/opensearch/knn/index/VectorDataType.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoreScript.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtil.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringUtil.java, src/main/resources/org/opensearch/knn/plugin/script/knn_allowlist.txt, src/test/java/org/opensearch/knn/index/KNNVectorDVLeafFieldDataTests.java, src/test/java/org/opensearch/knn/index/KNNVectorScriptDocValuesTests.java, src/test/java/org/opensearch/knn/index/VectorDataTypeTests.java, src/test/java/org/opensearch/knn/integ/KNNScriptScoringIT.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtilTests.java, src/test/java/org/opensearch/knn/plugin/script/KNNScoringUtilTests.java
Removes the unnecessary type conversion from byte[] to float[] and again float[] to byte for script score on KNN Binary vector using hamming space. This would help bring down the overall query latency.
For details, check https://github.com/opensearch-project/k-NN/issues/1827#issuecomment-2555581909
Resolves #1827 
- N/A API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- N/A Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).
For more information on following Developer Certificate of Origin and signing off your …
=> Binary hamming fix 2.x

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNSettings.java
Update default to 0 to always build graph as default behavior
We performed following experiment to analyze the increase in latency (p90) 
Data set: Cohere
Vector Count: 10M
Dimension: 768
Force merge to 1 segment: No
Concurrent Segment Enabled: yes
No of runs per limit: 5
Comparison
P90 Metrics (ms) for Search
|Metric	|LIMIT = 0	|LIMIT = 5K	|LIMIT = 10K	|LIMIT = 15K	| 
|---	|---	|---	|---	|---	|
|MIN	|21.56	|22.8	|25.4	|27.1	|
|MAX	|22.5	|23.4	|26.2	|28.1	|
|AVG	|21.56	|22.94	|25.6	|27.78	|
Indexing 
|LIMIT	|Total Indexing Time (secs)	| 
|---	|---	|
|0	| 2023	|
|5K	| 1306	|
|10K	| 1210	|
|15K	| 1016	|
In order to avoid any regression from vector search, we are falling back to 0 as limit. However, users can configure this if they want to improve indexing performance by considering how that …
=> Update default to 0 to always build graph as default behavior

build.gradle, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
A prior PR https://github.com/opensearch-project/k-NN/pull/2445 was breaking the release build of 2.19 due to https://github.com/opensearch-project/k-NN/issues/2458. This PR fixes the issue by updating the `path.repo` used to register snapshot repositories in integ tests
Resolves #2458 
=> Add path.repo for registering snapshot repository in integ tests

src/main/java/org/opensearch/knn/index/query/KNNQuery.java, src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java
Adds debug logs with timing information for various knn query components
Cluster setting changed in local
```
curl --request PUT \
--url http://localhost:9200/_cluster/settings \
--header 'Content-Type: application/json' \
--data '{
"persistent" : {
"logger.org.opensearch.knn.index.query" : "DEBUG"
}
}'
```
Output
```
q.KNNQueryFactory] [integTest-0] Creating custom k-NN query for index:target_index_faiss, field:location, k:3, filterQuery:+IndexOrDocValuesQuery(indexQuery=rating:[8 TO 10], dvQuery=rating:[8 TO 10]), efSearch:null
[2025-01-29T11:20:21,929][DEBUG][o.o.k.i.q.KNNQuery       ] [integTest-0] Creating filter weight for field [location] took [603583] nanos
[2025-01-29T11:20:21,930][DEBUG][o.o.k.i.q.KNNWeight      ] [integTest-0] Creating filter bitset for field [location] took …
```
=> Adds debug logs for KNNQuery and KNNWeight

CHANGELOG.md, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
Manually raised PR to backport #2410 to 2.x branch due to conflicts
=> Fixing bug where mapping accepts both dimension and model-id (#2410)

src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/DerivedSourceStoredFieldsReader.java, src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/DerivedSourceStoredFieldsWriter.java
I was running the DerivedSourceIts for the derived source feature in a multi-node setting with replicas and was noticing that getMergeInstance was being called outside of merge when reindex was happening. I couldnt figure out the stack trace, but decided to revert back to wrapping the readers during merge. This fixed it.
It might be getting called in the SequentialStoredFieldsReader in this hack: 
* https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/fetch/FetchPhase.java#L154-L157
* https://github.com/opensearch-project/OpenSearch/blob/2847695ad1fcc04c88b96c8bab0bfdf694fa05dc/server/src/main/java/org/opensearch/common/lucene/index/SequentialStoredFieldsLeafReader.java#L71
By …
=> Switch away from getMergeInstance for derived source

CHANGELOG.md, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java
- Adds a version check for field name validation 
- This is to prevent issues during version upgrades for users moving from versions <2.17.0 to a higher version - essentially preventing upgrade failures and rendering the check for indexes created on or after 2.17.0
=> Add version check for full field name validation

.github/CODEOWNERS, MAINTAINERS.md
Adding Vikasht34 as the maintainer in k-NN repo
NA
=> Adding Vikasht34 as maintainer for k-NN repo

.github/CODEOWNERS, MAINTAINERS.md
Adding Vikasht34 as maintainer for k-NN repo (#2482)
Backport of PR: #2482
NA
=> Adding Vikasht34 as maintainer for k-NN repo (#2482)

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/KNN9120PerFieldKnnVectorsFormat.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexWriter.java, src/main/java/org/opensearch/knn/training/TrainingJob.java, src/test/java/org/opensearch/knn/index/KNNSettingsTests.java
Enabled concurrent graph creation for Lucene engine with index thread qty settings
Resolves https://github.com/opensearch-project/k-NN/issues/1581
=> Enabled concurrent graph creation for Lucene engine with index thread qty settings

CHANGELOG.md, release-notes/opensearch-knn.release-notes-2.19.0.0.md
- Adds release notes for 2.19.0
N/A
=> Add release notes for 2.19.0

src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/DerivedSourceStoredFieldsFormat.java, src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/DerivedSourceStoredFieldsReader.java, src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/DerivedSourceStoredFieldsWriter.java, src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/KNN9120Codec.java, src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceReaders.java, src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceReadersSupplier.java, src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorInjector.java, src/main/java/org/opensearch/knn/index/codec/derivedsource/ParentChildHelper.java, src/main/java/org/opensearch/knn/index/vectorvalues/VectorValueExtractorStrategy.java, src/test/java/org/opensearch/knn/index/codec/KNN9120Codec/DerivedSourceStoredFieldsWriterTests.java, src/test/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceStoredFieldVisitorTests.java, src/test/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorInjectorTests.java, src/test/java/org/opensearch/knn/index/codec/derivedsource/ParentChildHelperTests.java, src/test/java/org/opensearch/knn/index/codec/derivedsource/PerFieldDerivedVectorInjectorFactoryTests.java, src/test/java/org/opensearch/knn/index/codec/derivedsource/RootPerFieldDerivedVectorInjectorTests.java
Fixes a bug in the derived source writer where we are reading the entire bytes array from the bytes ref instead of just the offset+length.
This was the error:
```
[2025-02-04T23:43:54,004][WARN ][o.o.i.e.Engine           ] [test] [target_index][0] failed engine [already closed by tragic event on the index writer]
org.opensearch.core.compress.NotXContentException: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes
at org.opensearch.core.compress.CompressorRegistry.compressor(CompressorRegistry.java:75) ~[opensearch-core-2.19.0.jar:2.19.0]
at org.opensearch.common.xcontent.XContentHelper.convertToMap(XContentHelper.java:166) ~[opensearch-2.19.0.jar:2.19.0]
at org.opensearch.knn.index.codec.KNN9120Codec.DerivedSourceStoredFieldsWriter.writeField(Derive …
```
=> Fix bytes offset bug and duplicate readers and add uTs for derived source

.github/workflows/maven-publish.yml
Changes to publish the jar of knn plugin to maven.
Resolves #1351 
Since it is a call to an existing gradle task. I couldn't exactly test it.
But I'm to run the equivalent task `publishNebulaPublicationToMavenLocal` and use the locally published jar from my another project.
=> Changes to publish jar to maven

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/KNN9120PerFieldKnnVectorsFormat.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexWriter.java, src/main/java/org/opensearch/knn/training/TrainingJob.java, src/test/java/org/opensearch/knn/index/KNNSettingsTests.java
Backport of https://github.com/opensearch-project/k-NN/pull/2480
=> [Backport main] Enabled concurrent graph creation for Lucene engine with index thread qty settings (#2480)

release-notes/opensearch-knn.release-notes-2.19.0.0.md, src/main/java/org/opensearch/knn/index/engine/EngineResolver.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/plugin/transport/TrainingModelRequest.java, src/test/java/org/opensearch/knn/index/engine/EngineResolverTests.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
We changed default engine from NMSLIB to FAISS on 2.18. Hence, for use case where mode is not configured and compression is 1x or undefined we default to nmslib since cosine similarity was not supported. From 2.19, we added support to cosine, so, we can now change it to faiss for no compression or 1x compression to align with our strategy on deprecating nmslib in future releases.
=> Update engine for version 2.19 or above

.github/workflows/CI.yml, .github/workflows/test_security.yml, build.gradle, qa/restart-upgrade/build.gradle, qa/rolling-upgrade/build.gradle, scripts/build.sh
Update build.gradle and build.sh to separate x64 linux nmslib build with different gcc versions
Closes https://github.com/opensearch-project/k-NN/issues/2484
- ~~[ ] New functionality includes testing.~~
- ~~[ ] New functionality has been documented.~~
- ~~[ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~~
- ~~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~~ …
=> Update build.gradle and build.sh to separate x64 linux nmslib build with different gcc versions

CHANGELOG.md, build.gradle, jni/cmake/init-faiss.cmake, src/main/java/org/opensearch/knn/index/KNNCircuitBreaker.java, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/indices/ModelDao.java, src/main/java/org/opensearch/knn/plugin/KNNPlugin.java, src/main/java/org/opensearch/knn/plugin/rest/RestClearCacheHandler.java, src/main/java/org/opensearch/knn/plugin/rest/RestDeleteModelHandler.java, src/main/java/org/opensearch/knn/plugin/rest/RestGetModelHandler.java, src/main/java/org/opensearch/knn/plugin/rest/RestKNNStatsHandler.java, src/main/java/org/opensearch/knn/plugin/rest/RestKNNWarmupHandler.java, src/main/java/org/opensearch/knn/plugin/rest/RestSearchModelHandler.java, src/main/java/org/opensearch/knn/plugin/rest/RestTrainModelHandler.java, src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportAction.java, src/main/java/org/opensearch/knn/training/VectorReader.java, src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportActionTests.java, src/test/java/org/opensearch/knn/quantization/models/quantizationState/QuantizationStateCacheTests.java
Addresses a bug and house cleaning during build.
1. Cmake has invalid syntax in if condition causing this message:
```
CMake Error at cmake/init-faiss.cmake:114 (if):
if given arguments:
"AND" "NOT" "" "STREQUAL" ""
Unknown arguments specified
Call Stack (most recent call first):
CMakeLists.txt:107 (include)
```
2. Move all build artifacts created into a build directory following conventional build standards. Currently there are multiple temporary artifacts generated by cmake which are scattered under `jni` directory.
- [ x] New functionality includes testing.
- [x ] New functionality has been documented.
- [x ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/ma …
=> fix broken build flag, move build to one directory

.gitignore, CHANGELOG.md, build.gradle, jni/cmake/macros.cmake, qa/restart-upgrade/build.gradle, qa/rolling-upgrade/build.gradle
More build tidiness changes:
1. Clean JNI artifacts with `./gradlew clean` to make local builds idempotent and more reliable.
2. Places `release` under `binary_dir` instead of under `source_dir` this makes all artifacts only show up under single directory without the need to hunt them down in multiple places when cleaning up.
3. Switch to cmake instead of make when building native JNI for improved readability
Resolves https://github.com/opensearch-project/k-NN/issues/2515
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-o …
=> Clean JNI artifacts with ./gradlew clean

scripts/build.sh
Fix main knnlib dir in build script based on #2442
```
+ cp -v './jni/release/libopensearchknn*' /home/ci-runner/k-NN2/build/distributions/lib
cp: cannot stat './jni/release/libopensearchknn*': No such file or directory
```
https://build.ci.opensearch.org/job/distribution-build-opensearch/10808/
- ~~[ ] New functionality includes testing.~~
- ~~[ ] New functionality has been documented.~~
- ~~[ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~~
- ~~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~~
For more …
=> Fix main knnlib dir in build script based on #2442

CHANGELOG.md, src/main/java/org/opensearch/knn/index/codec/derivedsource/AbstractPerFieldDerivedVectorInjector.java, src/main/java/org/opensearch/knn/index/codec/derivedsource/NestedPerFieldDerivedVectorInjector.java, src/main/java/org/opensearch/knn/index/codec/derivedsource/RootPerFieldDerivedVectorInjector.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java, src/test/java/org/opensearch/knn/integ/DerivedSourceIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java, src/testFixtures/java/org/opensearch/knn/TestUtils.java
For binary and byte vectors, for derived source, we were not formatting them before adding them back to the source. Thus, they were binary strings in the source. This change fixes this formatting to format them as ints before adding back.
=> Fix derived source for binary and byte vectors

CHANGELOG.md, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/test/java/org/opensearch/knn/index/KNNMapperSearcherIT.java
Fix the put mapping issue for already created index with flat mapper
When put mappings is called for an already created index, the mappings are merged from the old index. During that merge the buildContext https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java#L243 doesn't have the index version. 
The failure happens only when index.knn is false because checking of the index version is in `&&` hence when `index.knn` is true buildContext is not getting hit.
Resolves https://github.com/opensearch-project/k-NN/issues/2540
For more information on following Developer Certificate of Origin and signing off your …
=> Fix the put mapping issue for already created index with flat mapper

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/test/java/org/opensearch/knn/index/RestoreSnapshotIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
This PR builds on another PR https://github.com/opensearch-project/OpenSearch/pull/16957. In the other PR we added a new Setting property UnmodifiableOnRestore to prevent settings from being modified on restore. So in this PR we're adding that new UnmodifiableOnRestore property to the index.knn setting to prevent it from being modified or removed on restore snapshot.
Resolves #2334 
Also resolves Issue 17019 in Core Opensearch repository https://github.com/opensearch-project/OpenSearch/issues/17019
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING …
=> [Backport Main] Add UnmodifiableOnRestore property to index.knn setting

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexBuildStrategyFactory.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexWriter.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/DefaultVectorRepositoryAccessor.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/DocIdInputStream.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildStrategy.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/VectorRepositoryAccessor.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/VectorValuesInputStream.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/package-info.java, src/test/java/org/opensearch/knn/index/codec/nativeindex/remote/DefaultVectorRepositoryAccessorTests.java, src/test/java/org/opensearch/knn/index/codec/nativeindex/remote/KnnVectorValuesInputStreamTests.java, src/test/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildStrategyTests.java, src/test/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildTests.java, src/test/java/org/opensearch/knn/index/vectorvalues/TestVectorValues.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
This PR includes implementation + testing for upload vector and doc id blobs to a remote repository with the `RemoteIndexBuildStrategy`. This PR also includes a new `knn.remote_index_build.size_threshold` setting to control the size threshold above which the remote index build service will be used.
---
For a detailed explanation on the vector uploads, please see the `Parallel Blob Upload` section from the LLD: https://github.com/opensearch-project/k-NN/issues/2465
At a high level the flow is as follows (Currently only repository-s3 supports parallel blob uploads via this interface, so I will reference S3 directly in the following):
1. KNN Plugin provides an InputStream supplier to asyncBlobUpload (See: `RemoteIndexBuildStrategy#getTransferPartStreamSupplier`)
2. Repository S3 determines …
=> [Remote Vector Index Build] Add vector data upload implementation to RemoteIndexBuildStrategy

src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
(cherry picked from commit 02fdd70f1a10e9faa290c5a92d2c2dc5db3fe31e)
=> [Backport main] Fix Faiss byte vector efficient filter bug (#2448)

CHANGELOG.md, src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryEntryContext.java, src/main/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategy.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryCacheManagerTests.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryEntryContextTests.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategyTests.java
Fixes https://github.com/opensearch-project/k-NN/issues/2265 
Refactors the graph load into a 2 step approach detailed here - https://github.com/opensearch-project/k-NN/issues/2265#issuecomment-2518306522 
This will help to move out the opening of indexInput file outside of the synchronized block so that the graphfile can be downloaded in parallel even if the graph load and createIndexAllocation are inside synchronized block.
Resolves #2265 
=> Concurrency optimization for native graph loading

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/engine/SpaceTypeResolver.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java, src/main/java/org/opensearch/knn/index/query/KNNQuery.java, src/main/java/org/opensearch/knn/jni/FaissService.java, src/main/java/org/opensearch/knn/jni/JNIService.java, src/main/java/org/opensearch/knn/training/FloatTrainingDataConsumer.java, src/test/java/org/opensearch/knn/index/KNNCreateIndexFromModelTests.java, src/test/java/org/opensearch/knn/index/KNNESSettingsTestIT.java, src/test/java/org/opensearch/knn/index/NmslibIT.java, src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java, src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java, src/test/java/org/opensearch/knn/index/engine/SpaceTypeResolverTests.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryAllocationTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java, src/test/java/org/opensearch/knn/jni/JNIServiceTests.java, src/test/java/org/opensearch/knn/training/TrainingJobTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
As part of OpenSearch 3.0.0 release , we are removing some of the already deprecated feature from KNN Plugin , this will be breaking change from KNN. Here is the list of changes.
1. Remove Knn Plugin enabled setting 
2. Remove ef construction from Index Seeting.
3. Remove m from Index Setting.
4. Remove space type from index setting
5. Remove deprecated apis from JNI Layer.
=> 3.0.0 Breaking Changes For KNN

src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/DefaultVectorRepositoryAccessor.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/DocIdInputStream.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/VectorValuesInputStream.java, src/test/java/org/opensearch/knn/index/codec/nativeindex/remote/DefaultVectorRepositoryAccessorTests.java, src/test/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildTests.java
In this PR we are making the decision to leave integrity checking up to the individual vendor SDK and repository implementations. For example, in https://github.com/opensearch-project/OpenSearch/pull/17396 the aws s3 SDK was bumped to automatically support integrity checking.
We are making the decision to leave integrity checking to the vendor implementation in all cases. This section will give a brief overview of how this is done for S3. 
When using the aws java sdk and repository-s3, during object upload a CRC32 checksum is automatically computed by the SDK, and validated + persisted to the object store. During object download, if a checksum is present in the object store, the SDK will automatically validate the downloaded object against the checksum found in the object store.
As a …
=> Remove integrity checking TODO and leave up to the vendor implementation

src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReader.java, src/main/java/org/opensearch/knn/index/engine/KNNEngine.java, src/main/java/org/opensearch/knn/index/engine/KNNLibrary.java, src/main/java/org/opensearch/knn/index/engine/faiss/Faiss.java, src/main/java/org/opensearch/knn/memoryoptsearch/VectorSearcher.java, src/main/java/org/opensearch/knn/memoryoptsearch/VectorSearcherFactory.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissMemoryOptimizedSearcher.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissMemoryOptimizedSearcherFactory.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReaderTests.java, src/test/java/org/opensearch/knn/memoryoptsearch/FaissEngineTests.java
[1/11] This is the first PR to establish the building blocks for memory optimized search.
At the moment, FAISS is the only engine that supports memory optimized search where loading vectors in demand fashion.
Note that this will be merged into the feature branch first. Unit tests + IT tests will be covered in PR-9 and PR-10.
=> [LuceneOnFaiss - Part1] Added building blocks for memory optimized search.

build.gradle
json-path 2.9.0 has been flagged in https://github.com/advisories/GHSA-pq2g-wx69-c263. They do not have fix yet, and their devs suggest to switch to json-smart https://github.com/json-path/JsonPath/issues/1031.
We need to have this library for ml-commons, follow their strategy: keep json-path, but excluding json-smart part of it, and include json-mart of the proper version separately.
Picking up version of json-smart from the OS core, they added in the recent PR https://github.com/opensearch-project/OpenSearch/pull/17569 …
=> Use latest json-smart lib to fix  CVE-2024-57699

src/test/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildStrategyTests.java
`RemoteIndexBuildStrategy.shouldBuildIndexRemotely` [makes a check](https://github.com/opensearch-project/k-NN/blob/b77b6b6d1ccab63f0b01f4891cf30d7e45b4acf0/src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildStrategy.java#L86) comparing the size of the vector blob to the minimum remote build threshold. If the size threshold is not met, the remote build will not be triggered.
Before this PR's change, a random `BYTE_SIZE` was being generated in the range `BYTE_SIZE - 1, BYTE_SIZE * 2` to trigger the happy path. But, since the lower bound is inclusive, it was possible the random `BYTE_SIZE` was actually below the threshold (at exactly `BYTE_SIZE - 1`). With this change, the minimum random size will be exactly `BYTE_SIZE` as to always meet the threshold.
I …
=> Fix flaky test in RemoteIndexBuildStrategyTests.java 

CHANGELOG.md, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/test/java/org/opensearch/knn/index/OpenSearchIT.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
Following code prevents the state of a NullPointerException from occurring while doing PUT mappings. The expected behavior is to block the update by telling the user that we cannot update the mapping.
Resolves #2556
- [ ✔️ ] New functionality includes testing.
- [ ✔️ ] New functionality has been documented.
- [ ✔️ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [ ✔️ ] Commits are signed per the DCO using `--signoff`.
- [ ✔️ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose). …
=> Fixing bug to prevent NullPointerException while doing PUT mappings

src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndexFloatFlat.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/IndexTypeToFaissIndexMapping.java, src/test/java/org/opensearch/knn/memoryoptsearch/FaissIndexFloatFlatTests.java
This PR covers flat float vector storage in FAISS.
It will be used in HNSW search algorithm to load vectors in similarity scorer.
=> [LuceneOnFaiss - Part4] Added FAISS float flat index.

src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexBuildStrategyFactory.java, src/main/java/org/opensearch/knn/index/engine/KNNEngine.java, src/main/java/org/opensearch/knn/index/engine/KNNLibrary.java, src/main/java/org/opensearch/knn/index/engine/faiss/Faiss.java, src/main/java/org/opensearch/knn/index/engine/faiss/FaissHNSWMethod.java, src/test/java/org/opensearch/knn/index/engine/KNNEngineTests.java
Check for supported `VectorDataType` in `NativeIndexBuildStrategy`
~- [ ] New functionality has been documented.~
~- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~
~- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~
=> Add VectorDataType check to NativeIndexBuildStrategy

src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReader.java, src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java, src/main/java/org/opensearch/knn/jni/JNIService.java, src/main/java/org/opensearch/knn/memoryoptsearch/VectorSearcherFactory.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissHnswGraph.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndexScalarQuantizedFlat.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissMemoryOptimizedSearcher.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissMemoryOptimizedSearcherFactory.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormatTests.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReaderTests.java, src/test/java/org/opensearch/knn/index/codec/nativeindex/MemoryOptimizedSearchIndexingSupport.java, src/test/java/org/opensearch/knn/memoryoptsearch/FaissEngineTests.java, src/test/java/org/opensearch/knn/memoryoptsearch/FaissHnswGraphTests.java, src/test/java/org/opensearch/knn/memoryoptsearch/FaissMemoryOptimizedSearcherTests.java
This PR enables memory optimized search in VectorReader for FAISS HNSW graph index.
Internally, it will delegate Lucene's HNSW graph searcher to perform vector search on FAISS index.
NOTE : Will add unit tests shortly.
=> [LuceneOnFaiss Part-7] Enable memory optimized searching in VectorReader for FAISS engine.

src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormat.java, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReader.java, src/main/java/org/opensearch/knn/index/engine/MemoryOptimizedSearchSupportSpec.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldType.java, src/main/java/org/opensearch/knn/index/query/BaseQueryFactory.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReaderTests.java, src/test/java/org/opensearch/knn/index/codec/nativeindex/MemoryOptimizedSearchFlagInFormatTests.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java, src/test/java/org/opensearch/knn/memoryoptsearch/MemoryOptimizedSearchSupportSpecTests.java
This PR adds `index.knn.memory_optimized_search` index settings.
Overall, this brings two major changes listed below along with the new setting definition:
1. In codec level, it relies on MapperService to retrieve `index.knn.memory_optimized_search` bool flag. Which then be used to determine whether to initialize partial loading on KNN fields. 
But this is not always working, during recovery MapperService can be null, therefore adding lazy-loading logic in both constructor and search method. For 99%, it will be loaded in the constructor, so it won't affect search p99 latency as by the time the search method is called, MemoryOptimizedSearch should be loaded already.
2. Branching in KNNQueryBuilder
This PR will make each knn field type decide whether memory-optimized-search is supported or …
=> [LuceneOnFaiss Part-8] Added `index.knn.memory_optimized_search` index setting.

src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissHNSW.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissHnswGraph.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIdMapIndex.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/MonotonicIntegerSequenceEncoder.java, src/test/java/org/opensearch/knn/memoryoptsearch/FaissHNSWTests.java, src/test/java/org/opensearch/knn/memoryoptsearch/FaissIdMapIndexTests.java, src/test/java/org/opensearch/knn/memoryoptsearch/MonotonicIntegerSequenceEncoderTests.java
This PR introduces a monotonic integer sequence encoding scheme for doc IDs in IdMapIndex and offsets in FAISS HNSW.
Previously, both were stored as long[], consuming O(N) memory where N is the total number of vectors. For example, with a 10M dataset, they occupied 228MB (76MB + 152MB). Using monotonic encoding, this can be reduced to a few hundred KB. Lucene already uses this encoding scheme [Link](https://github.com/apache/lucene/blob/9472dcad0ebfadf2ae6460793682635880ac48eb/lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99HnswVectorsReader.java#L402C13-L402C17)
The key difference is that Lucene applies encoding during segment creation, whereas we do it at load time. However, encoding is extremely fast, on my local setup it takes about 3.2 seconds for 100M integers.
A …
=> [LuceneOnFaiss] Apply monotonic increasing integer encoding to FAISS HNSW and IdMapIndex.

src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissHNSWIndex.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndexScalarQuantizedFlat.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/reconstruct/Faiss8BitsDirectSignedReconstructor.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/reconstruct/FaissFP16Reconstructor.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/reconstruct/FaissQuantizedValueReconstructor.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/reconstruct/FaissQuantizedValueReconstructorFactory.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/reconstruct/FaissQuantizerType.java, src/test/java/org/opensearch/knn/memoryoptsearch/FaissByteIndexTests.java, src/test/java/org/opensearch/knn/memoryoptsearch/FaissMemoryOptimizedSearcherTests.java, src/test/java/org/opensearch/knn/memoryoptsearch/QuantizedValueReconstructorTests.java
In this PR, it added decoding algorithm to decode byte quantization and FP16.
Likewise currently how FAISS is doing at the moment, it will reads bytes then restore them into float[].
This logic for each quantizer type is encapsulated `FaissQuantizedValueReconstructor`.
=> [LuceneOnFaiss Part-6] Adding byte index, FP16 index decoding.

CHANGELOG.md, jni/cmake/init-nmslib.cmake, jni/patches/nmslib/0006-Bump-cmake-version-nmslib.patch
Upgrade minimum required CMake version in NMSLib to 3.5 due to Ubuntu runner getting bumped to Cmake 4: https://github.com/actions/runner-images/commit/83ff3a65f622b420db5f9fa3643db34b327cdf5f which does not support versions before 3.5. 
N/A
~- [ ] New functionality includes testing.~
~- [ ] New functionality has been documented.~
~- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~
~- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~
For more information on following Developer Certificate of Origin and …
=> Bump cmake version

src/main/java/org/opensearch/knn/index/DerivedKnnByteVectorField.java, src/main/java/org/opensearch/knn/index/DerivedKnnFloatVectorField.java, src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsFormat.java, src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceIndexOperationListener.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java, src/main/java/org/opensearch/knn/index/util/IndexUtil.java, src/test/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceIndexOperationListenerTests.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/integ/DerivedSourceIT.java, src/testFixtures/java/org/opensearch/knn/DerivedSourceTestCase.java, src/testFixtures/java/org/opensearch/knn/DerivedSourceUtils.java
Adds checks to block derived fields under certain cases. This will prevent source derivation from happening. To accomplish this, I had to create a light wrapper around KnnFloatVectorField and KnnByteVectorField so that the index operation listener can get some of this information from the parsed document.
The checks that are being added are:
1. Is the source enabled
2. Is there a composite index present
3. Is derived source setting enabled
4. If a vector has the copyTo variable (this is broken right now in knn but added for safety in future - see #2636 )
5. Node to node segrep - there are some issues around translog where this will not work and so needs to be blocked.
Resolves #2377 
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> Add checks to block derived source feature

qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/DerivedSourceBWCRestartIT.java, src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceLuceneHelper.java, src/test/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceLuceneHelperTests.java, src/test/java/org/opensearch/knn/integ/DerivedSourceIT.java, src/testFixtures/java/org/opensearch/knn/DerivedSourceTestCase.java, src/testFixtures/java/org/opensearch/knn/DerivedSourceUtils.java
Optimization for derived source. The only changed source file is `src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceLuceneHelper.java`. The rest are tests. 
For nested documents, in order to initialize the iterators properly, we need to find the first child document of the parent document. To do this, we can scan the numeric doc values for the _primary_term field, which is only present for parent documents. In the code now, we start this scan at 0. This requires reading all of the numeric doc values. This code introduces an optimization where instead of starting at 0, it first tries 150 documents before the parentdoc, then 1500, then 6000, then tries from 0.
Along with this, I updated some testing logic.
By …
=> Optimize first child lookup for nested docs

build.gradle, src/test/java/org/opensearch/knn/integ/DerivedSourceIT.java, src/testFixtures/java/org/opensearch/knn/DerivedSourceTestCase.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Enhances derived source integ tests to have a bit more complex mappings. This is probably overkill, but good to be sure. With this, it also reduces the number of docs/max dimension to prevent tests from running too long. 
Also, it adds a snapshot/restore test to ensure after snapshot, everything works as expected.
=> Enhance derived source integ tests

build.gradle, remote-index-build-client/build.gradle, src/main/java/org/opensearch/knn/jni/PlatformUtils.java, src/main/java/org/opensearch/knn/plugin/KNNPlugin.java, src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java, src/test/java/org/opensearch/knn/jni/PlatformUtilTests.java
Fix build due to phasing off SecurityManager usage in favor of Java Agent
See please https://github.com/opensearch-project/k-NN/actions/runs/14364233941/job/40358433955?pr=2652
=> Fix build due to phasing off SecurityManager usage in favor of Java Agent

src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsFormat.java, src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsReader.java, src/main/java/org/opensearch/knn/index/codec/backward_codecs/KNN9120Codec/DerivedSourceVectorInjector.java, src/main/java/org/opensearch/knn/index/codec/backward_codecs/KNN9120Codec/KNN9120DerivedSourceReaders.java, src/main/java/org/opensearch/knn/index/codec/backward_codecs/KNN9120Codec/KNN9120DerivedSourceStoredFieldsFormat.java, src/main/java/org/opensearch/knn/index/codec/backward_codecs/KNN9120Codec/KNN9120DerivedSourceStoredFieldsReader.java, src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceReaders.java, src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java, src/test/java/org/opensearch/knn/index/codec/backward_codecs/KNN9120Codec/DerivedSourceVectorInjectorTests.java, src/test/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceReadersTests.java
Fixes a bug that was already fixed in #2494 but was then reverted by accident in a refactor. It makes it so that instead of opening up readers for each transform request, it opens up once per reader.
This was caught in a 100M perf test I was running. Im thinking we should maybe upgrade our nightlies to use this to prevent in future.
=> Prevent derived source from open reader per transform

release-notes/opensearch-knn.release-notes-3.0.0.0-beta1.md, src/main/java/org/opensearch/knn/common/KNNConstants.java, src/main/java/org/opensearch/knn/index/SpaceType.java, src/main/java/org/opensearch/knn/index/query/KNNQuery.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/main/java/org/opensearch/knn/index/query/common/DocAndScoreQuery.java, src/main/java/org/opensearch/knn/index/query/common/QueryUtils.java, src/main/java/org/opensearch/knn/index/query/explain/KnnExplanation.java, src/main/java/org/opensearch/knn/index/query/nativelib/NativeEngineKnnVectorQuery.java, src/test/java/org/opensearch/knn/index/ExplainIT.java, src/test/java/org/opensearch/knn/index/query/ExplainTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTestCase.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java, src/test/java/org/opensearch/knn/index/query/common/DocAndScoreQueryTests.java, src/test/java/org/opensearch/knn/index/query/nativelib/NativeEngineKNNVectorQueryTests.java
Add support for explain for Exact/ANN/Radial/Disk/Filtering k-nn search. Score calculation explanation is currently added only for ANN search.
Proposal for explain is given here: https://github.com/opensearch-project/k-NN/issues/875#issuecomment-2611349466
Resolves #875
=> Explain API for Exact/ANN/Radial/Disk based KNN search on Faiss

src/main/java/org/opensearch/knn/index/mapper/EngineFieldMapper.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
When memory optimized search is enabled, if a filtering is provided in a query, it will evaluate whether to fallback to exact search to preserve high recall.
During the exact search, Lucene will load FloatVectorValues and ByteVectorValues from configured VectorReader, which is NativeEngines990KnnVectorsReader at the moment - [Code](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReader.java#L107)
Currently, regardless of the space type in mapping, the default space type will be saved in .vec file - [Code](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java#L180)
We should change it to find the best matching similarity function with …
=> [Bug fix LuceneOnFaiss] Having field info to have a corresponding Lucene vector similarity function.

qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/DerivedSourceBWCRestartIT.java, src/main/java/org/opensearch/knn/common/FieldInfoExtractor.java, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/plugin/KNNPlugin.java, src/test/java/org/opensearch/knn/integ/DerivedSourceIT.java, src/testFixtures/java/org/opensearch/knn/DerivedSourceTestCase.java
Enables derived source by default. Benchmarks in https://benchmarks.opensearch.org show significant improvements, so we should turn on by default. 
Lucene latencies:
Faiss store size:
In particular, this change will help configurations that leverage disk in some component.
=> Switch derived to default and fix bug in byte derived

CHANGELOG.md, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/KNN990QuantizationStateReader.java, src/main/java/org/opensearch/knn/quantization/models/quantizationState/QuantizationStateCache.java, src/main/java/org/opensearch/knn/quantization/models/quantizationState/QuantizationStateCacheManager.java, src/test/java/org/opensearch/knn/quantization/models/quantizationState/QuantizationStateCacheManagerTests.java, src/test/java/org/opensearch/knn/quantization/models/quantizationState/QuantizationStateCacheTests.java
This PR fixes two bugs:
1. Scale issue : We are using KB as the limit as oppose to use bytes. As a result, even the value occupies few bytes, it is interpreted as KB leading to frequent cache eviction.
2. Non thread safe : Since Check-then-update logic is not properly guarded, leading to multiple threads are loading the meta info from the disk and update the value, which is unnecessary though.
https://github.com/opensearch-project/k-NN/issues/2665
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CON …
=> Fix quantization cache bugs.

build.gradle
Fix `build.gradle` script not to use `true` as a default AVX settings.
Currently, we have three AVX settings as listed below:
- AVX2
- AVX512
- AVX512-SPR
The issue is, regardless of whether if Linux environment supports the settings, since we are assigning the variable with `System.getProperty("...", "true")` which return "true" when it is not set, `gradle` always passes `-DAVX512_SPR_ENABLED=true` even for an instance not having the Intel SPR process installed.
This always force `make` to link `avx512-spr` shared library due to the `if-else` evaluation order in cmake file - [Code](https://github.com/opensearch-project/k-NN/blob/main/jni/cmake/init-faiss.cmake#L125)
It first evaluates whether OS is Windows, then check whether AVX512_SPR_ENABLED is set which is always true.
This is only …
=> Fix build.gradle AVX settings to not to use default value.

CHANGELOG.md, src/main/java/org/opensearch/knn/index/mapper/CompressionLevel.java, src/test/java/org/opensearch/knn/index/mapper/CompressionLevelTests.java, src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
If explicit rescoring was not getting passed in the k-NN query for disk based vector search, the rescoring was not happening when dim > 1000.
In https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/mapper/CompressionLevel.java#L29-L31, we set default rescore enabled to false for 32x, 16x, and 8x. However, this default only gets used if the dimension is greater than 1000 (https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/mapper/CompressionLevel.java#L118).
Thanks @jmazanec15 for doing the deep-dive.
I did a small benchmarks with 1024D dataset, and after the bug fix I can see the recall jumps from 0.66 to 0.92 for recall@k.
Without fix:
```
|                                                  Mean recall@k | …
```
=> Fix enable rescoring when dimensions > 1000

CHANGELOG.md, src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/DefaultVectorRepositoryAccessor.java, src/main/java/org/opensearch/knn/index/store/IndexOutputWithBuffer.java
Adds tuned upload and download buffer sizes from the benchmarking done in #2595, pasted below for convenience:
The following are the results of benchmarking the repository upload and download buffer size settings. The benchmarking was carried out on an `r6g.4xlarge` instance with 3 data nodes, using OpenSearch Benchmark's `vectorsearch` workload and its included `cohere-100k` and `cohere-1m` datasets. Time-based metrics were collected using OpenSearch's Stopwatch class and memory deltas were collected using Java's Runtime methods, which sometimes returned negative values.
The benchmarks were run a total of 3 times each. The values shown below are averages taken over all 3 iterations. 
`cohere-100k` dataset, uploaded file size was 293 MB.
| | 8kb (default) | 50mb | 100mb | 200mb | …
=> [Remote Vector Index Build] Add tuned upload/download values

CHANGELOG.md, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/KNN990QuantizationStateReader.java, src/main/java/org/opensearch/knn/index/mapper/CompressionLevel.java, src/main/java/org/opensearch/knn/quantization/models/quantizationState/QuantizationStateCache.java, src/main/java/org/opensearch/knn/quantization/models/quantizationState/QuantizationStateCacheManager.java, src/test/java/org/opensearch/knn/index/mapper/CompressionLevelTests.java, src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java, src/test/java/org/opensearch/knn/quantization/models/quantizationState/QuantizationStateCacheManagerTests.java, src/test/java/org/opensearch/knn/quantization/models/quantizationState/QuantizationStateCacheTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
1. Fix quantization cache bugs(https://github.com/opensearch-project/k-NN/pull/2666)
2. Fix enable rescoring when dimensions > 1000(https://github.com/opensearch-project/k-NN/pull/2671)
=> Backport to 3.0 for Binary Quantization Bugs

release-notes/opensearch-knn.release-notes-2.19.2.0.md, src/main/java/org/opensearch/knn/index/mapper/CompressionLevel.java, src/test/java/org/opensearch/knn/index/mapper/CompressionLevelTests.java, src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Backport of PR: https://github.com/opensearch-project/k-NN/pull/2671
NA
=> [Backport 2.19] [Bug-fix] Enables rescoring by default when dimensions > 1024. (#2671)

CHANGELOG.md, src/main/java/org/opensearch/knn/index/engine/KNNEngine.java, src/main/java/org/opensearch/knn/index/query/BaseQueryFactory.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java, src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java
With shard level query execution, slice count wasn't honored for the core part for search. This reverts to use KNNQuery for non-quantized case
=> Makes sure slice count is honored for non-quantization case

CHANGELOG.md, src/main/java/org/opensearch/knn/index/engine/KNNEngine.java, src/main/java/org/opensearch/knn/index/query/BaseQueryFactory.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java, src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java
* Makes sure slice count is honored for non-quantization case
* Adds change log
---------
https://github.com/opensearch-project/k-NN/pull/2692
=> [Backport 2.19] Makes sure slice count is honored for non-quantization case (#2692)

CHANGELOG.md, src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildMetrics.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildStrategy.java
Because it is in the `finally` block, the call to `endRemoteBuildMetrics` is happening after the fallback strategy so the failure time is inaccurate. 
Additionally, Exceptions in the remote build process are caught and rethrown to let each step give a failure message:
https://github.com/opensearch-project/k-NN/blob/76d6662a5e80c44a924c23491cc7e99715cb5c43/src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildStrategy.java#L251-L253
We should add the exception itself to these debug logs to add more insight into why the failure occurred (for example, adding this to the `submitBuild` step will give the HTTP status code instead of just saying "Submit vector build failed". This is already the case for `awaitVectorBuild`.
N/A
By submitting this pull request, I confirm …
=> [Remote Vector Index Build] fix: end remote build metrics before falling back to CPU, log exceptions

.github/workflows/remote_index_build.yml, CHANGELOG.md, src/test/java/org/opensearch/knn/index/KNNSettingsTests.java
This PR adapts k-NN tests to the change introduced in https://github.com/opensearch-project/OpenSearch/pull/16908.
There was a change in the MockNode constructor to accept a list of PluginInfo instead of a simple className to allow more flexibility in testing.
Resolves CI issues seen on https://github.com/opensearch-project/k-NN/pull/2699
=> Fix KNNSettingsTests after change in MockNode constructor

CHANGELOG.md, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/test/java/org/opensearch/knn/integ/DerivedSourceIT.java
This is a minor experience bug fix. Basically, for derived source, we need the knn codec to be used, so we need the index.knn setting to be set to true.
Adds setting dependency on derived source setting so that if index.knn is set to false, then index creation will be blocked.
=> [BUGFIX] Block derived source enable if index.knn is false

CHANGELOG.md, src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java, src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceIndexOperationListener.java, src/test/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceIndexOperationListenerTests.java
=> [Backport 3.0]  Apply mask operation in preindex to optimize derived source (#2704)

src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissHNSWProvider.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndex.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndexLoadUtils.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/IndexTypeToFaissIndexMapping.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/binary/FaissBinaryHnswIndex.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/binary/FaissBinaryIndex.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/binary/FaissIndexBinaryFlat.java, src/test/java/org/opensearch/knn/memoryoptsearch/FaissBinaryHnswIndexTests.java
This PR is to support binary HNSW in memory optimized search.
The binary HNSW consists of two parts:
1. HNSW
2. Binary flat vectors
In the change, added `FaissBinaryHnswIndex` along with an util class having a common loading functions that being used when loading both binary index and non-binary index.
N/A
=> [LuceneOnFaiss M2, PR2] Added binary HNSW graph support in Faiss index for memory optimized search

.github/workflows/remote_index_build.yml, src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java, src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/KNN9120BinaryVectorScorer.java, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/QuantizationConfigKNNCollector.java, src/main/java/org/opensearch/knn/index/query/KNNScorer.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/main/java/org/opensearch/knn/index/query/ResultUtil.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissHnswGraph.java, src/test/java/org/opensearch/knn/index/codec/backward_codecs/KNN9120Codec/KNN9120DerivedSourceStoredFieldVisitorTests.java, src/test/java/org/opensearch/knn/index/query/ExplainTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
- Build fixes for Lucene 10.2.1 and OpenSearch 3.1
1. RandomVectorScorer
- Adapts BinaryScorer to match the BitScorer implementation in Lucene 10.2.1
- BitScorer_10_0: https://github.com/apache/lucene/blob/branch_10_0/lucene/codecs/src/java/org/apache/lucene/codecs/bitvectors/FlatBitVectorsScorer.java#L61-L121
- BitScorer_10_2: https://github.com/apache/lucene/blob/main/lucene/codecs/src/java/org/apache/lucene/codecs/bitvectors/FlatBitVectorsScorer.java#L60-L123
3. HnswGraph
- Implements `maxConn()` and `neighborCount`
5. DerivedSourceFieldWriter
- Changes signature to include `StoredFieldDataInput` instead of `DataInput, length` explicitly
7. QuantizationKNNCollector
- Implements `getSearchStrategy` with `UnsupportedOperationException`
8. Bug fix to make it return an empty scorer every …
=> Fix compatibility with Lucene 10.2.1

CHANGELOG.md, src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryCacheManagerTests.java
Avoid opening of graph file if graph is already loaded in memory.
While doing some high performance query tests I saw that performance I was getting is not similar to what I was getting with same dataset on 2.15 version of OpenSearch. On doing some deep-dive and looking at flame graph I saw a weird trace of opening of a file with locks which should not be there as everything is loaded in the memory. This could be one of the reason why I am not seeing high performance for my tests(CPU was only 50% even when I tried putting 100 search clients), since most of the threads are blocked while previous one is opening the file. 
Will do a patch on my distribution to see if this fixes. Otherwise next step will be to find if there are other bottlenecks in the code. 
Pasting the reference of profiler …
=> Avoid opening of graph file if graph is already loaded in memory

CHANGELOG.md, src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java, src/test/java/org/opensearch/knn/index/memory/NativeMemoryCacheManagerTests.java
Backport of PR: https://github.com/opensearch-project/k-NN/pull/2719
NA
=> [Backport: 2.19] Avoid opening of graph file if graph is already loaded in memory

src/main/java/org/opensearch/knn/memoryoptsearch/faiss/AbstractFaissHNSWIndex.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissHNSW.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissHNSWIndex.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissHnswGraph.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIdMapIndex.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissMemoryOptimizedSearcher.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/IndexTypeToFaissIndexMapping.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/binary/FaissBinaryHnswIndex.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/binary/FaissBinaryIndex.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/binary/FaissIndexBinaryFlat.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/cagra/FaissHNSWCagraIndex.java, src/test/java/org/opensearch/knn/jni/JNIServiceTests.java, src/test/java/org/opensearch/knn/memoryoptsearch/FaissHNSWTests.java, src/test/java/org/opensearch/knn/memoryoptsearch/FaissHnswGraphTests.java, src/test/java/org/opensearch/knn/memoryoptsearch/FaissIdMapIndexTests.java, src/test/java/org/opensearch/knn/memoryoptsearch/FaissIndexTestUtils.java
In this PR, it made FaissIdMapIndex support both binary index and non-binary index.
The only difference is in the parsing header, where a binary index has one more column `codeSize` than non-binary index. 
And in the class, it branches on its index type to choose parsing function. 
Note that base classes are pasted from [PR1](https://github.com/opensearch-project/k-NN/pull/2675) and [PR2](https://github.com/opensearch-project/k-NN/pull/2676).  …
=> [LuceneOnFaiss M2, PR3] Make FaissIdMapIndex support binary format in Faiss index.

CHANGELOG.md, build.gradle, src/main/java/org/opensearch/knn/common/featureflags/KNNFeatureFlags.java, src/main/java/org/opensearch/knn/index/KNNSettings.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexBuildStrategyFactory.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildStrategy.java, src/main/java/org/opensearch/knn/plugin/KNNPlugin.java, src/main/java/org/opensearch/knn/plugin/transport/KNNStatsRequest.java, src/test/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildStrategyTests.java, src/test/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildTests.java, src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Depending on the implementation of the remote vector index build service being used, there may be an upper limit on the segment size that the GPU instances being used can handle. For segments about this size, the GPU instances will run OOM, so we should fail fast before uploading the vector to S3. This PR introduces a new cluster setting which specifies the upper bound of the vector size.
This PR also makes an attempt at updating the CHANGELOG the be more in line with core/other plugins. Ref:
- https://github.com/opensearch-project/OpenSearch/blob/main/CHANGELOG.md
- https://github.com/opensearch-project/neural-search/blob/main/CHANGELOG.md
Docs issue for settings name change + GA: https://github.com/opensearch-project/documentation-website/issues/10053
Also, muting the flakey test from …
=> Add upper bound setting for remote vector index build + GA settings changes

CHANGELOG.md, qa/restart-upgrade/build.gradle, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
Block from using mode and compression on indices that were created before version 2.17.0, even when the customer tries to create a new knn vector field with mode and compression after upgrading the cluster to version 2.17.0 or later.  
Resolves #2708 
=> Block mode and compression for indices created before version 2.17.0

CHANGELOG.md, src/main/java/org/opensearch/knn/index/query/KNNWeight.java
Fix RefCount and ClearCache in some race conditions
in #2619 @owenhalpert describe a bugs: `IndexAllocation-Reference is already closed can't increment refCount current count [0]`,  i met the same case at scenarios:  at the time with hight throughput search, doing clear cache.
also it would also cause memory leak because it would waiting the writeLock.
i analysis the race condition as following shows:
1. Time1: Search Thread, do `KNNWeight#doANNSearch` and get indexAllocation at https://github.com/opensearch-project/k-NN/blob/52dc64b6311a71e174a6ba7a6c6e904f2e2d378f/src/main/java/org/opensearch/knn/index/query/KNNWeight.java#L486-L501
2. Time2: Clear Thread, clear cache triggered, and google Cache do async clear cache, get into https://github.com/opensearch-project/k-NN/blob/52dc64b6311a71 …
=> [BUGFIX] Fix RefCount and ClearCache in some race conditions

CHANGELOG.md, src/main/java/org/opensearch/knn/index/query/DefaultKNNWeight.java, src/main/java/org/opensearch/knn/index/query/ExactSearcher.java, src/main/java/org/opensearch/knn/index/query/KNNScorer.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/main/java/org/opensearch/knn/index/query/PerLeafResult.java, src/main/java/org/opensearch/knn/index/query/ResultUtil.java, src/main/java/org/opensearch/knn/index/query/TopApproxKnnCollector.java, src/main/java/org/opensearch/knn/index/query/TopDocsDISI.java, src/main/java/org/opensearch/knn/index/query/explain/KnnExplanation.java, src/main/java/org/opensearch/knn/index/query/memoryoptsearch/MemoryOptimizedKNNWeight.java, src/main/java/org/opensearch/knn/index/query/nativelib/NativeEngineKnnVectorQuery.java, src/test/java/org/opensearch/knn/index/query/ExactSearcherTests.java, src/test/java/org/opensearch/knn/index/query/ExplainTests.java, src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java, src/test/java/org/opensearch/knn/index/query/ResultUtilTests.java, src/test/java/org/opensearch/knn/index/query/TopApproxKnnCollectorTests.java, src/test/java/org/opensearch/knn/index/query/TopDocsDISITests.java, src/test/java/org/opensearch/knn/index/query/nativelib/NativeEngineKNNVectorQueryTests.java, src/test/java/org/opensearch/knn/utils/TopDocsTestUtils.java
With this change all search leaf will return TopDocs instead of map and later converted to TopDocs at last step. This will help us align with other search interfaces where results are always returned as TopDocs.
=> Refactor Knn Search Results to use TopDocs

scripts/build.sh
Add build.snapshot to build script to fix lib build issue.
```
SNAPSHOT=true
./gradlew :buildJniLib -Pknn_libs=opensearchknn_nmslib -Dbuild.lib.commit_patches=false -Dbuild.lib.apply_patches=false -Dbuild.snapshot=$SNAPSHOT
...
CMake command: cmake -S jni -B jni/build -DKNN_PLUGIN_VERSION=3.1.0-SNAPSHOT -DCOMMIT_LIB_PATCHES=false -DAPPLY_LIB_PATCHES=false -DCMAKE_POLICY_VERSION_MINIMUM=3.5
...
BUILD SUCCESSFUL in 6s
```
Resolves #2569 
=> Add -Dbuild.snapshot=$SNAPSHOT in build script for libs

release-notes/opensearch-knn.release-notes-3.1.0.0.md, src/main/java/org/opensearch/knn/index/mapper/CompressionLevel.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldType.java, src/test/java/org/opensearch/knn/index/mapper/CompressionLevelTests.java, src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java
Since rescore is supported for lucene engine,
update rescore context for 4x compression to
use 1x oversampling factor.
=> Update rescore context for 4X Compression

CHANGELOG.md, remote-index-build-client/src/main/java/org/opensearch/remoteindexbuild/client/RemoteIndexHTTPClient.java
When there is failure on submit remote vector build, the full response body is not logged out. This PR logs the full response body to help with debugging build failures.
=> [Fix] Log error responseBody on submitVectorBuild failure

src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissMemoryOptimizedSearcher.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/cagra/FaissCagraHNSW.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/cagra/FaissHNSWCagraIndex.java, src/test/java/org/opensearch/knn/memoryoptsearch/faiss/RandomEntryPointsKnnSearchStrategyTests.java
Backport https://github.com/opensearch-project/k-NN/commit/ee3f2625efea27d410219b939f4ff66ed5b9ce98 from https://github.com/opensearch-project/k-NN/pull/2758
=> [Backport 3.1] [Bug Fix] Fix Cagra HNSW graph populates random entry points at the beginning of search.

CHANGELOG.md, src/main/java/org/opensearch/knn/common/exception/TerminalIOException.java, src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildStrategy.java, src/main/java/org/opensearch/knn/index/store/IndexOutputWithBuffer.java, src/main/java/org/opensearch/knn/plugin/stats/KNNRemoteIndexBuildValue.java, src/test/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildStrategyTests.java, src/test/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildTests.java
From the issue:
> Currently, if a k-NN index graph build fails at segment level for GPU based index acceleration, we always fallback to to CPU. But there are some hard failures like IndexInput is closed or index is deleted. We fallback to CPU and then again hit same hard failure before failing the shard. Ideally in case of hard failures we should throw the exception out and shouldn't fall back to CPU.
This PR introduces a new exception to signal to the remote build process that no fall back strategy should be invoked, instead the exception should be rethrown to the caller to terminate the build altogether.
Resolves #2766 
~- [] New functionality has been documented.~
~- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/ …
=> Don't fall back to CPU on terminal exceptions

.github/workflows/maven-publish.yml, build-tools/repositories.gradle, build.gradle, remote-index-build-client/build.gradle
Update the Maven Snapshots publish URL in accordance with the recent Sonatype migration. 
https://central.sonatype.org/publish/publish-portal-snapshots/
We have stored the `onepassword` token in this repo secrets and new credentials for Sonatypes username & password have been stored in `onepassword`.  These credentials will be exported as env variables which used by maven publish.
Part of a campaign from https://github.com/opensearch-project/opensearch-build/issues/5551
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of- …
=> Update the maven snapshot publish endpoint and credential

src/main/java/org/opensearch/knn/index/query/memoryoptsearch/MemoryOptimizedKNNWeight.java
Enabling [ACORN](https://github.com/apache/lucene/pull/14160) when filtering rate < 60% for LuceneOnFaiss.
Lucene's main branch is applying Acorn for 60% filtering case -- [code](https://github.com/apache/lucene/blame/main/lucene/core/src/java/org/apache/lucene/search/knn/KnnSearchStrategy.java#L30)
But this is disabled by default in release/lucene/10.2.2 branch that we're using -- [code](https://github.com/apache/lucene/blame/releases/lucene/10.2.2/lucene/core/src/java/org/apache/lucene/search/knn/KnnSearchStrategy.java#L30)
Therefore, we enabling the optimization in KNN.
N/A …
=> Enable ACORN when having filtering rate < 60% for LuceneOnFaiss

CHANGELOG.md, src/main/java/org/opensearch/knn/index/codec/util/NativeMemoryCacheKeyHelper.java, src/test/java/org/opensearch/knn/index/codec/util/NativeMemoryCacheKeyHelperTests.java
Change:
- Use lastIndexOf('@') instead of indexOf('@') to handle filenames containing '@'
- Add comprehensive unit tests covering edge cases and collision scenarios
Fixes issue where vector index filenames containing '@' characters would be incorrectly parsed when extracting from cache keys. Since segmentId is encoded as base64, it is safe to use lastIndexOf. 
#2809 
=> Fix @ collision in NativeMemoryCacheKeyHelper and add unit tests

CHANGELOG.md, src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReader.java, src/main/java/org/opensearch/knn/index/engine/MemoryOptimizedSearchSupportSpec.java, src/main/java/org/opensearch/knn/index/query/memoryoptsearch/MemoryOptimizedKNNWeight.java, src/main/java/org/opensearch/knn/memoryoptsearch/VectorSearcherFactory.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissMemoryOptimizedSearcher.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissMemoryOptimizedSearcherFactory.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FlatVectorsScorerProvider.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/binary/FaissBinaryHnswIndex.java, src/main/java/org/opensearch/knn/plugin/script/KNNScoringUtil.java, src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReaderTests.java, src/test/java/org/opensearch/knn/memoryoptsearch/FaissCagraHnswIndexTests.java, src/test/java/org/opensearch/knn/memoryoptsearch/FaissMemoryOptimizedSearcherTests.java
Draft implementation to integrate asymmetric distance calculation (ADC) with lucene-on-faiss.
This implementation uses the following low-level approach:
- Within the `NativeEngines990KnnVectorsReader` see from the `FieldInfo` if adc is enabled or not. We need to check here so we can obtain the original `SpaceType`, as this information is lost for binary indices when it is changed to hamming.
- Add new split within `trySearchWithMemoryOptimizedSearch` on if adc is enabled or not.
- Add `isAdc` parameter to `createVectorSearcher` method.
- Add new method `searchWithAdc`. The reason for a new method is that preexisting scorer supplier logic depends on the query and document vector types matching (`float/float` or `byte/byte`), whereas ADC is `float/byte`. 
- Create new ADC scorer, leveraging …
=> Support ADC in Lucene-on-faiss initial commit

CHANGELOG.md, src/main/java/org/opensearch/knn/common/KNNConstants.java, src/main/java/org/opensearch/knn/index/engine/EngineResolver.java, src/main/java/org/opensearch/knn/index/engine/KNNEngine.java, src/main/java/org/opensearch/knn/index/engine/KNNMethodContext.java, src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java, src/main/java/org/opensearch/knn/index/mapper/OriginalMappingParameters.java, src/main/java/org/opensearch/knn/index/util/IndexUtil.java, src/main/java/org/opensearch/knn/plugin/rest/RestTrainModelHandler.java, src/main/java/org/opensearch/knn/plugin/transport/TrainingModelRequest.java, src/test/java/org/opensearch/knn/index/engine/EngineResolverTests.java, src/test/java/org/opensearch/knn/index/engine/KNNEngineTests.java, src/test/java/org/opensearch/knn/index/engine/KNNMethodContextTests.java, src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java, src/test/java/org/opensearch/knn/index/mapper/OriginalMappingParametersTests.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java, src/test/java/org/opensearch/knn/integ/TopLevelEngineParameterIT.java
The engine parameter is currently located in the method section of the knn_vector mapping. Moving it up to be a top-level mapping field parameter would make the method subsection simpler for the user, as it would now only contain the algorithm and its parameters. The user can also then set the engine without defining the method section when creating a vector field.
This PR introduces engine as a top-level field parameter, similar to how space_type was moved in a previous release. It is an optional parameter, and the user can set engine in either the method or at the top-level. 
* “engine” added as a top-level mapping parameter
* new KNNEngine type “UNDEFINED” (similar to in SpaceType) that is used when user does not set an engine
Both integration testing and unit testing were performed to …
=> Add engine as a top level mapping parameter

CHANGELOG.md, build.gradle
Make build.gradle use the version library for commons-lang3 and slf4j. This should fix the vulnerability [CVE-2025-48924](https://github.com/advisories/GHSA-j288-q9x7-2f5v) and avoid us having to bump versions to be the same with core. 
Resolves [CVE-2025-48924](https://github.com/advisories/GHSA-j288-q9x7-2f5v)
=> Replace commons-lang with org.apache.commons:commons-lang3

CHANGELOG.md, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/test/java/org/opensearch/knn/index/FaissIT.java
Currently any query with a filter that yields more docs than k against a byte[] index will fail. See #2866 .
I suspect that this issue is due to us keeping byteVector [null](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java#L688) when creating a query with a FAISS engine. Then when we go into this [line](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/query/KNNWeight.java#L602) we run into a NPE.
Since only either `queryVector` or `byteVector` can be populated here we can replace this with a conditional check to avoid the NPE.
Resolves #2866 
For more information …
=> Use queryVector length if present in MDC check

.github/workflows/remote_index_build.yml
Increase the health check timeout for local stack to 30sec since it was failing quite often and retrying the CI run was making it successful.
NA
=> Increase the health check timeout for local stack to 30sec

CHANGELOG.md, qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java, qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/QueryANNIT.java, src/main/java/org/opensearch/knn/common/KNNConstants.java, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/index/query/KNNWeight.java, src/main/java/org/opensearch/knn/index/query/memoryoptsearch/MemoryOptimizedKNNWeight.java, src/main/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParser.java, src/main/java/org/opensearch/knn/index/util/IndexUtil.java, src/test/java/org/opensearch/knn/grpc/proto/request/search/query/KNNQueryBuilderProtoUtilsTests.java, src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java, src/test/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParserTests.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
KNNQuery k == 0 and k == null are used interchangeably, this change is to remove this logic (outside of Lucene library calls) by changing k from an int field to an Integer field.
Resolves [#2836](https://github.com/opensearch-project/k-NN/issues/2836)
Intended to replace PR [#2871](https://github.com/opensearch-project/k-NN/pull/2871)
=> Changed query k functionality so that empty k field is null instead of 0

CHANGELOG.md, src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java, src/main/java/org/opensearch/knn/index/query/MemoryOptimizedSearchScoreConverter.java, src/main/java/org/opensearch/knn/index/query/memoryoptsearch/MemoryOptimizedKNNWeight.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FlatVectorsScorerProvider.java, src/test/java/org/opensearch/knn/memoryoptsearch/AbstractMemoryOptimizedKnnSearchIT.java, src/test/java/org/opensearch/knn/memoryoptsearch/FaissMemoryOptimizedSearcherTests.java, src/test/java/org/opensearch/knn/memoryoptsearch/MOSFaissDiskBasedIndexIT.java, src/test/java/org/opensearch/knn/memoryoptsearch/MOSFaissFP16IndexIT.java, src/test/java/org/opensearch/knn/memoryoptsearch/MOSFaissFloatIndexIT.java, src/test/java/org/opensearch/knn/memoryoptsearch/MemoryOptimizedSearchScoreConverterTests.java, src/testFixtures/java/org/opensearch/knn/generate/Documents.java, src/testFixtures/java/org/opensearch/knn/generate/DocumentsGenerator.java, src/testFixtures/java/org/opensearch/knn/generate/NestedDocumentsGenerator.java, src/testFixtures/java/org/opensearch/knn/generate/NonNestedDocumentsGenerator.java, src/testFixtures/java/org/opensearch/knn/generate/SearchTestHelper.java
This PR fixes score translation bug in LuceneOnFaiss when cosine space type is being used.
For more details, please refer to this [issue](https://github.com/opensearch-project/k-NN/issues/2887).
https://github.com/opensearch-project/k-NN/issues/2887
=> Fix LuceneOnFaiss to have the same cosine score values with Faiss

CHANGELOG.md, src/main/java/org/opensearch/knn/search/processor/mmr/MMRRerankProcessor.java, src/main/java/org/opensearch/knn/search/processor/mmr/MMRUtil.java, src/test/java/org/opensearch/knn/search/extension/MMRSearchExtBuilderIT.java, src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Use right doc id for MMR. We should use the unique doc id rather than the internal lucene doc id. That doc id is not always unique especially when we have multiple nodes. That id of the search hit can be -1 if the hit is passed from one node to another one.
N/A
=> Use right doc id for MMR.

build.gradle, src/main/java/org/opensearch/knn/memoryoptsearch/MemorySegmentAddressExtractor.java, src/main/java/org/opensearch/knn/memoryoptsearch/MemorySegmentAddressExtractorJDK21.java, src/main/java/org/opensearch/knn/memoryoptsearch/MemorySegmentAddressExtractorJDK22.java, src/main/java/org/opensearch/knn/memoryoptsearch/MemorySegmentAddressExtractorUtil.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndexScalarQuantizedFlat.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissMemoryOptimizedSearcher.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/MMapByteVectorValues.java, src/main/java/org/opensearch/knn/memoryoptsearch/faiss/MMapFloatVectorValues.java, src/test/java/org/opensearch/knn/memoryoptsearch/MMapByteVectorValuesTests.java, src/test/java/org/opensearch/knn/memoryoptsearch/MMapFloatVectorValuesTests.java, src/test/java/org/opensearch/knn/memoryoptsearch/MemorySegmentAddressExtractorTests.java
This is the first PR to support native scoring in LuceneOnFaiss. 
RFC : https://github.com/opensearch-project/k-NN/issues/2875
In this first PR, FP16 flat index will return `MMapByteVectorValues` having `MemorySegment[]` extracted from MemorySegment$IndexInput. Each `MemorySegment` will have a raw pointer pointing to mapped region in memory.
Passing the raw pointer for distance calculation will be dealt with in the second PR. This PR is mostly set-up for the second PR.
Since the actual distance calculation is not there, still the distance calculation will be conducted in Java side.
This PR is mostly focusing on extracting `MemorySegment` from IndexInput.
N/A
- [O] New functionality includes testing.
- [O] New functionality has …
=> [BulkSimd PR1] Added MMapByteVectorValues for FP16 in LuceneOnFaiss.
