build.gradle
settings.gradle

Update name to follow standard format.
update plugin, project name

Update plugin name

---

release-notes/opensearch-knn.release-notes-1.0.0.0-beta1.md

Add release notes for 1.0.0.0-beta1

---

.github/workflows/CI.yml
build.gradle
release-notes/opensearch-knn.release-notes-1.0.0.0-beta1.md

Update upstream to use alpha2

---

.github/workflows/CI.yml
build.gradle
release-notes/opensearch-knn.release-notes-1.0.0.0-beta1.md

Signed-off-by: Vijayan Balasubramanian balasvij@amazon.com
Use OpenSearch 1.0.0-beta1 release as upstream.

Update upstream to use beta1

---

jni/CMakeLists.txt

Signed-off-by: Vijayan Balasubramanian balasvij@amazon.com
rename Open distro reference to OpenSearch

Update library description

---

src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/KNNPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/rest/RestKNNStatsHandler.java
src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/rest/RestKNNWarmupHandler.java
src/test/java/com/amazon/opendistroforelasticsearch/knn/KNNRestTestCase.java
src/test/java/com/amazon/opendistroforelasticsearch/knn/ODFERestTestCase.java
src/test/java/com/amazon/opendistroforelasticsearch/knn/plugin/action/RestLegacyKNNStatsHandlerIT.java
src/test/java/com/amazon/opendistroforelasticsearch/knn/plugin/action/RestLegacyKNNWarmupHandlerIT.java

Replace stats and warmup API starting with _opendistro to _plugins.
Created two new integration test class with prefix legacy, copied
from the existing test class and update request to use legacy base api.
We should not update this IT test in future since it uses deprecated
URI path.
https://github.com/opensearch-project/k-NN/issues/17
- [X ] All tests pass

Renaming RestAPIs while supporting backwards compatibility.

---

.github/workflows/CI.yml
build.gradle

use 1.0.0-rc1 as ref for upstream and rc1 as qualifier for plugin

Update upstream and qualifier

---

src/main/java/org/opensearch/knn/index/KNNWeight.java
src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java

Minor change to increment graph query errors when loading the graph fails.
#25 

Add extra place to increase knn graph query errors

---

release-notes/opensearch-knn.release-notes-1.0.0.0-rc1.md

Create release note file for 1.0.0-rc1

Add release note for rc1

---

src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java

Cherry picks #54 to feature/faiss-support branch

Cherry-pick #54 to feature/faiss-support

---

release-notes/opensearch-knn.release-notes-1.0.0.0.md

Add release notes for 1.0.0.0

---

release-notes/opensearch-knn.release-notes-1.0.0.0.md

Cherry-picks #59 to 1.x

---

release-notes/opensearch-knn.release-notes-1.0.0.0.md

Cherry-picks #59 to 1.0

---

.github/workflows/CI.yml
build.gradle

Update upstream and remove qualifier

Update OpenSearch upstream to 1.0.0

---

release-notes/opensearch-knn.release-notes-1.0.0.0.md

Including rc1 release notes and features that are merged after latest odfe release
to 1.0.0.0

Update release note

---

.github/workflows/CI.yml
build.gradle
release-notes/opensearch-knn.release-notes-1.0.0.0.md

Backport #58 #62 to 1.0 branch

Backport #58 #62 to 1.0

---

.github/workflows/CI.yml
build.gradle
release-notes/opensearch-knn.release-notes-1.0.0.0.md

Backport #58 #62 to 1.x branch

Backport #58 #62 to 1.x branch

---

NOTICE.txt
README.md

Modify Copyright Description in README. I could not find other instances outside of the README. 
Related: https://github.com/opensearch-project/.github/pull/24
#75 

Fix copyright in README

---

NOTICE.txt
README.md

Backport #76 to 1.x

---

.github/workflows/CI.yml
integtest.sh

Backport #44 to 1.0 branch so that integTests can be run for patch release.

Backport #44 to 1.0

---

RFC.md
release-notes/opensearch-knn.release-notes-1.1.0.0.md

- Fix invalid url
- Add release note for 1.1.0.0

Add release note for 1.1.0.0

---

.github/workflows/CI.yml

Update OpenSearch to build with 1.1 branch.

Update OpenSearch to build with 1.1 branch.

---

src/main/java/org/opensearch/knn/common/KNNConstants.java
src/main/java/org/opensearch/knn/indices/ModelDao.java
src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
src/main/java/org/opensearch/knn/plugin/rest/RestGetModelHandler.java
src/main/java/org/opensearch/knn/plugin/transport/GetModelAction.java
src/main/java/org/opensearch/knn/plugin/transport/GetModelRequest.java
src/main/java/org/opensearch/knn/plugin/transport/GetModelResponse.java
src/main/java/org/opensearch/knn/plugin/transport/GetModelTransportAction.java
src/test/java/org/opensearch/knn/KNNRestTestCase.java
src/test/java/org/opensearch/knn/plugin/action/RestGetModelHandlerIT.java
src/test/java/org/opensearch/knn/plugin/transport/GetModelRequestTests.java
src/test/java/org/opensearch/knn/plugin/transport/GetModelResponseTests.java

Added GetModel API to get Model properties like Id, description, blob, space_type for given ModelID.
This requires Handler to register route and prepare request, GetModelRequest, GetModelResponse to represent request and response, GetModelTransportAction to sends request across nodes.
Added unit test to check for Respones content and Request Input. Added integration test to check whether handler, request and response is serialized and deserialized ad expected. …

Add FAIS GetModel API

---

.github/workflows/dco.yml

Add DCO check to workflow
#107 

Add DCO workflow check

---

src/main/java/org/opensearch/knn/indices/Model.java
src/main/java/org/opensearch/knn/indices/ModelDao.java
src/main/java/org/opensearch/knn/indices/ModelMetadata.java
src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
src/main/java/org/opensearch/knn/plugin/rest/RestSearchModelHandler.java
src/main/java/org/opensearch/knn/plugin/transport/SearchModelAction.java
src/main/java/org/opensearch/knn/plugin/transport/SearchModelTransportAction.java
src/test/java/org/opensearch/knn/indices/ModelMetadataTests.java
src/test/java/org/opensearch/knn/indices/ModelTests.java
src/test/java/org/opensearch/knn/plugin/action/RestSearchModelHandlerIT.java

Allow users to search model similar to search requests. 
Example:
Using GET
```
GET /_plugins/_knn/models/_search?<query_filters>
{
"query": {
...
}
}
{
"took": 13,
"_shards": {
"total": 5,
"successful": 5,
"skipped": 0,
"failed": 0
},
"hits": {
...
}
} 
```
Using POST
```
POST /_plugins/_knn/models/_search?<query_filters>
{
"query": {
...
}
}
{
"took": 13,
"_shards": {
"total": 5,
"successful": 5,
"skipped": 0,
"failed": 0
},
"hits": {
...
}
} 
``` …

Add support for search model api

---

src/main/java/org/opensearch/knn/plugin/rest/RestSearchModelHandler.java
src/test/java/org/opensearch/knn/plugin/action/RestSearchModelHandlerIT.java

Update Search Action to SearchModelAction.
Updated test to verify that it doesn't return any other
document.

Update Search Action to SearchModelAction

---

build.gradle
src/test/java/org/opensearch/knn/plugin/transport/RemoveModelFromCacheTransportActionTests.java

[Checkstyle](https://github.com/opensearch-project/OpenSearch/pull/1370) was removed from OpenSearch. We need to add dependency on the plugin to fix CI
Broken CI: https://github.com/opensearch-project/k-NN/actions/runs/1414737164

Add checkstyle plugin dependency

---

src/main/java/org/opensearch/knn/index/KNNQueryBuilder.java

Similar to #159 but for k. This will return illegal arg exception instead of 500 for large k. 

Add validation to check max k limit

---

README.md
THIRD-PARTY

Add faiss to attributions and add openblas and faiss to third party (BSD 3 and MIT, respectively).

Update license and attributions for faiss addition

---

src/main/java/org/opensearch/knn/index/KNNMethod.java
src/main/java/org/opensearch/knn/index/KNNMethodContext.java
src/main/java/org/opensearch/knn/index/KNNVectorFieldMapper.java
src/main/java/org/opensearch/knn/index/MethodComponent.java
src/main/java/org/opensearch/knn/index/Parameter.java
src/main/java/org/opensearch/knn/index/util/KNNEngine.java
src/main/java/org/opensearch/knn/index/util/KNNLibrary.java
src/main/java/org/opensearch/knn/plugin/transport/TrainingModelRequest.java
src/test/java/org/opensearch/knn/index/KNNMethodContextTests.java
src/test/java/org/opensearch/knn/index/KNNMethodTests.java
src/test/java/org/opensearch/knn/index/MethodComponentTests.java
src/test/java/org/opensearch/knn/index/ParameterTests.java
src/test/java/org/opensearch/knn/index/util/KNNLibraryTests.java
src/test/java/org/opensearch/knn/plugin/transport/TrainingModelRequestTests.java

Adds more helpful validation exception messages. Instead of validate chain of calls throwing a Validation exception, they return a validation exception. That way, user knows all of the problems with the request when they get back the response.
#161 

Add more helpful validation messages

---

src/main/java/org/opensearch/knn/common/KNNConstants.java
src/main/java/org/opensearch/knn/indices/ModelCache.java
src/main/java/org/opensearch/knn/plugin/stats/KNNStatsConfig.java
src/main/java/org/opensearch/knn/plugin/stats/StatNames.java
src/main/java/org/opensearch/knn/plugin/stats/suppliers/EventOccurredWithinThresholdSupplier.java
src/main/java/org/opensearch/knn/plugin/stats/suppliers/ModelIndexingDegradingSupplier.java
src/test/java/org/opensearch/knn/indices/ModelCacheTests.java
src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
src/test/java/org/opensearch/knn/plugin/stats/suppliers/EventOccurredWithinThresholdSupplierTests.java

Add model_indexing_degraded stat to node stats response.

Include index model degraded status as stats for given node

---

src/main/java/org/opensearch/knn/common/KNNConstants.java
src/main/java/org/opensearch/knn/index/KNNSettings.java
src/main/java/org/opensearch/knn/index/util/KNNLibrary.java
src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
src/test/java/org/opensearch/knn/plugin/action/RestTrainModelHandlerIT.java

A few minor string updates. For PQ, I changed code count to m because thats what faiss refers to it as. For settings, I nested them.

Clean up some strings

---

src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java
src/main/java/org/opensearch/knn/index/util/KNNEngine.java
src/main/java/org/opensearch/knn/index/util/KNNLibrary.java
src/main/java/org/opensearch/knn/jni/FaissService.java
src/main/java/org/opensearch/knn/jni/NmslibService.java
src/main/java/org/opensearch/knn/plugin/stats/KNNCounter.java
src/main/java/org/opensearch/knn/plugin/stats/KNNStatsConfig.java
src/main/java/org/opensearch/knn/plugin/stats/StatNames.java
src/main/java/org/opensearch/knn/plugin/stats/suppliers/LibraryInitializedSupplier.java
src/main/java/org/opensearch/knn/plugin/transport/TrainingModelTransportAction.java
src/main/java/org/opensearch/knn/training/TrainingJobRunner.java
src/test/java/org/opensearch/knn/index/memory/NativeMemoryCacheManagerTests.java
src/test/java/org/opensearch/knn/plugin/stats/suppliers/LibraryInitializedSupplierTests.java

Backport 191: Add training stats and library initialized stats

---

jni/src/jni_util.cpp

Backport 196 to 1.2

---

jni/src/faiss_wrapper.cpp
src/main/java/org/opensearch/knn/index/MethodComponent.java
src/main/java/org/opensearch/knn/index/util/KNNLibrary.java
src/test/java/org/opensearch/knn/index/MethodComponentTests.java

Fix issue setting parameters (#199)

---

build-tools/knnplugin-coverage.gradle
build-tools/repositories.gradle
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
settings.gradle

Update license in gradle files
https://github.com/opensearch-project/k-NN/issues/193

Update license headers in gradle files

---

jni/src/faiss_wrapper.cpp
jni/src/nmslib_wrapper.cpp
src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
src/main/java/org/opensearch/knn/index/util/KNNLibrary.java
src/test/java/org/opensearch/knn/index/util/KNNLibraryTests.java
src/test/java/org/opensearch/knn/jni/JNIServiceTests.java

Fix parameter validation for both libs (#202)

---

build-tools/knnplugin-coverage.gradle
build-tools/repositories.gradle
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
settings.gradle

Update license header in gradle files (#201)

---

src/main/java/org/opensearch/knn/index/IndexUtil.java
src/main/java/org/opensearch/knn/index/memory/NativeMemoryEntryContext.java
src/main/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategy.java
src/main/java/org/opensearch/knn/plugin/transport/TrainingModelRequest.java
src/main/java/org/opensearch/knn/plugin/transport/TrainingModelTransportAction.java
src/main/java/org/opensearch/knn/training/TrainingJob.java
src/main/java/org/opensearch/knn/training/VectorReader.java
src/test/java/org/opensearch/knn/index/memory/NativeMemoryEntryContextTests.java
src/test/java/org/opensearch/knn/training/VectorReaderTests.java

Fix field validation in VectorReader (#207)

---

jni/CMakeLists.txt.in

Change googletest from master to main

---

release-notes/opensearch-knn.release-notes-1.2.0.0.md

Add release notes for 1.2

---

src/test/java/org/opensearch/knn/ODFERestTestCase.java

Adding fix to client in ODFERestTestCase
https://github.com/opensearch-project/k-NN/issues/214

Adding Client Fix to ODFERestTestCase

---

src/test/java/org/opensearch/knn/index/FaissIT.java

Update testEndToEnd_fromMethod (#218)

---

jni/tests/faiss_wrapper_test.cpp

Minor change to make google tests compile.

Fix broken test

---

jni/src/faiss_wrapper.cpp

Allow inner product for HNSWPQ by setting metric type manually after index has been built.
#222 

Fix space type for hnswpq faiss

---

release-notes/opensearch-knn.release-notes-1.2.0.0.md

Adds feature section to release notes for 1.2.

Add features section to release notes

---

DEVELOPER_GUIDE.md

Adds information in developer guide for faiss feature.
#182 

Update developer guide for faiss feature

---

.github/workflows/CI.yml
build.gradle
jni/CMakeLists.txt

Coming from https://github.com/opensearch-project/opensearch-build/issues/1365.

Incremented version to 1.2.3.

---

.github/workflows/CI.yml
build.gradle
jni/CMakeLists.txt

Coming from https://github.com/opensearch-project/opensearch-build/issues/1417.

Incremented version to 1.2.4.

---

src/main/java/org/opensearch/knn/index/KNNWeight.java

Backport #256 to 1.2

---

src/main/java/org/opensearch/knn/index/KNNWeight.java

Backport #256 to 1.0

---

build-tools/repositories.gradle
build.gradle

Backport of [#260](https://github.com/opensearch-project/k-NN/issues/260)
[#260](https://github.com/opensearch-project/k-NN/issues/260)

Backport #261 to 1.2

---

src/main/java/org/opensearch/knn/index/KNNIndexShard.java
src/main/java/org/opensearch/knn/index/codec/KNNCodecUtil.java
src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java
src/test/java/org/opensearch/knn/index/KNNIndexShardTests.java

[BUG FIX] Fix knn index shard to get bwc engine paths (#310)

---

src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java

Remove remaining mapping reference.
#303 

Remove remaining mapping type

---

build.gradle

Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
Update knn with dynamic version assignment
#315

Update knn with dynamic version assignment

---

src/main/java/org/opensearch/knn/common/KNNConstants.java
src/main/java/org/opensearch/knn/plugin/rest/RestSearchModelHandler.java
src/test/java/org/opensearch/knn/plugin/action/RestSearchModelHandlerIT.java

Backport [352](https://github.com/opensearch-project/k-NN/pull/352) to 1.x

Add size validation for Search Model API

---

release-notes/opensearch-knn.release-notes-2.0.0.0-rc1.md

Add release notes for 2.1.0 rc1
#299 

Adding release notes for 2.0.0 rc1

---

.github/workflows/CI.yml
src/main/java/org/opensearch/knn/index/KNNWeight.java

Backport #256 to 1.1

---

qa/rolling-upgrade/build.gradle
qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/PainlessScriptScoringIT.java
qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/ScriptScoringIT.java
qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/StatsIT.java
qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java

Add Rolling-Upgrade BWCTests
https://github.com/opensearch-project/k-NN/issues/360

Add Rolling-Upgrade BWC Tests

---

.github/workflows/CI.yml
.github/workflows/backwards_compatibility_tests_workflow.yml
gradle.properties
qa/build.gradle
qa/restart-upgrade/build.gradle
qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java
qa/rolling-upgrade/build.gradle

Improve BWC framework and add support for multiple BWC Versions
https://github.com/opensearch-project/k-NN/issues/360

Add support for multiple BWC Versions

---

.github/workflows/backwards_compatibility_tests_workflow.yml

Update opensearch version in BWCTests workflow to test it against version 2.0 GA

Update opensearch version in BWCWorkflow

---

build.gradle
jni/CMakeLists.txt

Signed-off-by: pgodithi <pgodithi@amazon.com>
https://github.com/opensearch-project/opensearch-build/issues/2101
https://github.com/opensearch-project/opensearch-build/issues/2101

Version Increment to 1.3.3 OpenSearch release

---

src/main/java/org/opensearch/knn/training/VectorReader.java
src/test/java/org/opensearch/knn/training/VectorReaderTests.java

[Backport 1.x] Change VectorReaderListener to expect number array

---

src/main/java/org/opensearch/knn/training/VectorReader.java
src/test/java/org/opensearch/knn/training/VectorReaderTests.java

[Backport 1.2] Change VectorReaderListener to expect number array

---

build.gradle

Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Increment version to 2.0.1
Part of https://github.com/opensearch-project/opensearch-build/issues/2165

Increment version to 2.0.1

---

src/main/java/org/opensearch/knn/plugin/script/KNNWhitelistExtension.java
src/test/java/org/opensearch/knn/plugin/script/PainlessScriptIT.java
src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java

Backport PR #421 to 2.0

---

build.gradle
jni/CMakeLists.txt

Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Increment version to 1.3.4
Part of https://github.com/opensearch-project/opensearch-build/issues/2205

Incremented version to 1.3.4.

---

src/test/java/org/opensearch/knn/indices/ModelDaoTests.java

Adding a fix for the flaky test in ModelDaoTests which is sometimes failing the build. Will add a separate PR to refactor the tests. Using the same github issue for tracking purpose.
https://github.com/opensearch-project/k-NN/issues/461

Add fix to flaky test in ModelDaoTests

---

build.gradle

Manually backporting #442 to 2.1

[Backport 2.1] Staging for version increment automation

---

build.gradle

Manually backporting  #442 to 2.0. 
#433 

 [Backport 2.0] Staging for version increment automation

---

build.gradle

[Backport 2.x] Staging for version increment automation

---

.github/workflows/backwards_compatibility_tests_workflow.yml
build.gradle
qa/restart-upgrade/build.gradle

Upgrade OpenSearch version to 2.2.0
https://github.com/opensearch-project/k-NN/issues/467

Bump OS version to 2.2.0

---

gradle.properties

Bump default bwc version to 1.3.4

Bump default bwc version to 1.3.4

---

src/test/java/org/opensearch/knn/index/LuceneEngineIT.java

Replace call to VectorSimilarityFunction.convertToScore by custom implementation. Method convertToScore has been removed in [Lucene 9.3](https://github.com/apache/lucene/blob/branch_9_3/lucene/core/src/java/org/apache/lucene/index/VectorSimilarityFunction.java), comparing to earlier implementation in [Lucene 9.2](https://github.com/apache/lucene/blob/branch_9_2/lucene/core/src/java/org/apache/lucene/index/VectorSimilarityFunction.java#L108). This causes build failures like [this one](https://github.com/opensearch-project/k-NN/runs/7656569723?check_suite_focus=true)
I've done it in [2.x branch](https://github.com/opensearch-project/k-NN/commit/aebff805b0d47c9297d59741422d82e7dc0c8087), no backport needed, at that time "main" branch was …

Change call to Lucene VectorSimilarityFunction.convertToScore

---

release-notes/opensearch-knn.release-notes-2.2.0.0.md

Add 2.2.0.0 release note 
https://github.com/opensearch-project/k-NN/issues/467

Add 2.2.0.0 release notes

---

build.gradle
jni/CMakeLists.txt

Signed-off-by: prudhvigodithi <pgodithi@amazon.com>
Incremented version to 1.3.5.
Part of: https://github.com/opensearch-project/opensearch-build/issues/2348

[Release 1.3.5] Version increment 

---

DEVELOPER_GUIDE.md

Adds instructions for installing dependencies on mac.
#493 

Update dev guide with instructions for mac

---

release-notes/opensearch-knn.release-notes-2.3.0.0.md

Added release notes for version 2.3.0
Signed-off-by: Navneet Verma <navneev@amazon.com>
#524 

Added release notes for version 2.3.0

---

release-notes/opensearch-knn.release-notes-2.3.0.0.md

Fixed the pull request links in the k-nn release notes 2.3.0.
#524

Fixed the pull request links in the k-nn release notes 2.3.0.

---

.github/workflows/backwards_compatibility_tests_workflow.yml
build.gradle
qa/build.gradle
src/main/java/org/opensearch/knn/index/codec/KNN920Codec/KNN920PerFieldKnnVectorsFormat.java
src/main/java/org/opensearch/knn/index/codec/KNN940Codec/KNN940Codec.java
src/main/java/org/opensearch/knn/index/codec/KNN940Codec/KNN940PerFieldKnnVectorsFormat.java
src/main/java/org/opensearch/knn/index/codec/KNNCodecFactory.java
src/main/java/org/opensearch/knn/index/codec/KNNFormatFactory.java
src/main/java/org/opensearch/knn/plugin/script/KNNAllowlistExtension.java
src/main/resources/META-INF/services/org.apache.lucene.codecs.Codec
src/test/java/org/opensearch/knn/index/codec/KNN920Codec/KNN920CodecTests.java
src/test/java/org/opensearch/knn/index/codec/KNN940Codec/KNN940CodecTests.java
src/test/java/org/opensearch/knn/index/codec/KNNCodecFactoryTests.java
src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
src/test/java/org/opensearch/knn/index/codec/KNNFormatFactoryTests.java

This PR includes the following changes:
- Increment version on main to 3.0.0-SNAPSHOT
- Nomenclature changes from Whitelist to Allowlist
- Update Lucene 92 package
- Add new KNN Codec KNN940Codec based on Lucene 94 
Nomenclature changes from Whitelist to Allowlist and increment version on main to 3.0.0-SNAPSHOT

Increment version to 3.0.0-SNAPSHOT

---

.github/workflows/CI.yml
build.gradle
jni/CMakeLists.txt

Need to update core to 1.3.6 in order to pull some fixes (e.g. https://github.com/opensearch-project/opensearch-plugins/issues/168)
https://github.com/opensearch-project/opensearch-plugins/issues/168

Increment version to 1.3.6-SNAPSHOT

---

README.md

Cherry pick fix of #540. DCO was failing, so opensing a new PR.

[Backport 2.x] Replace Forum link in k-NN plugin README.md

---

release-notes/opensearch-knn.release-notes-2.4.0.0.md

Include https://github.com/opensearch-project/k-NN/pull/618 in the Release Notes

Update 2.4.0 Release Notes

---

.github/workflows/CI.yml
build.gradle
jni/CMakeLists.txt

Increment opensearch version to 1.3.7

[1.x] Increment version to 1.3.7

---

scripts/build.sh

Add Windows build.sh script changes
Cherry-picked from 195d26d0f4b1f2d1bdb89eee7cb51897b33b3077
https://github.com/opensearch-project/k-NN/issues/635

[Backport 1.x] Add windows build script changes here

---

scripts/build.sh

Add Windows build.sh script changes
Cherry-picked from https://github.com/opensearch-project/k-NN/commit/195d26d0f4b1f2d1bdb89eee7cb51897b33b3077
https://github.com/opensearch-project/k-NN/issues/635

[Backport 1.3] Add windows build script changes here

---

release-notes/opensearch-knn.release-notes-1.3.7.0.md

Add Release notes for opensearch release 1.3.7

Add Release notes for opensearch release 1.3.7

---

.github/workflows/backwards_compatibility_tests_workflow.yml

Updates minor/patch versions of backwards compatibility workflow on main

Update backwards compatibility versions

---

src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java

Closing gap in manual backport, original PR for main https://github.com/opensearch-project/k-NN/pull/610, backport PR https://github.com/opensearch-project/k-NN/pull/613. 

Fixed flaky test

---

release-notes/opensearch-knn.release-notes-2.5.0.0.md

Add 2.5 release notes

---

.github/workflows/backwards_compatibility_tests_workflow.yml
build.gradle
qa/build.gradle
qa/restart-upgrade/build.gradle
qa/rolling-upgrade/build.gradle

Upgrade to 2.6.0-SNAPSHOT

---

.github/workflows/backwards_compatibility_tests_workflow.yml
qa/build.gradle
qa/restart-upgrade/build.gradle
qa/rolling-upgrade/build.gradle

Add Windows Support to Backwards Compatibility Tests

Add Windows Support to BWC Tests

---

.github/workflows/backwards_compatibility_tests_workflow.yml

Updates 2.5 to 2.5.0 for bwc testing. Also updates 1.3.7 to 1.3.8.

Update 2.5 bwc on 2.x branch

---

release-notes/opensearch-knn.release-notes-2.6.0.0.md

Add 2.6 release notes

---

.github/workflows/backwards_compatibility_tests_workflow.yml

Include 2.6 as latest release and update 2.7.0-SNAPSHOT as next release

Update bwc version to next release

---

release-notes/opensearch-knn.release-notes-1.3.9.0.md

Add Release Notes for OpenSearch Release 1.3.9

Add Release Notes for 1.3.9

---

CHANGELOG.md
build.gradle

Update BWC Version when the OpenSearch version is incremented.

Update BWC Version with OpenSearch Version Bump

---

.github/workflows/backwards_compatibility_tests_workflow.yml

Temporarily disabling BWC tests on Windows OS to unblock the PRs to merge into main branch.

Disable BWC Tests on Windows OS

---

CHANGELOG.md
release-notes/opensearch-knn.release-notes-2.7.0.0.md

Add Release Notes for 2.7.0
https://github.com/opensearch-project/k-NN/issues/835

Add 2.7.0 Release Notes

---

CHANGELOG.md
release-notes/opensearch-knn.release-notes-2.7.0.0.md

Manually backport https://github.com/opensearch-project/k-NN/pull/857

[Backport 2.x] Add 2.7.0 Release Notes (#857)

---

MAINTAINERS.md

Baseline Maintainers
https://github.com/opensearch-project/k-NN/issues/761

Baseline Maintainers

---

.github/CODEOWNERS

Baseline Codeowners
https://github.com/opensearch-project/k-NN/issues/761

Baseline Codeowners

---

MAINTAINERS.md

Cherry-picked from https://github.com/opensearch-project/k-NN/pull/883

[Backport 2.7] Baseline Maintainers (#883)

---

MAINTAINERS.md

Cherry-picked from https://github.com/opensearch-project/k-NN/pull/883

[Backport 1.3] Baseline Maintainers (#883)

---

MAINTAINERS.md

Cherry-picked from https://github.com/opensearch-project/k-NN/pull/883

[Backport 1.x] Baseline Maintainers (#883)

---

src/main/java/org/opensearch/knn/index/codec/KNNCodecService.java

Consume core change https://github.com/opensearch-project/OpenSearch/pull/8312 and fix corresponding compilation errors.

Add index settings to super constructor call for knn codec service

---

CHANGELOG.md
release-notes/opensearch-knn.release-notes-2.9.0.0.md

Add 2.9.0 release notes
https://github.com/opensearch-project/k-NN/issues/944

Add 2.9.0 release notes

---

benchmarks/osb/requirements.txt
benchmarks/perf-tool/requirements.txt

Bump version certifi and aiohttp to fix vulnerabilities in benchmark tools

Bump version certifi and aiohttp to fix vulnerabilities in benchmark tools

---

CHANGELOG.md
src/main/java/org/opensearch/knn/index/query/KNNWeight.java
src/test/java/org/opensearch/knn/index/FaissIT.java
src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java

Enabled the IVF algorithm to work with Filters of K-NN Query
#903 
Pr for 2.x branch: https://github.com/opensearch-project/k-NN/pull/1013, as the main branch was blocked due to opensearch backward incompatible changes. So raised the PR for 2.x early.

Enabled the IVF algorithm to work with Filters of K-NN Query. (#1013)

---

CHANGELOG.md
src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoNodeResponseTests.java
src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoResponseTests.java

Fix TransportAddress Refactoring Changes in Core https://github.com/opensearch-project/OpenSearch/pull/9073

Fix TransportAddress Refactoring Changes in Core

---

CHANGELOG.md
release-notes/opensearch-knn.release-notes-2.10.0.0.md

Created release notes for 2.10 release
#995

Created release notes for 2.10 release

---

benchmarks/perf-tool/okpt/io/config/parsers/test.py
benchmarks/perf-tool/okpt/io/config/schemas/test.yml
benchmarks/perf-tool/okpt/test/steps/factory.py
benchmarks/perf-tool/okpt/test/steps/steps.py
benchmarks/perf-tool/release-configs/faiss-hnsw/filtering/relaxed-filter/relaxed-filter-test.yml
benchmarks/perf-tool/release-configs/faiss-hnsw/filtering/restrictive-filter/restrictive-filter-test.yml
benchmarks/perf-tool/release-configs/faiss-hnsw/test.yml
benchmarks/perf-tool/release-configs/faiss-hnswpq/test.yml
benchmarks/perf-tool/release-configs/faiss-ivf/test.yml
benchmarks/perf-tool/release-configs/faiss-ivfpq/test.yml
benchmarks/perf-tool/release-configs/nmslib-hnsw/test.yml
benchmarks/perf-tool/sample-configs/faiss-sift-ivf/test.yml
benchmarks/perf-tool/sample-configs/nmslib-sift-hnsw/test.yml

Add Warmup Operation in Perf-tool Benchmarking Tests.

Add Warmup Operation in Perf-tool Benchmarking Tests

---

CHANGELOG.md
release-notes/opensearch-knn.release-notes-2.11.0.0.md

Add 2.11 release note
https://github.com/opensearch-project/k-NN/issues/1131

Add 2.11 release note

---

.github/workflows/backwards_compatibility_tests_workflow.yml

Update bwc test from 2.10 to 2.11
N/A

Update bwc test from 2.10 to 2.11

---

.github/workflows/CI.yml

Tweak docker retrival method to be simpler
https://github.com/opensearch-project/k-NN/issues/1042

Tweak docker retrival method to be simpler

---

src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java

Removes print lines from debugging

Remove print lines

---

benchmarks/perf-tool/release-configs/run_all_tests.sh

Update default test run from 10 to 3
N/A

Update default test run from 10 to 3

---

CHANGELOG.md
benchmarks/osb/requirements.txt
benchmarks/perf-tool/requirements.txt

Backport of https://github.com/opensearch-project/k-NN/pull/1278

[Backport 2.x] Upgrade urllib to 1.26.17

---

.github/workflows/CI.yml
jni/include/jni_util.h
src/test/java/org/opensearch/knn/index/FaissIT.java

Fix Windows CI
https://github.com/opensearch-project/k-NN/issues/938

Fix Failing Windows CI

---

release-notes/opensearch-knn.release-notes-2.11.1.0.md

Add release note for 2.11.1
N/A

Add release note for 2.11.1

---

src/test/java/org/opensearch/knn/index/AdvancedFilteringUseCasesIT.java
src/test/java/org/opensearch/knn/index/NestedSearchIT.java

* Increase sample document number from 2 to 15
* Add validation of totalSearchHit for filtering test
* Force merge before query
N/A

Few changes in integration test

---

build.gradle

Changes eclipse version to latest release, which is 4.20

Change eclipse version to latest

---

CHANGELOG.md
release-notes/opensearch-knn.release-notes-2.12.0.0.md

Add release notes for 2.12.0 release

Add release notes for 2.12.0 release

---

.github/workflows/CI.yml
CHANGELOG.md

In Windows CI, we need to manually install zlib in order for build to succeed.
#1494

Manually install zlib for win CI

---

CHANGELOG.md
src/main/java/org/opensearch/knn/index/SpaceType.java
src/test/java/org/opensearch/knn/index/FaissIT.java
src/test/java/org/opensearch/knn/index/SpaceTypeTests.java

(cherry picked from commit 62fc890e068238bd63dac713d989c4e4272028ba)
Backport #1532 to 2.x manually

[Backport 2.x] Switch spacetype similarity function to MAXIMUM_INNER_PRODUCT

---

CHANGELOG.md
src/main/java/org/opensearch/knn/common/KNNValidationUtil.java
src/main/java/org/opensearch/knn/common/KNNVectorUtil.java
src/main/java/org/opensearch/knn/index/SpaceType.java
src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java
src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java
src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtil.java
src/main/java/org/opensearch/knn/plugin/script/KNNScoringUtil.java
src/test/java/org/opensearch/knn/common/KNNVectorUtilTests.java
src/test/java/org/opensearch/knn/index/OpenSearchIT.java
src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceFactoryTests.java
src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceTests.java
src/test/java/org/opensearch/knn/plugin/script/KNNScoringUtilTests.java
src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java

Manually backport #1501 to 2.x

[Backport 2.x] Validate zero vector when using cosine metric

---

CHANGELOG.md
qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/FaissSQIT.java
src/main/java/org/opensearch/knn/common/KNNConstants.java
src/main/java/org/opensearch/knn/index/Parameter.java
src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java
src/main/java/org/opensearch/knn/index/util/Faiss.java
src/test/java/org/opensearch/knn/index/FaissIT.java
src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java

This PR includes the changes for Faiss SQFP16 range validation and clipping (if outside of range) which includes the changes from https://github.com/opensearch-project/k-NN/pull/1493 and https://github.com/opensearch-project/k-NN/pull/1557.
https://github.com/opensearch-project/k-NN/issues/1138

Faiss SQFP16 Range Validation and Clipping

---

benchmarks/osb/README.md
benchmarks/perf-tool/README.md

Added notice to inform developers to consider adding new features to OSB

Add no new development notice to perf tool

---

.github/workflows/backwards_compatibility_tests_workflow.yml

Update BWC CI to 2.14 version as 2.13 is released
NA

Update BWC CI to 2.14 version as 2.13 is released

---

CHANGELOG.md
src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java
src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtil.java
src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java
src/test/java/org/opensearch/knn/plugin/script/KNNScriptScoringIT.java

Backport of https://github.com/opensearch-project/k-NN/pull/1649

[Backport 2.x] Enable script score to work with model based indices

---

CHANGELOG.md
release-notes/opensearch-knn.release-notes-2.14.0.0.md

Add 2.14 release notes

---

CHANGELOG.md
release-notes/opensearch-knn.release-notes-2.14.0.0.md

[Backport 2.x] Add 2.14 release notes

---

release-notes/opensearch-knn.release-notes-2.14.0.0.md

Update 2.14 release notes to include k-NN clear cache api.

Update 2.14 release notes

---

DEVELOPER_GUIDE.md

Update DEVELOPER_GUIDE.md for M Chip Mac after cmake folder got refactored from https://github.com/opensearch-project/k-NN/pull/1636

Update DEVELOPER_GUIDE.md for M Chip Mac

---

src/main/java/org/opensearch/knn/index/IndexUtil.java
src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
src/test/java/org/opensearch/knn/index/query/parser/MethodParametersParserTests.java

Gates method_parameters behind a version for backward compatibility

---

CHANGELOG.md
release-notes/opensearch-knn.release-notes-2.15.0.0.md

Add release note and prepare changelog for next release

Add 2.15.0 release notes

---

src/main/java/org/opensearch/knn/index/IndexUtil.java
src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
src/main/java/org/opensearch/knn/index/query/parser/MethodParametersParser.java

MethodParameterParser needs to be used in neural search. Making it reusable

Changes to be able to reuse MethodParameterParser class for neural search

---

benchmarks/osb/requirements.txt

Bump jinja2 from 2.11.3 to 3.1.3

Bump jinja2 from 2.11.3 to 3.1.3

---

CHANGELOG.md
jni/include/faiss_wrapper.h
jni/include/org_opensearch_knn_jni_FaissService.h
jni/src/faiss_wrapper.cpp
jni/src/org_opensearch_knn_jni_FaissService.cpp
jni/tests/faiss_wrapper_test.cpp
jni/tests/faiss_wrapper_unit_test.cpp
src/main/java/org/opensearch/knn/index/VectorQueryType.java
src/main/java/org/opensearch/knn/index/query/KNNQuery.java
src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
src/main/java/org/opensearch/knn/index/query/KNNWeight.java
src/main/java/org/opensearch/knn/index/query/RNNQueryFactory.java
src/main/java/org/opensearch/knn/index/util/EngineSpecificMethodContext.java
src/main/java/org/opensearch/knn/index/util/Lucene.java
src/main/java/org/opensearch/knn/index/util/LuceneHNSWContext.java
src/main/java/org/opensearch/knn/index/util/QueryContext.java
src/main/java/org/opensearch/knn/jni/FaissService.java
src/main/java/org/opensearch/knn/jni/JNIService.java
src/test/java/org/opensearch/knn/index/FaissIT.java
src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
src/test/java/org/opensearch/knn/index/query/RNNQueryFactoryTests.java
src/test/java/org/opensearch/knn/index/util/AbstractKNNLibraryTests.java

This PR cherry picks https://github.com/opensearch-project/k-NN/commit/3a4b10d07ac14cbc242555677f3aeb55654ec9ea, https://github.com/opensearch-project/k-NN/commit/3a4b10d07ac14cbc242555677f3aeb55654ec9ea from feature branch to main branch.
Related PR: https://github.com/opensearch-project/k-NN/pull/1754, https://github.com/opensearch-project/k-NN/pull/1765

[feature to main branch] Support ef_search parameter in radial search faiss engine

---

CHANGELOG.md
release-notes/opensearch-knn.release-notes-2.16.0.0.md

Adds release notes for 2.16

---

src/main/java/org/opensearch/knn/index/codec/transfer/VectorTransferByte.java
src/main/java/org/opensearch/knn/index/codec/transfer/VectorTransferFloat.java
src/test/java/org/opensearch/knn/index/codec/transfer/VectorTransferByteTests.java
src/test/java/org/opensearch/knn/index/codec/transfer/VectorTransferFloatTests.java

The change in https://github.com/opensearch-project/k-NN/pull/1804 is overridden by a new PR. So apply the change again.
N/A

Apply https://github.com/opensearch-project/k-NN/pull/1804

---

.github/workflows/backwards_compatibility_tests_workflow.yml

Update CI for 2.17

---

src/main/java/org/opensearch/knn/quantization/factory/QuantizerFactory.java
src/main/java/org/opensearch/knn/quantization/factory/QuantizerRegistry.java
src/main/java/org/opensearch/knn/quantization/models/quantizationParams/ScalarQuantizationParams.java
src/main/java/org/opensearch/knn/quantization/models/quantizationState/MultiBitScalarQuantizationState.java
src/test/java/org/opensearch/knn/quantization/factory/QuantizerFactoryTests.java
src/test/java/org/opensearch/knn/quantization/factory/QuantizerRegistryTests.java

This PR fixes Java Doc issue with 2.x Branch and improvements with code style

BackPort Java Doc Fix with Code Improvements

---

src/main/java/org/opensearch/knn/index/util/IndexUtil.java

Related to #1974 . Once merged, this can be merged

Fixes bwc change for rescore query

---

src/main/java/org/opensearch/knn/common/FieldInfoExtractor.java
src/main/java/org/opensearch/knn/common/KNNConstants.java
src/main/java/org/opensearch/knn/index/engine/AbstractKNNMethod.java
src/main/java/org/opensearch/knn/index/engine/KNNLibraryIndexingContext.java
src/main/java/org/opensearch/knn/index/engine/KNNLibraryIndexingContextImpl.java
src/main/java/org/opensearch/knn/index/engine/MethodComponent.java
src/main/java/org/opensearch/knn/index/engine/faiss/AbstractFaissMethod.java
src/main/java/org/opensearch/knn/index/engine/faiss/FaissFlatEncoder.java
src/main/java/org/opensearch/knn/index/engine/faiss/FaissHNSWMethod.java
src/main/java/org/opensearch/knn/index/engine/faiss/FaissHNSWPQEncoder.java
src/main/java/org/opensearch/knn/index/engine/faiss/FaissIVFMethod.java
src/main/java/org/opensearch/knn/index/engine/faiss/FaissIVFPQEncoder.java
src/main/java/org/opensearch/knn/index/engine/faiss/FaissSQEncoder.java
src/main/java/org/opensearch/knn/index/engine/faiss/MethodAsMapBuilder.java
src/main/java/org/opensearch/knn/index/engine/faiss/QFrameBitEncoder.java
src/main/java/org/opensearch/knn/index/engine/qframe/QuantizationConfig.java
src/main/java/org/opensearch/knn/index/engine/qframe/QuantizationConfigParser.java
src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java
src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java
src/main/java/org/opensearch/knn/index/query/KNNWeight.java
src/test/java/org/opensearch/knn/index/engine/AbstractKNNLibraryTests.java
src/test/java/org/opensearch/knn/index/engine/AbstractKNNMethodTests.java
src/test/java/org/opensearch/knn/index/engine/MethodComponentTests.java
src/test/java/org/opensearch/knn/index/engine/faiss/FaissTests.java
src/test/java/org/opensearch/knn/index/engine/faiss/QFrameBitEncoderTests.java
src/test/java/org/opensearch/knn/index/engine/qframe/QuantizationConfigParserTests.java
src/test/java/org/opensearch/knn/integ/QFrameworkIT.java

[Backport 2.x] Add support for qframework from interface

---

src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java

This was merged https://github.com/opensearch-project/k-NN/pull/2021
The PR was merged before I got a chance to fix it so creating another PR

Fixes the build for 2.x

---

CHANGELOG.md
release-notes/opensearch-knn.release-notes-2.17.0.0.md

Add release notes for 2.17

---

CHANGELOG.md
release-notes/opensearch-knn.release-notes-2.17.0.0.md

Backport https://github.com/opensearch-project/k-NN/pull/2037/commits/b093e93ddfa955550fd66d6142977a5836453629 from #2037 

[Backport 2.x] Add release notes for 2.17

---

src/main/java/org/opensearch/knn/index/codec/KNN990Codec/KNN990QuantizationStateReader.java
src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReader.java
src/test/java/org/opensearch/knn/index/codec/KNN990Codec/KNN990QuantizationStateReaderTests.java
src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormatTests.java

Fixes failing unit tests and removes the Ignore annotation from unit tests related to quantization state.

Fix tests related to quantization state

---

src/test/java/org/opensearch/knn/plugin/transport/GetModelResponseTests.java

[Backport 2.17] Fix expected string for get model response tests

---

qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java

Fixes spotless for restart upgrade

---

.github/workflows/backwards_compatibility_tests_workflow.yml

Fix BWC CI for 2.18

---

CHANGELOG.md
release-notes/opensearch-knn.release-notes-2.17.1.0.md

Add Release Notes for 2.17.1.0

Add Release Notes for 2.17.1.0

---

release-notes/opensearch-knn.release-notes-2.17.1.0.md

Update release notes 2.17.1

---

CHANGELOG.md
release-notes/opensearch-knn.release-notes-2.18.0.0.md

Backport https://github.com/opensearch-project/k-NN/pull/2227 (cherry picked from commit 8f2d9114df33d232a9b749b8863922219cf56afd)

[Backport 2.x] Add Release Notes for 2.18.0.0 (#2227)

---

CHANGELOG.md
src/main/java/org/opensearch/knn/index/engine/KNNEngine.java
src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
src/main/java/org/opensearch/knn/index/query/iterators/GroupedNestedDocIdSetIterator.java
src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java
src/test/java/org/opensearch/knn/index/query/iterators/GroupedNestedDocIdSetIteratorTests.java
src/test/java/org/opensearch/knn/integ/BinaryIndexIT.java
src/test/java/org/opensearch/knn/integ/BinaryIndexInvalidMappingIT.java
src/test/java/org/opensearch/knn/integ/ExpandNestedDocsIT.java
src/test/java/org/opensearch/knn/integ/FilteredSearchBinaryIT.java
src/test/java/org/opensearch/knn/integ/FilteredSearchByteIT.java
src/test/java/org/opensearch/knn/integ/IndexIT.java
src/test/java/org/opensearch/knn/integ/NestedSearchBinaryIT.java
src/test/java/org/opensearch/knn/integ/NestedSearchByteIT.java
src/test/java/org/opensearch/knn/integ/NestedSearchIT.java
src/test/java/org/opensearch/knn/integ/search/ConcurrentSegmentSearchIT.java

Backport https://github.com/opensearch-project/k-NN/commit/d31149c53ff623ab2044920eafd37b5256acbc6c from https://github.com/opensearch-project/k-NN/pull/2331

[Backport 2.x] Add expand_nested_docs Parameter support to NMSLIB engine

---

src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java

Removing temp debugging println from testing code.
N/A

Remove debugging println from source

---

CHANGELOG.md
src/main/java/org/opensearch/knn/index/engine/AbstractKNNMethod.java
src/main/java/org/opensearch/knn/index/engine/KNNLibraryIndexingContext.java
src/main/java/org/opensearch/knn/index/engine/KNNLibraryIndexingContextImpl.java
src/main/java/org/opensearch/knn/index/engine/faiss/AbstractFaissMethod.java
src/main/java/org/opensearch/knn/index/engine/faiss/Faiss.java
src/main/java/org/opensearch/knn/index/engine/faiss/FaissHNSWMethod.java
src/main/java/org/opensearch/knn/index/engine/faiss/FaissIVFMethod.java
src/main/java/org/opensearch/knn/index/mapper/FlatVectorFieldMapper.java
src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldType.java
src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java
src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java
src/main/java/org/opensearch/knn/index/mapper/NormalizeVectorTransformer.java
src/main/java/org/opensearch/knn/index/mapper/VectorTransformer.java
src/main/java/org/opensearch/knn/index/mapper/VectorTransformerFactory.java
src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
src/test/java/org/opensearch/knn/index/FaissIT.java
src/test/java/org/opensearch/knn/index/mapper/NormalizeVectorTransformerTests.java
src/test/java/org/opensearch/knn/index/mapper/VectorTransformerFactoryTests.java
src/test/java/org/opensearch/knn/recall/RecallTestsIT.java
src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java

Backport f5cf25528 from #2376 

Manual backport #2376

---

CHANGELOG.md
gradle/formatting.gradle

- Add mirror repository for spotless to fix local builds
N/A

Add mirror repository for spotless

---

.github/workflows/backwards_compatibility_tests_workflow.yml
scripts/build.sh

Fix the failing rolling upgrade bwc workflow due to avx512spr changes and update gcc required version on ARM to 9.0

Fix rolling upgrade bwc workflow avx512spr

---

src/main/java/org/opensearch/knn/index/engine/EngineResolver.java
src/main/java/org/opensearch/knn/index/engine/KNNEngine.java
src/main/java/org/opensearch/knn/index/engine/nmslib/NmslibMethodResolver.java
src/main/java/org/opensearch/knn/jni/JNIService.java

- Fixes log flooding for engine deprecation notice
N/A

Fix warn logs for engine deprecation

---

.github/workflows/CI.yml
.github/workflows/test_security.yml
CHANGELOG.md
build.gradle
qa/restart-upgrade/build.gradle
qa/rolling-upgrade/build.gradle
scripts/build.sh

- Core renamed this package in https://github.com/opensearch-project/OpenSearch/pull/17272 .
This commit renames package accordingly
- Backport https://github.com/opensearch-project/k-NN/commit/107c4f1b485e37061f526856dd8a52cbf5103993 from https://github.com/opensearch-project/k-NN/pull/2506

Update package name to fix compilation issue

---

src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java

Was looking at the flame graph and trying to see if these minor improvements help. Not expecting any major change in latencies though

Minor performance improvments in KNNQueryBuilder

---

CHANGELOG.md
release-notes/opensearch-knn.release-notes-3.0.0.0-alpha1.md

Adding Release Notes for 3.0.0.0-alpha1

Adding Release Notes for 3.0.0.0-alpha1

---

scripts/build.sh

NMSLib Build Issue due to GCC upgrade

NMSLib Build Issue due to GCC upgrade

---

CHANGELOG.md
src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
src/test/java/org/opensearch/knn/index/FaissIT.java
src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java

Add filter function to KNNQueryBuilder with unit tests and integration tests

Add filter function to KNNQueryBuilder with unit tests and integration tests

---

release-notes/opensearch-knn.release-notes-3.0.0.0-alpha1.md

Adding Breaking Changes Section in Release Note for 3.0.0

Adding Breaking Changes Section in Release Note for 3.0.0

---

CHANGELOG.md
release-notes/opensearch-knn.release-notes-3.0.0.0-beta1.md

3.0.0 Beta Release Notes

---

src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissMemoryOptimizedSearcher.java

This fixes concurrency bug that shares non-threading safe graph structure among search threads.
N/A

Fix concurrency bug to share non-thread safe graph structure.

---

src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java

Change log levels of skip building vector data structure code path to debug level
Resolves #2638 
~- [ ] New functionality includes testing.~
~- [ ] New functionality has been documented.~
~- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~
~- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin) …

Change skip building vector data structure log to debug level

---

src/main/java/org/opensearch/knn/index/query/KNNWeight.java
src/test/java/org/opensearch/knn/index/ExplainIT.java

following up on some minor comments on the pr: https://github.com/opensearch-project/k-NN/pull/2403
~~- [ ] New functionality includes testing.~~
~~- [ ] New functionality has been documented.~~
~~- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~~
~~- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~~
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate- …

Minor code refactoring for explain

---

CHANGELOG.md
src/main/java/org/opensearch/knn/index/KNNSettings.java
src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java
src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceIndexOperationListener.java
src/test/java/org/opensearch/knn/integ/DerivedSourceIT.java

[Backport 3.0] Block derived source enable if index.knn is false

---

CHANGELOG.md
release-notes/opensearch-knn.release-notes-3.1.0.0.md

3.1.0 Release Notes, back porting into 3.1 branch
N/A

3.1.0 Release Notes, back porting into 3.1 branch

---

CHANGELOG.md
release-notes/opensearch-k-NN.release-notes-3.2.0.0.md

3.2 Release Notes (need to be merged before 9am code freeze).
Contains features merged after https://github.com/opensearch-project/k-NN/pull/2827 was opened:
https://github.com/opensearch-project/k-NN/pull/2819
https://github.com/opensearch-project/k-NN/pull/2806

Add 3.2 release notes

---

CHANGELOG.md
src/main/java/org/opensearch/knn/index/query/nativelib/NativeEngineKnnVectorQuery.java
src/test/java/org/opensearch/knn/memoryoptsearch/AbstractMemoryOptimizedKnnSearchIT.java
src/test/java/org/opensearch/knn/memoryoptsearch/DiskMode1xCompressionSupportedIT.java
src/testFixtures/java/org/opensearch/knn/generate/Documents.java
src/testFixtures/java/org/opensearch/knn/generate/DocumentsGenerator.java

Details of the issue are described in https://github.com/opensearch-project/k-NN/issues/2895
Resolves #2895
[](https://github.com/opensearch-project/k-NN/issues/2895)
~~- [ ] New functionality includes testing.~~
~~- [ ] New functionality has been documented.~~
~~- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~~
~~- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~~ …

Fix rescoring logic for nested exact search
